### PR TITLE
[14.0][IMP] base_time_parameter: more data types

### PR DESCRIPTION
**Pull request by norlinhenrik**
@nimarosa This is a quick draft. Will finish on Sunday.

field value_text -> value (will require migration script)

new function _validate() will check that the value can convert to the desired data type.

Another function/method can return the desired data type (not implemented yet).

### CODE REVIEW

**Comment by nimarosa** [comment]
@norlinhenrik i like the approach. Great. I will merge the other one in payroll and then when this is ready I change the function. 

Thanks Henrik.

**Comment by norlinhenrik** [comment]
base_time_parameter is ready now.

**Review by nimarosa — APPROVED** [review]
Looks very good. Thanks @norlinhenrik I think this approach will suit us more and leave us with a lot of possibilities.

**Comment by nimarosa** [comment]
Merging as major to trigger migration scripts. 

/ocabot merge major

**Pull request merged**
