### PR TITLE
[MIG] sql_export: Migration to 13.0

### PR DESCRIPTION
**Pull request by captivea-dcr**

### CODE REVIEW

**Comment by florian-dacosta** [comment]
Hello,
Thanks for the  contribution. I started to test a query with a variable, and it failed during the wizard view rendering : 
```
 File "/odoo/src/addons/web/controllers/main.py", line 1322, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/odoo/src/addons/web/controllers/main.py", line 1314, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/src/odoo/api.py", line 383, in call_kw
    result = _call_kw_model(method, model, args, kwargs)
  File "/odoo/src/odoo/api.py", line 356, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/odoo/src/odoo/models.py", line 1441, in load_views
    for [v_id, v_type] in views
  File "/odoo/src/odoo/models.py", line 1441, in <dictcomp>
    for [v_id, v_type] in views
  File "/odoo/external-src/server-tools/sql_export/wizard/wizard_file.py", line 44, in fields_view_get
    osv.orm.setup_modifiers(view_field, self.fields_get(field.name))
AttributeError: module 'odoo.osv' has no attribute 'orm'
```

I guess this module is lacking some test, it could be nice to add some about that.

**Comment by florian-dacosta** [comment]
Thanks for the fix.
The wizard view  with variable seems now to work, but my test with a datetime variable still does not work.
I believe it is the same issue than in version 12 where I have a pending PR to fix this : https://github.com/OCA/server-tools/pull/1614

These changes should be incorporated here, mainly the tests.
For this to work, one change in sql_abstract_query is necessary (https://github.com/OCA/server-tools/pull/1614/files#diff-509ed4e9bedc552c50cdc538a74d13abR147)
Then it should be good

**Comment by captivea-dcr** [comment]
thanks for pointing out this fix. I was hitting the wall on how to cleanly fix this :smile:

**Comment by captivea-dcr** [comment]
@florian-dacosta seems linting rules changed and now it complains about sql injection issue

**Comment by captivea-dcr** [comment]
BTW, i'm not really happy with the lint disabled ... if you have better idea than rewrite the code in abstract that does it, i'm okay to discuss

**Comment by pedrobaeza** [comment]
Use psycopg.sql class for that:
```python
from psycopg2 import sql

query = sql.SQL("COPY ({}) TO STDOUT WITH {}").format(
    sql.SQL(query)
    sql(copy_options)
)
```
Maybe you need some `sql.Identifier(table)` or `sql.Identifier(column)` in the middle, as I haven't read full code, but this is the general idea.

**Comment by captivea-dcr** [comment]
@pedrobaeza thanks for the hint. However the code works with your suggestion, pylint still not happy (see https://github.com/OCA/pylint-odoo/issues/219 for further explanation)

**Comment by captivea-dcr** [comment]
pylint disabled for ql-injection`because of https://github.com/OCA/pylint-odoo/issues/219

**Comment by pedrobaeza** [comment]
@captivea-dcr with https://github.com/OCA/pylint-odoo/pull/287 merged, now you should be able to remove the pylint disable comments and it shouldn't warn you about the SQL injection.

**Comment by CasVissers-360ERP** [comment]
Some change are made in #1659 which should be included here?

**Comment by florian-dacosta** [comment]
It woud be nice indeed!

**Comment by CasVissers-360ERP** [comment]
@captivea-dcr do you plan to continue this PR?

**Pull request closed without merging**
