### PR TITLE
[14.0][MIG] dbfilter_from_header

### PR DESCRIPTION
**Pull request by eantones**

### CODE REVIEW

**Comment by steven-bouillon** [comment]
When will this be merged?

**Review by hailangvn — APPROVED** [review]
Functional test ok. Thank you.

**Review by ypapouin — APPROVED** [review]
LGTM - Code Review

**Review by MiquelRForgeFlow — APPROVED** [review]

**Review by LoisRForgeFlow — APPROVED** [review]
LGTM

**Comment by LoisRForgeFlow** [comment]
@eantones Could you do a rebase to see if that solves travis issues?

**Comment by eantones** [comment]
@LoisRForgeFlow done! Let's see if it works now. Let me know if you need anything else.

**Comment by LoisRForgeFlow** [comment]
Seems that it is good now, thanks! Let's try again:

/ocabot merge nobump

**Comment by LoisRForgeFlow** [comment]
this seems stuck... once again:

/ocabot merge nobump

**Comment by LoisRForgeFlow** [comment]
Oh no, it is actually failing in one of the travis tests:

https://github.com/OCA/server-tools/runs/3759419582

image

@eantones could you have a look?

**Comment by MiquelRForgeFlow** [comment]
@eantones please, could you rebase again? It's due to https://github.com/OCA/server-tools/issues/2191.

**Comment by eantones** [comment]
@MiquelRForgeFlow done, you can try to merge it again

**Comment by LoisRForgeFlow** [comment]
one more time :crossed_fingers: 

/ocabot merge nobump

**Review by robyf70 — COMMENTED** [review]
Tested in production, LGTM!

**Pull request merged**
