### PR TITLE
[13.0] update dotfiles and use GitHub actions

### PR DESCRIPTION
**Pull request by sbidoul**

### CODE REVIEW

**Comment by sbidoul** [comment]
There are test failures in `module_analysis` (ping @legalsylvain @santostelmo) and `letsencrypt` (@janverb, maybey). Any help welcome.

**Comment by legalsylvain** [comment]
Hi : 
- ``module_analysis`` : I didn't see the errors. I see only some errors related to the other module. could you be more precise ?
- ``letsencrypt`` : at the first sight, maybe the port of this patch made by @StefanRijnhart  could fix the problem. https://github.com/OCA/server-tools/pull/2432

https://github.com/OCA/server-tools/actions/runs/3430455735/jobs/5717440422#step:8:2450

<details>
  <summary>See letsencrypt error</summary>

```
2022-11-09 17:51:15,692 802 ERROR odoo odoo.addons.letsencrypt.tests.test_letsencrypt: ERROR: TestLetsencrypt.test_http_challenge
Traceback (most recent call last):
  File "/opt/odoo-venv/lib/python3.6/site-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/__w/server-tools/server-tools/letsencrypt/tests/test_letsencrypt.py", line 72, in test_http_challenge
    letsencrypt._cron()
  File "/__w/server-tools/server-tools/letsencrypt/models/letsencrypt.py", line 212, in _cron
    authzr = client.new_order(csr)
  File "/opt/odoo-venv/lib/python3.6/site-packages/acme/client.py", line 704, in new_order
    response = self._post(self.directory['newOrder'], order)
  File "/opt/odoo-venv/lib/python3.6/site-packages/acme/client.py", line 103, in _post
    return self.net.post(*args, **kwargs)
  File "/opt/odoo-venv/lib/python3.6/site-packages/acme/client.py", line 1272, in post
    return self._post_once(*args, **kwargs)
  File "/opt/odoo-venv/lib/python3.6/site-packages/acme/client.py", line 1286, in _post_once
    response = self._check_response(response, content_type=content_type)
  File "/opt/odoo-venv/lib/python3.6/site-packages/acme/client.py", line 1131, in _check_response
    raise messages.Error.from_json(jobj)
acme.messages.Error: urn:ietf:params:acme:error:rejectedIdentifier :: The server will not issue certificates for the identifier :: Error creating new order :: Cannot issue for "www.example.com": The ACME server refuses to issue a certificate for this domain name, because it is forbidden by policy
```
</details>

**Comment by grindtildeath** [comment]
I tried to give a look to the `module_analysis` error mentioned by @sbidoul , we can actually see it here: https://github.com/OCA/server-tools/actions/runs/3430455735/jobs/5717440422#step:8:1796

However, I could not reproduce this on my local with latest revision of server-env repo, and either the `13.0` from server-tools or after a checkout of this PR. The code of `server_environment` was always analyzed properly:
```
2022-11-25 12:49:55,326 1 INFO testdb_travis odoo.addons.module_analysis.models.ir_module_module: Analysing Code for module server_environment ... 
2022-11-25 12:49:55,486 1 INFO testdb_travis pygount: /odoo/external-src/server-env/server_environment/serv_config.xml: analyze as XML using encoding utf-8 
2022-11-25 12:49:55,650 1 INFO testdb_travis pygount: /odoo/external-src/server-env/server_environment/server_env.py: analyze as Python using encoding utf-8 
2022-11-25 12:49:55,835 1 INFO testdb_travis pygount: /odoo/external-src/server-env/server_environment/__init__.py: analyze as Python using encoding utf-8 
2022-11-25 12:49:56,017 1 INFO testdb_travis pygount: /odoo/external-src/server-env/server_environment/system_info.py: analyze as Python using encoding utf-8 
2022-11-25 12:49:56,217 1 INFO testdb_travis pygount: /odoo/external-src/server-env/server_environment/security/res_groups.xml: analyze as XML using encoding utf-8 
2022-11-25 12:49:56,423 1 INFO testdb_travis pygount: /odoo/external-src/server-env/server_environment/models/server_env_mixin.py: analyze as Python using encoding utf-8 
2022-11-25 12:49:56,650 1 INFO testdb_travis pygount: /odoo/external-src/server-env/server_environment/models/server_env_tech_name_mixin.py: analyze as Python using encoding utf-8 
2022-11-25 12:49:56,835 1 INFO testdb_travis pygount: /odoo/external-src/server-env/server_environment/models/__init__.py: analyze as Python using encoding utf-8 
```

**Comment by grindtildeath** [comment]
@sbidoul Just wondering but I don't have time to verify this week, could this error happen because oca addons are installed through pypi instead of sources with github actions (whereas it was from source with travis)? In such case it could be that `module_analysis` will not find the source to analyze and throws this error on `server_environment` because it's the first OCA module to be tested?

**Comment by sbidoul** [comment]
@grindtildeath could be. How does `module_analysis` locate the code to analyze ?

**Comment by grindtildeath** [comment]
@sbidoul it looks like it relies on `get_module_path` and `os` functions: 
https://github.com/OCA/server-tools/blob/13.0/module_analysis/models/ir_module_module.py#L130
https://github.com/OCA/server-tools/blob/13.0/module_analysis/models/ir_module_module.py#L161

**Comment by StefanRijnhart** [comment]
All tests are fixed here: https://github.com/OCA/server-tools/pull/2518

**Comment by StefanRijnhart** [comment]
Just spotted your fix for the installation of nsca-client and I picked it in https://github.com/OCA/server-tools/pull/2520. Otherwise, this PR is superseded by https://github.com/OCA/server-tools/pull/2518 which is already merged.

**Pull request closed without merging**
