### PR TITLE
[12.0] module_analysis fix _get_files_to_analyse

### PR DESCRIPTION
**Pull request by santostelmo**
Backport https://github.com/OCA/server-tools/commit/492828c0f7a236d4f5452904e67b68229e87d335

### CODE REVIEW

**Review by legalsylvain — APPROVED** [review]
thanks.

**Review by nbessi — APPROVED** [review]

**Review by grindtildeath — APPROVED** [review]

**Comment by dreispt** [comment]
Travis is red.

**Comment by legalsylvain** [comment]
santostelmo could you check travis ?

**Comment by santostelmo** [comment]
@legalsylvain I have this traceback in travis. I don't see the link with the module being migrated:
`File "/home/travis/odoo-12.0/odoo-bin", line 5, in <module>
import odoo
File "/home/travis/odoo-12.0/odoo/__init__.py", line 129, in <module>
from . import service
File "/home/travis/odoo-12.0/odoo/service/__init__.py", line 8, in <module>
from . import server
File "/home/travis/odoo-12.0/odoo/service/server.py", line 23, in <module>
from odoo.tests.common import OdooSuite
File "/home/travis/odoo-12.0/odoo/tests/__init__.py", line 1, in <module>
from . import common
File "/home/travis/odoo-12.0/odoo/tests/common.py", line 211
errorName = f'{method_name} ({parent})'
^
SyntaxError: invalid syntax`

Any idea?

**Comment by legalsylvain** [comment]
No idea.

**Pull request merged**
