### PR TITLE
[13.0][MIG][WIP] module_auto_update migration to 13

### PR DESCRIPTION
**Pull request by schout-it**
@sbidoul I'm migrating this module, but found #1429 
should the module still be split up?

Also, is there a reason the hashes are stored in the system parameters and not on ir.module.module?
If a lot of modules are installed, this could get messy.

### CODE REVIEW

**Comment by sbidoul** [comment]
@schout-it I remember trying to split the module or storing the hashes on ir.module.module created several reliability issues. Especially when module_auto_update updates itself, but not only.

In the end I don't use this module anymore and warmly recommend using `click-odoo-update` (in [click-odoo-contrib](https://pypi.org/project/click-odoo-contrib/)) which is much more reliable and battle tested.

**Comment by gustavovalverde** [comment]
Hi @schout-it @sbidoul was this PR dropped? Just to know if I can take over it

**Comment by sbidoul** [comment]
@gustavovalverde I don't maintain this module anymore and I don't recommend using it. Use [click-odoo-update](https://github.com/acsone/click-odoo-contrib#click-odoo-update-beta) instead: it's the same principle but much more robust.

**Comment by gustavovalverde** [comment]
@sbidoul Oh, my bad. I actually thought that click-odoo-update used this one as a dependency.

**Comment by sbidoul** [comment]
@gustavovalverde at some point it did depend on this module, but it had stability issues and now it's a standalone tool.

**Pull request closed without merging**
