### PR TITLE
[14.0][MIG] dbfilter_from_header

### PR DESCRIPTION
**Pull request by PhilDL**
- ADD a test suite
- Move the monkey patching into the post_load hook so it is possible to be tested also.

### CODE REVIEW

**Comment by PhilDL** [comment]
Can anybody take a look at this PR? 
I know there are others on the same subject, but I saw the other one was failing the CI so in April,
I created this one with tests and changed and updated to use post_load hooks (to make everything more testable).

**Comment by thomaspaulb** [comment]
@PhilDL I see you added tests for this module, that's great!

Another version of the module has already been merged; could you perhaps rebase this PR and make it a PR that just adds the tests? Then I'll happily review and merge.

**Comment by PhilDL** [comment]
Hi @thomaspaulb sorry but this is quite old, I don't even have my Odoo 14 envs anymore 😵‍💫 and not doing too much Odoo these days. I will close my PR but if the code was interesting feel free to pick it up.

**Comment by thomaspaulb** [comment]
Thanks! one way or the other this cleans up some of the PR pile

**Pull request closed without merging**
