### PR TITLE
[FIX] base_tier_validation: _compute_need_validation (rec vs self)

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
A fix.

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
@lreficent @jbeficent

**Review by JordiBForgeFlow — APPROVED** [review]

**Review by LoisRForgeFlow — APPROVED** [review]
Thanks :+1:

**Comment by MiquelRForgeFlow** [comment]
:green_apple: please, merge this

**Review by AaronHForgeFlow — APPROVED** [review]
:+1:

**Pull request merged**
