### PR TITLE
[ADD] Authentication via HTTP Remote User 8.0

### PR DESCRIPTION
**Pull request by lmignon**
Resubmit https://github.com/OCA/server-tools/pull/34 since the original PR was made on the master branch before the creation of the 8.0

The module allows integration with external security systems (Shibolleth, Tivoli access manager, ..) that can pass along authentication of a user via Remote_User HTTP header field. In many cases, this is achieved via server like Apache HTTPD or nginx proxying Odoo.

### CODE REVIEW

**Comment by lmignon** [comment]
in the original PR:
sbidoul commented 20 days ago
:+1:  code review and tests

**Comment by lmignon** [comment]
Travis has failed due to https://github.com/OCA/maintainer-quality-tools/issues/78

**Comment by max3903** [comment]
:+1:

**Comment by hbrunn** [comment]
Please fix the flake8 errors travis indicates:

```
flake8 . --config=${FLAKE8_CONFIG_DIR}/travis_run_flake8.cfg
./auth_from_http_remote_user/__openerp__.py:43:80: E501 line too long (80 > 79 characters)
./auth_from_http_remote_user/tests/test_res_users.py:71:80: E501 line too long (80 > 79 characters)
./auth_from_http_remote_user/tests/test_res_users.py:72:80: E501 line too long (80 > 79 characters)
./auth_from_http_remote_user/tests/test_res_users.py:84:80: E501 line too long (80 > 79 characters)
```

otherwise: :+1:

**Comment by JonathanNEMRY** [comment]
Hello,
Is there any blocking factor to merge this PR? (there already are three thumbs up)

**Comment by pedrobaeza** [comment]
I don't think so, but nobody informs about PEP8 already fixed, I suppose.

**Comment by JonathanNEMRY** [comment]
Tks for the merge @pedrobaeza  !!

**Pull request merged**
