### PR TITLE
Missing templates and translations added

### PR DESCRIPTION
**Pull request by sysadminmatmoz**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Technically :+1:

**Comment by alejandrosantana** [comment]
Same as Pedro: technically: :+1: (no idea of Slovenian)

**Comment by sysadminmatmoz** [comment]
Well, since I'm the Odoo translation coordinator for the Slovene, you'll have to trust me on that :smile:

**Comment by sysadminmatmoz** [comment]
Are there any other issues?

**Comment by pedrobaeza** [comment]
No, but we need 3 approvals for merging or 2 approvals and last 5 days. Please ping if that's the case.

**Comment by laetitia-gangloff** [comment]
technically too :+1: !

**Comment by mdietrichc2c** [comment]
:+1: to go ahead

**Pull request merged**
