### PR TITLE
Made Mass Editing module v11 compatible

### PR DESCRIPTION
**Pull request by jnegrete**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
You have to follow migration guide for preserving commit history: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0#technical-method-to-migrate-a-module-from-100-to-110-branch

Please sign also the CLA and check Travis status and runbot status.

**Comment by bealdav** [comment]
Thanks @jnegrete for your work.

But you removed the work of other contibutors : only 1 commit

Please read first https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0#technical-method-to-migrate-a-module-from-100-to-110-branch
... and apply rules to retrieve old commits

Thanks

**Comment by RoelAdriaans** [comment]
Also, shoudn't this be moved to https://github.com/OCA/server-ux/ as per https://docs.google.com/spreadsheets/d/1Xg95cW4TFMf_Lo5i_CZC_qOOfN8RgxPRc0LJTLTkdUI/edit?usp=sharing ( From issue #1008 )

**Comment by RoelAdriaans** [comment]
When i create a new mass_edit, type a name, select res.partner.
Save, edit and add an item i get an error:

```Fout:
Odoo Server Error

Traceback (most recent call last):
  File "/home/roel/odoo/odoo/odoo/http.py", line 646, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/roel/odoo/odoo/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/roel/odoo/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/roel/odoo/odoo/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/home/roel/odoo/odoo/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/roel/odoo/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/roel/odoo/odoo/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/roel/odoo/odoo/odoo/http.py", line 927, in __call__
    return self.method(*args, **kw)
  File "/home/roel/odoo/odoo/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/home/roel/odoo/odoo/addons/web/controllers/main.py", line 862, in search_read
    return self.do_search_read(model, fields, offset, limit, domain, sort)
  File "/home/roel/odoo/odoo/addons/web/controllers/main.py", line 884, in do_search_read
    offset=offset or 0, limit=limit or False, order=sort or False)
  File "/home/roel/odoo/odoo/odoo/models.py", line 4118, in search_read
    records = self.search(domain or [], offset=offset, limit=limit, order=order)
  File "/home/roel/odoo/ps_github/mass_editing/models/ir_model_fields.py", line 16, in search
    isinstance(domain[2], basestring) and
NameError: name 'basestring' is not defined
```

**Comment by jnegrete** [comment]
I'm sorry, I added the wrong branch code.
I will follow the guide that you mension

2017-11-07 4:25 GMT-06:00 Roel Adriaans <notifications@github.com>:

**Comment by yajo** [comment]
I'll close this since this should go into the `server-ux` repo, after you manage to keep git history.

Please reopen there as soon as you have it ready, thanks! 😊

**Pull request closed without merging**
