### PR TITLE
[9.0][FIX][IMP] Backport of auth_totp bug fixes and improvements from v10 PR

### PR DESCRIPTION
**Pull request by obulkin**
This PR brings several bug fixes and an admin improvement from the v10 ``auth_totp`` PR to v9. Please see the v10 PR for more info: #703.

### CODE REVIEW

**Comment by obulkin** [comment]
@moylop260 - Could you take a look at what's going on here? Locally, all the ``auth_totp`` tests are passing, and I can't recreate the error showing up in the Travis logs. Runbot doesn't seem to be running any tests at all, but when I log in the functionality associated with the failing test case is  present, so I would expect the tests to pass there as well.

**Comment by moylop260** [comment]
You can reproduce the error using a ssh connection for runbot build:

```bash
ssh -L 18080:localhost:18069 -p 8779 odoo@runbot2.odoo-community.org
cp -r ~/data_dir/filestore/openerp_template ~/data_dir/filestore/obulkin
createdb -T openerp_template obulkin
~/odoo-9.0/odoo.py -d obulkin --db-filter=obulkin --xmlrpc-port=18069 --stop-after-init -i auth_totp --test-enable
```

screen shot 2017-07-13 at 10 20 27


Now you can debbug it:
 - Note check [requirements mqt vs odoo diff](https://docs.google.com/spreadsheets/d/1BuEjEhrdl2caXnl_YIH780hDAAqkP9oZREyZdoMebuU/edit?usp=drive_web) and run with `pip install --upgrade PACKAGES` based on differences.

NOTE: Run `dropdb obulkin;createdb -T openerp_template obulkin` in order to reproduce the error from scratch again.
NOTE2: You can connect to this second instance opening your browse: http://localhost:18080

**Comment by lasley** [comment]
@obulkin - once you solve this one, please also make a contribution to [runbot_travis2docker](https://github.com/OCA/runbot-addons/tree/10.0/runbot_travis2docker) ReadMe explaining how to SSH to runbot so that we can help minimize pings to Moises in the future. Looks like theres some info in the [travis2docker ReadMe](https://github.com/Vauxoo/travis2docker#ssh-key-without-password)

**Comment by obulkin** [comment]
Thanks, @moylop260! Unfortunately, I'm getting a ``Permission denied (publickey).`` error when I try to SSH in.

**Comment by moylop260** [comment]
Little detail runbot take your ssh key from your github user: https://github.com/obulkin.keys
But you don't have registered one.

Send me email with your public key, please
`cat ~/.ssh/id_rsa.pub`

**Comment by obulkin** [comment]
This PR should be ready for review now. There was an actual bug here, caused by the overloaded ``_build_model`` method in ``res.users``, which is designed differently in v9 than in v10.

**Comment by moylop260** [comment]
Do you know why locally you can't reproduce it?

**Comment by obulkin** [comment]
@moylop260 - The short answer is no.

As you can see [here](https://github.com/OCA/server-tools/pull/703/files#diff-86a6308a179237cf51cf7238129c39adR17), the v10 code overloads ``_build_model`` in ``res.users`` to add a couple MFA fields to the ``SELF_WRITEABLE_FIELDS`` attribute on that class. The problem is that in v9, ``_build_model`` returns an instance of the model class rather than the class itself, so when I first brought the code over, it was making these changes at the instance level. With an attribute pointing to a basic type, this probably would have thrown an error right away, but the attribute is a list, so in some cases this was still working through mutation by reference. However, in others it clearly wasn't. I don't know what differentiates the two scenarios as I stopped investigating once I was able to figure this out and could confirm that it was fixing the Travis test failure.

**Comment by obulkin** [comment]
@lasley - I've created a PR that adds this SSH info to the OCA guidelines: https://github.com/OCA/maintainer-tools/pull/282. This seemed like a better place to put it given that the instructions are specific to the OCA Runbot setup and are more likely to be found by contributors in this spot.

**Review by moylop260 — APPROVED** [review]

**Review by lasley — APPROVED** [review]

**Pull request merged**
