### PR TITLE
[11.0][MIG] webhook

### PR DESCRIPTION
**Pull request by Menestrels**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
There's now a dedicated repo for this: https://github.com/OCA/webhook

**Comment by mlaitinen** [comment]
@pedrobaeza Is this module still needed in that repository or has it been refactored into different modules?

**Comment by pedrobaeza** [comment]
It seems there's a little refactoring in 2 PRs:

https://github.com/OCA/webhook/pull/4
https://github.com/OCA/webhook/pull/3

but nothing finished yet.

**Comment by mlaitinen** [comment]
Ok. They seem to be for Odoo 10.0, and no action since last year :confused:

**Comment by pedrobaeza** [comment]
Yes. The contributor is no longer active on Odoo, so proceed the way you think it's the best, but on the other repo.

**Pull request closed without merging**
