### PR TITLE
[14.0][PORT] session_db 2593 from 13.0

### PR DESCRIPTION
**Pull request by sbidoul**
Port #2593 from 13.0 to 14.0.

### CODE REVIEW

**Comment by sbidoul** [comment]
@adrienpeiffer session_db 14 is now green. It was just a test issue. Let me know when you have feedback from deployment.

**Review by IT-Ideas — APPROVED** [review]

**Comment by IT-Ideas** [comment]
@thomaspaulb rebase done

**Comment by sbidoul** [comment]
This has been working fine in production for almost a year now, so merging.

/ocabot merge patch

**Pull request merged**
