### PR TITLE
[13.0][MIG] database_cleanup

### PR DESCRIPTION
**Pull request by newtratip**
Work in process

### CODE REVIEW

**Comment by CasVissers-360ERP** [comment]
Maybe #1396 would be a nice addition?

**Comment by AaronHForgeFlow** [comment]
Hi @newtratip, do you plan to work on this? in case you don't I will supersede this PR. Just let me know.

**Comment by jjscarafia** [comment]
@newtratip any news on this? @AaronHForgeFlow have you begin working on a new PR for this?

**Comment by AaronHForgeFlow** [comment]
@jjscarafia I started working on this branch https://github.com/ForgeFlow/server-tools/tree/13.0-mig-database_cleanup Still some work pending

**Comment by newtratip** [comment]
@AaronHForgeFlow you can migrate supersede this PR. I will close it.

Sorry for my late reply.

**Pull request closed without merging**
