### PR TITLE
[MIG] base_optional_quick_create: MIGRATED to 10.0

### PR DESCRIPTION
**Pull request by espo-tony**

### CODE REVIEW

**Comment by espo-tony** [comment]
@eLBati @JonathanNEMRY , please, can you give a look to this migration?

**Comment by pedrobaeza** [comment]
It's already migrated in #597 . Please check that one.

**Comment by CasVissers-360ERP** [comment]
@pedrobaeza 
I tested both modules, this module works in v10. The other ported module didn't give the correct functionality.

**Comment by pedrobaeza** [comment]
Are you sure? It already counts with the approval of lot of people.

**Pull request closed without merging**
