### PR TITLE
[9.0][MIG] auth_from_http_remote_user

### PR DESCRIPTION
**Pull request by lmignon**
Migration from 8.0

### CODE REVIEW

**Comment by sbidoul** [comment]
The DEBUG logging mentioned in the README is not there in this version. It should be re-added or removed from the README.

Otherwise :+1: (manual test and code review)

**Comment by StefanRijnhart** [comment]
:+1:

**Comment by moylop260** [comment]
👍 
Do you want fix the following lint?

``` bash
auth_from_http_remote_user/tests/test_res_users.py:27: [C8104(class-camelcase), test_res_users] Use `CamelCase` "TestResUsers" in class name "test_res_users". You can use oca-autopep8 of https://github.com/OCA/maintainer-tools to auto fix it.
```

**Comment by lmignon** [comment]
good catch @moylop260 . Change done.

**Comment by sbidoul** [comment]
The runbot error was fixed in #464 so I think we can merge.

**Comment by lmignon** [comment]
@pedrobaeza This one is ready to merge....

**Pull request merged**
