### PR TITLE
Fix ExternalId error on "disable_openerp_online" module update

### PR DESCRIPTION
**Pull request by dreispt**
Error found here: https://travis-ci.org/dreispt/server-tools/jobs/35732685

### CODE REVIEW

**Comment by dreispt** [comment]
Red because of #64.

**Comment by rvalyi** [comment]
:+1:  LGTM

**Comment by dreispt** [comment]
If this can be reviewed and merged before https://github.com/OCA/maintainer-quality-tools/pull/99 it would spare us from a red TravisCI on server-tools.

**Comment by hbrunn** [comment]
I'm fine with this specific changes, but i think it creates the wrong precedent: As of https://github.com/odoo/odoo/blob/master/openerp/tools/convert.py#L294 we'll get a warning every time we try to delete something not existing any more. In effect that means OCA modules can't ever delete anything. Do we really want that? I think we should rather have the tests ignore this case.

**Comment by pedrobaeza** [comment]
I also think that we are changing the meaning of the module: disable_openerp_online, not hiding them in other menu.

**Comment by dreispt** [comment]
@pedrobaeza I don't believe this affects the module's effectiveness.

@hbrunn The error found in the test log is different from that, its: `ValueError: External ID not found in the system: base.menu_module_updates`. Ignoring this particular message could hide actual issues on modules.

I believe that this is caused because the test script first install the module, and only in a second run in tests it. The actual test triggers again the deletes and fails because the deletion target is gone by now.
I tried adding a `noupdate="1"` flag to the XML but it has no effect. I'm not sure if it's because of the `<delete>` tag or because of the `-i` option in the test run.

Could this be a design issue with the test script? If so, how could it be improved?

**Comment by hbrunn** [comment]
@dreispt Ultimately, I think we have to move away from a line based approach and look at the complete error message (that would be 460 through 481 in your log). Then we see that in this case, it's within a warning context which is why it seems safe to ignore it.

I'll prepare a PR for maintainer-quality-tools that allows this, then we can treat warnings emitting this error differently than errors/exceptions.

**Comment by dreispt** [comment]
I see. You could "navigate back" until you find a INFO/WARNING/ERROR "parent" line and have the rules work on both line and parent line text.

**Comment by hbrunn** [comment]
I made my proposal here: https://github.com/OCA/maintainer-quality-tools/pull/102

**Comment by guewen** [comment]
I think the line that makes travis red should not:

```
----------
2014-10-02 09:35:18,759 23425 WARNING openerp_test openerp.modules.loading: The model base.field.serialized.test.model has no access rules, consider adding one. E.g. access_base_field_serialized_test_model,access_base_field_serialized_test_model,model_base_field_serialized_test_model,,1,1,1,1
----------
Found 1 lines with errors
```

Do you know why this error is there? I don't remember seeing it in other builds.

**Comment by max3903** [comment]
:+1:

**Comment by bwrsandman** [comment]
@guewen Missing access rights Warnings cause travis to fail. This is intended behaviour.

**Comment by yvaucher** [comment]
Was travis restarted it's not red ? I don't see that access right error. So unless I'm missing something :+1:

**Comment by guewen** [comment]
:+1:

**Pull request merged**
