### PR TITLE
13.0 mig sql request abstract

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by legalsylvain — APPROVED** [review]
Hi @alfadil

Thanks for porting this module.

LGTM. (code review / no test).

Did you planned to migrate ``bi_sql_editor`` too ? 

kind regards.

**Comment by ghost** [comment]
I'm working on sql_export right now, I have new ideas to add more functionality to it

**Comment by florian-dacosta** [comment]
@alfadil 
Thanks for the PR, I'll try to review it properly soon enough. (maybe together with sql_export when you are done migrating it)
About new functionality on sql_export, it is great. But I think that if it is feasible in a separated module, it is even better! (will make migration easier).

Anyway, I think these modules should not be in server-tools repo anymore.
Check comment here : https://github.com/OCA/server-tools/pull/1554#issuecomment-480891219
And I just saw that `bi_sql_editor` is in reporting-engine already in v12.
I guess all these module should go to the same place.

@legalsylvain You still agree with this?

**Comment by ghost** [comment]
@florian-dacosta  
hi , looking forward to finish migrating them, I was also thinking about adding new module for  sql_export added functionality.

**Comment by legalsylvain** [comment]
Well the module was in server-tools : https://github.com/OCA/server-tools/pull/351
and then has moved into https://github.com/OCA/reporting-engine

I have no point of view about what is the best place. Maybe reporting-engine in all cases. kind regards.

**Comment by luisg123v** [comment]
Hi @alfadil, why mixing migration of two modules?

Wouldn't be better to migrate them separately?

**Review by AaronHForgeFlow — APPROVED** [review]
Functional tests with https://github.com/OCA/reporting-engine/pull/389

**Review by HviorForgeFlow — APPROVED** [review]

**Review by LoisRForgeFlow — APPROVED** [review]
LGTM

**Review by AdriaGForgeFlow — APPROVED** [review]

**Comment by LoisRForgeFlow** [comment]
@alfadil I realized commit history is not clean, I will abort merge until is fixed.

**Comment by LoisRForgeFlow** [comment]
This shoule be fixed now,

/ocabot merge patch

**Comment by HviorForgeFlow** [comment]
Awesome story redo @LoisRForgeFlow :) Thanks

**Pull request merged**
