### PR TITLE
[MIG] cron_inactivity_period: Migration to 12.0

### PR DESCRIPTION
**Pull request by ioans73**
Standard migration

### CODE REVIEW

**Review by legalsylvain — APPROVED** [review]
Thanks for porting this module 

Note : empty files in readme folder are not nexessary.

**Review by thomaspaulb — APPROVED** [review]

**Comment by thomaspaulb** [comment]
@ioans73 This needs:

- a rebase
- a small [pre-commit fix](https://github.com/OCA/server-tools/actions/runs/7856971857/job/21440319598) regarding the website manifest key.

**Comment by ioans73** [comment]
> @ioans73 This needs:
> 
> * a rebase
> * a small [pre-commit fix](https://github.com/OCA/server-tools/actions/runs/7856971857/job/21440319598) regarding the website manifest key.

@thomaspaulb done!

**Pull request merged**
