### PR TITLE
[FIX] unconfigured server_environment doesn't play

### PR DESCRIPTION
**Pull request by hbrunn**
nice with static files

### CODE REVIEW

**Comment by yvaucher** [comment]
:+1: restore previous behavior prior to #229 I fast-track

**Comment by yvaucher** [comment]
linking https://github.com/odoo/odoo/issues/7507

**Comment by moylop260** [comment]
FYI [CONTRIBUTING.md#external-dependencies](https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md#external-dependencies)

**Comment by yvaucher** [comment]
@moylop260 this is not due to python external dependencies.

It tries to load a dependency `server_environement_files` module which should be created based on `server_environement_files_sample` so you need to create it and if you don't install `server_environement_files` you shouldn't need it.

**Pull request merged**
