### PR TITLE
[16.0][MIG] base_domain_inverse_function: Migrate to version 16.0

### PR DESCRIPTION
**Pull request by sonhd91**
Based upon:
* https://github.com/OCA/server-tools/pull/2474

### CODE REVIEW

**Review by sebalix — APPROVED** [review]

**Review by StephaneMangin — APPROVED** [review]

**Comment by grindtildeath** [comment]
@sonhd91 Thanks for the mig. I did update the original PR with pre-commit improvements and fixing the test.

**Review by gurneyalex — APPROVED** [review]

**Comment by gurneyalex** [comment]
There seems to be an issue in the tests https://github.com/OCA/server-tools/actions/runs/4980917389/jobs/8914445178#step:8:307 I'm not sure if it is related to another module that was merged in the meantime...

@sonhd91 can you rebase your PR?

**Comment by sonhd91** [comment]
> There seems to be an issue in the tests https://github.com/OCA/server-tools/actions/runs/4980917389/jobs/8914445178#step:8:307 I'm not sure if it is related to another module that was merged in the meantime...
> 
> @sonhd91 can you rebase your PR?

reabase done, thanks
ping @gurneyalex

**Comment by hailangvn2023** [comment]
Good day @gurneyalex, the PR is now green for merging. Thanks in advance for your attention.

**Pull request merged**
