### PR TITLE
[9.0][MIG][auth_signup_verify_email] Migration.

### PR DESCRIPTION
**Pull request by yajo**
Migrate to v9.

@Tecnativa #271.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Is there any chance to increase test coverage?

**Comment by yajo** [comment]
Let me try

**Comment by yajo** [comment]
It's being tested now.

Is it possible that Travis is failing because it's runing in a non-CSRF mode while this test is CSRF-enabled?

**Comment by moylop260** [comment]
@Yajo 
What change we need in server to run the tests fine?

**Comment by yajo** [comment]
As you see [in the docs](https://www.odoo.com/documentation/9.0/reference/http.html#csrf), there's built in CSRF protection for v9. My tests woked fine locally, but [it seems like the `csrf_token` field cannot be found in the result](https://travis-ci.org/OCA/server-tools/jobs/133359359#L732-L733). The most probable cause I imagine is that somehow Travis' Odoo does not have that CSRF validation enabled. Is it possible? Otherwise it makes no sense that local and runbot's tests work and Travis not. If so, it should be enabled and further tests should implement it (although mine I think is the first test in OCA that acutally needs that).

**Comment by moylop260** [comment]
@Yajo 
I have reproduced the error locally.

I ran a travis2docker

``` bash
# Create Dockerfiles
travisfile2dockerfile git@github.com:OCA/server-tools.git pull/436

# Create docker image
/tmp/script/git_github.com_oca_server-tools.git/pull_436/1ce88c2a2300653fdf1f784c088814293999d49e/3/10-build.sh --no-cache

# Create docker container
/tmp/script/git_github.com_oca_server-tools.git/pull_436/1ce88c2a2300653fdf1f784c088814293999d49e/3/20-run.sh "--name=csrf_token_error --entrypoint=bash"

# In container ran
/entrypoint.sh

After In container ran
~/odoo-9.0/odoo.py -d openerp_test -u auth_signup_verify_email --test-enable --stop-after-init
```

screen shot 2016-05-30 at 12 00 52 pm

I added a pdb to debug.

``` patch
diff --git a/auth_signup_verify_email/tests/test_verify_email.py b/auth_signup_verify_email/tests/test_verify_email.py
index 29ce113..e3da7a1 100644
--- a/auth_signup_verify_email/tests/test_verify_email.py
+++ b/auth_signup_verify_email/tests/test_verify_email.py
@@ -13,6 +13,7 @@ class UICase(HttpCase):
         super(UICase, self).setUp()
         settings = self.env["base.config.settings"].create({})
         settings.auth_signup_uninvited = True
+        import pdb;pdb.set_trace()
         self.data = {
             "csrf_token": self.csrf_token(),
             "name": "Somebody",
```

In the line

``` bash
server-tools/auth_signup_verify_email/tests/test_verify_email.py(37)csrf_token() <- return doc.xpath("//input[@name='csrf_token']")[0].get("value")
```

I used: 
`import lxml;lxml.html.tostring(doc)`
The result was:
`<html><head><title>404 Not Found</title>\n</head><body><h1>Not Found</h1>\n<p>The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.</p>\n</body></html>`

I don't know how to fix it but if this information is useful for you, Could you help me to create hypothesis to check them?

**Comment by moylop260** [comment]
In other matter:
runbot don't ran the test of this module
[runbot-log](https://runbot.odoo-community.org/runbot/static/build/3147860-436-1ce88c/logs/job_20_test_all.txt)

``` bash
...
2016-05-27 12:01:21,282 13958 INFO 3147860-436-1ce88c-all openerp.modules.loading: loading sales_team/sales_team_demo.xml
2016-05-27 12:01:21,527 13958 INFO 3147860-436-1ce88c-all openerp.modules.module: module auth_signup_verify_email: creating or updating database tables
2016-05-27 12:01:21,528 13958 INFO 3147860-436-1ce88c-all openerp.modules.loading: loading auth_signup_verify_email/views/signup.xml
# Here should be the tests
2016-05-27 12:01:21,620 13958 INFO 3147860-436-1ce88c-all openerp.modules.module: module mail_environment: creating or updating database tables
```

screen shot 2016-05-30 at 12 46 48 pm

**Comment by pedrobaeza** [comment]
@moylop260, OCA runbot doesn't perform any test, or are you talking about your runbot?

**Comment by moylop260** [comment]
> @moylop260, OCA runbot doesn't perform any test, or are you talking about your runbot?

@pedrobaeza 
Thank you
I did not know that

> Otherwise it makes no sense that local and runbot's tests work and Travis not.

@Yajo FYI runbot doesn't perform any test

**Comment by moylop260** [comment]
@Yajo 
I have created a test-runbot using [runbot_travis2docker](https://github.com/OCA/runbot-addons/tree/9.0/runbot_travis2docker) module.

http://test.runbot.vauxoo.com/runbot/repo/git-github-com-oca-server-tools-git-2

Here you can see the error replicated.

If you give me your public ssh key I can give you ssh access to container with the error reproduced.

moylop260(at)vauxoo(dot)com

**Comment by yajo** [comment]
Hi, thanks for the debugging, I think I have a clue, let me see.

**Comment by yajo** [comment]
Test was affected by https://github.com/odoo/odoo/issues/12237, it's workarounded now. Thanks!

**Comment by moylop260** [comment]
Thank you @Yajo 

👍

**Comment by carlosdauden** [comment]
👍

**Comment by sergio-teruel** [comment]
:+1:

**Comment by yajo** [comment]
Ready to merge

**Pull request merged**
