### PR TITLE
13.0 mig scheduler error mailer

### PR DESCRIPTION
**Pull request by AMhadhbi**
- Simple migration scheduler_error_mailer

### CODE REVIEW

**Comment by dannyadair** [comment]
1.5 years - will this get merged?
Does everybody just use git-aggregator to bring these PRs in?
Thank you for your help!

**Comment by dannyadair** [comment]
Hello @pedrobaeza Anything I can do to get this merged?

**Comment by pedrobaeza** [comment]
https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#721please-respect-a-few-basic-rules
https://odoo-community.org/page/review

**Review by dannyadair — APPROVED** [review]
Great stuff!

**Comment by dannyadair** [comment]
> https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#721please-respect-a-few-basic-rules https://odoo-community.org/page/review

Thank you @pedrobaeza I forced a rebuild and checked it (apart from using this branch here locally). I did a review with "Approve".
Cannot find a development_status key in the manifest. Scheduler Error Mailer is in 12.0 and also already in 14.0.
Thank you for your help!

**Comment by pedrobaeza** [comment]
Then only one review from a PSC is needed for being merged.

**Comment by dannyadair** [comment]
Sorry that took me a while..... is it one of these people? https://odoo-community.org/psc-teams/tools-30

**Comment by pedrobaeza** [comment]
Yes, but the idea always is to be equitable. The contributor of this pull request can review other 2 o 3 pull request (or you), and then ask in exchange to get reviewed this one. All work, including PSCs one, is voluntary, so they don't have the obligation of reviewing the PR, but will have more will to do it seeing this equitability.

**Comment by StefanRijnhart** [comment]
~~Please check https://github.com/OCA/server-tools/pull/2174~~ Sorry, wrong PR

**Comment by andreampiovesana** [comment]
can you close this?

**Comment by andreampiovesana** [comment]
we need migration to odoo 16

**Pull request closed without merging**
