### PR TITLE
[16.0][IMP] excel_import_export: Set import wizard filename

### PR DESCRIPTION
**Pull request by PauBForgeFlow**

### CODE REVIEW

**Review by flotho — COMMENTED** [review]
Hi,
Thanks for this.
Could you explain the usecase that leads you to add a filename , I'm not sure to understand.
Regards

**Comment by PauBForgeFlow** [comment]
> Hi, Thanks for this. Could you explain the usecase that leads you to add a filename , I'm not sure to understand. Regards

Hi, the purpose of the improvement is to display correctly the filename of the imported file. Let me show an example:

Without improvement:
Screenshot from 2023-12-11 08-57-23

With improvement:
Screenshot from 2023-12-11 08-54-46

**Review by rinaldifirdaus — APPROVED** [review]
Functional test: Work as expected.

**Review by flotho — APPROVED** [review]
thanks for your answer
LGTM

**Pull request merged**
