### PR TITLE
[12.0][MIG] auto_backup: Migration to 12.0

### PR DESCRIPTION
**Pull request by valentincastravete**
Retake of https://github.com/OCA/server-tools/pull/2791

### CODE REVIEW

**Comment by valentincastravete** [comment]
Hi @thomaspaulb 

I've fixed all the tests and recreate the MR as the other one was a bit "dirty", sorry about that.
The branch also has been recently rebased, so it's all ready to Merge.

Thanks!

**Comment by thomaspaulb** [comment]
@valentincastravete Thanks! I would merge, there's just one minor thing, is that the pre-commit changes and the actual changes are in the same commit. It's easier to review and also to look back if these are separated in two commits.

It's pretty easy to do, something like

```
cp -R auto_backup /tmp/auto_backup
git reset --hard HEAD~1
pre-commit run -A
git commit -a -m "[UPD] black, isort, prettier"
rm -Rf auto_backup
cp -R /tmp/auto_backup .
git add .
git commit -m "[MIG] auto_backup to 12.0"
```

**Review by JorgeQuinteros — APPROVED** [review]
LGTM!

**Comment by valentincastravete** [comment]
@thomaspaulb 
Two separated commits done! Thanks for the tip/minor thing advice.
All ready now?

**Comment by thomaspaulb** [comment]
@valentincastravete All good now and thanks a lot!

/ocabot merge nobump

/ocabot migration auto_backup

**Pull request merged**
