### PR TITLE
[ADD] allow developers to have stable times over dst borders

### PR DESCRIPTION
**Pull request by hbrunn**
@feketemihai this is the extension of the rrule field I talked about in https://github.com/OCA/hr/pull/307#pullrequestreview-36434790

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please change module version number

**Comment by hbrunn** [comment]
done. I need to come around to hack versioned dependencies into base_manifest_extension, then the version number dance makes more sense.

**Comment by pedrobaeza** [comment]
Yeah, for now it's only a way to see that there's has been a change and that if you have a bug in a certain version, and the bug is fixed, then looking at the version you see that there has been a change. It's also triggers the automatic update in apps store (which is based on this version).

**Review by pedrobaeza — APPROVED** [review]
Quick code review, but hey, there are tests for it and it's Holger!

**Review by feketemihai — APPROVED** [review]

**Review by feketemihai — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Please squash at your taste before merging.

**Comment by hbrunn** [comment]
done. Funny coincidence, today I wanted to do the last work on this and the resource calendar module anyways and deploy at the customer's

**Pull request merged**
