### PR TITLE
[9.0] port - inactive_session_timeout

### PR DESCRIPTION
**Pull request by dvdhinesh**
Porting module "inactive_session_timeout" to 9.0

### CODE REVIEW

**Comment by dvdhinesh** [comment]
@pedrobaeza Currently i am testing the steps needed for contributing to OCA with this ported module. To get merged with 9.0, does the coverage increase is a must to have?

**Comment by pedrobaeza** [comment]
Not really needed, but it should be great if you add tests for this module. This will ease future migrations, avoid regressions, and so on.

**Comment by aristobulo-eezee** [comment]
Any news on this one? Do you need help?

**Comment by dvdhinesh** [comment]
@pedrobaeza Sorry for being late. Added a basic test for this module.

**Comment by dvdhinesh** [comment]
@aristobulo-eezee Basic tests are added and the module is ported to V9. You are welcome to add the session validation tests, if you are interested.

**Comment by pedrobaeza** [comment]
Sorry for the late reply. I recommend this one to be renamed as _auth_session_timeout_ before merging. May I do it?

**Comment by dvdhinesh** [comment]
:+1: for _auth_session_timeout_ 
@pedrobaeza yes you are welcome.

**Pull request merged**
