### PR TITLE
[MIG] base name search improved to 16.0  

### PR DESCRIPTION
**Pull request by maq-adhoc**

### CODE REVIEW

**Review by jjscarafia — APPROVED** [review]
LGTM. 
Tested on runboat, working properly

**Comment by kikopeiro** [comment]
I have detected problems when uninstalling the module. The error obtained is the following

```
Traceback (most recent call last):
  File "/opt/odoo/odoo-base/odoo-server/odoo/http.py", line 1584, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/opt/odoo/odoo-base/odoo-server/odoo/service/model.py", line 134, in retrying
    result = func()
  File "/opt/odoo/odoo-base/odoo-server/odoo/http.py", line 1613, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/opt/odoo/odoo-base/odoo-server/odoo/http.py", line 1810, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/opt/odoo/odoo-base/odoo-server/odoo/addons/base/models/ir_http.py", line 149, in _dispatch
    result = endpoint(**request.params)
  File "/opt/odoo/odoo-base/odoo-server/odoo/http.py", line 699, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/opt/odoo/odoo-base/odoo-server/addons/web/controllers/dataset.py", line 46, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/odoo-base/odoo-server/addons/web/controllers/dataset.py", line 33, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo-base/odoo-server/odoo/api.py", line 461, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo-base/odoo-server/odoo/api.py", line 448, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/odoo-base/odoo-server/odoo/addons/base/wizard/base_module_uninstall.py", line 59, in action_uninstall
    return modules.button_immediate_uninstall()
  File "<decorator-gen-81>", line 2, in button_immediate_uninstall
  File "/opt/odoo/odoo-base/odoo-server/odoo/addons/base/models/ir_module.py", line 76, in check_and_log
    return method(self, *args, **kwargs)
  File "/opt/odoo/odoo-base/odoo-server/odoo/addons/base/models/ir_module.py", line 640, in button_immediate_uninstall
    return self._button_immediate_function(type(self).button_uninstall)
  File "/opt/odoo/odoo-base/odoo-server/odoo/addons/base/models/ir_module.py", line 615, in _button_immediate_function
    registry = modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "<decorator-gen-14>", line 2, in new
  File "/opt/odoo/odoo-base/odoo-server/odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "/opt/odoo/odoo-base/odoo-server/odoo/modules/registry.py", line 90, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/opt/odoo/odoo-base/odoo-server/odoo/modules/loading.py", line 564, in load_modules
    getattr(py_module, uninstall_hook)(cr, registry)
  File "/opt/odoo/odoo-base/common-16.0/server-tools/base_name_search_improved/hooks.py", line 10, in uninstall_hook
    models.BaseModel._revert_method("fields_view_get")
  File "/opt/odoo/odoo-base/odoo-server/odoo/models.py", line 5031, in _revert_method
    method = getattr(cls, name)
AttributeError: type object 'BaseModel' has no attribute 'fields_view_get'
```

@maq-adhoc , could you review the problem?

**Comment by kikopeiro** [comment]
Seems work fine! (without code review)

**Comment by RodrigoBM** [comment]
PR MIG: https://github.com/OCA/server-tools/issues/2412

**Review by chusamo — APPROVED** [review]
LGTM

**Pull request merged**
