### PR TITLE
[11.0][MIG] auth_brute_force

### PR DESCRIPTION
**Pull request by zamberjo**
WIP

### CODE REVIEW

**Comment by yajo** [comment]
Yikes, git history is truncated due to the rename.

**Comment by MiquelRForgeFlow** [comment]
What is the state of this PR? Still WIP? Will be finished?

**Comment by yajo** [comment]
This seems stale. I was planning on replacing it when #1219 is finished.

**Comment by yajo** [comment]
Superseded by https://github.com/OCA/server-auth/pull/19

**Pull request closed without merging**
