### PR TITLE
[FIX] Fixes 8.0 main branch tests (adapt to newer versions of python-ldap and lxml)

### PR DESCRIPTION
**Pull request by StefanRijnhart**
[IMP] Mute ERROR level log messages from false positives

### CODE REVIEW

**Comment by StefanRijnhart** [comment]
@hbrunn the ldap change fixes https://travis-ci.org/OCA/server-tools/jobs/309037188#L2235

**Comment by StefanRijnhart** [comment]
What's wrong with codecov? 'No report found to compare against'?

**Review by hbrunn — APPROVED** [review]
codecov behaves funny when the main branch is red, so I think we have to merge this in order to get proper reports again

**Comment by StefanRijnhart** [comment]
Trying as a new PR here: https://github.com/OCA/server-tools/pull/1079

**Comment by StefanRijnhart** [comment]
New PR is fully green!  https://github.com/OCA/server-tools/pull/1079 :clap::clap::clap: @pedrobaeza

**Pull request closed without merging**
