### PR TITLE
[13.0][BACKPORT] base_sparse_field_list_support 

### PR DESCRIPTION
**Pull request by HviorForgeFlow**
port OCA/server-tools#1950 to v13

### CODE REVIEW

**Review by LoisRForgeFlow — APPROVED** [review]
LG

**Review by JordiMForgeFlow — APPROVED** [review]
LGTM 👍🏼

**Comment by HviorForgeFlow** [comment]
@sbidoul something went wrong with pypi module generation

**Comment by sbidoul** [comment]
Hm, looks like this module belongs to the `shopinvader` organization. I'll investigate.

**Comment by sbidoul** [comment]
I added OCA as PyPI maintainer of the package, and [bumped the version](https://github.com/OCA/server-tools/commit/1dc1472e7728f24f67c7187657382b044d33bc82) so it's greated than the one from the shopinvader org. Also made a PR to remove it from the shopinvader org: https://github.com/shopinvader/odoo-misc/pull/13

**Pull request merged**
