### PR TITLE
[16.0][MIG] auto_backup

### PR DESCRIPTION
**Pull request by tafaRU**
Superseeds https://github.com/OCA/server-tools/pull/2514 and https://github.com/OCA/server-tools/pull/2651

### CODE REVIEW

**Comment by tafaRU** [comment]
@manuelcalerosolis @dalonsod would you mind reviewing this? Here I have only made a standard migration and squash the Bot commits. Thank you in advance.

**Comment by manuelcalerosolis** [comment]
It's ok for me.

Thanks

**Comment by thomaspaulb** [comment]
@tafaRU please fix pre-commit

**Comment by tafaRU** [comment]
@thomaspaulb pre-commit fixed!

**Comment by thomaspaulb** [comment]
@rvalyi You should use the ocabot for merging...

**Comment by rvalyi** [comment]
Wow! Guys that's bad I believe I merged this by accident with my cell phone in my pocket. I absolutely didn't try to merge it on purpose...

What is the best way to fix this?
cc @pedrobaeza @thomaspaulb

**Comment by rvalyi** [comment]
Fortunately it seems it was quite close for merge at least. I'm looking better at the PR... reverting things on 16.0 is an option too if we do it fast, it would screw people who pulled meanwhile, so eventually it will be better to keep it. Again much sorry for this. We all get our cell phone do weird things in our pockets, but that's the very first try I got mine click on a merge button...

**Comment by pedrobaeza** [comment]
One possibility is to revert the pull request, and do it again, but if the code is correct, no problem in keeping it this way. The bot will put extra commits, and tonight the wheel will be created.

**Comment by thomaspaulb** [comment]
Yes this was ready for merge, well then lets keep it like this.

**Pull request merged**
