### PR TITLE
[12.0][autovacuum_mail_message] Standard migration

### PR DESCRIPTION
**Pull request by florian-dacosta**
@bealdav @bguillot

### CODE REVIEW

**Comment by pedrobaeza** [comment]
This should go to OCA/social IMO

**Review by bealdav — APPROVED** [review]

**Comment by florian-dacosta** [comment]
@pedrobaeza 
Why not... I am not sure as this module have more a technical goal of database cleaning.
It was made to avoid the mail_message table to become too huge overtime.
So even if it concerns messages, I find more logic if the module is together with database_cleanup and similar modules.
I am not sure someone would search for such a module in social repo?

**Comment by pedrobaeza** [comment]
Well, as the involved table is mail, that was why I said that, and for not crowding a lot this generic repo, but you decide.

**Review by legalsylvain — APPROVED** [review]
Thanks a lot for porting this module. 
About the repos. Both are ok imho.
It's a social module because it's about mail, and it's a server-tools module, as it will be used by admin user to maintain a database small.
So ok to merge this PR. 

Regards.

**Comment by florian-dacosta** [comment]
@legalsylvain Could you merge this one then?

**Comment by florian-dacosta** [comment]
@legalsylvain 
On second thought, I'd like to wait a little since I may do a big refactore to extract the logic and share for a similar module about attachments...

**Pull request closed without merging**
