### PR TITLE
[7.0] add graylog2_handler module

### PR DESCRIPTION
**Pull request by katyukha**

### CODE REVIEW

**Comment by gurneyalex** [comment]
I think that in 7.0 the description has to be in the manifest file (README.rst is nice but not handled). 

Please update the author entry in this branch too.

**Comment by katyukha** [comment]
Rebased.

**Comment by katyukha** [comment]
Is there somebody interested in this MR or I may close it?
We have no plans to port this addon to 9.0+ versions.

**Comment by pedrobaeza** [comment]
I don't think so, as the version is very old. If Travis will be green, I can merge it, but as is, I will close it.

**Comment by katyukha** [comment]
Ok. I am closing it.

**Pull request closed without merging**
