### PR TITLE
[11.0][MIG] scheduler_error_mailer

### PR DESCRIPTION
**Pull request by AMhadhbi**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please preserve commit history following technical method explained in https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

**Comment by AMhadhbi** [comment]
I tried with `git format-patch --keep-subject --stdout origin/11.0..origin/10.0 -- scheduler_error_mailer | git am -3 --keep` 
but  I have this issue received 
`Applying: [INIT] intial import
You still have unmerged paths in your index.
You should 'git add' each file with resolved conflicts to mark them as such.
You might run `git rm` on a file to accept "deleted by them" for it.
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".
Achrafs-MacBook-Pro:server-tools machraf$ git am --abort
`

**Comment by pedrobaeza** [comment]
You have to start from scratch, as it seems you have the branch dirty. Some of your colleagues at Bloopark are used to make this, so maybe you can ask them.

**Comment by AMhadhbi** [comment]
I created new pull request [#1297](https://github.com/OCA/server-tools/pull/1297) and everything is ok with runbot and Travis.  @pedrobaeza should I fix the issue on codecov/patch?. thanks

**Comment by pedrobaeza** [comment]
Superseeded by #1297 

About codecov, it would be great to have tests for covering this, but if not's possible, I'm not forcing you.

**Pull request closed without merging**
