### PR TITLE
[10.0][FIX][date_range] Periods of one day should be allowed

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Forward port of https://github.com/OCA/server-tools/pull/921.

### CODE REVIEW

**Review by yajo — APPROVED** [review]

**Review by sebalix — APPROVED** [review]

**Review by pedrobaeza — COMMENTED** [review]
Maybe you can change translations in mass in the same commit for avoiding to retranslate all in Transifex

**Comment by MiquelRForgeFlow** [comment]
And what about translations in v9? 🤔

**Comment by pedrobaeza** [comment]
Well, I didn't think it in that moment, but we have the occasion to make it right here in v10.

**Comment by yajo** [comment]
I think those can be done in Transifex for v9 if you don't want to open a PR just for that

**Comment by MiquelRForgeFlow** [comment]
Yeah, I won't do a PR for that in v9.

All :green_apple:

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
