### PR TITLE
[FIX][mass_editing] v10 Fixing error when removing value for fields being…

### PR DESCRIPTION
**Pull request by BT-rmartin**
… translatable, as their translations were not removed.

### CODE REVIEW

**Review by yajo — CHANGES_REQUESTED** [review]
Big amount of code, fixing a weird bug... Please add tests 😊

**Comment by BT-rmartin** [comment]
@Yajo Tests is ready here as well

**Review by yajo — APPROVED** [review]
Code OK, let's wait for bots.

**Comment by pedrobaeza** [comment]
Travis is failing. Please check.

**Review by rafaelbn — APPROVED** [review]
Thanks @BT-rmartin 

Only tested functionally in runbot :+1:

**Comment by rafaelbn** [comment]
@Yajo we should take care this is included in v11

**Comment by yajo** [comment]
Rebase please, it could fix travis here too

**Comment by rafaelbn** [comment]
All bots are green :+1:  great!

**Comment by rafaelbn** [comment]
@BT-rmartin I founf more fixes in https://github.com/OCA/server-tools/pull/1209

**Comment by BT-rmartin** [comment]
Thanks @pedrobaeza @rafaelbn @Yajo for your reviews and comments. 
I will do it for v11 as well, but I noticed that module mass_editing now it's not in server-tools but in server-ux right?
Why do you mention #1209? To include their changes here or to review it?

**Comment by BT-rmartin** [comment]
Here you have PR to v11 https://github.com/OCA/server-ux/pull/12

**Pull request merged**
