### PR TITLE
WIP: [MIG 9.0] migrate mass_editing to 9.0

### PR DESCRIPTION
**Pull request by njeudy**
- Initial work on migration.
# TODO:
- Add README.md

### CODE REVIEW

**Comment by StefanRijnhart** [comment]
May I suggest migration to the new API?

**Comment by StefanRijnhart** [comment]
Same as #315. Care to join forces there?

**Comment by njeudy** [comment]
Hello,

Yes I messed #315 pull request .. think new api should be a way to go .. Actually mass_Editing works in V9. think update new api should be a new merge request ?

**Comment by njeudy** [comment]
should we close this merge request as this is duplicate ?
How to contribute to #315 pull request ?

**Comment by pedrobaeza** [comment]
Yeah, usually the first PR has priority. You can make a PR against his branch, and when he merges it, PR will incorporate automatically your changes.

**Pull request closed without merging**
