### PR TITLE
[FIX] As an ERP manager, allow to reset users' passwords

### PR DESCRIPTION
**Pull request by StefanRijnhart**
Port forward of https://github.com/OCA/server-tools/pull/1049

### CODE REVIEW

**Comment by legalsylvain** [comment]
:+1: thanks.
Not sure to understand why runbot and travis are red.

**Comment by StefanRijnhart** [comment]
@legalsylvain thanks for noting, let me have look at the tests

**Comment by legalsylvain** [comment]
OK, Travis is now green, but runbot is still red, even if it's running... weird.

**Comment by StefanRijnhart** [comment]
@legalsylvain runbot fails when there are warning level log messages. These are triggered by base_view_inheritance_extension

```
2017-11-14 10:32:58,447 177 INFO openerp_test odoo.modules.loading: loading base_view_inheritance_extension/demo/ir_ui_view.xml
2017-11-14 10:32:58,470 177 WARNING openerp_test odoo.tools.safe_eval: Looks like you are trying to pass a dynamic environment, you should probably pass nocopy=True to safe_eval().
2017-11-14 10:32:58,470 177 WARNING openerp_test odoo.tools.safe_eval: Looks like you are trying to pass a dynamic environment, you should probably pass nocopy=True to safe_eval().
2017-11-14 10:32:58,514 177 WARNING openerp_test odoo.tools.safe_eval: Looks like you are trying to pass a dynamic environment, you should probably pass nocopy=True to safe_eval().
2017-11-14 10:32:58,514 177 WARNING openerp_test odoo.tools.safe_eval: Looks like you are trying to pass a dynamic environment, you should probably pass nocopy=True to safe_eval().
```

**Comment by StefanRijnhart** [comment]
@legalsylvain it's already fixed here: https://github.com/OCA/server-tools/pull/1020. If you approve that one, we can have it fixed today!

**Comment by legalsylvain** [comment]
done. Thanks.

**Comment by StefanRijnhart** [comment]
@legalsylvain thanks! Rebasing this one.

**Review by yajo — APPROVED** [review]

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
