### PR TITLE
[12.0][IMP] module_analysis: Remove automatic analyse at installation and update

### PR DESCRIPTION
**Pull request by thomaspaulb**
Analyse can take some time and a cron task can do it every day if needed, no need to recompute it in real time.

Backport from:

https://github.com/OCA/server-tools/pull/2609

[commit](https://github.com/OCA/server-tools/pull/2609/commits/e4e22e080ede60a64869a466ae63ec3d5e4ada02)

(main motivation, tests take ages without this mod - tests took 20+ mins, now 8mins)

### CODE REVIEW

**Comment by legalsylvain** [comment]
Thanks for the backport. The cron is missing. Could you add it ? 
Thanks !

**Comment by thomaspaulb** [comment]
@legalsylvain Done, I had to cherry-pick a couple of other ones as well.

**Review by legalsylvain — APPROVED** [review]
Lgtm. Thanks !

**Comment by thomaspaulb** [comment]
Looks like the other PR already got enough positive reviews, so I'll merge this.

/ocabot merge patch

**Pull request merged**
