### PR TITLE
[14.0] base_jsonify: fail gracefully

### PR DESCRIPTION
**Pull request by simahawk**
It could happen that a module adds an ir.export.line for a new field
but when tests run the field is not loaded
if this module is not a dependency of the module running tests.

Furthermore, in general, it seems too strict to break the whole computation
if there's a field that is missing.
It seems more reasonable to log an error when this happen
so that technical action can be taken to fix it.

### CODE REVIEW

**Review by sebalix — APPROVED** [review]
Seems legit

**Review by TDu — APPROVED** [review]
LG, would be good to have a not in the readme about that feature

**Comment by simahawk** [comment]
@sebastienbeau any feedback?

**Review by ivantodorovich — APPROVED** [review]
LG ;)

**Pull request merged**
