### PR TITLE
[11.0][MIG] auto_backup

### PR DESCRIPTION
**Pull request by astirpe**
Porting to v11 + code review

### CODE REVIEW

**Comment by astirpe** [comment]
I'm noticing that the Travis failure:
```
----------
Model base.exception.test.purchase.line has no table.
Model base.exception.test.purchase has no table.
----------
FAIL Found 2 lines with errors
```

is related to execution of tests of `base_exception`. The code present in file [base_exception/tests/purchase_test.py](https://github.com/OCA/server-tools/blob/11.0/base_exception/tests/purchase_test.py) somehow generates side effects during the installation of the next module (this one).

**Comment by astirpe** [comment]
And there is also a warning from the tests of `sentry`:

```
2018-02-15 10:30:21,590 5277 INFO openerp_test odoo.addons.sentry.tests.test_client: test_capture_event (odoo.addons.sentry.tests.test_client.TestClientSetup)
2018-02-15 10:30:21,616 5277 WARNING openerp_test odoo.addons.sentry.tests.test_client: Test event, can be ignored
```

**Comment by luistriana28** [comment]
@astirpe 

can you do

**git rebase -i remote/11.0**
**fixup Transifex commits**
**git push -f**

Regards!

**Comment by astirpe** [comment]
@luistriana28 done.

**Comment by luistriana28** [comment]
👍

**Review by alan196 — APPROVED** [review]

**Comment by pedrobaeza** [comment]
@astirpe can you please squash a bit the commit history by logic set/author and I'll merge this?

**Comment by astirpe** [comment]
@pedrobaeza done

**Pull request merged**
