### PR TITLE
[12.0][UPD] Update from copier. Update pre-commit.

### PR DESCRIPTION
**Pull request by AungKoKoLin1997**
- Update dotfiles using copier and pre-commit
- Backport of https://github.com/OCA/server-tools/pull/2433 to fix letsencrypt tests
- Fix module_analysis tests by cherry-pick commit from  [13.0][FIX] pre-commit; letsencrypt tests; module_analysis tests; nsca_client tests #2518 

@qrtl

### CODE REVIEW

**Comment by AungKoKoLin1997** [comment]
I don't know why development status check is failed in CI? May be I make some adjustments in `module_auto_update` that is `Production/Stable` development_status?

**Comment by yostashiro** [comment]
@AungKoKoLin1997 Yeah, please try `Production/Stable`.  https://github.com/OCA/pylint-odoo/blob/0ac19f44eeee2466b290c2ce68f68afe985631c6/src/pylint_odoo/checkers/odoo_addons.py#L269

**Comment by AungKoKoLin1997** [comment]
This PR can be processed after these two PRs (https://github.com/OCA/storage/pull/232, https://github.com/OCA/server-env/pull/141) are merged

**Comment by thomaspaulb** [comment]
@AungKoKoLin1997 Could you retrigger this? The two dependencies are merged.

**Comment by thomaspaulb** [comment]
Superseded by https://github.com/OCA/server-tools/pull/2821

**Pull request closed without merging**
