### PR TITLE
[17.0] [FIX] auditlog: Dismiss logging when not needed.

### PR DESCRIPTION
**Pull request by rven**
When fast logging is enabled on the audit log rules, empty records are created when fields are excluded from the list.
This results in a lot of empty unneeded log records, without any details.

This PR solves the issue so only a log record is created when needed.

### CODE REVIEW

**Review by StefanRijnhart — CHANGES_REQUESTED** [review]
Thanks! This is literally a ticket in one of my backlogs :smiley: 

The module name is included in the PR title, but not in the commit message. Can you add it there as well? And strictly speaking, `[MOD]` is not a valid tag listed in https://www.odoo.com/documentation/16.0/contributing/development/git_guidelines.html#tag-and-module-name. I think this counts as a `[FIX]`. Please update the commit message on that point as well.

Do you think you can include a small test so that we can rule out a regression in the future?

**Review by StefanRijnhart — APPROVED** [review]
Excellent, thanks!

**Review by MiquelRForgeFlow — APPROVED** [review]
LGTM

**Comment by StefanRijnhart** [comment]
@rven Please check https://github.com/OCA/server-tools/pull/3153 that adapts a test to this change

**Pull request merged**
