### PR TITLE
11.0 mig disable odoo online

### PR DESCRIPTION
**Pull request by hieulucky111**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Is this one still needed? Check also that this module should go to the new repo server-brand.

**Comment by hieulucky111** [comment]
Let me check again. Thanks :)

**Comment by hieulucky111** [comment]
After checked, i updated the usage of module.

**Comment by hieulucky111** [comment]
As @pedrobaeza commented, i created a new PR of this module to server-brand repository: https://github.com/OCA/server-brand/pull/1. So, i closed this pull request.

**Pull request closed without merging**
