### PR TITLE
Delete tags: /> line 136

### PR DESCRIPTION
**Pull request by arisgith**
Delete tags: /> line 136 which causes the error of "Uncaught TypeError: Cannot read property 'colspan' of undefined"

### CODE REVIEW

**Review by legalsylvain — APPROVED** [review]
make sense. 

@ maintainers : could you fast track this one.

thanks.

**Review by dreispt — APPROVED** [review]

**Comment by dreispt** [comment]
Can't merge, pre-commit checks are failing.

**Comment by StefanRijnhart** [comment]
My (merged) PR https://github.com/OCA/server-tools/pull/2087 was a duplicate. Sorry I hadn't spotted your earlier PR!

**Pull request closed without merging**
