### PR TITLE
FIX super_calendar images URL in README

### PR DESCRIPTION
**Pull request by eLBati**

### CODE REVIEW

**Comment by tafaRU** [comment]
:+1:

**Comment by sebalix** [comment]
:+1:

**Comment by pedrobaeza** [comment]
Please use the same technique as in here to allow to see the image in all the possible places: https://github.com/OCA/web/pull/336

**Comment by hbrunn** [comment]
@eLBati I had to think twice what @pedrobaeza means, but the proposal is to have absolute urls (so the change should be to add a slash at the beginning)

**Comment by pedrobaeza** [comment]
Yeah, sorry for not being clear, but I mean exactly that: put the `/` at the beginning with the absolute path. It seems to work in both GitHub and apps. I'm not so sure about in Odoo itself.

**Comment by eLBati** [comment]
@pedrobaeza @hbrunn thanks, done

**Comment by hbrunn** [comment]
:+1:

**Pull request merged**
