### PR TITLE
[MIG] fetchmail_notify_error_to_sender: Migration to 13.0

### PR DESCRIPTION
**Pull request by denisvalenchyts**

### CODE REVIEW

**Comment by okuryan** [comment]
@dreispt , @pedrobaeza could you, please, do code review of this pull request?
As I guess we require at least 2 code reviews and at least one should be PSC to merge it.

**Review by AaronHForgeFlow — APPROVED** [review]
Code review LGTM

**Review by okuryan — APPROVED** [review]
Changes approved

**Review by MiquelRForgeFlow — APPROVED** [review]
LGTM

**Comment by okuryan** [comment]
@MiquelRForgeFlow thank! What are the next steps? Who will merge it?

**Comment by okuryan** [comment]
@pedrobaeza ,  I guess you can initiate merge on this PR?

**Comment by HviorForgeFlow** [comment]
@denisvalenchyts could you squesh last 2 commits into migration one, Thanks!

**Comment by denisvalenchyts** [comment]
@HviorForgeFlow I did squash last 2 commits.

**Review by HviorForgeFlow — APPROVED** [review]

**Comment by okuryan** [comment]
@HviorForgeFlow , who can finally merge this commit?

**Comment by ventor-dev** [comment]
@pedrobaeza ,  @HviorForgeFlow , seems this request is ready for merge already for 15 days, but nobody is looking at it. Who can do merging?

**Pull request merged**
