### PR TITLE
9.0 mig auth brute force

### PR DESCRIPTION
**Pull request by nicomacr**

### CODE REVIEW

**Review by Emiq2 — APPROVED** [review]

**Review by jjscarafia — APPROVED** [review]
Tested on ADHOC v9 instance

**Comment by pedrobaeza** [comment]
What has happened with the branch?

**Comment by jjscarafia** [comment]
@pedrobaeza, I've made a rebase from origin/9.0. Isn't that ok?

**Comment by pedrobaeza** [comment]
It seems it hasn't been correct. You only need to see the number of changed files (453).

**Comment by jjscarafia** [comment]
UPs, yes, I can see that now.. It was just a "git rebase origin/9.0" but something else was not ok..

**Comment by nicomacr** [comment]
replace with https://github.com/OCA/server-tools/pull/663

**Pull request closed without merging**
