### PR TITLE
[18.0][MIG] database_cleanup: Migration to 18.0

### PR DESCRIPTION
**Pull request by nguyenminhchien**
It found only 3 commits to port:
- 1 ported successfully: https://github.com/OCA/server-tools/commit/77ccd1975f487a111d02f7d0af546968b39015ab
- 2 were ignored, i added them to blacklist: https://github.com/oca/server-tools/commit/c08c174bd593d9a86590b8ca650ac8276eca4696

# Big changes:
- Remove `database_cleanup/models/purge_properties.py`: model `ir.property` has been removed by this commit [[IMP] core: jsonb company dependent fields](https://github.com/odoo/odoo/commit/de302c2d36305c0d7562572a30587641eabfe914)

### CODE REVIEW

**Review by sebalix — APPROVED** [review]

**Review by mmequignon — APPROVED** [review]

**Review by pedrobaeza — APPROVED** [review]
Code review 

/ocabot merge nobump

**Comment by sebalix** [comment]
Hello @nguyenminhchien , can you rebase and run pre-commit again to fix the build?

```diff
diff --git a/database_cleanup/views/menu.xml b/database_cleanup/views/menu.xml
index a931997..9618986 100644
--- a/database_cleanup/views/menu.xml
+++ b/database_cleanup/views/menu.xml
@@ -63,5 +63,4 @@
         <field name="action" ref="cleanup_create_indexes_wizard_action" />
         <field name="parent_id" ref="menu_database_cleanup" />
     </record>
-
 </odoo>
Error: Process completed with exit code 1.
```

**Comment by nguyenminhchien** [comment]
> Hello @nguyenminhchien , can you rebase and run pre-commit again to fix the build?
> 
> ```diff
> diff --git a/database_cleanup/views/menu.xml b/database_cleanup/views/menu.xml
> index a931997..9618986 100644
> --- a/database_cleanup/views/menu.xml
> +++ b/database_cleanup/views/menu.xml
> @@ -63,5 +63,4 @@
>          <field name="action" ref="cleanup_create_indexes_wizard_action" />
>          <field name="parent_id" ref="menu_database_cleanup" />
>      </record>
> -
>  </odoo>
> Error: Process completed with exit code 1.
> ```

@sebalix  Updated

**Pull request merged**
