### PR TITLE
8.0 pdf compression & PDF/a

### PR DESCRIPTION
**Pull request by Benniphx**
This addon provides the ability to convert outgoing and imported PDF attachments. You can compress the PDFs to save space in you database or file system. Also the possibility exists to convert PDFs in PDF/A

### CODE REVIEW

**Comment by dreispt** [comment]
Maybe this is best hosted at OCA/knowledge ?

**Comment by pedrobaeza** [comment]
Or even OCA/reporting-engine

**Comment by Benniphx** [comment]
moved pull request to https://github.com/OCA/reporting-engine/pull/60

**Comment by Benniphx** [comment]
https://github.com/OCA/server-tools/pull/474 can be closed

**Pull request closed without merging**
