### PR TITLE
[MIG][10.0] base_user_gravatar

### PR DESCRIPTION
**Pull request by lasley**
- Bump version
- Change openerp namespace to odoo
- Change XML Ids to match OCA spec
- Remove depends on base

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]
Tried on runbot. The button might be better after the image itself instead of after the name, but not blocking.

**Comment by rafaelbn** [comment]
Why runbot is red? there is not any errors

**Comment by pedrobaeza** [comment]
@rafaelbn, runbot wasn't working correctly due to an error in Odoo.  Don't take care about that.

**Review by rafaelbn — APPROVED** [review]
Thanks!

**Comment by moylop260** [comment]
> Why runbot is red? there is not any errors

Really the [log of runbot](https://runbot2.odoo-community.org/runbot/static/build/3272157-584-d4a398/logs/job_20_test_all.txt) is showing a `Traceback (most recent call last):` error.

NOTE: But is unrelated with this PR 👍

**Comment by moylop260** [comment]
FYI fixed from https://github.com/OCA/server-tools/pull/604

**Pull request merged**
