### PR TITLE
12 port sql export READY

### PR DESCRIPTION
**Pull request by bealdav**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Should this go here on in server-backend?

**Comment by pedrobaeza** [comment]
Or server-ux?

**Comment by bealdav** [comment]
What is the difference with server-backend and server-tools ?

**Comment by florian-dacosta** [comment]
This one is not easy to place... That actually why it has ended up in server-tools!

Maybe it could be reporting-engine...Because, it is used for reporting... and it is not generic to any domain (financial, sale...) It is kind of a sql report engine...
What do you think?

**Comment by legalsylvain** [comment]
Well, for the time being 3 modules : 
- ``sql_request_abstract`` : in server-tools in 8.0 ; 10.0 ; 12.0 (at least)
- ``sql_export`` (current module) in server-tools in 8.0 ; 10.0 (this PR port to 12.)
- ``sql_bi_editor`` in reporting-engine in 8.0 ; 10.0 ; 12.0.

Propose to keep this module in server-tools for that version 12.0 and move ``sql_request_abstract`` and ``sql_export`` to reporting-engine in V13 adding a comment in the current "roadmap part" (just a proposal, not a blocking point).

regards.

**Comment by pedrobaeza** [comment]
OK for me. Not strong opinion on this one.

**Comment by bealdav** [comment]
I'm ok.

To go on this PR, could you check #1555 

Thanks

**Comment by florian-dacosta** [comment]
Also ok to leave the repo change for v13

**Review by mourad-ehm — APPROVED** [review]

**Review by bguillot — APPROVED** [review]

**Pull request merged**
