### PR TITLE
[13.0][MIG] base_deterministic_session_gc

### PR DESCRIPTION
**Pull request by nilshamerlinck**
Migration of https://github.com/OCA/server-tools/pull/1665 to 13.0

### CODE REVIEW

**Review by fshah-initos — APPROVED** [review]
Looks good to me
Functional test and code review.

**Comment by dsolanki-initos** [comment]
it would be nice if we get the reviews here.

**Comment by dsolanki-initos** [comment]
it would be nice if we get the reviews here.

**Comment by dsolanki-initos** [comment]
it would be nice if we get the reviews here.

**Comment by dsolanki-initos** [comment]
it would be nice if we get the reviews here.

**Comment by dsolanki-initos** [comment]
It would be great if we get the reviews.

**Comment by dsolanki-initos** [comment]
Hi, @hparfr it would be nice if you review this pull as you reviewed the v12 pull.

**Review by fshah-initos — COMMENTED** [review]
Hi, @hparfr it would be nice if you review.

**Comment by ikapasi-initos** [comment]
Hello @hparfr it would be nice if you review this pull.

**Review by hparfr — APPROVED** [review]
Code review

**Review by ikapasi-initos — APPROVED** [review]
Code review and functional test
LGTM

**Pull request merged**
