### PR TITLE
[RFR] Explicit access rights so that tests can run

### PR DESCRIPTION
**Pull request by StefanRijnhart**
Fixes #505

### CODE REVIEW

**Comment by gurneyalex** [comment]
thanks for looking into this.

**Comment by StefanRijnhart** [comment]
Travis is green!

**Comment by gurneyalex** [comment]
:+1: 

@StefanRijnhart any idea why splitting the tests of dabase_cleanup is required?

**Comment by StefanRijnhart** [comment]
@gurneyalex I was on holiday but it would be good to find out what goes wrong indeed. Need to coordinate with @hbrunn

**Pull request merged**
