### PR TITLE
[11.0][ADD] profiler icon

### PR DESCRIPTION
**Pull request by thomaspaulb**

### CODE REVIEW

**Comment by thomaspaulb** [comment]
@gjotten @ntsirintanis

**Review by gjotten — APPROVED** [review]
Lgtm, professionally done.

**Review by legalsylvain — APPROVED** [review]
Nice ! Could you do the same PR against the more recent version of the module ?

**Comment by thomaspaulb** [comment]
@legalsylvain I think this is the newest one that is merged, the 12.0 one is only a PR.

**Comment by thomaspaulb** [comment]
@dreispt typo

**Comment by thomaspaulb** [comment]
@hbrunn Could you merge?

**Pull request merged**
