### PR TITLE
[MIG] 14.0 base_technical_user

### PR DESCRIPTION
**Pull request by PierrickBrun**
Nothing changed from v13.0

### CODE REVIEW

**Review by sebastienbeau — APPROVED** [review]
LGTM Code review

can you check why runbot is red?

**Comment by PierrickBrun** [comment]
> LGTM Code review
> 
> can you check why runbot is red?

@sebastienbeau I forced rebuild and it is green now

**Review by atchuthan — APPROVED** [review]
code :+1:

**Pull request merged**
