### PR TITLE
[FIX][12.0] add safe_eval context

### PR DESCRIPTION
**Pull request by mourad-ehm**
Add safe_eval context to allow evaluation domain with python params ex(use ref method to get object by xml_id).

### CODE REVIEW

**Comment by mourad-ehm** [comment]
ping @hparfr , @florian-dacosta, @bealdav , @pedrobaeza

**Review by hparfr — APPROVED** [review]

**Review by bguillot — APPROVED** [review]

**Comment by dreispt** [comment]
Travis is red. A rebase might fix it.

**Comment by thomaspaulb** [comment]
@mourad-ehm Could you rebase and solve the conflict in manifest

**Pull request closed without merging**
