### PR TITLE
[FIX] renamed 'email_template' m2o field in 'email_template_id' in sched...

### PR DESCRIPTION
**Pull request by bealdav**
in scheduler_error_mailer module

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Why renaming it? Nowadays, I'm preferring notation without '_id', because most of the time you use dot notation for accesing subfields, and it gets weird with that name. For example, _order.partner.name_ instead of _order_id.partner_id.name_. It's also more weird if you do _order_id.id_, because there are two 'id' very close each other. The only use I can see is for distinguishing relation field (many2one, many2many, etc) from other fields, but having a good field name, you would know.

**Comment by dreispt** [comment]
I disagree with Perdo: IMO the `_id`  and `_ids` are useful conventions.
But changing a field name will break existing installations so it should be avoided.
It would be best to do that when porting to v8.

**Comment by bealdav** [comment]
Hi Pedro, 
99% of m2o fields are my_field_id.
I don't know what name I prefer but I can't do 5000 PR to rename all m2o without id, don't you think ?
I prefer consistency even if could have an idea about convention choice. 
When I see onename_id it's easy to me to think 'foreign key' and foreign keys implies to have a particular attention to them in coding.
Without 'id' I think char or text if no string 'date' in name
Thanks

**Comment by nbessi** [comment]
Hello, 

Thanks for the patch.

I agree with @dreispt 

For me there is a kind of tacit convention _id means m2o _ids mean o2n m2m .
But anyway, changing a column name, if it does not fix something should not be accepted until module migration as we do not want to break other devs.

:-1:

**Comment by bealdav** [comment]
Hello, 
Is it Ok if I switch my PR to 8.0 ?

**Comment by pedrobaeza** [comment]
I'm not talking of renaming all of the existing fields, but to keep the non '_id' fields, and taking into account for future developments.

**Comment by dreispt** [comment]
@bealdav Renaming fields is acceptable when porting to 8.0

**Comment by pedrobaeza** [comment]
...but providing the corresponding migration script.

**Comment by bealdav** [comment]
Is 'oldname' attribute is accepted in field definition ? Included in this proposal.
Framework provide this feature, it works and field will never renamed, isn't it ?
Thanks

**Comment by pedrobaeza** [comment]
OK, I think 'oldname' it's handled by standard upgrade machinery, but I abstain, as I say about my preferences.

**Comment by hbrunn** [comment]
`oldname` is fine to use for that purpose, but as the previous posters wrote, renaming a column without necessity is a very bad idea (think of customer modules depending on this one). Please do that when porting to 8.0. Meanwhile, I close this PR.

**Comment by bealdav** [comment]
Ok, 
You're right Holger. As I said, I'll switch my PR to 8.0

**Pull request closed without merging**
