### PR TITLE
[MIG][14.0] attachment_queue: Migration to 14.0

### PR DESCRIPTION
**Pull request by kevinkhao**

### CODE REVIEW

**Review by len-foss — APPROVED** [review]
Code review: LGTM
You could squash some intermediary administrative commits ([UPD] ones) to clean up the git history a bit, but that's fine with me.

**Comment by hparfr** [comment]
@kevinkhao can you resolve conflicts ?

**Comment by kevinkhao** [comment]
> @kevinkhao can you resolve conflicts ?

done

**Review by hparfr — APPROVED** [review]

**Comment by kevinkhao** [comment]
merge with https://github.com/OCA/server-tools/pull/2001 because the modules are destined to be used together for now anyways; to simplify the merge

**Pull request closed without merging**
