### PR TITLE
[12.0][FIX] company_country: handle nonexisting env variable gracefully

### PR DESCRIPTION
**Pull request by hbrunn**
@moylop260 @luisg123v I'd like to make this module play nice with runboat (we can't inject env vars there, and probably shouldn't want that), does this totally destroy the point of this module for you or is this change fine?

### CODE REVIEW

**Review by luisg123v — CHANGES_REQUESTED** [review]
I agree with the changes, I'd just adjust commit message. I would:
- Add ":" after module name
- Add a small description on why is this change necessary

**Comment by hbrunn** [comment]
thanks, done

**Comment by moylop260** [comment]
👍 
LGTM

I think the user even will not see the logs error and the instance will be displayed with l10n wrong module but if there is not another solution so go ahead

The good news is new versions has already fixed this matter

and maybe the new instances for old versions are less

so 👍 

(I even have the doubt about queue_* modules since that they will need environment variables to be tested in runboat)

**Comment by luisg123v** [comment]
@hbrunn typo in description: neccessary -> necessary

**Comment by hbrunn** [comment]
thanks, I keep doing this wrong since I learned English I think

@moylop260 I think the queue modules default do something safe for similar reasons, stuff like https://github.com/OCA/queue/blob/14.0/queue_job/jobrunner/runner.py#L170

**Review by luisg123v — APPROVED** [review]
/ocabot merge minor

**Comment by hbrunn** [comment]
@luisg123v I repeated your command as you don't seem to have writing permissions in this repo

**Pull request merged**
