### PR TITLE
[16.0][FIX] jsonifier: Call callable for unknown field

### PR DESCRIPTION
**Pull request by lmignon**
If a field name into the parser definition doesn't exist into the model but is resolved by a callable, call the method. Prior to this change, it was o more possible to define computed json value for custome keys

### CODE REVIEW

**Comment by thomaspaulb** [comment]
@lmignon Could you rebase to retrigger tests?

**Comment by lmignon** [comment]
@thomaspaulb rebase done

**Review by thomaspaulb — APPROVED** [review]

**Pull request merged**
