### PR TITLE
WIP - Forward port of remote_logs

### PR DESCRIPTION
**Pull request by bwrsandman**
Implementation by @xrg of #35 taken from http://git.hellug.gr/?p=xrg/openobject-addons;a=commit;h=fc321ca2ee1304

Code is quite old and probably needs to be updated

### CODE REVIEW

**Comment by rvalyi** [comment]
@bwrsandman I assume you are aware that in v8 logs go into the database too. What do you think about that and how will it relates (or not) with this module? Thanks.

**Comment by bwrsandman** [comment]
I wasn't aware of this.

**Comment by hbrunn** [comment]
Two questions: Is the name actually appropriate? To me, the name implies logging to a remote location, wouldn't something involving http be more appropriate?
Logging can include sensitive information, so I think users should be made aware that this path should be blocked by their proxy or something similar.

**Comment by pedrobaeza** [comment]
This one is not going to be worked anymore, so I close.

**Pull request closed without merging**
