### PR TITLE
[ADD] stock_enterprise_remove

### PR DESCRIPTION
**Pull request by woodbrettm**
This module removes any settings marked as enterprise from the stock res_config view.

Cheers,
Brett

@lasley

### CODE REVIEW

**Comment by lasley** [comment]
LGTM 👍

**Comment by elicoidal** [comment]
:+1:

**Comment by rvalyi** [comment]
:+1:

**Comment by pedrobaeza** [comment]
You have merged all of this stuff including the SVG icon that it's not needed. Now, the repository is going to contain a diff history adding them and lately removing it, making very big (well, bigger than before). The only solution is to amend the commits, but this means that some people making `git pull` will receive an error. What do you think?

**Pull request merged**
