### PR TITLE
[12.0] [UPD] pre-commit [FIX] letsencrypt and module_auto_update tests

### PR DESCRIPTION
**Pull request by thomaspaulb**
- Rebase and fixup of https://github.com/OCA/server-tools/pull/2525
- Includes https://github.com/OCA/server-tools/pull/2215 to fix failing `base_exception` tests
- Includes https://github.com/OCA/server-tools/pull/2647/files to fix `letsencrypt` tests
- Includes https://github.com/OCA/server-tools/pull/1981/commits/4f6cbfb10687f7e05e9997bd977b1204086ffb24 to fix `module_analysis` tests
- Adds a small fix to a `database_cleanup` logger.info statement to fix `database_cleanup` tests
- Adds a fix as suggested in #2296 to fix `company_country` tests
- Includes https://github.com/OCA/server-tools/pull/2586 and parts of https://github.com/OCA/server-tools/pull/2725 to fix `sentry` tests

### CODE REVIEW

**Comment by thomaspaulb** [comment]
@OCA/tools-maintainers Lots of cherry picks, now 12.0 branch is green again! Can someone take a second look for sanity and then merge?

**Review by hbrunn — APPROVED** [review]

**Comment by thomaspaulb** [comment]
@pedrobaeza Silly question but: since this touches multiple modules, should I merge with nobump, or with patch?

I think patch, because that would also produce new Pypi packages for each module, but just asking to be sure.

**Comment by pedrobaeza** [comment]
Yes, go with `patch`.

**Pull request merged**
