### PR TITLE
[9.0][MIG] sentry

### PR DESCRIPTION
**Pull request by azmeuk**
This is a migration from the 8.0 branch. Almost no code has changed.

### CODE REVIEW

**Comment by azmeuk** [comment]
@Menestrels @IvanShirokikh @naglis @aisopuro @luisg123v Can you please review this pull request?
That should be pretty quick :)

**Review by luisg123v — CHANGES_REQUESTED** [review]
There is only one commit, yours one. Shouldn't previous ones also be here?

**Comment by azmeuk** [comment]
I did not know that was required, but I can make the history appear if you prefer.

**Comment by luisg123v** [comment]
@azmeuk it's desirable, [here](https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-9.0#howto) is the documentation on how to do it.

**Comment by azmeuk** [comment]
@luisg123v This is done. Thank you for the links.

**Review by luisg123v — APPROVED** [review]

**Comment by azmeuk** [comment]
@Menestrels @IvanShirokikh @naglis @aisopuro 

By chance, would you have 5 minutes to spend reviewing this patch? Thank you in advance

**Comment by azmeuk** [comment]
@Menestrels @IvanShirokikh @naglis @aisopuro
Up. Any chance you can quickly review this patch?

**Comment by aisopuro** [comment]
Sorry, I don't really feel like I know enough about the Sentry module to say one way or another.

**Comment by azmeuk** [comment]
Closing this as it won't probably never be merged.

**Pull request closed without merging**
