### PR TITLE
[16.0][MIG] iap_alternative_provider: Migration to 16.0

### PR DESCRIPTION
**Pull request by FernandoRomera**

### CODE REVIEW

**Comment by FernandoRomera** [comment]
#2412

**Review by AntoniRomera — APPROVED** [review]

**Review by MRomeera — APPROVED** [review]
Ok

**Comment by fanchlegal** [comment]
Hi @FernandoRomera, there is a bug I think in the xml view. I try to use it on my new odoo 16, and when I install this module I can not change the field company_ids no more. 
So i try changing this code : 

```
<xpath expr="//group[@name='account']" position="before">
      <group string="Info" name="info">
          <field name="provider" />
          <field name="name" />
          <field name="company_ids" position="move" />
      </group>
  </xpath>
```

            
With this one : 

```
<xpath expr="//group[@name='account']" position="before">
    <group string="Info" name="info">
        <field name="provider" />
        <field name="name" />
    </group>
</xpath>
<xpath expr="//group[@name='info']" position="inside">
   <field name="company_ids" position="move" />
</xpath>
```
And now it's working for me. 

Have you the same problem or is it only on my Odoo ?

**Pull request merged**
