### PR TITLE
[15.0][MIG] sequence_python

### PR DESCRIPTION
**Pull request by epanisset**

### CODE REVIEW

**Review by sebalix — APPROVED** [review]

**Review by yankinmax — APPROVED** [review]

**Comment by thomaspaulb** [comment]
@epanisset Do you have any idea why the wrappers were added around the random functions? I believe it was this PR that added it, the migration commit to 14.0.

**Comment by epanisset** [comment]
> @epanisset Do you have any idea why the wrappers were added around the random functions? I believe it was this PR that added it, the migration commit to 14.0.

Absolutely no idea.. This migration has been done using oca_port (https://github.com/OCA/oca-port). 
I am a functionnal consultant. 

@sebalix any idea? :)

**Pull request merged**
