### PR TITLE
[SEC] auth_generate_password, fetchmail_attach_from_folder: fix unsaf…

### PR DESCRIPTION
**Pull request by gurneyalex**
…e eval

### CODE REVIEW

**Comment by legalsylvain** [comment]
:+1: Thanks.

**Comment by sebalix** [comment]
:+1:

**Comment by pedrobaeza** [comment]
Travis says:

```
No module named opener.tools.safe_eval
```

Isn't the import sentence `from opener.tools import safe_eval`?

**Comment by gurneyalex** [comment]
@pedrobaeza that's a typo (missing `p` at the end of `openerp`)...

**Comment by gurneyalex** [comment]
@pedrobaeza fixed :smile_cat:

**Comment by pedrobaeza** [comment]
Oh, right... let's see the CIs result and I'll merge

**Comment by antespi** [comment]
:+1:

**Comment by hbrunn** [comment]
I'll merge this as we have enough approvals and travis' complaints are unrelated

**Pull request merged**
