### PR TITLE
[8.0] database_cleanup fix tests

### PR DESCRIPTION
**Pull request by hbrunn**
cf #509

### CODE REVIEW

**Comment by gurneyalex** [comment]
:+1: (and very favorable to fast tracking)

**Comment by pedrobaeza** [comment]
:+1:

**Comment by gurneyalex** [comment]
@hbrunn we are still experiencing semi random build failures on the 8.0 branch, since this PR was merged:
- https://travis-ci.org/OCA/server-tools/builds/151397863
- https://travis-ci.org/OCA/server-tools/builds/151383320
- https://travis-ci.org/OCA/server-tools/builds/152153713

Could it be that your fix missed something?

**Comment by rvalyi** [comment]
I confirm this issue, got these Travis heisenbugs on this other PR of my own https://travis-ci.org/akretion/server-tools/jobs/152596166

**Comment by hbrunn** [comment]
can you comment out https://github.com/hbrunn/server-tools/blob/53e43317b6ade35477ed5dff9c8e43d6aef2fbb9/database_cleanup/tests/test_database_cleanup.py#L59-L72 and see what happens then?

**Comment by StefanRijnhart** [comment]
Cool trick, again.

**Pull request merged**
