### PR TITLE
Skip init if raven is not available on the system

### PR DESCRIPTION
**Pull request by bwrsandman**
I've been informed that modules and repos using server tools are getting errors related to raven when the module is not installed.

This is a quick fix which skips everything when raven is not available.

If someone has a solution to have this code only run when sentry is installed, please let me know so I can integrate it.

### CODE REVIEW

**Comment by dreispt** [comment]
This is similar to https://github.com/OCA/server-tools/issues/89

**Comment by lepistone** [comment]
In general the problem is that odoo imports (in the python sense) the modules that are not installed. So if we don't have python dependencies of modules that are not installed, they crash.

For that reason, I agree we want to catch and ignore import errors (otherwise, for an **installed** module, it's not bad to get an `ImportError`).

This can potentially affect many people, and I'm for merging that quickly even if it's not ideal. :+1: 

Thanks!

**Comment by joaoalf** [comment]
I agree with @lepistone about quick merge.

:+1:

**Comment by bwrsandman** [comment]
This isn't an ideal solution, but it's a quick one.

**Comment by foutoucour** [comment]
:+1:

**Comment by bwrsandman** [comment]
@foutoucour, @joaoalf please make sure this patch fixes your problem. I haven't tested this.

**Comment by joaoalf** [comment]
@bwrsandman 

I just tested and it works.
:+1:

**Comment by bwrsandman** [comment]
Okay, please merge!

**Comment by max3903** [comment]
:+1:

**Comment by foutoucour** [comment]
A bit late, but tested and it works :)

On Wed, Dec 17, 2014 at 11:53 AM, max3903 notifications@github.com wrote:

> [image: :+1:]
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/OCA/server-tools/pull/98#issuecomment-67353356.

## 
- Jordi Riera, Connecting Softwares and people.
  +1 438 930 3718
  www.linkedin.com/in/jordirieracg/ http://ca.linkedin.com/in/jordirieracg/

**Pull request merged**
