### PR TITLE
[14.0][FIX] only play onchange on editable field

### PR DESCRIPTION
**Pull request by sebastienbeau**
solve issue when have limited access right (do not try to read none accesible field)
solve perf issue by avoiding to compute computed readonly field

TODO
- [ ] write test case

### CODE REVIEW

**Comment by sebastienbeau** [comment]
@PierrickBrun

**Review by legalsylvain — COMMENTED** [review]
Hi sebastien. Thanks for this patch. I wonder if it s a good idea to remove fields if user doesnt have correct access write. I fear that it let data in inconsitent state. 
Could you provide valid use case when it is ok to do that ?
Thanks.

**Review by PierrickBrun — COMMENTED** [review]
I agree with @legalsylvain , apart from that, that looks very good ! Is the performance boost noticeable ?

**Comment by sebastienbeau** [comment]
Hi I will be back soon on this point with test and real case.
My initial issue it that I am using a user for an API with restricted access.
When I play the onchange on partner it will compute field like "rma_ids", stock information... so at this end I request access to a lot of object.
Do not merge yet, it's quiet experimental

**Comment by legalsylvain** [comment]
Hi. Well, logged with your limited user, can you create an item (without ``onchange_helper`` installed) ? 
If not, you should not have the possibility to do it with the module installed.
At first glance, If an onchange requires access right, you should give the access to your user.

**Review by alexis-via — APPROVED** [review]

**Pull request closed without merging**
