### PR TITLE
[14.0][OU-MIG] upgrade_analysis: add migration scripts

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Just in case.

The module rename is added in https://github.com/OCA/OpenUpgrade/pull/2629.

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
@pedrobaeza

**Comment by pedrobaeza** [comment]
I don't think this is going to happen, as this tool can be uninstalled and re-install. Moreover, I doubt the records created from one version serves for another, so I would instead write in the README about not migrating having this module installed.

**Comment by MiquelRForgeFlow** [comment]
I know this might don't happen, but just for the fun of continuation, as a keepsake of the old openugrade_records. I think it doesn't add any harm in adding that :)

I could also add a text in the readme, no problem.

**Comment by pedrobaeza** [comment]
But the main question remains: if you generate the records for the analysis in N - 1, are that records removed in version N?

**Comment by MiquelRForgeFlow** [comment]
No, why should them be removed? The person who happens (if happens) migrating a db with the old module installed will decide. Here it's just the table renames, to make the migration work. I don't mind here if there are generated records or not.

**Comment by pedrobaeza** [comment]
But that's why I told you about never do that, as the module will do wrong things if kept migrating from one version to another.

**Comment by pedrobaeza** [comment]
@StefanRijnhart do you follow my rationale?

**Comment by MiquelRForgeFlow** [comment]
> write in the README about not migrating having this module installed.

I added a text in the readme.

**Comment by StefanRijnhart** [comment]
The upgrade records are supposed to be volatile. Up to 13.0, they were truncated before each new analysis: https://github.com/OCA/OpenUpgrade/blob/13.0/odoo/addons/openupgrade_records/models/generate_records_wizard.py#L38-L44
But this is missing in this module: https://github.com/OCA/server-tools/blob/14.0/upgrade_analysis/wizards/upgrade_generate_record_wizard.py#L20-L27. @legalsylvain what was the reason to leave it out?

Having that said, there is no harm in having this migration here as far as I'm concerned.

**Comment by pedrobaeza** [comment]
OK, let's merge it and wait for @legalsylvain to say if the clean operation should be restored.

**Comment by legalsylvain** [comment]
> @legalsylvain what was the reason to leave it out?

Hi all. The offending commit seems this one : https://github.com/OCA/server-tools/commit/f8f40d36174c9bc04ec6d4db93c7d856f7f7c1fe#diff-cea8bc48b215b1ea3ddbc78a8fdd4eb94fd4e9c1670cfa07199e820dfb21cb05L36

I must confess I don't remember why I removed that lines, and the commit message doesn't help me...

So yes, if we want to call many times the ``generate`` function, data should be dropped, indeed. What I just don't understand in the previous implementation is the test, to check if tables exists. if the module ``upgrade_anlysis`` is installed, the two tables should exist. Don't you tink ? 

So i'm in favour to readd simply

    self.env.cr.execute("TRUNCATE upgrade_attribute, upgrade_record;")

Anyway, thanks @MiquelRForgeFlow to play with the new implementation of ``upgrade_analysis`` module and OpenUpgrade and thanks for your fixes !

**Comment by pedrobaeza** [comment]
OK for me

**Comment by MiquelRForgeFlow** [comment]
Can I add this in the other PR o make a new one?

**Comment by pedrobaeza** [comment]
I think you can add it as separate commit.

**Comment by MiquelRForgeFlow** [comment]
Ok, done in https://github.com/OCA/server-tools/pull/2057.

**Comment by StefanRijnhart** [comment]
Thanks @legalsylvain and thanks @MiquelRForgeFlow for the follow-up.

**Pull request merged**
