### PR TITLE
[16.0][IMP] tracking_manager: Hide Custom Tracking if the model does not inherit from mail.thread

### PR DESCRIPTION
**Pull request by victoralmau**
Hide Custom Tracking if the model does not inherit from `mail.thread`

Please @pedrobaeza can you review it?

@Tecnativa TT50571

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Comment by CRogos** [comment]
This change would prevent tracking sale.order.line values in sale.order:
image

Nevertheless I agree we also had some trouble creating product.category after activating tracking on this model.

**Comment by pedrobaeza** [comment]
Uhm, how can we detect that situations...?

**Comment by pedrobaeza** [comment]
Or we can simply silently avoid the error:

```
AttributeError: 'model' object has no attribute 'message_post_with_view'
```

**Comment by CRogos** [comment]
How about this suggestion? https://github.com/OCA/server-tools/pull/3021

**Comment by pedrobaeza** [comment]
Let's go with #3021

**Pull request closed without merging**
