### PR TITLE
[ADD] Added admin_technincal_features module.

### PR DESCRIPTION
**Pull request by foutoucour**
A simple module that check the box of technical features for adminastrator user (base.user_root).

### CODE REVIEW

**Comment by bwrsandman** [comment]
:+1:

**Comment by jholze** [comment]
A long missed feature. Thanks !!

**Comment by tafaRU** [comment]
:+1:

**Comment by dreispt** [comment]
I remember reading in another review that OCA modules should have as icon the a company brand .
IMO the license text in the empty `__init__.py`is unnecessary.

**Comment by pedrobaeza** [comment]
Yes, company brand logos cannot be put in OCA modules, so please remove it. Until then, :-1:

**Comment by foutoucour** [comment]
The failures seem not related to the pull I am doing.
Any advice on how to moving on here?

**Comment by dreispt** [comment]
:+1:

**Comment by pedrobaeza** [comment]
:+1: 

Errors are unrelated and will be solved in other PR.

I merge this one.

**Pull request merged**
