### PR TITLE
[8.0] FIX auto_backup: avoid overwrinting of configuration at module update

### PR DESCRIPTION
**Pull request by eLBati**
(already fixed in 9.0 and 10.0)

### CODE REVIEW

**Comment by hurrinico** [comment]
IMHO :+1:

**Comment by astirpe** [comment]
👍

**Review by sebalix — APPROVED** [review]

**Review by sebalix — CHANGES_REQUESTED** [review]
Sorry, can you bump the version number please? `8.0.1.0.1`->`8.0.1.0.2`

**Comment by eLBati** [comment]
@sebalix thanks, done

**Review by sebalix — APPROVED** [review]

**Review by tafaRU — APPROVED** [review]

**Review by astirpe — APPROVED** [review]

**Pull request merged**
