### PR TITLE
[16.0][FIX] letsencrypt: re-enable tests

### PR DESCRIPTION
**Pull request by hbrunn**

### CODE REVIEW

**Review by MiquelRForgeFlow — APPROVED** [review]

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge patch

**Comment by pedrobaeza** [comment]
That sentry error that Miquel has mentioned in other PR...

**Comment by hbrunn** [comment]
it's not sentry, it's [auditlog](https://github.com/OCA/server-tools/actions/runs/12295037243/job/34311080746?pr=3143#step:8:256), fixed in https://github.com/OCA/server-tools/pull/3146

**Pull request merged**
