### PR TITLE
[14.0][backport] database_cleanup: Prevent deletion of columns added in the init method of the model.

### PR DESCRIPTION
**Pull request by hparfr**
purge_column:  issues with `totp_secret` field 
See issue https://github.com/OCA/server-tools/issues/2851.

Backport of from v16 https://github.com/OCA/server-tools/issues/2851

### CODE REVIEW

**Comment by hparfr** [comment]
@MrGigSolutions

**Comment by legalsylvain** [comment]
The PR is empty.

**Comment by hparfr** [comment]
ooops :)

**Comment by hparfr** [comment]
@legalsylvain commit added

**Review by rvalyi — APPROVED** [review]

**Comment by rvalyi** [comment]
BTW the original v16 PR is actually #2852

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge patch

**Pull request merged**
