### PR TITLE
[16.0][MIG] sentry: Migration to 16.0

### PR DESCRIPTION
**Pull request by SodexisTeam**

### CODE REVIEW

**Review by odoo-sh — APPROVED** [review]

**Review by StefanRijnhart — APPROVED** [review]

**Review by amkarthik — APPROVED** [review]

**Comment by amkarthik** [comment]
@Versada @barsi @moylop260 @fernandahf Can we get this merged?

**Comment by atchuthan** [comment]
@OCA/deployment-tools-maintainers Can we get this merged?

**Review by atchuthan — APPROVED** [review]

**Pull request merged**
