### PR TITLE
[17.0][MIG] dbfilter_from_header

### PR DESCRIPTION
**Pull request by nilshamerlinck**
no httpocalypse this year, so no change needed :)

### CODE REVIEW

**Review by ryanc-me — APPROVED** [review]

**Review by mostafabarmshory — APPROVED** [review]
TX.

**Comment by mostafabarmshory** [comment]
Dear all,

I could not understand why this migration was not merged?! 
All tests are passed and @pedrobaeza commands the bot to merge. What is the problem?

**Pull request merged**
