### PR TITLE
[12.0][FIX] onchange_helper: read inverse field values without side effects

### PR DESCRIPTION
**Pull request by hbrunn**
this is a fix for https://github.com/OCA/server-tools/pull/2075, see discussion from https://github.com/OCA/server-tools/pull/2075#issuecomment-870454021

@hparfr @len-foss please amend the tests with your cases, the test added here breaks with the current code

### CODE REVIEW

**Review by StefanRijnhart — APPROVED** [review]

**Review by rousseldenis — APPROVED** [review]
I can confirm it solves AccessError of this comment https://github.com/OCA/server-tools/pull/2075#issuecomment-870454021

@len-foss It solves too the shopinvader 12.0 branch that is red since https://github.com/OCA/server-tools/pull/2075

**Comment by rousseldenis** [comment]
@StefanRijnhart

**Comment by len-foss** [comment]
Sorry for the inconvenience caused and all that, but I don't have any time. So yeah I approve any change or revert.

**Comment by rousseldenis** [comment]
@guewen

**Comment by rousseldenis** [comment]
@OCA/core-maintainers Thanks

**Pull request merged**
