### PR TITLE
Add requirements.txt

### PR DESCRIPTION
**Pull request by dreispt**

### CODE REVIEW

**Comment by max3903** [comment]
:+1:

**Comment by sebalix** [comment]
:+1:

**Comment by hbrunn** [comment]
travis doesn't like this change

**Comment by dreispt** [comment]
@hbrunn I feared that could happen. I guess that means some digging on MQT.

**Comment by dreispt** [comment]
The [call](https://github.com/OCA/maintainer-quality-tools/blob/bb79045675ee1e8f08edfdd021f83c2e85a34401/travis/travis_install_nightly#L52) on `clone_oca_dependencies` is not doing anything:https://travis-ci.org/OCA/server-tools/jobs/109363437#L186

**Comment by moylop260** [comment]
@dreispt 
Let me see this case

**Comment by dreispt** [comment]
@moylop260 I think MQT is not installing the main repo's requirements.txt, [only the dependencies](https://github.com/OCA/maintainer-quality-tools/blob/master/travis/clone_oca_dependencies#L80).
Either this is added, or we need to pip install them on the repo `.travis.yml`.
I would rather have the first...

**Comment by moylop260** [comment]
Fix here: https://github.com/OCA/maintainer-quality-tools/pull/314
Let me see the result of .travis.yml

**Comment by moylop260** [comment]
Now is green
:+1:

**Comment by dreispt** [comment]
Thanks!

**Pull request merged**
