### PR TITLE
[14.0][IMP] base_jsonify: review

### PR DESCRIPTION
**Pull request by florentx**
Cosmetic adjustments while learning `base_jsonify`:
 - avoid 1 letter function name in `base_jsonify/models/utils.py`
 - rename `base_jsonify/models/ir_export.py` --> `base_jsonify/models/ir_exports.py`
 - documentation: `odoo api` --> `Odoo API`
 - documentation: `json` --> `JSON`
 - minor typos

### CODE REVIEW

**Review by gurneyalex — APPROVED** [review]

**Review by ivantodorovich — APPROVED** [review]
LG

**Comment by StefanRijnhart** [comment]
Can you rebase to resolve conflicts?

**Comment by florentx** [comment]
> Can you rebase to resolve conflicts?

Done

**Review by StefanRijnhart — APPROVED** [review]

**Comment by StefanRijnhart** [comment]
Thanks!

/ocabot merge minor

**Pull request merged**
