### PR TITLE
16.0 mig auto backup

### PR DESCRIPTION
**Pull request by dani-xtendoo**
migration of the auto_backup module to version 16

### CODE REVIEW

**Review by manuelcalerosolis — APPROVED** [review]
Functional review ok!

**Comment by dalonsod** [comment]
Hello @dani-xtendoo , thanks for the contribution!

Inspecting commit history, last commit doesn't follow OCA's guidelines (see https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0), could you take a look?

Thanks!

**Comment by tafaRU** [comment]
@OCA/tools-maintainers this could be closed in favour of https://github.com/OCA/server-tools/pull/2712

**Comment by tafaRU** [comment]
@@OCA/tools-maintainers please see https://github.com/OCA/server-tools/pull/2514#issuecomment-1713812398 and update https://github.com/OCA/server-tools/issues/2412

**Pull request closed without merging**
