### PR TITLE
11.0 mig dbfilter from header

### PR DESCRIPTION
**Pull request by yelizariev**
PR with updates from https://github.com/OCA/server-tools/pull/1137

### CODE REVIEW

**Comment by jaredkipe** [comment]
LGTM

**Review by ilmir-k — APPROVED** [review]
I've just checked this ported module on my test server (with nginx), it works correctly :+1:

**Comment by ilmir-k** [comment]
@pedrobaeza could you review it please? There are not many changes

**Comment by pedrobaeza** [comment]
Sorry, I'm not a user of this module, so I can't say if it's correctly migrated.

**Comment by jaredkipe** [comment]
Can we merge this?

**Comment by pedrobaeza** [comment]
Well, I see that you haven't reviewed properly (putting the approval), so I didn't see it your comment, but as there are 2 reviews counting yours and more than 5 days, I merge.

**Comment by jaredkipe** [comment]
@pedrobaeza Apologies, I see nothing in my UI that would indicate that I can do anything other than comment on this.
What should I be looking for to properly 'put the approval' on this?

**Comment by pedrobaeza** [comment]
Please see the image:

seleccion_005

**Comment by pedrobaeza** [comment]
But now you can't approve as it's merged. Next time :wink:

**Review by jaredkipe — COMMENTED** [review]
LGTM

**Comment by jaredkipe** [comment]
Oh apparently I can! Thanks!
Stange.. twice with one click?

**Pull request merged**
