### PR TITLE
[16.0][MIG] base_import_odoo

### PR DESCRIPTION
**Pull request by thomaspaulb**
Continuation of https://github.com/OCA/server-tools/pull/3004

### CODE REVIEW

**Review by len-foss — APPROVED** [review]

**Review by hbrunn — APPROVED** [review]
I think it's good to have maintainers recorded on modules, would you mind adding yourself and me?

**Comment by thomaspaulb** [comment]
@hbrunn Added

**Review by MiquelRForgeFlow — APPROVED** [review]

**Comment by thomaspaulb** [comment]
```
2024-12-12 12:32:49,277 415 INFO odoo odoo.addons.auditlog.tests.test_multi_company: ====================================================================== 
2024-12-12 12:32:49,277 415 ERROR odoo odoo.addons.auditlog.tests.test_multi_company: FAIL: TestMultiCompany.test_group_set_users_with_auditlog
Traceback (most recent call last):
  File "/__w/server-tools/server-tools/auditlog/tests/test_multi_company.py", line 113, in test_group_set_users_with_auditlog
    self.test_group_set_users()
  File "/__w/server-tools/server-tools/auditlog/tests/test_multi_company.py", line 86, in test_group_set_users
    self.assertEqual(group_with_user.users, self.user2)
AssertionError: res.users(11, 12) != res.users(12,)
```

:-/

**Comment by hbrunn** [comment]
fixed in https://github.com/OCA/server-tools/pull/3146

**Pull request merged**
