### PR TITLE
[8.0][ADD] Add list manipulation operations to base_view_inheritance_extension.

### PR DESCRIPTION
**Pull request by NL66278**
list_add might be used to change a value for an attribute for instance from states='draft,open' to 'draft,open,valid'. list_remove can be used to change for instance 'draft,proforma,open' to 'draft,open'.

### CODE REVIEW

**Review by hbrunn — APPROVED** [review]

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
I have cherry-picked the PR for 9.0, checking that tests are correct, and increase version number in that branch.

**Comment by NL66278** [comment]
@pedrobaeza I do not see the cherrypicking on the 9.0 branch. Am I looking in the wrong place?

**Comment by pedrobaeza** [comment]
Sorry, I forget to push. It's now in https://github.com/OCA/server-tools/commit/d3494cc334481a89aa57178ef28fe568d85d51d6

**Comment by NL66278** [comment]
Got it! Thanks!

**Pull request merged**
