### PR TITLE
[14.0][MIG] html_text : Migration to 14.0

### PR DESCRIPTION
**Pull request by hkapatel-initos**
Migration to 14.0

### CODE REVIEW

**Comment by hkapatel-initos** [comment]
@wpichler It would be great if you could add reviews here.

**Comment by hkapatel-initos** [comment]
@etobella It would be nice if you could review the PR.

**Comment by hkapatel-initos** [comment]
@ernestotejeda can you please review this PR ?

**Review by dsolanki-initos — APPROVED** [review]
No major change. LGTM

**Comment by hkapatel-initos** [comment]
@victoralmau can you please review this PR?

**Review by victoralmau — APPROVED** [review]
Code review OK.

**Comment by hkapatel-initos** [comment]
@chienandalu Can you please try to merge this PR?

**Review by chienandalu — COMMENTED** [review]
@hkapatel-initos I'm afraid I'm not PSC in this repo

**Comment by hkapatel-initos** [comment]
> @hkapatel-initos I'm afraid I'm not PSC in this repo
okay

**Comment by hkapatel-initos** [comment]
@pedrocasi @OCA-git-bot Can you please try to merge this PR?

**Comment by hkapatel-initos** [comment]
maintainer can you  please try to merge this pr

**Comment by hkapatel-initos** [comment]
@Stéphane Bidoul can you please review this PR?

**Comment by hkapatel-initos** [comment]
@dreispt  It would be great if you could try to merge it again.

**Comment by hkapatel-initos** [comment]
Hello maintainers,
 It would be great if you could try to merge it again.

**Comment by hkapatel-initos** [comment]
Hello maintainers,
Can you please try to merge it again?

**Pull request merged**
