### PR TITLE
[15.0][MIG] scheduler_error_mailer: Migration to 15.0

### PR DESCRIPTION
**Pull request by annadurai-sodexis**

### CODE REVIEW

**Review by CasVissers-360ERP — APPROVED** [review]
Functional review.

**Comment by pedrobaeza** [comment]
As the PR title was not correctly formatted, searching for the module name doesn't match with this PR, so my colleague has created another PR: #2553 

Can you rebase to see if you have a green CI? If not, can we supersede this PR?

**Comment by pedrobaeza** [comment]
I see also that the commit message is not correct for the migration one.

**Comment by pedrobaeza** [comment]
Let's go with #2553 if you don't mind.

**Pull request closed without merging**
