### PR TITLE
[MIG] sql_request_abstract v10

### PR DESCRIPTION
**Pull request by serpentcs-dev1**
Migrates **sql_request_abstract** from [v9](https://github.com/OCA/server-tools/tree/9.0/sql_request_abstract) to v10

### CODE REVIEW

**Comment by serpentcs-dev1** [comment]
@legalsylvain @jbeficent Could you please take a look?

**Comment by legalsylvain** [comment]
LGTM. (trivial changes)
Waiting for test on https://github.com/OCA/reporting-engine/pull/162 to see if all is OK.

**Review by AaronHForgeFlow — APPROVED** [review]
:+1: It works fine together with https://github.com/OCA/reporting-engine/pull/162

**Review by legalsylvain — APPROVED** [review]
thanks ! 
LGTM.

**Pull request merged**
