### PR TITLE
[9.0][auto_backup] Menu entry moved

### PR DESCRIPTION
**Pull request by pedrocs-exo**
The new entry is under Settings/Technical/Database Structure

### CODE REVIEW

**Comment by astirpe** [comment]
:+1:

**Review by sebalix — APPROVED** [review]
Tested on runbot.

**Review by elicoidal — APPROVED** [review]
:+1:

**Comment by elicoidal** [comment]
FT

**Comment by astirpe** [comment]
@elicoidal could you apply fast tracking to #735 also?

**Comment by lasley** [comment]
Looks like the version number in this module did not get bumped. I don't personally rely on these because all my scripts base on git commit, but is this actually used in any context? Odoo Apps store perhaps? An update of the module is required for this change to hit an instance db.

**Comment by yajo** [comment]
Version bumped directly in https://github.com/OCA/server-tools/commit/be446c74ee188d35675a3d477054c569f77754c1

**Pull request merged**
