### PR TITLE
[FIX] turn off prefetching when reading values

### PR DESCRIPTION
**Pull request by hbrunn**

### CODE REVIEW

**Comment by StefanRijnhart** [comment]
Does this prevent fetching all the other regular fields from the records?

**Comment by sebalix** [comment]
Hi,

What kind of error did you encounter? (just to understand the fix and the `prefetch_fields` context key)

**Comment by hbrunn** [comment]
It prevents fetching fields not requested, in my case function fields. And this is not a fix for an error, but a fix for performace.
The key's explanation is here: https://github.com/OCA/OCB/blob/9.0/openerp/models.py#L3238

**Comment by sebalix** [comment]
In our case, we use it to log computed fields (say, fields B and C) based on the field A. This way we have a complete log when the field A is updated. Does this break this use case?
As you say, it can be very slow, and I have in mind another feature: choose the log policy on the rule:
- full log (as it is now, including the computed values, default)
- restricted log (to log just the fields which are updated - the `vals` -, avoiding the read operations before/after the CRUD query, speeding the log process)

**Comment by hbrunn** [comment]
for the current model, it reads all fields anyways (we pass `_fields`), so your use case won't be impacted. But depending on the calling tree, he would prefetch way too many other fields in other models while doing the computation

**Comment by sebalix** [comment]
You are right, I tested on the runbot, there is no impact. :+1:

**Comment by StefanRijnhart** [comment]
:+1:

**Comment by sebalix** [comment]
Hi,

5 days have passed, is there someone available to merge this please?

**Comment by guewen** [comment]
:+1: 
Thanks!

**Pull request merged**
