### PR TITLE
15.0 mig base exception

### PR DESCRIPTION
**Pull request by augusto-weiss**

### CODE REVIEW

**Comment by bruno-zanotti** [comment]
> Hey @augusto-weiss, thank you for your Pull Request.
> 
> It looks like some users haven't signed our **C**ontributor **L**icense **A**greement, yet. You can read and sign our full Contributor License Agreement here: http://odoo-community.org/page/cla Here is a list of the users:
> 
> * Ivan Todorovich [ivan.todorovich@druidoo.io](mailto:ivan.todorovich@druidoo.io) (no github login found)
> 
> Appreciation of efforts, OCA CLAbot

Hey, @ivantodorovich how are you?
Could you help us with this message, I think you have made some commits with your email from Druidoo, maybe you can change it? I'm not sure what would be the best solution here.
The commits are:
- https://github.com/OCA/server-tools/pull/2279/commits/b7217ae9ec71a517df52ea1a337270d45be68cad
- https://github.com/OCA/server-tools/pull/2279/commits/d14ae5a60a1dc86e6bc53d87e7a0f3714785479e
 
Thanks!

**Comment by ivantodorovich** [comment]
Hey @Bruno-Zanotti 

Yeap, that address no longer exists.
Could you amend those commits to change the author's email address? change druidoo.io by gmail.com.

**Comment by bruno-zanotti** [comment]
Perfect @ivantodorovich thank you!

**Comment by damdam-s** [comment]
Hello @augusto-weiss. Where do you stand at this migration? Can I help on something or you're currently working on it?
many thanks

**Comment by augusto-weiss** [comment]
Hi @damdam-s !! we have several problems runing tests... maybe could you check it?

**Comment by augusto-weiss** [comment]
@damdam-s thanks about that!!

**Comment by damdam-s** [comment]
@augusto-weiss please see #2319 to continue. I splitted the tests in a dedicated module. The PR is based on this one so that you don't lose the authoring ;)

**Comment by pedrobaeza** [comment]
Superseded by #2366

**Pull request closed without merging**
