### PR TITLE
[16.0][FIX] sentry: respect sentry_logging_level (forward-port)

### PR DESCRIPTION
**Pull request by hugosantosred**
Superseeds https://github.com/OCA/server-tools/pull/2719

### CODE REVIEW

**Review by StefanRijnhart — APPROVED** [review]
Thank you for considering to port this one! (errors seem unrelated and occur on other recent PRs as well)

**Review by danielduqma — APPROVED** [review]
LGTM, thanks!

**Review by xAdrianCif — APPROVED** [review]
Tech review! god job, thanks!

**Review by xAdrianCif — APPROVED** [review]
Tech review, god job, thanks!

**Pull request merged**
