### PR TITLE
12.0 mig sentry

### PR DESCRIPTION
**Pull request by jeffery9**

### CODE REVIEW

**Review by elicoidal — APPROVED** [review]
LGTM. needs test

**Comment by pedrobaeza** [comment]
CIs are red.

**Comment by jeffery9** [comment]
can not get more details from CI.

**Comment by pedrobaeza** [comment]
The problem is the same for both: a lack of a Python library called `raven`. You have to put it on requirements.txt file in root folder. Look how I saw it:

peek 05-11-2018 09-35

peek 05-11-2018 09-36

**Comment by jeffery9** [comment]
code testing coverage going down, how to improve this.

**Comment by moylop260** [comment]
Add new unitests in the tests folder in order to cover the cases that is not tested

**Review by sbidoul — APPROVED** [review]
(code review)

The global coverage of the repo drops because we start from an almost empty repo which has 100% coverage. This is not a problem for a migration, IMO so we can approve this.

**Comment by legalsylvain** [comment]
thanks.

**Pull request merged**
