### PR TITLE
[MIG] dbfilter_from_header : Migration to 13.0

### PR DESCRIPTION
**Pull request by newtratip**
Standard Migration.

### CODE REVIEW

**Review by schout-it — APPROVED** [review]
lgtm

**Comment by newtratip** [comment]
@pedrobaeza You added milestone to 12.0 not 13.0.

**Comment by pedrobaeza** [comment]
Sorry, my bad

**Comment by newtratip** [comment]
Hello @pedrobaeza 

I'm a new contributor. I try to fix ci/runbot red by rebuild bot again but still red when I see log I found this error 
> AssertionError: Outdated python version detected, Odoo requires Python >= 3.6 to run.
Selection_021

Can you suggest me ?

Big thank

**Comment by pedrobaeza** [comment]
Not sure. I have launched a rebuild to see. Any way, I'm not in charge of this anymore.

**Comment by newtratip** [comment]
#1781 supersedes this pr.

I will close it.

**Pull request closed without merging**
