### PR TITLE
14.0 mig sequence python

### PR DESCRIPTION
**Pull request by OpenCode**

### CODE REVIEW

**Review by moylop260 — APPROVED** [review]
👍

**Review by dsolanki-initos — APPROVED** [review]
LGTM

**Comment by dsolanki-initos** [comment]
It would be nice if maintainers merge it.

**Comment by dsolanki-initos** [comment]
It would be nice if maintainers merge it.

**Comment by dsolanki-initos** [comment]
It would be nice if maintainers merge it.

**Comment by moylop260** [comment]
@sbidoul 

It generated a few commits with the message `[UPD] Update fetchmail_notify_error_to_sender.pot`:
 - https://github.com/OCA/server-tools/commits/33bf0c0480fa67b2841a702e88e294fec4068f2d

Should we re-try to merge it?

**Comment by sbidoul** [comment]
Let's try to resolve the makepot loop first. Discussion in https://github.com/OCA/server-tools/issues/2191

**Comment by sbidoul** [comment]
@moylop260 can you please retry the merge command ?

**Comment by dsolanki-initos** [comment]
Can we merge this?

**Pull request merged**
