### PR TITLE
[IMP] Drop table with CASCADE option

### PR DESCRIPTION
**Pull request by clonedagain**
It should be relativly safe to use this option, as it should normally only drop foreign keys and views.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
I'm not sure if this is safe. @StefanRijnhart should say because he was the original developer and he will know the reason to put that block.

**Comment by StefanRijnhart** [comment]
I fear a loss of consistency. The current code means to check this consistency by only allowing the removal of foreign keys between the tables that are going to be dropped, and not outside this table space. In other words: if the current method fails, then you probably have a live column in your database that is affected by the table drop and you want that to fail.

**Comment by hbrunn** [comment]
One thing I can imagine where the current code fails is with views depending on the table. Or is this also a wanted failure?

**Comment by StefanRijnhart** [comment]
Not a wanted feature, no. If this is the case, maybe it can be resolved by scheme introspection as well?

**Comment by clonedagain** [comment]
OK I'll withdraw this proposal then, maybe the foreign keys that were left in my test databse are there for a reason, maybe a fault in the migration procedure or faulty module uninstalling.

**Comment by clonedagain** [comment]
After more investigation, I'm now pretty sure the blocking foreign keys are artefacts of the previous migrations, ie. o2m fields changed into m2m.
So I'll manually delete the faulty keys.

**Pull request closed without merging**
