### PR TITLE
Fix failing yaml test

### PR DESCRIPTION
**Pull request by bwrsandman**
On top of #21

### CODE REVIEW

**Comment by pedrobaeza** [comment]
You will have to make a rebase after #21 was merged, but specific commit LGTM

:+1: (code review)

**Comment by bwrsandman** [comment]
Fails due to bzr Error Logging.

Either fix community test tools so it doesn't fail on that error, or figure out why bzr is even used and why it is failing.

**Comment by gurneyalex** [comment]
@bwrsandman could you rebase your branch?

**Comment by bwrsandman** [comment]
No point. I fixed this in another commit

**Pull request closed without merging**
