### PR TITLE
[MIG] migrate auth_from_http_basic to 9

### PR DESCRIPTION
**Pull request by sebastienbeau**
@florian-dacosta @hbrunn 
Hi I start to migrate the basic_auth module to v9

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please include in the commit name the module to migrate so that we identify the module

**Comment by sebastienbeau** [comment]
@pedrobaeza done, (I will not forget the next time)

**Review by hbrunn — CHANGES_REQUESTED** [review]
That's a lot simpler than I expected! Still some minor travis issues: that's a lot simpler than I expected. After fixing https://travis-ci.org/OCA/server-tools/jobs/162847588#L453

Logging out will trigger an ugly exception because (at least in v7) the 301 status triggers an exception on the client side. That's why we added the supplementary module auth_from_http_basic_logout which turns this into a nice error message. How does v9 behave here? You might either mention in the README that this module is yet to be migrated or if we don't need it any more, add removing it from the branch in your PR

**Comment by hbrunn** [comment]
another thing to take care of would be using short headers

**Comment by hbrunn** [comment]
actually, we can make this module play nice with multi database setups by now - given this happens in a model, just move the monkey patching into `ir.http`'s `_register_hook` (I think we made this policy anyways that no module should monkey patch unconditionally if not absolutely necessary) while taking care that you only monkey patch once globally, probably by setting some property on the `JsonRequest` object

**Pull request closed without merging**
