### PR TITLE
[15.0][MIG] database_cleanup: Migration to 15.0

### PR DESCRIPTION
**Pull request by yankinmax**

### CODE REVIEW

**Comment by yankinmax** [comment]
@leemannd @damdam-s can you pls review?

**Comment by yankinmax** [comment]
Tests are failing because of other modules. I wonder what I can do here more. Locally tests run without errors

**Comment by pedrobaeza** [comment]
The problem I'm seeing is that your module affects other module tests:

https://github.com/OCA/server-tools/actions/runs/4134604852/jobs/7145942706#step:8:1111

so you should care about that. Testing locally is isolated. Here, you have some kind on "integration tests".

**Comment by gurneyalex** [comment]
https://github.com/yankinmax/server-tools/pull/1/files might fix the CI

**Review by gurneyalex — APPROVED** [review]

**Comment by paulius-sladkevicius** [comment]
@hbrunn all is green, can you merge it? I would be happy to start the migration to v16.

**Comment by yankinmax** [comment]
> @hbrunn all is green, can you merge it? I would be happy to start the migration to v16.

it's module to migrate to v15 not v16. if you need to v16 you should use this one in your project:
- [ ] https://github.com/OCA/server-tools/pull/2473

**Comment by paulius-sladkevicius** [comment]
> > @hbrunn all is green, can you merge it? I would be happy to start the migration to v16.
> 
> it's module to migrate to v15 not v16. if you need to v16 you should use this one in your project:
> 
> * [ ]  [[16.0][MIG] database_cleanup: Migration to 16.0 #2473](https://github.com/OCA/server-tools/pull/2473)

Thanks for pointing it out, somehow I missed this already existing PR :+1:

**Pull request merged**
