### PR TITLE
[IMP] keychain: get_password must not be accessible from outside

### PR DESCRIPTION
**Pull request by lmignon**
ping @sebastienbeau

### CODE REVIEW

**Comment by sebastienbeau** [comment]
Totaly agree

**Review by sebastienbeau — APPROVED** [review]

**Comment by sebastienbeau** [comment]
@hparfr

**Review by hparfr — APPROVED** [review]

**Comment by hparfr** [comment]
It's a breaking change, version number should be updated.

**Comment by lmignon** [comment]
@hparfr Version number changed

**Pull request merged**
