### PR TITLE
9.0 fix remove static folders add preloadable key

### PR DESCRIPTION
**Pull request by ntsirintanis**
Related:

[OCA/server-env#21](https://github.com/OCA/server-env/pull/21)

@hbrunn @mreficent

### CODE REVIEW

**Review by sbidoul — APPROVED** [review]

**Comment by MiquelRForgeFlow** [comment]
travis ci is red :S

**Comment by ntsirintanis** [comment]
Yup, that's a pity. How can we force-green this?

**Comment by hbrunn** [comment]
we/you can't. Stuff will be red until the involved modules are fixed

**Review by hbrunn — APPROVED** [review]

**Review by MiquelRForgeFlow — APPROVED** [review]

**Comment by dreispt** [comment]
Lint check are failing. Needs fixing.

**Comment by thomaspaulb** [comment]
@ntsirintanis could you rebase and solve the linting issue

**Pull request merged**
