### PR TITLE
[14.0] [mig] fetchmail_notify_error_to_sender_test

### PR DESCRIPTION
**Pull request by fshah-initos**

### CODE REVIEW

**Comment by fshah-initos** [comment]
It would be nice if we get the reviews here

**Comment by fshah-initos** [comment]
Travis is not happy as the depened module is not yet merged

**Review by atchuthan — APPROVED** [review]
Waiting for dependent module's migration in https://github.com/OCA/server-tools/pull/2102

**Review by dsolanki-initos — APPROVED** [review]
LGTM.

**Comment by fshah-initos** [comment]
Depended module PR #2102  is merged in main branch.

**Comment by fshah-initos** [comment]
Can we merge this as the depended PR is also merged?

**Comment by fshah-initos** [comment]
Can we merge this?

**Pull request merged**
