### PR TITLE
[16.0][MIG] base_multi_image

### PR DESCRIPTION
**Pull request by taiebnourddine12**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Thanks for the contribution.

Please preserve commit history following technical method explained in https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0.

If the jump is between several versions, you have to modify the source branch in the main command to accommodate it to this circumstance.

**Comment by taiebnourddine12** [comment]
This pull request ready to review.

**Comment by thomaspaulb** [comment]
@taiebnourddine12 Could you rebase, in order to retrigger runboat?

**Comment by IJOL** [comment]
I badly need this pull request to be merged, there is something we can do  about it, or repost is the only way to go?

**Comment by thomaspaulb** [comment]
@IJOL Since the OP is unresponsive, just rebase and repost it, and tag me, I will review

**Comment by thomaspaulb** [comment]
Superseded by https://github.com/OCA/server-tools/pull/3010

**Pull request closed without merging**
