### PR TITLE
[17.0][FIX] module_analysis: interpret exclude_directories as relative to module's folder

### LINKED ISSUE #3042: module_analysis does not count code lines from odoo core when installed from the debian package
## Module
module_analysis

## To Reproduce
**Affected versions**: all

1. Prerequisites: Odoo is installed using the debian package; module_analysis is installed
2. Go to the account_cancel module page (in Applications app) in debug mode
3. Press the "Refresh Code Analysis" button in the "Technical data" tab

**Expected behavior**
The Python Code Quantity field's value is 0 also it should not, as there are non-empty python files in the module (models/account_bank_statement.py).

**Additional context**
Debugging shows that [this line](https://github.com/OCA/server-tools/blob/12.0/module_analysis/models/ir_module_module.py#L167) is a true condition when odoo is installed by a debian package (root = /usr/lib/python3/dist-packages/odoo/addons/account_cancel), because `exclude_directories` value is `['lib', 'demo', 'test', 'tests', 'doc', 'description']`, so the test returns {'lib'}

The `exclude_directories` comes from ir.config_parameter `module_analysis.exclude_directories` which interpretation is questionable. As a user of the module I expect its value to list folders relative to the module's folder, while in the code if any of the listed folder is found in the module's root path the entire module will be ignored.

I'm working on a PR to fix this.

### PR DESCRIPTION
**Pull request by fcayre**
Fixes #3042.

### CODE REVIEW

**Review by legalsylvain — APPROVED** [review]
Thanks a lot ! 

/ocabot merge patch

**Comment by legalsylvain** [comment]
@fcayre : could you rebase ?

**Comment by fcayre** [comment]
@legalsylvain my branch is already based on 17.0's head.

oca-gen-addon-readme seems to generate the error (`Duplicate substitution definition name: "image".`).
It works locally on my computer so this needs more investigations...

**Comment by legalsylvain** [comment]
@OCA/tools-maintainers : could we have some help here ? 

Step to reproduce : 
- checkout fcayre:17.0-fix-module_analysis-when-odoo-installed-by-debian-pkg
- rm ./module_analysis/README.rst 
- pre-commit run -a

<code>
docutils.utils.SystemMessage: ./module_analysis/README.rst:141: (ERROR/3) Duplicate substitution definition name: "image".
</code>


I suspect something wrong in the md -> rst conversion with many files.

Thanks for your help !

**Comment by thomaspaulb** [comment]
> I suspect something wrong in the md -> rst conversion with many files.

Yes, looks like that; I think need to open an issue [here](https://github.com/OCA/maintainer-tools/issues)

Though I think I found out the solution: it works if you define unique captions for each image in the MD source files, that don't overlap with the ones automatically generated for the caption-less OCA images by Pandoc, which default to image, image1, image2... if the MD image captions overlap with those, errors occur.

image

**Comment by legalsylvain** [comment]
OK. I opened this issue : https://github.com/OCA/maintainer-tools/issues/632

merging in the meantime, because it's a bugfix, and CI is green.

**Comment by thomaspaulb** [comment]
How was CI green if `oca-gen-addons-readme` failed?

**Comment by legalsylvain** [comment]
CI was green, but merge bot commit failed.

**Pull request merged**
