### PR TITLE
[12.0] Add module base_import_module_group

### PR DESCRIPTION
**Pull request by grindtildeath**
This module adds a security group to restrict importation of users 
to members of this specific group.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
This already exists: https://github.com/OCA/server-ux/tree/12.0/base_import_security_group

**Comment by pedrobaeza** [comment]
OK, seen that is not the same

**Review by hailangvn — COMMENTED** [review]
LGTM

**Review by hailangvn — APPROVED** [review]

**Review by yvaucher — APPROVED** [review]

**Pull request merged**
