### PR TITLE
[MIG] base_external_system: Upgrade to v11 

### PR DESCRIPTION
**Pull request by lasley**
Perform standard v11 migration. Includes #1033 as 6e2a54f

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Should this module be here or in another server-* repo?

**Comment by lasley** [comment]
Hmmm you're prolly right @pedrobaeza. `server-backend`?

**Comment by pedrobaeza** [comment]
Yeah, I think so

**Comment by lasley** [comment]
Moved to OCA/server-backend#2

**Pull request closed without merging**
