### PR TITLE
[12.0][MIG] auto_backup: Migration to 12.0

### PR DESCRIPTION
**Pull request by valentincastravete**

### CODE REVIEW

**Review by JorgeQuinteros — APPROVED** [review]
LGTM Technical review.

**Review by angelmoya — APPROVED** [review]
LGTM

**Comment by thomaspaulb** [comment]
/ocabot rebase

@valentincastravete (this will probably fail, could you do it manually? It should make the pipeline green)

**Comment by valentincastravete** [comment]
@thomaspaulb Hi, rebase done

**Comment by thomaspaulb** [comment]
@valentincastravete Thanks! pre-commit error still, probably something small

**Comment by valentincastravete** [comment]
> @valentincastravete Thanks! pre-commit error still, probably something small

Hi, pre-commit fixed

**Comment by thomaspaulb** [comment]
now auto_backup tests are failing

**Comment by valentincastravete** [comment]
> now auto_backup tests are failing

Hi @thomaspaulb , sorry about all the

**Pull request closed without merging**
