### PR TITLE
[14.0] [FW] base_exception: forward port PR#2042, PR#2054

### PR DESCRIPTION
**Pull request by hailangvn**
This is to forward port two PR below.
* https://github.com/OCA/server-tools/pull/2042
* https://github.com/OCA/server-tools/pull/2054

### CODE REVIEW

**Review by sebalix — APPROVED** [review]

**Review by TDu — APPROVED** [review]

**Comment by sebalix** [comment]
seems some oca-bot commands were looping on this repository and we got a lot of `[UPD] Update fetchmail_notify_error_to_sender.pot` commits
https://github.com/OCA/server-tools/commits/14.0?after=83ec8f1e7621516bd6e46277bdebb1c0d63270ff+34&branch=14.0
(3 pages like that).
I canceled the jobs on Travis, let's try again:

/ocabot merge minor

**Comment by sebalix** [comment]
There is still jobs failing with
```
Pushing .pot files changes to GitHub
To https://github.com/OCA/server-tools
 ! [rejected]        HEAD -> 14.0-ocabot-merge-pr-2198-by-sebalix-bump-minor (non-fast-forward)
error: failed to push some refs to 'https://github.com/OCA/server-tools'
hint: Updates were rejected because a pushed branch tip is behind its remote
hint: counterpart. Check out this branch and integrate the remote changes
hint: (e.g. 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```
@hailangvn can you try to rebase your PR on top of last 14.0?

**Comment by sebalix** [comment]
Issue was fixed here I suppose: https://github.com/OCA/server-tools/pull/2203
Trying again...
/ocabot merge minor

**Comment by hailangvn** [comment]
Thanks @sebalix  for the note. This PR has been rebased.

**Pull request merged**
