### PR TITLE
[18.0][MIG] base_view_inheritance_extension: Migration to 18.0

### PR DESCRIPTION
**Pull request by LucasTran380381**
Supersedes https://github.com/OCA/server-tools/pull/3100

- Due to `attrs` attribute is not use anymore in odoo v17 and later. => change to use `context` to make test-case suitable
- Add test-case for `operation="text_add"` and `operation="domain_add"`

### CODE REVIEW

**Review by hbrunn — CHANGES_REQUESTED** [review]
migration itself is fine, but the test code you removed tests the valuable case where the dictionary doesn't exist in the base view.

And given there was barely anything to do for this migration, I think it's fair to ask for test cases for `operation="text_add"` and/or `operation="domain_add"`

**Comment by LucasTran380381** [comment]
> migration itself is fine, but the test code you removed tests the valuable case where the dictionary doesn't exist in the base view.
> 
> And given there was barely anything to do for this migration, I think it's fair to ask for test cases for `operation="text_add"` and/or `operation="domain_add"`

Thanks for review. I have add test-case for 2 operation

**Review by hbrunn — APPROVED** [review]

**Review by sebalix — APPROVED** [review]

**Pull request merged**
