### PR TITLE
[ADD] base_exports_manager

### PR DESCRIPTION
**Pull request by JavierIniesta**
This module allow admin to manage export profiles (ir.exports) that Odoo
doesn't show anywhere.

### CODE REVIEW

**Comment by rafaelbn** [comment]
Tested in runbot, very useful. :+1: 
Please add a TODO section with:
- Module must enable the functionality for creating export profiles from that view so:
  - Field resource must show all models available to export
  - Field "Field name" must show fields from that model

**Comment by rafaelbn** [comment]
cc @janetrp @antespi @yajo @sergio-incaser @carlos-incaser

**Comment by janetrp** [comment]
tested in runbot :+1:

**Comment by JavierIniesta** [comment]
Known issues / Roadmap section added to README

**Comment by rafaelbn** [comment]
Rebuilding for testing! cc @yajo @antespi @sergio-incaser @carlos-incaser @janetrp

**Comment by JavierIniesta** [comment]
Tests added.

**Comment by rafaelbn** [comment]
cc @pedrobaeza this is a recent merge, we are on time to change name if you consider it. Please @Yajo  review

**Comment by pedrobaeza** [comment]
Yes please, I rename it directly.

**Comment by rafaelbn** [comment]
@JavierIniesta please rename directly as @pedrobaeza said. Thanks

**Comment by pedrobaeza** [comment]
I have already rename it. He hasn't got direct commit rights

**Pull request merged**
