### PR TITLE
[13.0][MIG] module_auto_update

### PR DESCRIPTION
**Pull request by eantones**
Migration to 13.0

### CODE REVIEW

**Comment by xavierjimenez** [comment]
Hello @eantones 

Travis is red, can you check it out please?

**Review by dalonsod — CHANGES_REQUESTED** [review]
@eantones  `migrations` folder should be removed, isn't it?

**Comment by eantones** [comment]
@dalonsod yes, you're right, I forgot it Thanks!! :-)

**Review by dalonsod — APPROVED** [review]
👍

**Review by newtratip — APPROVED** [review]
LGTM :+1:

**Pull request merged**
