### PR TITLE
super_calendar: Improve images in README, to show in apps

### PR DESCRIPTION
**Pull request by eLBati**
see https://apps.odoo.com/apps/modules/8.0/super_calendar/

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Why figure?

**Comment by eLBati** [comment]
@pedrobaeza this is the only way I found to make it work on both apps.odoo.com and github. I saw mis_builder follows this way: https://raw.githubusercontent.com/OCA/account-financial-reporting/8.0/mis_builder/README.rst

**Comment by pedrobaeza** [comment]
OK, I didn't know. 

Maybe we should include an example of this in the template in https://github.com/OCA/maintainer-tools/blob/master/template/module/README.rst

**Comment by elicoidal** [comment]
and I would add the px marker as well.
IMO 400 is maybe too small and 800 too big so I suggest 600

**Comment by pedrobaeza** [comment]
@eLBati are you going to take into account @elicoidal's suggestions?

**Comment by eLBati** [comment]
@pedrobaeza I should be able to do them next week

**Comment by eLBati** [comment]
@pedrobaeza @elicoidal done, thanks

**Pull request merged**
