### PR TITLE
11.0 auto backup hourly

### PR DESCRIPTION
**Pull request by foutoucour**
Add the option to setup the frequency of the back up from hourly or daily

### CODE REVIEW

**Review by ddufresne — APPROVED** [review]

**Review by sebalix — APPROVED** [review]

**Comment by foutoucour** [comment]
@pedrobaeza hey could you merge the PR?
Thanks!
Jordi

**Comment by JordiBForgeFlow** [comment]
@foutoucour can you squash your commits before merging? Do you know how?

**Comment by foutoucour** [comment]
@jbeficent I am not familiar with the commands. Could you guide me?

**Comment by foutoucour** [comment]
@jbeficent new year, new skill! I did the squash. Let me know if it is good for you.

**Comment by foutoucour** [comment]
@jbeficent hey Jordi, do you think the PR could be merged?

**Comment by rousseldenis** [comment]
@OCA/core-maintainers

**Comment by foutoucour** [comment]
Hello @jbeficent 
Who should I contact to merge the PR ?

**Comment by dreispt** [comment]
Hello @rmsolucoeseminformatica , you are a contributor in this PR, but I can't confirm your CLA.
Can you submit it to the OCA? Thanks!

**Pull request merged**
