### PR TITLE
[SEC] fetchmail_attach_from_folder: fix unsafe eval

### PR DESCRIPTION
**Pull request by gurneyalex**

### CODE REVIEW

**Comment by legalsylvain** [comment]
:+1: Thanks.

**Comment by sebalix** [comment]
:+1:

**Comment by pedrobaeza** [comment]
Please fix the flake8 error

**Comment by gurneyalex** [comment]
@pedrobaeza I wish the guys who change MQT settings would fix the builds.

**Comment by antespi** [comment]
:+1:

**Comment by gurneyalex** [comment]
@pedrobaeza CI errors fixed, and let's forget about coveralls, shall we :smile_cat:

**Comment by pedrobaeza** [comment]
:+1:

**Pull request merged**
