### PR TITLE
[10.0] module_auto_update: maintainer, developement_status and readme fragments

### PR DESCRIPTION
**Pull request by sbidoul**
Mainly, I propose myself as [maintainer](http://odoo-community.org/page/maintainer-role) of `module_auto_update`.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
@Yajo has worked a lot on this too, so I think you should be co-maintainers.

**Comment by sbidoul** [comment]
Well, all the active code is mine but if @Yajo wants to help, no problem of course. As a maintainer here I want to maintain feature parity across all versions from 8 to 11.

Let me repeat that it's better we share the load by having many maintainers on few modules each. Being maintainer is not a recognition nor a gift, it's a burden.

**Comment by pedrobaeza** [comment]
OK, I was saying for indeed sharing the load, but as you prefer.

**Review by yajo — APPROVED** [review]
Great! :blush:

**Comment by sbidoul** [comment]
Thanks! Back and forward ports done. I also fixed rst syntax errors in the whole repo on branches 8, 9, 10.

**Pull request merged**
