### PR TITLE
[9.0][ADD] Migration scripts for mass_editing

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Added migration scripts and analysis file.

### CODE REVIEW

**Review by JordiBForgeFlow — APPROVED** [review]

**Comment by MiquelRForgeFlow** [comment]
ping: @pedrobaeza

**Comment by JordiBForgeFlow** [comment]
@JayVora-SerpentCS can your team review?

**Review by AaronHForgeFlow — APPROVED** [review]
:+1: Cool

**Review by LoisRForgeFlow — APPROVED** [review]
LGTM

**Comment by JayVora-SerpentCS** [comment]
Good to go! We actually did v11 too and we are in the process of making a PR.

**Review by StefanRijnhart — APPROVED** [review]

**Pull request merged**
