### PR TITLE
[15.0][MIG] base_time_parameter

### PR DESCRIPTION
**Pull request by andrel-exo**
Modules works on v15 as it was on v14. Just changed the version number and some stuff for pre-commit.

### CODE REVIEW

**Comment by ghost** [comment]
Dear@arleite
Thank you for migrating base_time_parameter to 15.0.
I just rebased #2521 which has an improvement for 14.0. Would you like to approve it and include it in this PR?

**Comment by nimarosa** [comment]
PR https://github.com/OCA/server-tools/pull/2521 is being merged in 14.0 branch. When it's done please @arleite include it in this PR so we migrate the updated module.

**Comment by nimarosa** [comment]
Also please edit this commit message https://github.com/OCA/server-tools/pull/2631/commits/ba766939e3cbf28458cc4c7ec8fc9bd78a852b44 to comply to OCA commit naming structure.

**Review by nimarosa — CHANGES_REQUESTED** [review]
- Change the name of the commit https://github.com/OCA/server-tools/pull/2631/commits/ba766939e3cbf28458cc4c7ec8fc9bd78a852b44 to comply to OCA naming structure.  
- Please pick this PR https://github.com/OCA/server-tools/pull/2521 and include it in the migration, so we migrate an updated version of the module.

**Review by ghost — APPROVED** [review]

**Comment by ghost** [comment]
Hi @nimarosa I have approved this PR. Would you like to approve it as well? @arleite is a **first-time contributor** so let's appreciate the contribution and not be too demanding. One of us can make a new PR afterwards to get the 14.0 improvements into 15.0.

**Review by nimarosa — APPROVED** [review]

**Comment by andrel-exo** [comment]
Hi @nimarosa @appstogrow thank you for approving the PR, I will conduct another PR to update this one based on the new v14 updates.

**Comment by ghost** [comment]
Hi @arleite 
If you want to do the 14.0 improvements in a separate PR, this needs to wait until this PR is merged.
I recommend to take a backup and then include the 14.0 improvements in this PR.
You can do it this way:

git fetch origin pull/2521/head
git cherry-pick 09f0d5e4a2d21e1a030c24075a704a9299e15ab9
git cherry-pick 4773d125cfff53745505c6acc23219ccaa9753e7
git cherry-pick 21caee960d9360274de6e51e0707db1dde8a8c1d

The migration folder 14.0.3.0.0 should be deleted.
The migration folder 14.0.4.0.0 should be renamed to 15.0.1.0.0.

**Comment by norlinhenrik** [comment]
Thank you @arleite and sorry I haven't had time to test. We need to make sure that the migration works for to cases:

- Migration to 15.0 before #2521 is merged into 14.0.
- Migration to 15.0 after #2521 is merged into 14.0.

I will be traveling for the next two weeks. Will try to test these cases the third week from now.

**Comment by norlinhenrik** [comment]
Or you can test and let us know if it works. Then we can merge.

**Comment by norlinhenrik** [comment]
Thank you @arleite 

Now #2521 is merged. So pre-migration will happen when a database is updated to the most recent version of 14.0. So could you please delete the migration folder with the pre-migration?

Did you test upgrading to latest 14.0 before migrating to 15.0?

I will be traveling the next two weeks, so I cannot test myself right now...

**Comment by thomaspaulb** [comment]
@norlinhenrik If this is OK now, then I will merge

**Comment by norlinhenrik** [comment]
I successfully tested migration to 15.0.

In __manifest__.py please change the version number to 15.0.1.0.0

**Review by nimarosa — APPROVED** [review]

**Comment by nimarosa** [comment]
@pedrobaeza Pedro, can you merge this please?

**Comment by pedrobaeza** [comment]
Please squash the migration commits.

**Comment by norlinhenrik** [comment]
https://stackoverflow.com/questions/5189560/how-do-i-squash-my-last-n-commits-together

**Comment by norlinhenrik** [comment]
Hi @arleite 
I see that you have squashed some commits. There are still two migration commits. I think they should be squashed into one.

IMPORTANT
When I looked through the commits now, I saw that you deleted `from . import tests` inside `__init__`. Please add it again!

**Comment by andrel-exo** [comment]
Hi, I tried to squash all the commits, but for some reason, I couldn't. I'll attempt it again later.

When I ran the pre-commit, it prompted me to remove tests from `init`.

**Review by norlinhenrik — APPROVED** [review]

**Review by nimarosa — APPROVED** [review]

**Comment by thomaspaulb** [comment]
Still needs squashing plus another bump to retrigger Runboat, IMO

**Pull request merged**
