### PR TITLE
 [IMP] sql_export : add preview button

### PR DESCRIPTION
**Pull request by legalsylvain**
Add a preview button.

image

When clicking, you'll have a quick preview of your request.

image

CC : original commiters : @florian-dacosta , @bealdav, @bguillot 
CC : @quentinDupont

### CODE REVIEW

**Review by len-foss — APPROVED** [review]
Cool feature.
Name seems a bit confusing, maybe something like 'test query' or 'preview results'?

**Comment by legalsylvain** [comment]
Hi @len-foss. Thanks for your review. I updated the code, to replace by "Preview Results". 

Note : could you also review trivial related PR ? https://github.com/OCA/reporting-engine/pull/496

thanks.

**Review by florian-dacosta — COMMENTED** [review]
I am not so sure about this one.
I don't really see the point of preview a part of the query when it is as fast as generate the full file, but why not if you have a use case, but, I think it won't work if query uses variable. (I guess it would fail for now)
You have to manage this case. (simplest would be to just not to allow preview if query uses variables, hiding the button?) Or allowing user to set variables also in this case...

**Comment by legalsylvain** [comment]
Hi @florian-dacosta, I updated the code, hidding the button in case of variables. 
could you update your review ?

**Review by florian-dacosta — APPROVED** [review]

**Comment by legalsylvain** [comment]
hi maintainers. Could you merge this one ? thanks !

**Review by pedrobaeza — APPROVED** [review]

**Comment by legalsylvain** [comment]
I don't understand why oca-git-bot doesn't merge. This message (https://travis-ci.com/github/OCA/server-tools/jobs/512030152#L1336)
```
 ! [rejected]        HEAD -> 12.0-ocabot-merge-pr-2061-by-pedrobaeza-bump-minor (fetch first)
error: failed to push some refs to 'https://github.com/OCA/server-tools'
hint: Updates were rejected because the remote contains work that you do

hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

I rebased the branch. @pedrobaeza could you try again to merge. (or do you think I have something to fix ?)

**Comment by pedrobaeza** [comment]
There has been an outage of GitHub, Pypi, etc due to a failure in Fastly, and it was due to that. Restarting again:

/ocabot merge minor

**Pull request merged**
