### PR TITLE
[14.0][UPD] openupgrade_records: forward-port from v13

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Forward port of https://github.com/OCA/OpenUpgrade/pull/2565.

Later, I will update the analysis in OU.

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
PR is ready :)

**Comment by MiquelRForgeFlow** [comment]
@StefanRijnhart @legalsylvain @pedrobaeza

**Review by StefanRijnhart — APPROVED** [review]
Thanks!

**Review by legalsylvain — APPROVED** [review]

**Pull request merged**
