### PR TITLE
[FIX] onchange_helper: compute related values for onchange applications

### PR DESCRIPTION
**Pull request by len-foss**
I haven't had the time to write a test, as it probably needs to define a custom model for that.

If you have a compute field `f` that depends on a related, then the onchange result will be `False`, and that will propagate to any field depending on `f`.
For instance, on sale.order.line we have order_partner_id; if we have a compute method that depends on it, that field would not get computed. The end result is that the onchange application is completely False it any related is involved in the computation.

### CODE REVIEW

**Review by rousseldenis — APPROVED** [review]

**Comment by hparfr** [comment]
Hi, we have some regressions due to this patch.

One day after the merge of the current PR,  @len-foss 's PR encounter a regression https://github.com/shopinvader/odoo-shopinvader/pull/958

```
2021-05-10 09:03:14,900 322 ERROR odoo odoo.addons.shopinvader.tests.test_cart: Traceback (most recent call last): 
2021-05-10 09:03:14,900 322 ERROR odoo odoo.addons.shopinvader.tests.test_cart: `   File "/__w/odoo-shopinvader/odoo-shopinvader/shopinvader/tests/test_cart.py", line 221, in test_cart_pricelist_apply 
2021-05-10 09:03:14,900 322 ERROR odoo odoo.addons.shopinvader.tests.test_cart: `     line_values, line_values.keys() 
2021-05-10 09:03:14,900 322 ERROR odoo odoo.addons.shopinvader.tests.test_cart: `   File "/opt/odoo-venv/lib/python3.6/site-packages/odoo/addons/onchange_helper/models/base.py", line 63, in play_onchanges 
2021-05-10 09:03:14,900 322 ERROR odoo odoo.addons.shopinvader.tests.test_cart: `     onchange_values = new.onchange(all_values, field, onchange_specs) 
2021-05-10 09:03:14,900 322 ERROR odoo odoo.addons.shopinvader.tests.test_cart: `   File "/opt/odoo/odoo/models.py", line 5557, in onchange 
2021-05-10 09:03:14,900 322 ERROR odoo odoo.addons.shopinvader.tests.test_cart: `     record._onchange_eval(name, field_onchange[name], result) 
2021-05-10 09:03:14,900 322 ERROR odoo odoo.addons.shopinvader.tests.test_cart: `   File "/opt/odoo/odoo/models.py", line 5401, in _onchange_eval 
2021-05-10 09:03:14,900 322 ERROR odoo odoo.addons.shopinvader.tests.test_cart: `     method_res = method(self) 
2021-05-10 09:03:14,901 322 ERROR odoo odoo.addons.shopinvader.tests.test_cart: `   File "/opt/odoo/addons/sale_stock/models/sale_order.py", line 312, in _onchange_product_uom_qty 
2021-05-10 09:03:14,901 322 ERROR odoo odoo.addons.shopinvader.tests.test_cart: `     product_uom_qty_origin = self._origin.read(["product_uom_qty"])[0]["product_uom_qty"] 
2021-05-10 09:03:14,901 322 ERROR odoo odoo.addons.shopinvader.tests.test_cart: `   File "/opt/odoo/odoo/models.py", line 2835, in read 
2021-05-10 09:03:14,901 322 ERROR odoo odoo.addons.shopinvader.tests.test_cart: `     vals[name] = convert(record[name], record, use_name_get) 
2021-05-10 09:03:14,901 322 ERROR odoo odoo.addons.shopinvader.tests.test_cart: `   File "/opt/odoo/odoo/models.py", line 5167, in __getitem__ 
2021-05-10 09:03:14,901 322 ERROR odoo odoo.addons.shopinvader.tests.test_cart: `     return self._fields[key].__get__(self, type(self)) 
2021-05-10 09:03:14,901 322 ERROR odoo odoo.addons.shopinvader.tests.test_cart: `   File "/opt/odoo/odoo/fields.py", line 1065, in __get__ 
2021-05-10 09:03:14,901 322 ERROR odoo odoo.addons.shopinvader.tests.test_cart: `     value = record.env.cache.get(record, self) 
2021-05-10 09:03:14,901 322 ERROR odoo odoo.addons.shopinvader.tests.test_cart: `   File "/opt/odoo/odoo/api.py", line 1053, in get 
2021-05-10 09:03:14,901 322 ERROR odoo odoo.addons.shopinvader.tests.test_cart: `     return value.get() if isinstance(value, SpecialValue) else value 
2021-05-10 09:03:14,901 322 ERROR odoo odoo.addons.shopinvader.tests.test_cart: `   File "/opt/odoo/odoo/api.py", line 1096, in getter 
2021-05-10 09:03:14,901 322 ERROR odoo odoo.addons.shopinvader.tests.test_cart: `     raise exception 
2021-05-10 09:03:14,901 322 ERROR odoo odoo.addons.shopinvader.tests.test_cart: ` odoo.exceptions.AccessError: ('The requested operation cannot be completed due to security restrictions. Please contact your system administrator.\n\n(Document type: Sales Order Line, Operation: read) - (Records: [], User: 1)', None) 

```


I don't have time to work on a patch for the moment, so in my projects, I freeze this module to the commit before the merge.

**Comment by len-foss** [comment]
@hparfr 
Thank you for your report. I was hoping to get some feedback on it, but it was merged quite fast.
The approach I have taken is the one that seemed the only correct one. If this one is also flawed, it's pretty bad.

It's really interesting, to say the least, that that other PR fails because of this one, since both were done for the same use-case. What a mess.

**Comment by hbrunn** [comment]
I think this should be reverted. What we really want is just [this part](https://github.com/OCA/OCB/blob/12.0/odoo/models.py#L4995-L5000) of the `new` function I think. It would indeed be very helpful to have this test, then it would be a nobrainer to just try it in a PR

**Pull request merged**
