### PR TITLE
[13.0][BKP] url_attachment_search_fuzzy

### PR DESCRIPTION
**Pull request by JaumeBforgeFlow**
Backport from v14.0 https://github.com/OCA/server-tools/pull/2571

### CODE REVIEW

**Review by GuillemCForgeFlow — APPROVED** [review]

**Review by MiquelRForgeFlow — APPROVED** [review]

**Review by JordiMForgeFlow — APPROVED** [review]
code review LGTM

**Comment by JordiBForgeFlow** [comment]
@pedrobaeza Can you merge this one?

**Comment by pedrobaeza** [comment]
A fuzzy search over URL seems a bit weird, but merging as technically correct:

/ocabot merge nobump

**Pull request merged**
