### PR TITLE
[MIG] base_import_match: Migration to 11.0

### PR DESCRIPTION
**Pull request by renzo1974**
Module base_import_match migrated to Odoo 11.0

### CODE REVIEW

**Comment by pedrobaeza** [comment]
This should be moved to OCA/server-backend, and there's already a PR for the module in OCA/server-backend#17

**Comment by harlibeub** [comment]
wy movd and pr till 10 month open?

**Comment by renzo1974** [comment]
What if I made my PR for server-backend? Would that shorten the duration until this module is available for v11.0?

**Comment by pedrobaeza** [comment]
Why don't you simply review the existing PR? A PR is merged when people review it, but without reviews, the PR will be stalled forever.

**Pull request closed without merging**
