### PR TITLE
[IMP] : run cron from tree view

### PR DESCRIPTION
**Pull request by AdilHoumadi**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1:

**Comment by hbrunn** [comment]
I suggest doing the view override only for groups that are supposed to run this, like `group_system` (you might add the same to the form view)

**Comment by pedrobaeza** [comment]
Isn't it supposed that you didn't see that tree if you belong to that group?

**Comment by hbrunn** [comment]
right, forget about it. :+1:

**Comment by AdilHoumadi** [comment]
OCA runbot is not happy, is there any reason ? 

Thanks.

**Comment by hbrunn** [comment]
we can ignore it for now

**Comment by dreispt** [comment]
:+1:

**Pull request merged**
