### PR TITLE
[12.0][MIG] nsca_client

### PR DESCRIPTION
**Pull request by jarroyomorales**
Migration to 12.0 of nsca_client.

@etobella

### CODE REVIEW

**Review by etobella — COMMENTED** [review]
LGTM 
Could you split the readme?

**Comment by jarroyomorales** [comment]
@etobella Done!

**Review by etobella — APPROVED** [review]
LGTM

**Comment by jarroyomorales** [comment]
ping @aheficent

**Comment by thomaspaulb** [comment]
@jarroyomorales Recently CI was migrated from Travis to Github, could you modify the PR

**Comment by thomaspaulb** [comment]
@etobella Tests failing because of https://github.com/OCA/server-tools/pull/2850, maybe a review

**Comment by etobella** [comment]
Well, I just rebased the module because you asked. but we are no longer maintaining this version. Also, the error seems unrelated :thinking: 

image

**Comment by thomaspaulb** [comment]
@etobella That's why I added a link to the PR that fixes that test, and asked you to review ;-)

**Pull request merged**
