### PR TITLE
[10.0][FIX] Error when set disable History password (set History in Company as 0) of user in company

### PR DESCRIPTION
**Pull request by nguyenductamlhp**

### CODE REVIEW

**Review by moylop260 — APPROVED** [review]

**Review by astirpe — APPROVED** [review]

**Comment by astirpe** [comment]
Please bump the version in manifest

**Comment by nguyenductamlhp** [comment]
@astirpe, so which version we should bump to?

**Comment by astirpe** [comment]
According to https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md#version-numbers it should be 10.0.1.1.3

**Comment by nguyenductamlhp** [comment]
Ok, Thank you

**Pull request merged**
