### PR TITLE
Use OCA template

### PR DESCRIPTION
**Pull request by bwrsandman**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Thanks :+1:

**Comment by tafaRU** [comment]
:+1:

**Comment by dreispt** [comment]
Isn't the README file in the wrong directory?

**Comment by bwrsandman** [comment]
@dreispt you're right. I fixed that

**Comment by dreispt** [comment]
:eyeglasses:

**Comment by dreispt** [comment]
:+1:

**Comment by alejandrosantana** [comment]
:+1: (Code review, no test)

**Pull request merged**
