### PR TITLE
[11.0][UPD] dotfiles, fix tests

### PR DESCRIPTION
**Pull request by thomaspaulb**
Fix 11.0 CI

### CODE REVIEW

**Comment by thomaspaulb** [comment]
@OCA/tools-maintainers If someone wants to glance over this, otherwise I think it's OK to just merge

**Comment by dreispt** [comment]
I wonder if not having a commit per module could cause problems to the version migration apply patches process.
Any idea @pedrobaeza ?

**Comment by pedrobaeza** [comment]
No problem. git command extracts the contents for only the filtered directory.

**Review by dreispt — APPROVED** [review]

**Comment by dreispt** [comment]
Thank you, in that case LGTM.
If no one opposes, I will merge.

**Review by StefanRijnhart — APPROVED** [review]

**Pull request merged**
