### PR TITLE
[DOC] upgrade_analysis : update roadmap.rst + add maintainers

### PR DESCRIPTION
**Pull request by legalsylvain**
Add new item in the roadmap section for the next migration of the module in V16

See : https://github.com/OCA/OpenUpgrade/pull/3209#issuecomment-1157449981

CC : @StefanRijnhart

### CODE REVIEW

**Review by StefanRijnhart — APPROVED** [review]

**Review by pedrobaeza — APPROVED** [review]

**Comment by legalsylvain** [comment]
thanks for your review.

fastracking trivial patch

/ocabot merge patch

**Comment by legalsylvain** [comment]
FYI, I added me as maintainers to avoid such situation. hope is ok for you. 
@StefanRijnhart : let me know if you want to be set as maintainer as well.

**Comment by StefanRijnhart** [comment]
Can you add me as a maintainer as well?

**Comment by legalsylvain** [comment]
> Can you add me as a maintainer as well? 

Of course. done.

**Comment by StefanRijnhart** [comment]
Thanks!

/ocabot merge patch

**Pull request merged**
