### PR TITLE
Migration of mail_environment

### PR DESCRIPTION
**Pull request by guewen**
Migration and annual cleaning of the mail_environment module

### CODE REVIEW

**Comment by guewen** [comment]
Travis fails due to an error in disable_openerp_online

**Comment by dreispt** [comment]
There's a PR for that: #65

**Comment by guewen** [comment]
Red due to pylint errors in other modules.

**Comment by hbrunn** [comment]
:+1:

**Comment by pedrobaeza** [comment]
There's a little typo in module description: `outgoint_mail` instead of `outgoing_mail`.

Otherwise, :+1:

**Comment by pedrobaeza** [comment]
Time of merging...

**Pull request merged**
