### PR TITLE
Fix 9.0 version number

### PR DESCRIPTION
**Pull request by sbidoul**

### CODE REVIEW

**Comment by sbidoul** [comment]
These errors should be detected by MQT.

**Comment by pedrobaeza** [comment]
Why this doesn't have the description in the README.rst?

**Comment by sbidoul** [comment]
@pedrobaeza no idea. I guess it was missed during the review https://github.com/OCA/server-tools/pull/299.

I'm not going to fix that part myself.

**Comment by rvalyi** [comment]
what is the policy for LDAP populate: move to 9.0.1.2.0 as you suggested or reset to 9.0.1.0.0 ?
Not sure about this...

**Comment by sbidoul** [comment]
Is there a policy for that? Keeping 9.0.1.2.0 makes sense to me as it expresses the module is not new.

**Comment by pedrobaeza** [comment]
On previous migration strategies threads, we talked about resetting version number to 9.0.1.0.0, because it's the first version that arrives to that version, so I'm with @rvalyi

**Comment by elicoidal** [comment]
In favor of resetting. It doesnot make sense to keep the progression reached in 8 and set it in 9 as if the module have had several migration step which is not the case

**Comment by dreispt** [comment]
There is no guideline about resetting version number when upgrading to a major version.
IMO the common practice on software is to reset them, but not an issue if not.

:+1: for the trivial fix

**Comment by sbidoul** [comment]
IMO, resetting encourage people to consider the series as independent. I think there should be more efforts in maintaining parity of fixes across series. But maybe it's not realistic...

**Comment by pedrobaeza** [comment]
I prefer to reset, or numbers will be very big on Odoo version 12, 13, etc (if we get that number...). There's no gain indicating through version number that this module is also present in a previous "series". That's why we have the prefix, so 7.0.2.0.0 is the previous series version to 8.0.1.0.0.

**Comment by sbidoul** [comment]
Reset done.

**Comment by sbidoul** [comment]
> There's no gain indicating through version number that this module is also present in a previous "series"

I don't agree with that but okay.

**Comment by pedrobaeza** [comment]
:+1:

**Comment by yvaucher** [comment]
Usually what I have been doing is resetting to 9.0.1.0.0 when version is lower than 9.0.1 (ex 9.0.0.1.20)
Because, as it has been used for a whole version and being migrated we can consider it a major version.

Otherwise, about resetting, firstly I had the same idea as @sbidoul that keeping version gives more info. But now I think resetting version might be preferable as we don't want people to think 8.0.1.4.10 is equivalent to 9.0.1.4.10. As both evolved since x.0.1.2 differently.

**Comment by yvaucher** [comment]
Thus :+1:

**Pull request merged**
