### PR TITLE
[10.0][auto_backup] Menu entry moved

### PR DESCRIPTION
**Pull request by astirpe**
This is the porting of PR #728 to V10.

### CODE REVIEW

**Review by lasley — APPROVED** [review]
Travis lint was stuck for some reason, so I restarted it

**Comment by astirpe** [comment]
Yes, I noticed. Thank you @lasley !

**Comment by lasley** [comment]
@astirpe - Can you please bump the module version by a patch number to indicate the change made here? Assuming the current version is `10.0.1.0.0` we want `10.0.1.0.1`

I'll merge after that, taking into consideration the approvals from #728 and the fact this is an incredibly obvious change to fix a usability bug existing on a production branch. 

Sucks to be anyone relying on version numbers for the v9 branch, looks like that module version didn't get bumped 😦

**Comment by astirpe** [comment]
@lasley done, could you check?

**Review by elicoidal — APPROVED** [review]

**Pull request merged**
