### PR TITLE
[15.0][FIX] auditlog: Allow passing a chunk size for autovacuum

### PR DESCRIPTION
**Pull request by StefanRijnhart**
Ported from https://github.com/OCA/server-tools/pull/2335 by @hbrunn

### CODE REVIEW

**Review by yostashiro — APPROVED** [review]

**Review by hbrunn — APPROVED** [review]

**Comment by hbrunn** [comment]
@StefanRijnhart looks like we have to pin some openssl version

**Comment by StefanRijnhart** [comment]
Thanks for noting! Fixed here: https://github.com/OCA/server-tools/pull/2532

**Comment by StefanRijnhart** [comment]
And this one is now rebased.

**Pull request merged**
