### PR TITLE
[9.0][FIX] dbfilter_from_header: prevent autoloading

### PR DESCRIPTION
**Pull request by nilshamerlinck**

### CODE REVIEW

**Review by sbidoul — APPROVED** [review]

**Review by RoelAdriaans — CHANGES_REQUESTED** [review]
See my request at #1329

**Comment by nilshamerlinck** [comment]
@RoelAdriaans I've just made README.rst a bit more explicit. Thanks!

**Review by RoelAdriaans — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Why Travis is red?

**Comment by nilshamerlinck** [comment]
Hi @pedrobaeza :)

Seems due to a [recent patch on odoo](https://github.com/odoo/odoo/commit/af2e480e419b5817933fb5250fb84fa99e5c3839#diff-5e2f434047c379642786a87195c806f9) that broke `oauth_provider` and `oauth_provider_jwt` test cases. Unrelated to this PR.

I will try to dig more though.

**Comment by pedrobaeza** [comment]
Merging as error is unrelated.

**Comment by Garamotte** [comment]
@nilshamerlinck For the `oauth_provider` issue, `env` is a `mock.PropertyMock` at this place, which has no `__del__` method.

**Pull request merged**
