### PR TITLE
[10.0] Adds a property in Selection fields to show void values in kanbans

### PR DESCRIPTION
**Pull request by rousseldenis**
First version

### CODE REVIEW

**Comment by rousseldenis** [comment]
@hbrunn, @pedrobaeza 

Is there someone to help me to fix my issue ?

In my tests, I create a 'test' model but this one has to be destroyed at the end (as it is not saved in DB) not to interfere with tests in other modules of the repo.

Thanks

**Comment by pedrobaeza** [comment]
Sorry, I'm not able to look at this right now. If you continue with the problem next week, please ping me.

**Comment by rousseldenis** [comment]
@pedrobaeza Can you put tag 'needs fixing' as I need to fix?

**Comment by hbrunn** [comment]
for your issue, consult the tests for [database_cleanup](https://github.com/OCA/server-tools/blob/9.0/database_cleanup/tests/test_database_cleanup.py)

**Pull request closed without merging**
