### PR TITLE
[imp] users_ldap_populate: migrate feature added to 8.0 (ref #408)

### PR DESCRIPTION
**Pull request by simahawk**
Original PR https://github.com/OCA/server-tools/pull/408
I'll wait reviews and port it to v9 too.
ping @hbrunn @gurneyalex

### CODE REVIEW

**Review by gurneyalex — APPROVED** [review]

**Comment by lasley** [comment]
Hey @simahawk - thanks for porting this totally needed feature. Would it be possible, however, to use cherry-pick or format-patch to bring the change in so that the inline attribution remains to Holger? Any changes you make for porting should be in another commit so that you are attributed for those.

**Comment by simahawk** [comment]
Hey @lasley I'll be glad to... but I followed the [official guideline](https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0#howto) that already implies using format-patch. Can't remember now but I guess that I squashed and squashing the commits screws the committer from the patch.

**Comment by lasley** [comment]
@simahawk - squashing still maintains the committer of the oldest commit in the squash, and just puts you as a secondary on it. No matter though, maybe just a `git commit --amend --author`?

Did you make any other changes, or was this just the format-patch?

**Comment by simahawk** [comment]
@lasley yes, I had to migrate to new api and I splitted a piece of code into a method. If it's ok I could keep 2 commits: the 1st one from Holger and the other one w/ the changes. Sounds good?

**Comment by simahawk** [comment]
@lasley better? https://github.com/OCA/server-tools/compare/10.0...simahawk:users_ldap_populate-port-v8-feat-reprise

**Comment by simahawk** [comment]
@lasley if I try format-patch now I get tons of conflicts on po files: could I just discard them and rely on transbot update?

**Comment by lasley** [comment]
@simahawk - I'm good with the two commits.

Regarding Transifex - honestly I have no idea how our translations work. @pedrobaeza, can Simone simply ignore the conflicts in `po` files under the assumption that the Transifex processes will update them once merged?

**Review by hbrunn — APPROVED** [review]
@lasley @simahawk +1 for two commits. Translations will be ruthlessly overwritten, so no need to care about them

**Comment by simahawk** [comment]
@lasley @hbrunn ping

**Pull request merged**
