### PR TITLE
13.0 mig auto backup

### PR DESCRIPTION
**Pull request by jcarlosmontoya**

### CODE REVIEW

**Comment by JonathanNEMRY** [comment]
Dear mister,
Is this PR still relevant? Looking at the discussion into https://github.com/OCA/server-tools/pull/1689 where I see that @sbidoul  recommends using click-odoo-update, there is also a backup features into click-odoo-update-beta so @sbidoul do you also recommend using this awasome tools for the backup function? If yes, then maybe this PR can be closed and the other too?
best regards,
-jne

**Comment by sbidoul** [comment]
Hi @JonathanNEMRY I don't use this auto backup module so I don't have an opinion on it.

**Comment by newtratip** [comment]
Hello @jcarlosmontoya, Is this WIP ?

**Comment by zeroheure** [comment]
@Yajo looks like it can't be merged because of an old commit

**Comment by yajo** [comment]
I also don't use this one, but according to the logs you're missing a dependency.

**Comment by LoisRForgeFlow** [comment]
Superseded by https://github.com/OCA/server-tools/pull/2013.

**Pull request closed without merging**
