### PR TITLE
[12.0] WIP mig letsencrypt

### PR DESCRIPTION
**Pull request by eLBati**

### CODE REVIEW

**Comment by hbrunn** [comment]
check out https://github.com/OCA/server-tools/pull/1194, when we're finished with that, we want to cherry pick that. Are you in a hurry?

**Comment by eLBati** [comment]
> check out #1194, when we're finished with that, we want to cherry pick that

Ok

> Are you in a hurry?

In case, I will test and use the version of this PR, then upgrade my DB when #1194 will be merged

**Comment by pedrobaeza** [comment]
Can you check CIs status?

**Comment by daramousk** [comment]
Is this PR still active? Or even #1582? I sort of need this. Let me know so that I can take over

**Comment by NL66278** [comment]
@eLBati Hi Lorenzo, there are still failures on runbot and travis. Can you have a look at them?

**Comment by eLBati** [comment]
Sorry everyone, I don't plan to work on this. Feel free to move to another PR and close this one

**Comment by hbrunn** [comment]
superseded by https://github.com/OCA/server-tools/pull/1763

**Pull request closed without merging**
