### PR TITLE
[15.0] [MIG] letsencrypt

### PR DESCRIPTION
**Pull request by NL66278**
Standard migration.

### CODE REVIEW

**Review by legalsylvain — APPROVED** [review]
Maybe changes in pre-commit should be done in a separate pr / commit don't you think ?

Otherwise. Lgtm.

**Comment by NL66278** [comment]
@legalsylvain I could not get my commit through the local pre-commit without the change. Now will look why it is failing here...

**Comment by legalsylvain** [comment]
You can use the option --no-verify for git commit command.

**Comment by thomaspaulb** [comment]
@NL66278 Could you rebase this? Getting a conflict in precommit config file.

**Comment by NL66278** [comment]
@thomaspaulb Rebase done. Everything green now. Please rereview...

**Review by thomaspaulb — APPROVED** [review]

**Review by ntsirintanis — APPROVED** [review]

**Pull request merged**
