### PR TITLE
[MIG][10.0] Profiler module

### PR DESCRIPTION
**Pull request by thomaspaulb**
Backport of Profiler 11.0 based on

- https://github.com/OCA/server-tools/pull/1465
- https://github.com/OCA/server-tools/pull/1986
- https://github.com/OCA/server-tools/pull/2014

### CODE REVIEW

**Comment by JordiBForgeFlow** [comment]
@LoisRForgeFlow @AdriaGForgeFlow @AaronHForgeFlow

**Comment by thomaspaulb** [comment]
@JordiBForgeFlow It's now ready, do you want to do a review? I think you can even start the tour on the runbot, which will automatically take you through the steps.

**Review by gjotten — APPROVED** [review]
This module is already proving very useful with one of our 10.0 clients and we haven't encountered any problems with it.

**Comment by thomaspaulb** [comment]
Rebased this on the 11.0 work, so that it's just one simple backport commit and easier to review.

**Pull request closed without merging**
