### PR TITLE
[MIG] base_view_inheritance_extension: Migration to 16.0

### PR DESCRIPTION
**Pull request by etobella**
Migration to 16.0

@legalsylvain

### CODE REVIEW

**Comment by rven** [comment]
Superseeded by https://github.com/OCA/server-tools/pull/2495

It was not just enough to do the upgrade like @legalsylvain mentioned on Twitter.
The attributes where perfectly changed, but the demo view was not showing stuff correctly when creating a parent from the simple contact form.
I've changed the fields so it reflects them correctly when verifying it in the application.

**Comment by etobella** [comment]
@rven There is no issue in superseeding my PR, but I think some things must be followed before doing it:

1. When we superseed a PR, we are expecting an answer from the author and he does not answer.
2. We ask the author for supersseding and let him/her some time to answer (usually a week, but at least a day)
3. On a superseeding PRs, we keep original PR history and commits

So, if you want to superseed this PR, follow at least the last point, as there is no problem from my side in doing the superseed.

**Comment by etobella** [comment]
Meanwhile, I added your change :wink:

**Comment by legalsylvain** [comment]
> It was not just enough to do the upgrade like @legalsylvain mentioned on Twitter.

? Which tweet ?

**Comment by rven** [comment]
> > It was not just enough to do the upgrade like @legalsylvain mentioned on Twitter.
> 
> ? Which tweet ?

It wasn't yours it was https://twitter.com/alexisdlattre/status/1600095838700707840 :-)
I read it wrong, he didn't do any changes at all...
This happens when in the meantime watch football ;-)

**Comment by rven** [comment]
> @rven There is no issue in superseeding my PR, but I think some things must be followed before doing it:
> 
> 1. When we superseed a PR, we are expecting an answer from the author and he does not answer.
> 2. We ask the author for supersseding and let him/her some time to answer (usually a week, but at least a day)
> 3. On a superseeding PRs, we keep original PR history and commits
> 
> So, if you want to superseed this PR, follow at least the last point, as there is no problem from my side in doing the superseed.

@etobella It was just a timing issue of a couple minutes I guess, we both were working on the same migration at the same time :-)
I wasn't aware of the guidelines you mention. I only superseded your PR because mine was only completer (!= better) ;-).
I only superseded yours because it also happened to one of my PR's in the past, with the same reason.
Maybe it's a good thing to take notice of the superseding guidelines in the OCA guidelines?

When I started on the migration, there was no PR, no mentioning on the issue that someone was working on the migration as mentioned in the guidelines.

For me it's fine to leave this PR open, I'l close mine and approve yours, because I also verified it functionally :100: 

The only thing I wan't is a happy community :-p

**Review by rven — APPROVED** [review]
Working fine!

Reviewed code and functionally tested :+1:

**Comment by etobella** [comment]
I know it happened because we where too fast, for that reason I wasn't angry at all. It happens sometimes to everyone, don't worry. About the changes from your PR thanks for them 😁

**Comment by etobella** [comment]
> > It was not just enough to do the upgrade like @legalsylvain mentioned on Twitter.
> 
> ? Which tweet ?

My fault, I confused github users, it was a tweet by @alexis-via 🥲

**Comment by pedrobaeza** [comment]
Please propose at https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#github a section about how to act for doing pull requests and this protocol about superseding.

**Review by simahawk — APPROVED** [review]
Pure code review: LG

**Comment by alexis-via** [comment]
Thank you very much for this migration.

In fact, I had done myself the same kind of "easy" migration of base_view_inheritance_extension with just an update of tests, but I had some crash with my port of account_invoice_transmit_method which depend on base_view_inheritance_extension, and I thought that the crash was caused by base_view_inheritance_extension v16. I eventually figured out that the crash was caused by a missing coma in a domain in a view of account_invoice_transmit_method !!! But the backtrace was so horrible that I thought the bug was in some low-level code like the code of base_view_inheritance_extension.

**Pull request merged**
