### PR TITLE
[12.0][IMP] excel_import_export: Export multiple files as files.zip

### PR DESCRIPTION
**Pull request by AungKoKoLin1997**
This PR is backport of Export multiple files as files.zip from [14.0 Migration](https://github.com/OCA/server-tools/pull/2022)

@qrtl

### CODE REVIEW

**Review by kanda999 — APPROVED** [review]
Function review:  It worked as expected.

**Comment by kanda999** [comment]
I updated PR because we needed to update `export_xlsx` method to export multiple files.
Prior to my update, PR used code from this commit..　https://github.com/OCA/server-tools/commit/c9c6ea2379f949ef55e3cbe6311fad00f5dd6e21
But the latest code actually used in V14 is this.　https://github.com/OCA/server-tools/blob/a4fee3e4d882404a4d3d5a5660fb6a408113847c/excel_import_export/models/xlsx_export.py#L229

**Comment by AungKoKoLin1997** [comment]
@kittiu Can you please review this PR?

**Review by kittiu — APPROVED** [review]

**Comment by AungKoKoLin1997** [comment]
@thomaspaulb I will rebase.

**Comment by thomaspaulb** [comment]
@AungKoKoLin1997 Some silly flake8 issue.

**Comment by AungKoKoLin1997** [comment]
@thomaspaulb Fixed it!

**Comment by AungKoKoLin1997** [comment]
@thomaspaulb I fixed the tests case. Can you please merge again?

**Pull request merged**
