### PR TITLE
[ADD] module fetchmail_notify_error_to_sender

### PR DESCRIPTION
**Pull request by eLBati**
If fetchmail is not able to correctly route an email, the email is "silently" lost (you get an error message in server log).
For example, if you configure odoo mail system to route received emails according to recipient address, it may happen users send emails to wrong email address.

This module allows to automatically send a notification email to sender, when odoo can't correctly process the received email.

### CODE REVIEW

**Comment by gurneyalex** [comment]
could you rebase your PR to benefit from the recent runbot fixes?

**Comment by eLBati** [comment]
@gurneyalex done

**Comment by pedrobaeza** [comment]
:+1:

**Comment by gurneyalex** [comment]
:+1:

**Pull request merged**
