### PR TITLE
[RFR] try to find out why database_cleaup messes up on travis

### PR DESCRIPTION
**Pull request by hbrunn**
this is an exploratory PR, don't merge!

### CODE REVIEW

**Comment by hbrunn** [comment]
@gurneyalex @StefanRijnhart as authors of #507 #508 would you agree if I PR reverting your change and replace it by this?

**Comment by gurneyalex** [comment]
@hbrunn please do 

Thanks for taking care of this :smile_cat: 

:+1: :cake:

**Comment by hbrunn** [comment]
thanks, done

**Comment by StefanRijnhart** [comment]
Thanks!

**Pull request closed without merging**
