### PR TITLE
[BACKPORT][8.0] date_range

### PR DESCRIPTION
**Pull request by andhit-r**

### CODE REVIEW

**Review by lmignon — CHANGES_REQUESTED** [review]
@andhit-r Thank you for this back port. Nevertheless could you please squash the 'OCA Tansbot' commits

**Comment by andhit-r** [comment]
@lmignon sure. Thanks for reviewing.

**Comment by andhit-r** [comment]
@lmignon done. Would you kindly review it again. Many thanks.

**Comment by lmignon** [comment]
@andhit-r When I try to use a range into a search (in runbot) I've an exception
image

**Comment by thomaspaulb** [comment]
@lmignon If you're OK with the last change and both of us approve, maybe this can still be merged in.

**Comment by thomaspaulb** [comment]
Agh, nevermind, let's leave this 8.0 module. If someone really needs it, he/she can revive the PR.

**Pull request closed without merging**
