### PR TITLE
[10.0] migrate fetchmail attach from folder

### PR DESCRIPTION
**Pull request by NL66278**

### CODE REVIEW

**Comment by NL66278** [comment]
Red travis seems not related to this PR.

**Comment by Bilbonet** [comment]
Hello, thanks for sharing your work :-)
I'm testing your module but it doesn't work for me.
I tried several configurations whitout success. None of them create any mail.
When I try to attach email manually to an Opportunity it shows this python error.
could be an error on my configuration?
```
Traceback (most recent call last):
  File "/home/bilbonet/odoo-estable/server/odoo/http.py", line 641, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/bilbonet/odoo-estable/server/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/home/bilbonet/odoo-estable/server/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/bilbonet/odoo-estable/server/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/bilbonet/odoo-estable/server/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/bilbonet/odoo-estable/server/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/home/bilbonet/odoo-estable/server/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/home/bilbonet/odoo-estable/server/addons/web/controllers/main.py", line 894, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/bilbonet/odoo-estable/server/addons/web/controllers/main.py", line 882, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/bilbonet/odoo-estable/server/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/home/bilbonet/odoo-estable/server/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/bilbonet/odoo-estable/server/3addons/fetchmail_attach_from_folder/wizard/attach_mail_manually.py", line 75, in attach_mails
    folder.attach_mail(mail.object_id, mail_message)
  File "/home/bilbonet/odoo-estable/server/3addons/fetchmail_attach_from_folder/models/fetchmail_server_folder.py", line 194, in attach_mail
    fname, fcontent = attachment
ValueError: too many values to unpack
Traceback (most recent call last):
  File "/home/bilbonet/odoo-estable/server/odoo/http.py", line 641, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/bilbonet/odoo-estable/server/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/home/bilbonet/odoo-estable/server/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/bilbonet/odoo-estable/server/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/bilbonet/odoo-estable/server/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/bilbonet/odoo-estable/server/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/home/bilbonet/odoo-estable/server/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/home/bilbonet/odoo-estable/server/addons/web/controllers/main.py", line 894, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/bilbonet/odoo-estable/server/addons/web/controllers/main.py", line 882, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/bilbonet/odoo-estable/server/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/home/bilbonet/odoo-estable/server/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/bilbonet/odoo-estable/server/3addons/fetchmail_attach_from_folder/wizard/attach_mail_manually.py", line 75, in attach_mails
    folder.attach_mail(mail.object_id, mail_message)
  File "/home/bilbonet/odoo-estable/server/3addons/fetchmail_attach_from_folder/models/fetchmail_server_folder.py", line 194, in attach_mail
    fname, fcontent = attachment
ValueError: too many values to unpack
```

**Comment by NL66278** [comment]
@Bilbonet Hi! It is not an error in your configuration. After debugging I conclude that the attachment tuple can now contain more then two elements. I will change the code to guard against this possibility.

**Comment by Bilbonet** [comment]
Thanks :-)
Now it works fine.
Good job.
I hope OCA acepts your PR

**Comment by NL66278** [comment]
@Bilbonet Thanks! I hope PR will be accepted as well. Might need to include some more testing to get coverage up.

**Comment by NL66278** [comment]
@Bilbonet You might help by doing an official review and approve.

**Comment by Bilbonet** [comment]
Of course.
How can I do that?
I think I canot do it. Maybe I need permisions

**Comment by NL66278** [comment]
@Bilbonet You should be able to go to the tab 'Files Changed'  and then use the button Review Changes

**Review by Bilbonet — APPROVED** [review]
I have tested the changes and the module works fine.
I´ve attached emails from an imap folder to an account and an opportunity with success.

**Review by ofonseca-pyming — APPROVED** [review]
I tested in v10 without issues creating records in mail.channel.

**Pull request merged**
