### PR TITLE
[14.0] mig scheduler_error_mailer

### PR DESCRIPTION
**Pull request by fredzamoabg**
scheduler_error_mailer module migration from version 12.0

### CODE REVIEW

**Review by SimoneVagile — APPROVED** [review]
LGTM

**Comment by SimoneVagile** [comment]
Can a maintainer unlock pre-commit run?

**Review by dsolanki-initos — APPROVED** [review]
LGTM

**Comment by dsolanki-initos** [comment]
Can we merge this PR?

**Comment by dsolanki-initos** [comment]
Can we merge this PR?

**Comment by hkapatel-initos** [comment]
Hello maintainers,
It would be nice if you are trying to merge it

**Comment by hkapatel-initos** [comment]
Hello maintainers,
It would be nice if you are trying to merge it

**Comment by hkapatel-initos** [comment]
Hello maintainers,
It would be nice if you are trying to merge it

**Comment by hkapatel-initos** [comment]
@dreispt Can we merge this PR?

**Pull request merged**
