### PR TITLE
[FIX] travis

### PR DESCRIPTION
**Pull request by hbrunn**

### CODE REVIEW

**Comment by lepistone** [comment]
thanks @hbrunn . Can you specify what you mean by "travis" ? Is it lint, or failing tests?

**Comment by hbrunn** [comment]
flake8

**Comment by lepistone** [comment]
thanks @hbrunn! :+1: (next time, I'd love a more specific commit message, but that's a detail )

**Comment by tafaRU** [comment]
:+1:

**Comment by pedrobaeza** [comment]
:+1:

**Pull request merged**
