### PR TITLE
14.0 mig base search fuzzy

### PR DESCRIPTION
**Pull request by cbssolutions**
done

### CODE REVIEW

**Review by PieterPaulussen — APPROVED** [review]

**Comment by rousseldenis** [comment]
@alexteodor don't forget to install pre-commit before commiting locally. You need to fix.

**Comment by cbssolutions** [comment]
I verified and runed precomit -r run or how is the commnad
what I need to modify?

**Comment by moylop260** [comment]
@alexteodor 

Could you rebase it, please?

I think it pre-commit was an internal issue

**Comment by cbssolutions** [comment]
2-5 days i'm not at computer

**Comment by dreispt** [comment]
Superseded by https://github.com/OCA/server-tools/pull/2096

**Pull request closed without merging**
