### PR TITLE
[MIG][12.0] base_kanban_stage

### PR DESCRIPTION
**Pull request by AaronHForgeFlow**
Standard migration from v10

### CODE REVIEW

**Comment by AaronHForgeFlow** [comment]
Dismissed

**Comment by AaronHForgeFlow** [comment]
@mreficent you will find this interesting

**Review by MiquelRForgeFlow — APPROVED** [review]
:+1:  ready to review and merge! :green_apple:

**Review by HviorForgeFlow — APPROVED** [review]

**Comment by AaronHForgeFlow** [comment]
Ready to merge

**Pull request merged**
