### PR TITLE
 [FIX] sql_request_abstract: make call to button idempotens

### PR DESCRIPTION
**Pull request by legalsylvain**
Trivial patch. 
- make two functions calls idempotens.
- return values for button_set_draft() to allow XML-RPC call.

CC : @quentinDupont

### CODE REVIEW

**Review by rvalyi — APPROVED** [review]

**Comment by legalsylvain** [comment]
Thanks for taking time to merge PRs

**Comment by legalsylvain** [comment]
@dreispt / @rvalyi  could you merge again ? 

thanks.

**Pull request merged**
