### PR TITLE
[8.0][FIX] auth_admin_passkey bugs #699 and #754

### PR DESCRIPTION
**Pull request by alexis-via**

### CODE REVIEW

**Review by legalsylvain — APPROVED** [review]
Code review / No test. LGTM. Thanks !
:+1:

**Review by legalsylvain — APPROVED** [review]

**Comment by legalsylvain** [comment]
@thomaspaulb, @bealdav, could your review ?

Thanks.

**Review by sebalix — CHANGES_REQUESTED** [review]
Small lint to fix: `auth_admin_passkey/models/res_users.py:9:1: F401 'openerp.tools.safe_eval.safe_eval' imported but unused`
https://travis-ci.org/OCA/server-tools/jobs/206217092#L483

**Comment by bealdav** [comment]
LGTM

**Review by sebalix — APPROVED** [review]

**Pull request merged**
