### PR TITLE
[FIX] import odbc to new api

### PR DESCRIPTION
**Pull request by mileo**
Replace #461 
- [X] Make module instable;
- [X] Test with old api and fix erros;
- [X] Add README.rst

### CODE REVIEW

**Comment by dreispt** [comment]
@mileo For v8 the new API is not mandatory. But if you find time to do that, it would be great!

**Comment by gurneyalex** [comment]
setting to 'wip' as there's an unchecked box. But I'll set to 'needs review' if asked :smile_cat:

**Comment by mileo** [comment]
Anyone seen this? PyLint complaining of a line that does not exist .... 

https://travis-ci.org/OCA/server-tools/jobs/153339309#L440

**Comment by mileo** [comment]
Please change label to needs review

**Review by moylop260 — APPROVED** [review]

**Review by dreispt — APPROVED** [review]

**Pull request merged**
