### PR TITLE
[11.0][MIG] html_image_url_extractor

### PR DESCRIPTION
**Pull request by tarteo**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please squash translation commits

**Comment by tarteo** [comment]
Squashed the transbot commits

**Review by pedrobaeza — APPROVED** [review]

**Review by yajo — APPROVED** [review]
Please include https://github.com/OCA/server-tools/pull/1148/

**Review by yajo — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Travis is red

**Comment by tarteo** [comment]
Yes sorry, I forgot to run flake locally. It's fixed now.

**Pull request merged**
