### PR TITLE
Port Scheduler error mailer

### PR DESCRIPTION
**Pull request by yajo**
It's hard to test this, as it is supposed to work automatically.

### CODE REVIEW

**Comment by yajo** [comment]
I reviewed Travis log and only find that [the failure is in pylint](https://travis-ci.org/OCA/server-tools/jobs/35723953#L554). Can anyone point me to the failure please?

**Comment by pedrobaeza** [comment]
This is fixed on #64, so don't worry about that.

**Comment by yajo** [comment]
https://github.com/OCA/server-tools/pull/64 is merged, can you trigger travis again please?

**Comment by pedrobaeza** [comment]
As said in the other PR, you need to rebase.

**Pull request closed without merging**
