### PR TITLE
[MIG] sentry: Backport sentry addon to Odoo 8.0

### PR DESCRIPTION
**Pull request by naglis**
For backporting changes see f2e61bb.

### CODE REVIEW

**Review by legalsylvain — APPROVED** [review]
Hi @naglis. Thanks for backporting this module. 
LGTM for me. (Code review / no test).

Any point of view, initial commiters / reviewers: @lasley @bwrsandman, @rwsdigital, @pedrobaeza  ?

regards.

**Review by lasley — APPROVED** [review]
Change look good, thanks @naglis

**Review by moylop260 — APPROVED** [review]

**Comment by lasley** [comment]
@naglis - can you resolve the conflict for merge please?

**Review by lasley — APPROVED** [review]
Thanks @naglis

**Pull request merged**
