### PR TITLE
11.0 mig base optional quick create

### PR DESCRIPTION
**Pull request by fmdl**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please move it to OCA/server-ux as stated in the migration issue and squash together adjacent translation commits.

**Comment by fmdl** [comment]
Hi @pedrobaeza what the git command to move with historique ?

I have try this :
```
git remote add -f server-tool https://github.com/OCA/server-tools.git -t 11.0
git checkout -b 11.0-mig-base_optional_quick_create origin/11.0
git format-patch --keep-subject --stdout origin/11.0..server-tool/10.0 -- base_optional_quick_create | git am -3 --keep
```
At the last one I have : 
`fatal: bad revision 'origin/11.0..server-tool/10.0'`

Thanks

**Comment by pedrobaeza** [comment]
From scratch:
```
git clone https://github.com/OCA/server-ux
git remote add server-tools https://github.com/OCA/server-tools
git fetch server-tools
git checkout -b 11.0-mig-base_optional_quick_create
git format-patch --keep-subject --stdout origin/11.0..server-tools/10.0 -- base_optional_quick_create | git am -3 --keep
```

**Comment by fmdl** [comment]
Move here : https://github.com/OCA/server-ux/pull/13

**Pull request closed without merging**
