### PR TITLE
[8.0] Module 'auditlog' - Log HTTP user sessions and requests

### PR DESCRIPTION
**Pull request by sebalix**
This PR updates `auditlog` to:
- log HTTP user sessions,
- log HTTP requests (linked to the user session),
- link those above to the "CRUD" log,
- view updated (search views to allow group by, etc).

### CODE REVIEW

**Comment by sebalix** [comment]
WIP

**Comment by dreispt** [comment]
Marvelous! :trophy: for first PR (AFAIK) implementing and removing lines from a Roadmap section!

**Comment by pedrobaeza** [comment]
I think both new models deserve a computed display_name field as _rec_name that reflects useful information on many2one links.

**Comment by sebalix** [comment]
@dreispt : thanks!
@pedrobaeza what kind of useful fields do you see in the display_name?
Session => "user_id.name (create_date)" 
HTTP Request => "path" + ?

**Comment by pedrobaeza** [comment]
Thanks, that changes are perfect :+1:

**Comment by sebalix** [comment]
I would like to add the user context in the CRUD log, it could help to analyse some logs.
There was also the `ir.cron` to clean up logs (#187). Unless you prefer another PR for that?

**Comment by pedrobaeza** [comment]
I think it's better to treat that in separate PRs, so that each of them can evolve isolated for the rest.

**Comment by sebalix** [comment]
Okay, so I'm done with this one! Waiting for other reviewers.

**Comment by moylop260** [comment]
Could you review beta messages?

``` bash
************* Module auditlog.__openerp__
auditlog/__openerp__.py:22: [C8102(manifest-required-key), ] Missing required key "license" in manifest file
************* Module auditlog.models.log
auditlog/models/log.py:25: [C8104(class-camelcase), auditlog_log] Use `CamelCase` "AuditlogLog" in class name "auditlog_log". You can use oca-autopep8 of https://github.com/OCA/maintainer-tools to auto fix it.
auditlog/models/log.py:45: [C8104(class-camelcase), auditlog_log_line] Use `CamelCase` "AuditlogLogLine" in class name "auditlog_log_line". You can use oca-autopep8 of https://github.com/OCA/maintainer-tools to auto fix it.
************* Module auditlog.models.rule
auditlog/models/rule.py:61: [C8104(class-camelcase), auditlog_rule] Use `CamelCase` "AuditlogRule" in class name "auditlog_rule". You can use oca-autopep8 of https://github.com/OCA/maintainer-tools to auto fix it.
```

**Comment by sebalix** [comment]
@moylop260 Done

**Comment by gurneyalex** [comment]
:+1:

**Comment by sebalix** [comment]
@gurneyalex Thanks!

**Pull request merged**
