### PR TITLE
[16.0][MIG] dbfilter_from_header

### PR DESCRIPTION
**Pull request by carmenbianca**

### CODE REVIEW

**Comment by carmenbianca** [comment]
Not making decent progress on this. The signature of `db_filter` was changed from `db_filter(dbs, httprequest=None)` to `db_filter(dbs, host=None)`, where `host` is (for example) 'localhost:8069'.

The upstream `db_filter` code contains this snippet:

```python
    if config['dbfilter']:
        #        host
        #     -----------
        # www.example.com:80
        #     -------
        #     domain
        if host is None:
            host = request.httprequest.environ.get('HTTP_HOST', '')
```

If I pause my debugger on the first line and execute `request.httprequest`, I get the following traceback:

```python
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/var/home/coopiteasy/.virtualenvs/odoo16/lib64/python3.10/site-packages/werkzeug/local.py", line 432, in __get__
    obj = instance._get_current_object()
  File "/var/home/coopiteasy/.virtualenvs/odoo16/lib64/python3.10/site-packages/werkzeug/local.py", line 554, in _get_current_object
    return self.__local()  # type: ignore
  File "/var/home/coopiteasy/.virtualenvs/odoo16/lib64/python3.10/site-packages/werkzeug/local.py", line 226, in _lookup
    raise RuntimeError("object unbound")
RuntimeError: object unbound
```

The request object is `<LocalProxy>` (its repr is '<LocalProxy unbound>'). Attempting to do anything with this object results in the above traceback.

So the Odoo code seems broken to me in any scenario where `host is None`.

So of course, when I do `httprequest = http.request.httprequest` in `override.py`, I get a similar traceback:

```python
Traceback (most recent call last):
  File "/home/odoo16/venv/lib/python3.8/site-packages/werkzeug/serving.py", line 306, in run_wsgi
    execute(self.server.app)
  File "/home/odoo16/venv/lib/python3.8/site-packages/werkzeug/serving.py", line 294, in execute
    application_iter = app(environ, start_response)
  File "/home/odoo16/src/odoo/odoo/http.py", line 1942, in __call__
    request = Request(httprequest)
  File "/home/odoo16/src/odoo/odoo/http.py", line 1101, in __init__
    self.session, self.db = self._get_session_and_dbname()
  File "/home/odoo16/src/odoo/odoo/http.py", line 1133, in _get_session_and_dbname
    if session.db and db_filter([session.db], host=host):
  File "/home/odoo16/src/oca/server-tools/dbfilter_from_header/override.py", line 17, in db_filter
    print(http.request)
  File "/home/odoo16/venv/lib/python3.8/site-packages/werkzeug/local.py", line 367, in <lambda>
    __str__ = lambda x: str(x._get_current_object())
  File "/home/odoo16/venv/lib/python3.8/site-packages/werkzeug/local.py", line 307, in _get_current_object
    return self.__local()
  File "/home/odoo16/venv/lib/python3.8/site-packages/werkzeug/local.py", line 137, in _lookup
    raise RuntimeError("object unbound")
RuntimeError: object unbound - - -
```

The request objects that we actually want is in the process of being created in line 1101 above (Request's `__init__` function). The httprequest object we want already exists in the request object's `__init__`.

Not sure what the correct course of action is to tackle this problem.

**Comment by nilshamerlinck** [comment]
Hello @carmenbianca I faced this issue as well. Worked around it [here](https://github.com/OCA/server-tools/pull/2429). Not very elegant, but works :sweat_smile: Thoughts welcome!

**Review by nilshamerlinck — APPROVED** [review]

**Comment by Entrepreneur-AJ** [comment]
Just tested on a virsh setup seems to be working well, mention me when your ready for it to be merged and (providing there's no drastic changes) i will code review it. Should be able to get OCA Bot to kick in then.

**Comment by carmenbianca** [comment]
Squashed the last commit. Just tested this as well → it works. Ready for merging as far as I'm concerned.

**Review by Entrepreneur-AJ — APPROVED** [review]

**Comment by skaag** [comment]
Tested this in a QA environment with multiple instances of Odoo 16 and it works well 🤙
(to clarify: A single install of Odoo 16 on a single server, with multiple tenants, via db_filter)

**Pull request merged**
