### PR TITLE
[13.0][ENH] auditlog: track unlink record

### PR DESCRIPTION
**Pull request by bodedra**
Fortward-port https://github.com/OCA/server-tools/pull/2112 + run pre-commit

### CODE REVIEW

**Comment by bodedra** [comment]
Functional reviewed. Working as expected.

**Comment by bodedra** [comment]
Ping @kittiu @Saran440 @dreispt @sebalix

**Comment by kittiu** [comment]
Works great! can't wait to see this to land in v14 :)

**Review by kittiu — APPROVED** [review]

**Comment by bodedra** [comment]
> Works great! can't wait to see this to land in v14 :)

Thanks for review and interest. Me too. I got problem on cherry-pick during 12-13 and format. So from 13-14 will be quick.

**Review by Saran440 — APPROVED** [review]

**Pull request merged**
