### PR TITLE
7.0 travis coverage

### PR DESCRIPTION
**Pull request by yvaucher**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1:

**Comment by bwrsandman** [comment]
Don't forget to add README.md with badges

**Comment by yvaucher** [comment]
Will need to add settable options on run test for that running_env parameter

**Comment by bwrsandman** [comment]
> Will need to add settable options on run test for that running_env parameter

What do you mean? What is running_env?

**Comment by yvaucher** [comment]
See the thrace:

> File "/home/travis/build/OCA/server-tools/server_environment/serv_config.py", line 40, in <module>
> 
> "The parameter 'running_env' has not be set neither in base config "
> 
> Exception: The parameter 'running_env' has not be set neither in base config file option -c or in openerprc.
> 
> We strongly recommend against using the rc file but instead use an explicit config file with this content:
> 
> [options]
> 
> running_env = dev

This is used in server_environement module to define dev/test/qa/prod instance

**Comment by yvaucher** [comment]
yay it passed the test with server_environment

**Pull request merged**
