### PR TITLE
updated example usage link; trash VIM statements

### PR DESCRIPTION
**Pull request by rvalyi**

### CODE REVIEW

**Comment by rvalyi** [comment]
Trivial documentation change as requested by @pedrobaeza in v8 port https://github.com/OCA/server-tools/pull/61

**Comment by pedrobaeza** [comment]
:+1:

Thanks

**Comment by guewen** [comment]
:+1:

**Comment by LeartS** [comment]
+1

**Comment by dreispt** [comment]
:+1:

**Pull request merged**
