### PR TITLE
[WIP][11.0][ADD] base_cron_oneshot: Add the module

### PR DESCRIPTION
**Pull request by ghost**
### TODO:
- [ ] provide README
- [ ] finalize API method that should schedule new oneshot crons

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Well, without explanation on what is the intention of the module, it's difficult to review it.

**Comment by simahawk** [comment]
@pedrobaeza goal is to have single-purpose jobs. Nowadays to achieve this you have to pull in queue_job but for simple cases like "I want to do/compute something only once without impacting user threads" you can simply rely on the cron mechanism and its thread(s).
We'll improve description & co. soon. '[WIP]' is really the case here :)

**Comment by simahawk** [comment]
@pedrobaeza I have no rights on Artem's fork and he's on holidays. 
There you go https://github.com/OCA/server-tools/pull/1352
You can close this ;)

**Comment by pedrobaeza** [comment]
Superseeded by #1352

**Pull request closed without merging**
