### PR TITLE
[15.0] [MIG] dbfilter_from_header: Migration to 15.0

### PR DESCRIPTION
**Pull request by ghost**
Only needed to bump version number, everything else worked out the box.

### CODE REVIEW

**Review by StefanRijnhart — APPROVED** [review]

**Comment by paragasu** [comment]
can we approve this merge? seems to be working fine

**Comment by StefanRijnhart** [comment]
@paragasu if you tested this module's funcntionality, or reviewed its code, please press 'Approve' under the 'Review changes' button on the 'Files changed' tab!

**Comment by ghost** [comment]
@paragasu We need 2 people approving merges @StefanRijnhart was the first I cant approve my own needs to be a 3rd party to test and review. If your happy with the code and it works on your instance please follow @StefanRijnhart comment been months since I pushed this PR

**Review by ryanc-me — APPROVED** [review]

**Comment by ryanc-me** [comment]
@StefanRijnhart do you have access to merge? I've tested this at several clients sites, and added a review :-)

**Comment by ghost** [comment]
@pedrobaeza or @StefanRijnhart finally a second approval :) any chance you can merge it please.

**Pull request merged**
