### PR TITLE
[15.0][MIG] module_auto_update

### PR DESCRIPTION
**Pull request by mlaitinen**
- Didn't squash the OCA Transbot commits since I ended up with some weird git errors I couldn't resolve. There are only two OCA Transbot commits though, so it doesn't mess up the git history anyway.
- Added user-friendly notifications when "Auto-Upgrade Modules" is ran from the user interface.
- The module worked pretty much out-of-the-box without requiring other changes than the version bump.

### CODE REVIEW

**Comment by ghost** [comment]
I will test and feedback/review/approve shortly for you. If possible could you please do the same for either or both of my 2 PR's which are stuck awaiting peer review it would be appreciated: https://github.com/OCA/server-tools/pull/2218 or https://github.com/OCA/server-tools/pull/2214

**Review by ghost — APPROVED** [review]
Ran on clean Ubuntu 20.04 install tested by changes core odoo addons .py files detects the different hash properly. Default config used. No errors on console, logs or shell.

**Review by StefanRijnhart — APPROVED** [review]

**Comment by mlaitinen** [comment]
Merge failed due to cache issue? https://github.com/OCA/server-tools/pull/2225#issuecomment-997676709

**Comment by StefanRijnhart** [comment]
@mlaitinen let's try again!

/ocabot merge nobump

**Pull request merged**
