### PR TITLE
[MIG] module_change_auto_install: Migration to 15.0

### PR DESCRIPTION
**Pull request by kafai-lam**
related issue #2400

generated commit follows [this migration guide](https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-15.0#technical-method-to-migrate-a-module-from-140-to-150-branch)

### CODE REVIEW

**Review by legalsylvain — APPROVED** [review]
Diff review. No test. Thanks !

**Review by AungKoKoLin1997 — COMMENTED** [review]
LGTM

**Comment by kafai-lam** [comment]
@legalsylvain @AungKoKoLin1997 
updated README addons table via `oca-gen-addons-table` command

**Comment by legalsylvain** [comment]
That's not necessary, as bot is doing it automatically. (but it doesn't hurt)

**Comment by kafai-lam** [comment]
@lasley @AungKoKoLin1997 any update on it?

**Comment by StefanRijnhart** [comment]
\ocabot migration module_change_auto_install

**Review by StefanRijnhart — APPROVED** [review]

**Pull request merged**
