### PR TITLE
Global pylint cleanup

### PR DESCRIPTION
**Pull request by simahawk**

### CODE REVIEW

**Comment by simahawk** [comment]
any good reason to keep[ these classes ](https://travis-ci.org/OCA/server-tools/jobs/423821580#L589)splitted? 
```bash
module_auto_update/models/module_deprecated.py:10: [R7980(consider-merging-classes-inherited), Module] Consider merging classes inherited to "ir.module.module" from models/module.py:51.
```
If not, I can merge them, otherwise I disable pylint check for that error.

**Comment by pedrobaeza** [comment]
@sbidoul @Yajo can you tell about the question?

**Comment by sbidoul** [comment]
@simahawk yes, we want to keep the code of the deprecated part separate from the the normal path. Please disable the warning if it's make the build red.

**Comment by simahawk** [comment]
@sbidoul no error, just warnings, but now the build is really clean w/out tons of warnings :fireworks:

**Review by pedrobaeza — APPROVED** [review]

**Review by yajo — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Let's merge it

**Pull request merged**
