### PR TITLE
[FIX] 11.0 auto_backup: .dump files not being cleaned

### PR DESCRIPTION
**Pull request by j-zaballa**
Description of the issue/feature this PR addresses:

cleanup method only looking for .dump.zip files, so .dump files are not
being deleted as intended

Current behavior:

No cleanup for .dump files

Desired behavior after PR is merged:

.dump files get deleted

### CODE REVIEW

**Review by CasVissers-360ERP — APPROVED** [review]
Critical fix in my opinion. Thanks a lot.

**Comment by pedrobaeza** [comment]
Please check Travis

**Comment by j-zaballa** [comment]
@pedrobaeza I'm terrible checking Travis errors and I might be missing something, but all the errors I can see are related to `onchange_helper`. I could use some help. Thanks!

**Comment by pedrobaeza** [comment]
Is the main branch also red?

**Comment by j-zaballa** [comment]
I think the main branch was green. I rebased and renamed a variable name to avoid variable shadowing (I was using `format` as a variable name before). Let's check if that was it.

**Review by enriquemartin — APPROVED** [review]
Looks good to me!

**Comment by j-zaballa** [comment]
@pedrobaeza could you please check this one? Thanks in advance :)

**Comment by pedrobaeza** [comment]
Sorry, I don't use this module, so I'm not a valid reviewer.

**Comment by pedrobaeza** [comment]
Seeing that it's already reviewed, I proceed with the merge

/ocabot merge minor

**Comment by j-zaballa** [comment]
Thank you very much!

**Pull request merged**
