### PR TITLE
[12.0][IMP] base_jsonify: Serialize Date and Datetime into ISO 8601 format

### PR DESCRIPTION
**Pull request by lmignon**
follows discussion https://github.com/OCA/server-tools/pull/1711#pullrequestreview-309157848

### CODE REVIEW

**Comment by lmignon** [comment]
@hparfr @sbidoul here it's the fix following your comments on #1711 (review)

**Review by sbidoul — APPROVED** [review]

**Review by hparfr — APPROVED** [review]

**Comment by hparfr** [comment]
Thanks

**Comment by lmignon** [comment]
@moylop260 Thank you for the merge but I'm very annoyed  that these change are merged these  without incrementing the version......  
@sbidoul How can we create a new version?  Do we have a new version published on Pypi If I make a new PR to manually increment the version number and we use the `ocabot merge` command?

**Comment by sbidoul** [comment]
@lmignon it is published, just with a .dev version.
But indeed doing ocabot merge without version bump should be exceptional.
To get a round version number on PyPI, just push a commit with the version bump to the main branch.

**Comment by lmignon** [comment]
ok thank you @sbidoul

**Pull request merged**
