### PR TITLE
[FIX] server_environment setup.py cannot find odoo-addon-server_environment_files

### PR DESCRIPTION
**Pull request by sbidoul**
Backport from v9

### CODE REVIEW

**Review by lasley — APPROVED** [review]

**Comment by lasley** [comment]
From what I can tell, that lint error is unrelated - would like a double check though please

**Comment by pedrobaeza** [comment]
It has been motivated by a check that has been introduce lately, but important to be fixed:

```
base_field_validator/models/ir_model.py:9: [W0404(reimported), ] Reimport '_' (imported line 6)
```

I have fixed it in 8.0, so please rebase.

**Comment by sbidoul** [comment]
rebased

**Review by pedrobaeza — APPROVED** [review]

**Comment by lasley** [comment]
Hah now we switched a 🔴 lint for a 🔴 build. Gotta love software development!

**Comment by sbidoul** [comment]
This one is red on OCB only. Anyone knows why?

**Comment by lasley** [comment]
I think I saw this in another server-tools PR that day as well - I just triggered a rebuild on it, and now we are 🍏 !

**Pull request merged**
