### PR TITLE
[ADD] - dbfilter_from_header: Migrated and reviewed module

### PR DESCRIPTION
**Pull request by fv-clearcorp**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Thanks for the contribution!

You can take the occasion to update the module to latest conventions:
- Short header, like in https://github.com/OCA/maintainer-tools/blob/master/template/module/__init__.py
- Extract the description in a README.rst and complete it with this template: https://raw.githubusercontent.com/OCA/maintainer-tools/master/template/module/README.rst
- Maybe you are able to provide a test?

**Comment by hbrunn** [comment]
you should also cherry-pick https://github.com/OCA/server-tools/commit/5737ebc97c048eb46c3850698bc3304fafb4a518

**Comment by ghost** [comment]
@hbrunn done :+1:

**Comment by hbrunn** [comment]
:+1:

**Comment by hbrunn** [comment]
@moylop260 I think you merged too early. @pedrobaeza still had some open points

**Comment by pedrobaeza** [comment]
Yes, they are only about form, not the module itself. @moylop260, now you have to make the PR fixing them :stuck_out_tongue_winking_eye:

**Comment by ghost** [comment]
Changes in #383

**Comment by moylop260** [comment]
haha

**Pull request merged**
