### PR TITLE
[ADD] support needaction

### PR DESCRIPTION
**Pull request by hbrunn**

### CODE REVIEW

**Comment by StefanRijnhart** [comment]
:+1:

**Comment by hbrunn** [comment]
@seb-elico your commit from #309 breaks because we need to pass timeout as keyword argument. Does this work for you as it is? I fixed it to work on my systems in e051174, could you check if this works on your python too?

**Comment by seb-elico** [comment]
@hbrunn Hi, I tested the latest version (the one with timeout as keyword argument) and it's working as well. All good for me!

**Comment by pedrobaeza** [comment]
Can you check Travis status?

**Comment by hbrunn** [comment]
@pedrobaeza thanks for the heads up, should become green now

**Comment by pedrobaeza** [comment]
:+1:

**Pull request merged**
