### PR TITLE
[9.0] base_export_manager - Fix TypeError: Session.get_export_models is not a function

### LINKED ISSUE #525: [base_export_manager] "TypeError: Session.get_export_models is not a function" bug.
After installing 'base_export_manager' module into odoo 9.0, by access any list tree view I met below error dialog:

Odoo Client Error

TypeError: Session.get_export_models is not a function

http://localhost:8069/base_export_manager/static/src/js/base_export_manager.js:54

### PR DESCRIPTION
**Pull request by max3903**
Fixes #525

### CODE REVIEW

**Comment by max3903** [comment]
@smangukiya's contributions are covered by Ursa's ECLA.

**Comment by max3903** [comment]
@smangukiya Can you fix it please? We get an error on each list view on runbot, making it unusable. Thanks!

**Comment by smangukiya** [comment]
@max3903 : Can you please look into this last pull request which I have made long before?
https://github.com/max3903/server-tools/pull/2/commits/00fb5e921d62962810ef49590d130048072ca309

This change has already fix regarding this, why I can't see it in main OCA/server-tools?
Thanks

**Comment by max3903** [comment]
@smangukiya https://github.com/max3903/server-tools/pull/2/commits/00fb5e921d62962810ef49590d130048072ca309 was not merged into OCA/server-tools. That's why I created this one. Can you fix the conflicts?

**Comment by max3903** [comment]
Merged @ https://github.com/OCA/server-tools/commit/c29c0f42221fd8e68f18275c915bb53db573b550

**Pull request closed without merging**
