### PR TITLE
[9.0][MIG][base_custom_info] Migration.

### PR DESCRIPTION
**Pull request by yajo**
Mostly no changes from 8.0 after all.

@Tecnativa https://github.com/OCA/server-tools/issues/271

### CODE REVIEW

**Comment by moylop260** [comment]
👍 
thanks

**Comment by rafaelbn** [comment]
:+1:

**Comment by pedrobaeza** [comment]
:+1:

**Comment by diggy128** [comment]
Last commit from @Yajo mentioned almost no changes to migrate to V9.0, however the merge from @pedrobaeza severely cripples the module removing several fields and changing the behavior with no visible migration path.

Was this an mentioned/inteded change or something got wrong?

**Comment by pedrobaeza** [comment]
See the other PR for the explanation of the changes.

**Pull request merged**
