### PR TITLE
[13.0][MIG] auto_backup

### PR DESCRIPTION
**Pull request by dalonsod**
Standard migratrion. Supersedes #1697 due to inactivity

### CODE REVIEW

**Comment by dalonsod** [comment]
@eLBati @jcarlosmontoya could you review? Thanks!

**Review by LoisRForgeFlow — APPROVED** [review]
Code review, LGTM

**Comment by dalonsod** [comment]
Rebase made due to a merge conflict with a recent `requirements.txt` update

**Comment by LoisRForgeFlow** [comment]
@dalonsod something went wrong in the rebase. You have added a merge commit:
image

You should clean that.

**Review by gaikaz — APPROVED** [review]
Code review + Partial (daily full backup creation) funcional testing.

**Comment by CasVissers-360ERP** [comment]
@dalonsod 
You forgot this critical fix: #1442

**Comment by dalonsod** [comment]
> You forgot this critical fix: #1442

Thanks, @CasVissers-360ERP , when I resume this PR I'll try. This PR was not cherry-picked in v12, that's why is missing here.

**Review by tcamberlin — APPROVED** [review]
Functional test and backups creation OK.

**Comment by dalonsod** [comment]
@CasVissers-360ERP #1442 applied

**Comment by dalonsod** [comment]
@LoisRForgeFlow rebase properly made

**Comment by dalonsod** [comment]
@LoisRForgeFlow travis is not passed due to aun error in tests of an OCB module. Is that correct?

**Comment by dalonsod** [comment]
> travis is not passed due to aun error in tests of an OCB module. Is that correct?

Could anyone help me with this? Travis is in error and I'm not sure if the issue belongs to this addon. Thanks!

**Comment by gaikaz** [comment]
@dalonsod Could you try triggering a rebuild?
It seems like other newer PRs are passing fine. Yours failed only on OCB, but passed on plain Odoo build. 
Maybe there were changes and it now passes?

**Pull request merged**
