### PR TITLE
[14.0][IMP] upgrade_analysis: log sql_constraints in analysis

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Solves https://github.com/OCA/server-tools/issues/2221.
Forward port of https://github.com/OCA/OpenUpgrade/pull/3012.

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
Analysis in https://github.com/OCA/OpenUpgrade/pull/3013.

**Review by legalsylvain — CHANGES_REQUESTED** [review]
Hi @MiquelRForgeFlow thanks a lot for this addition.

one remark however, could you remove the large change in the analysis file. the current structure is a change = a line. not a change = 40 lines).
see : https://github.com/OCA/OpenUpgrade/pull/3013/files#diff-34e246e6b6b9a1b02f62a0af334f4363a149756fb2ea89e9230ab3389b739f06R368

In all the other case, when there is a change, openupgrader will check the code to know what to do.

thanks !

**Comment by MiquelRForgeFlow** [comment]
Yeah, I will do that. One moment.

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
