### PR TITLE
[14.0][IMP] base_time_parameter: value_reference: standard selection

### PR DESCRIPTION
**Pull request by norlinhenrik**
Inherit like this:
```
value_reference = fields.Reference(
    selection_add=[("account.account", "Account")],
)
```

### CODE REVIEW

**Review by nimarosa — APPROVED** [review]

**Comment by nimarosa** [comment]
Very great change. Now it's easy to use value_reference.

Another improvement I have in mind is a view tweak maybe we can include it here: 

- Hide value reference field in views table when value_reference it's not selected

Do you think it's possible?

**Comment by norlinhenrik** [comment]
> Hide value reference field in views table when value_reference it's not selected

I think this would require javascript customization since the optional value is "hide" or "show".
If it would be "1" or "0", probably we could hide value_reference like this: attrs="{'hide':[('type', '!=', 'reference')]}"

So I set optional="hide" and added to the Reference a short description of how to show the column.

**Comment by nimarosa** [comment]
@norlinhenrik I think you can use the "column_invisible", something like this: 

attrs="{'column_invisible':[('parent.type', '!=', 'reference')]}"

"parent" is necessary to access the version parent class (base Time parameter) because the type field is in main class not in versions one. 

This should work, I used in some modules. We can also do the other part, and hide the value field if reference is selected. That way we only show only one field (value or value_reference) depending on type.

**Comment by norlinhenrik** [comment]
Thank you, @nimarosa !!! I think you can merge it.

**Review by nimarosa — APPROVED** [review]

**Pull request merged**
