### PR TITLE
[add] auth_oauth_multi_token

### PR DESCRIPTION
**Pull request by simahawk**
Take over #482 and migrate to v10. 
Cleaned up, improved, tested.

### CODE REVIEW

**Review by guewen — APPROVED** [review]

**Comment by fmdl** [comment]
@simahawk Thanks man !

**Review by fmdl — APPROVED** [review]

**Review by mpanarin — APPROVED** [review]

**Review by ghost — APPROVED** [review]
LGTM!

**Review by sla-subteno-it — APPROVED** [review]

**Comment by simahawk** [comment]
@guewen merge? :)

**Comment by fmdl** [comment]
Info : MIG V11 https://github.com/OCA/server-auth/pull/16

**Comment by fmdl** [comment]
@simahawk in the last version of odoo V10,  the security of the session have been increase, that why you need to add the code from this commit :

https://github.com/OCA/server-auth/commit/4b924230a7f13c258ce002d6a9e1dc4f5ae7febf

I can do that if you want.

**Comment by simahawk** [comment]
@fmdl tnx for reporting :)
Yes please, go ahead w/ a PR on my fork if you can. :)

**Comment by fmdl** [comment]
See here : https://github.com/OCA/server-tools/pull/1241

regards

**Comment by simahawk** [comment]
@fmdl cherry-picked

**Review by fmdl — APPROVED** [review]

**Comment by fmdl** [comment]
@guewen merge? :)

**Pull request merged**
