### PR TITLE
[15][MIG] Migrate auto_backup

### PR DESCRIPTION
**Pull request by anhvu-sg**
This module had been installed and used on my V15 project.

### CODE REVIEW

**Comment by bobslee** [comment]
Hi @anhvu-sg , do yo know how this modules differs from? https://apps.odoo.com/apps/modules/15.0/auto_backup/
Seems there's already a v15 release for the one in the link.

**Comment by flachica** [comment]
You need clean git history

**Review by flachica — CHANGES_REQUESTED** [review]
Please, squash commits

**Review by manuelcalerosolis — APPROVED** [review]

**Comment by anhvu-sg** [comment]
> Please, squash commits

done @flachica

**Review by flachica — APPROVED** [review]

**Comment by flachica** [comment]
@sebalix @sbidoul This PR is Approved but no merged, Help, please

**Comment by cubells** [comment]
@anhvu-sg you must add history of commits to this PR.

**Comment by anhvu-sg** [comment]
hi @cubells , thanks for your support. The history have been updated

**Comment by cubells** [comment]
thanks @anhvu-sg 

Now you can solve conflicts by rebasing

**Comment by anhvu-sg** [comment]
> thanks @anhvu-sg
> 
> Now you can solve conflicts by rebasing

done @cubells

**Pull request merged**
