### PR TITLE
[12.0][FIX] database_cleanup: only uninstall installed modules (greenify repo)

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Due to https://github.com/odoo/odoo/commit/0ca82f2a75b7c2559fd77eed4b65bf6e7bc46576.

### CODE REVIEW

**Review by AaronHForgeFlow — APPROVED** [review]
:+1:

**Comment by MiquelRForgeFlow** [comment]
@JordiBForgeFlow @kittiu

**Comment by MiquelRForgeFlow** [comment]
The last error, related to `fetchmail_notify_error_to_sender` (`test_mail` in reality), should be fixed in https://github.com/OCA/OCB/pull/916.

**Pull request merged**
