### PR TITLE
[15.0] [MIG] session db: Migration to 15.0

### PR DESCRIPTION
**Pull request by IT-Ideas**

### CODE REVIEW

**Comment by thomaspaulb** [comment]
@IT-Ideas 

- The version update should be part of the migration commit, so, needs to be separate from the pre-commit fixes
- You probably also want to include the fix [here](https://github.com/OCA/server-tools/pull/2596)
- And maybe you can leave your review there as well in order to get it merged quicker

**Review by IT-Ideas — COMMENTED** [review]
No real code change with 14.0 version but:
* disabling two pylint `except-pass`
* modifying tests as assertRaises uses a savepoint in 15.0, which was failing because of the patching made upfront


Tested functionally

**Comment by IT-Ideas** [comment]
@thomaspaulb , here you are!

**Review by thomaspaulb — APPROVED** [review]

**Comment by thomaspaulb** [comment]
@IT-Ideas thanks! If you can, your review still on https://github.com/OCA/server-tools/pull/2596 would be greatly appreciated

**Comment by IT-Ideas** [comment]
@lmignon

**Review by lmignon — APPROVED** [review]

**Pull request merged**
