### PR TITLE
Migrate mail_environment to 10.0

### PR DESCRIPTION
**Pull request by guewen**
need https://github.com/OCA/server-tools/pull/595

### CODE REVIEW

**Review by yvaucher — APPROVED** [review]

**Comment by yvaucher** [comment]
Tested and code LGTM

**Comment by moylop260** [comment]
Could you fix `mail_environment/README.rst:76: [E7901(rst-syntax-error), ]  Bullet list ends without a blank line; unexpected unindent.` and use 4 spaces for xml files, please?

**Comment by yvaucher** [comment]
@moylop260 this is a no for 4 spaces in xml files it was discussed long ago and people were mostly in favor of 2 spaces but for history reasons we didn't enforced it.

There are at least 554 xml files in OCA with 2 space indentation.

**Review by moylop260 — APPROVED** [review]

**Review by leemannd — APPROVED** [review]

**Comment by leemannd** [comment]
@gurneyalex @guewen Could be merged?

**Pull request merged**
