### PR TITLE
Migrate Sentry to 15.0

### PR DESCRIPTION
**Pull request by aisopuro**
This PR replaces #2386:
* This branch has been rebuilt on top of `14.0` in order to include the recently merged switch to using `sentry_sdk` instead of `raven`.
* I "stole credit" for the original migration from the previous author, but considering it was only changing the version in the manifest, this seems like a minor issue
* The previous PR included commits that fixed tests to run: these were already fixed in `14.0`, and so those commits are not necessary in this PR.
* This is a new PR because I need the old branch to exist as-is as it is being referenced in some projects, and I need to verify it is safe for them to suddenly change their pip-requirements.

### CODE REVIEW

**Comment by aisopuro** [comment]
2 tests are failing, but they are not in `sentry`. I'll try force-pushing to re-trigger the pipelines, in the hopes that helps.

**Comment by aisopuro** [comment]
Failing tests appear to be in `letsencrypt`. Judging by the exception the unit test is actually contacting LetsEncrypt, and getting an error about assigning certificates to `*.example.com`:
```
acme.messages.Error: urn:ietf:params:acme:error:rejectedIdentifier :: The server will not issue certificates for the identifier :: Error creating new order :: Cannot issue for "*.example.com": The ACME server refuses to issue a certificate for this domain name, because it is forbidden by policy
```
Possibly the policy has changed since the tests were written.

There are no errors in the 14.0 branch, I'll see if there are fixes in there.

**Comment by aisopuro** [comment]
There are no changes to `letsencrypt` between this branch and `14.0`. I don't know what to do.

@janverb and @NL66278 , you seem to be the ones who introduced one of the tests that is now failing: https://github.com/OCA/server-tools/blob/14.0/letsencrypt/tests/test_letsencrypt.py#L79

Do either of you have an idea of what might be going wrong here? Judging by the error, it almost seems like we're getting a response from actual LetsEncrypt, despite it seeming like we're mocking things pretty thoroughly.

This is the traceback I'm seeing in the test logs:
```
 2022-10-17 11:23:33,024 261 INFO odoo odoo.addons.letsencrypt.tests.test_letsencrypt: ====================================================================== 
2022-10-17 11:23:33,024 261 ERROR odoo odoo.addons.letsencrypt.tests.test_letsencrypt: ERROR: TestLetsencrypt.test_dns_challenge
Traceback (most recent call last):
  File "/opt/odoo-venv/lib/python3.8/site-packages/mock/mock.py", line 1346, in patched
    return func(*newargs, **newkeywargs)
  File "/__w/server-tools/server-tools/letsencrypt/tests/test_letsencrypt.py", line 114, in test_dns_challenge
    self.env["letsencrypt"]._cron()
  File "/__w/server-tools/server-tools/letsencrypt/models/letsencrypt.py", line 94, in _cron
    authzr = self._get_authorization_resource(client, main_domain, domains)
  File "/__w/server-tools/server-tools/letsencrypt/models/letsencrypt.py", line 265, in _get_authorization_resource
    return client.new_order(csr)
  File "/opt/odoo-venv/lib/python3.8/site-packages/acme/client.py", line 714, in new_order
    response = self._post(self.directory['newOrder'], order)
  File "/opt/odoo-venv/lib/python3.8/site-packages/acme/client.py", line 114, in _post
    return self.net.post(*args, **kwargs)
  File "/opt/odoo-venv/lib/python3.8/site-packages/acme/client.py", line 1289, in post
    return self._post_once(*args, **kwargs)
  File "/opt/odoo-venv/lib/python3.8/site-packages/acme/client.py", line 1303, in _post_once
    response = self._check_response(response, content_type=content_type)
  File "/opt/odoo-venv/lib/python3.8/site-packages/acme/client.py", line 1149, in _check_response
    raise messages.Error.from_json(jobj)
acme.messages.Error: urn:ietf:params:acme:error:rejectedIdentifier :: The server will not issue certificates for the identifier :: Error creating new order :: Cannot issue for "*.example.com": The ACME server refuses to issue a certificate for this domain name, because it is forbidden by policy
```

I couldn't see any obvious recent changes to the `acme` package, though I'll admit I don't really know what I'm looking for.

**Comment by thomaspaulb** [comment]
@aisopuro The failing tests are from `letsencrypt`, have asked @NL66278 to try and fix them in a separate PR, then we can rebase this one when it is merged.

**Comment by thomaspaulb** [comment]
Ah, you had already come to the same conclusion I see.

**Comment by NL66278** [comment]
@aisopuro Please rebase your branch on latest 15.0. This now contains a fix by @StefanRijnhart that should solve the letsencrypt problems.

**Comment by aisopuro** [comment]
Rebased and pushed, thanks for the help @NL66278

**Review by thomaspaulb — APPROVED** [review]

**Review by hugho-ad — APPROVED** [review]

**Pull request merged**
