### PR TITLE
[12.0][MIG] auto_backup: Migration to 12.0

### PR DESCRIPTION
**Pull request by aitorbouzas**
Migration to 12.0
**Changes**
- Added test coverage
- Added requirements.txt for pysftp
- Added in the roadmap the exact version of pysftp for this to work (0.2.8)
- Added in the roadmap the problem with ```list_db=False```
- Adapted calls to ```message_post```

### CODE REVIEW

**Comment by aitorbouzas** [comment]
I need help with runbot, it needs pysftp installed, how can I fix this?
Also, same as other PR's I did: Why is Travis not working?

**Comment by aitorbouzas** [comment]
By the way, just saw I needed [this](https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md#requirementstxt) for the pysftp.

**Comment by awa-si** [comment]
If config 'list_db = False' it does not execute because db management is deactivated just in case.
You need to change 'backup_log' with prefix 'body=' else it trow an error by execution 'message_post' 'TypeError: message_post() takes 1 positional argument but 2 were given':

    @api.multi
    @contextmanager
    def backup_log(self):
        """Log a backup result."""
        try:
            _logger.info("Starting database backup: %s", self.name)
            yield
        except Exception:
            _logger.exception("Database backup failed: %s", self.name)
            escaped_tb = tools.html_escape(traceback.format_exc())
            self.message_post(body="<p>%s</p><pre>%s</pre>" % (
                _("Database backup failed."), escaped_tb),
                subtype = self.env.ref(
                    "auto_backup.mail_message_subtype_failure"
                ),
            )
        else:
            _logger.info("Database backup succeeded: %s", self.name)
            self.message_post(body=_("Database backup succeeded."))

**Comment by aitorbouzas** [comment]
@awwea Thanks for the review. I just fixed the message_post call.
Could you please elaborate on what you mean by ```If config 'list_db = False' it does not execute because db management is deactivated just in case.```?

**Comment by aitorbouzas** [comment]
@awwea Oh well! I just understood and checked it. You are right, the db class won't let the module run ```db_dump ``` when ```list_db=False``` is set in the config...
Will ping @Yenthe666 to see if he can help us.
Guess we can only add this configuration issue to the roadmap and try to commit some changes to Odoo?

**Comment by Yenthe666** [comment]
@aitorbouzas hmm yes, this is a difficult one. We need a way to get the db details and historically I kept doing this from the database list option. The option to get the db's out is not available when `list_db=False` though. I've thought about it a few times but couldn't figure out a neat way to drop the `list_db` use so I'm not sure what would be the best approach to overcome that.

**Comment by aitorbouzas** [comment]
@Yenthe666 Well, just added it to the roadmap in the readme. We can't do anything about that in this PR.

**Comment by Yenthe666** [comment]
Exactly - good job!

**Comment by aitorbouzas** [comment]
This is ready, but I need some help with the coverage. Do I need to hit 100%? Can't see the non-covered lines =/
@Yenthe666

**Comment by Yenthe666** [comment]
Hmm I think somebody from OCA itself can answer this better, I'm not very active on the OCA parts. 😉

**Comment by ddufresne** [comment]
@aitorbouzas thanks for porting the module.
There is an open PR on v11 for supporting hourly backups. Your review would be much appreciated.

https://github.com/OCA/server-tools/pull/1341

**Review by ddufresne — APPROVED** [review]
LGTM

Tested with local instance.

**Review by foutoucour — APPROVED** [review]
Look good to me. Just fix the conflicts in the `requirements.txt` file

**Comment by LoisRForgeFlow** [comment]
@aitorbouzas Could you fix conflicts here?

**Comment by LoisRForgeFlow** [comment]
This does not look good, you should have done a rebase, not merging the main branch into your branch.

**Comment by aitorbouzas** [comment]
@lreficent phew, I thought I messed all up. Is it okay now?

**Comment by LoisRForgeFlow** [comment]
@aitorbouzas Perfect now, Thanks!

**Review by LoisRForgeFlow — APPROVED** [review]

**Comment by rousseldenis** [comment]
@OCA/core-maintainers

**Pull request merged**
