### PR TITLE
Migration to 12.0 

### PR DESCRIPTION
**Pull request by GoodERPJeff**
auditlog

base_cron_exclusion

base_exception

base_technical_user

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please, only one module per PR, so the review can be speed up and the number of files is manageable. Remember also to follow technical guide for preserving commit history. You can reuse this PR for one module or close it and start new ones.

**Comment by elicoidal** [comment]
@GoodERPJeff if you need me for review, just ping me in a comment

**Comment by GoodERPJeff** [comment]
> Please, only one module per PR, so the review can be speed up and the number of files is manageable. Remember also to follow technical guide for preserving commit history. You can reuse this PR for one module or close it and start new ones.

Thank you @pedrobaeza for your quickly comments.

Actually I hosted a codesprint in china this afternoon. 4 teams did pair work and push their code to osipass repo, I merged them all and create this PR to OCA. Seems I should merge them one by one and create PR for each of them separately next time.

What I wonder is what is the issue  of "preserving commit history" you mean?

the code change today if very small, each module is working fine on 12.0, so only the version number were increased, so can we just make it bulk in this PR? I promise I will split our work by module next time.

We are learning the whole process to contribute, thanks for all your kindly support and guidance.

@elicoidal Thank you. I will try my best to figure out why the CI fail... will ping you if need your help.

**Comment by pedrobaeza** [comment]
Migration can be considered easy for each module, but one proof that is not is that both runbot and Travis are red, so please split your contribution per module. The commit history seems to be preserved, as the number of commits is high. The guide for doing it is in https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-12.0#technical-method-to-migrate-a-module-from-110-to-120-branch

**Comment by GoodERPJeff** [comment]
I close this PR for now and will split them one bye one, thank you.

**Comment by pedrobaeza** [comment]
Thanks for the understanding

**Pull request closed without merging**
