### PR TITLE
[IMP] base_time_parameter: Added Reference ID type

### PR DESCRIPTION
**Pull request by divya891998**

### CODE REVIEW

**Review by norlinhenrik — APPROVED** [review]
Hello @nimarosa 
I have a use case where I should replace the parameter code with the reference record **id**.

**Review by nimarosa — APPROVED** [review]
Code review ok. No major change so we can merge this fast.

**Comment by nimarosa** [comment]
Checks looks good here... lets try again.

/ocabot merge patch

**Pull request merged**
