### PR TITLE
[FIX] Import safe_eval function instead of module.

### PR DESCRIPTION
**Pull request by daramousk**

### CODE REVIEW

**Comment by daramousk** [comment]
@hbrunn This should be fine as well

**Review by hbrunn — APPROVED** [review]

**Review by bealdav — APPROVED** [review]

**Comment by NL66278** [comment]
@pedrobaeza This is another one with the two green labels and not even a question outstanding.

**Comment by rousseldenis** [comment]
@OCA/core-maintainers

**Review by astirpe — APPROVED** [review]

**Comment by daramousk** [comment]
cc: @hbrunn Maybe this can be merged

**Pull request merged**
