### PR TITLE
Fix pylint on server_environment

### PR DESCRIPTION
**Pull request by dreispt**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1:

**Comment by dreispt** [comment]
@pedrobaeza Sorry Pedro, I changed my proposed fix: I wasn't happy with the previous change in the function signature.

**Comment by rvalyi** [comment]
:+1:  LGTM

**Comment by pedrobaeza** [comment]
OK, I see, it can affect deriving modules (if any).

Again, :+1:

**Comment by dreispt** [comment]
It would be nice to have on more OK before this is merged.

**Comment by eLBati** [comment]
:+1:

**Pull request merged**
