### PR TITLE
[14.0][IMP] base_jsonify: Allow to export many2one and referene field as simple field

### PR DESCRIPTION
**Pull request by Cedric-Pigeon**
foward port #2063

### CODE REVIEW

**Review by rousseldenis — APPROVED** [review]

**Review by lmignon — APPROVED** [review]

**Comment by lmignon** [comment]
Tired..... now it's not possible to merge a PR since some addons are calling external resources into their unittest without mocking the calls. And since these services are not reliable, (limit in number of calls / days / sec, ...) we are stuck.   This repo is too big and addons calling external resources, if not adapted to mock the call, should be isolated into a single addon repo...

**Pull request merged**
