### PR TITLE
[WIP] from 8.0 to 9.0 base_optional_quick_create

### PR DESCRIPTION
**Pull request by JonathanNEMRY**
- bump version to 9.0.1.0.0 and make it installable
- apply a views/models directory arch into the module
- fix xpath anchor on ir_model views (osv_memory to transient)
- add README.rst
- apply some new api

### CODE REVIEW

**Comment by pedrobaeza** [comment]
This modules shouldn't be migrated to 9.0. As discussed on https://github.com/OCA/server-tools/pull/300#issuecomment-159908187. We mustn't duplicate features between several modules. The module to be migrated is: https://github.com/OCA/web/tree/8.0/web_m2x_options

**Comment by sbidoul** [comment]
@pedrobaeza `base_optional_quick_create` is a feature accessible to the administrator and applies globally.

OTOH, if I understand well, `web_m2x_options` can achieve the same result but requires changing the option on all widgets in all the views where they are used.

So IMO it's a different use case and `base_optional_quick_create` must be kept.

**Comment by pedrobaeza** [comment]
No, you can apply it globally with a system parameter. Please read the discussion between @StefanRijnhart and me on the link provided to get background about it.

**Comment by sbidoul** [comment]
@pedrobaeza which link?

**Comment by pedrobaeza** [comment]
Sorry, I though I copied that link, but it was wrong: https://github.com/OCA/server-tools/pull/300#issuecomment-159908187 (copied also on the original quote).

**Comment by sbidoul** [comment]
I see. We have no budget to work on this at the moment so we'll leave it as is for the moment. I updated #271.

**Comment by StefanRijnhart** [comment]
I still don't agree with @pedrobaeza. Apparently, base_optional_quick_create has quite a number of sponsors here, and it's technically in a pretty good condition now.

**Comment by sbidoul** [comment]
rebased and added setup.py cc/ @JonathanNEMRY @Olivier-LAURENT

**Comment by JonathanNEMRY** [comment]
Thanks @sbidoul ! :+1: 
Regarding last @StefanRijnhart 's comment  do you now agree to take this one as a valid candidate for 9.0 @pedrobaeza ?

**Comment by pedrobaeza** [comment]
OK, go ahead

**Comment by sbidoul** [comment]
Tested on runbot. :+1:

**Comment by StefanRijnhart** [comment]
Thanks! :+1:

**Comment by atchuthan** [comment]
Tested on runbot :+1:

**Comment by JonathanNEMRY** [comment]
Thank you all!

**Pull request merged**
