### PR TITLE
Fix bug that made previous images to disappear.

### PR DESCRIPTION
**Pull request by yajo**
Fixes https://github.com/OCA/product-attribute/pull/135#issuecomment-191358505. (when merged).

Although this is a breaking change, it current submodules don't use hooks (the only breaking part). The current implementation was useless anyway.

@rafaelbn @carlos-incaser

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Why it has to be done in pre instead of post?

**Comment by yajo** [comment]
Because on post images are already gone.

**Comment by pedrobaeza** [comment]
OK, I understand. What about the signature change?

**Comment by yajo** [comment]
Signature?

**Comment by pedrobaeza** [comment]
The signature is the number and the name of the arguments of a method

**Comment by yajo** [comment]
ah sorry, pre_init_hooks lack the registry argument.

**Comment by pedrobaeza** [comment]
OK, thanks for the explanation. I didn't remember that.

:+1: 

I'm going to fast-track to avoid people that starts using this module uses this wrong hook.

**Comment by yajo** [comment]
Thank you :wink:

**Pull request merged**
