### PR TITLE
[MIG]Migrated base_export_manager module.

### PR DESCRIPTION
**Pull request by maulik-raval**

### CODE REVIEW

**Comment by mourad-ehm** [comment]
Code review :+1:

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
You haven't respected commit history. Please follow migration guide: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0#technical-method-to-migrate-a-module-from-90-to-100-branch

**Comment by rafaelbn** [comment]
Hi @maulik-raval-serpentcs are you going to continue this PR correctly? Thanks

**Comment by yvaucher** [comment]
I will be working on this to repair the missing commits

**Comment by yajo** [comment]
Long time no answer, closing; I'll retake.

**Comment by yvaucher** [comment]
@Yajo Did you see my comment ?

**Comment by yajo** [comment]
woah missed it, I've got the commits, will push here then

**Comment by yvaucher** [comment]
By the way it seems that the only missing commits are translation updates or am I missing something ?

**Comment by yvaucher** [comment]
@Yajo anyway we need to create a new pull request I don't have the write access on this one from serpent CS

**Comment by yajo** [comment]
OK, I overwrote this branch to get the translations. I do have write access, so we can close it or continue here, what do you prefer?

**Comment by yvaucher** [comment]
What you prefer. I have no additional change that those update translation commits you already did

**Comment by yajo** [comment]
OK, It's done now so let's continue here. Reviews please! 😊

**Review by yvaucher — APPROVED** [review]

**Comment by pedrobaeza** [comment]
I think there are changes in 8.0 that are not reflected here (you need to check also that branch).

**Comment by yajo** [comment]
Let me see.

**Comment by yajo** [comment]
Yikes, branches 8 and 9 evolved in different ways...

I'll close and open a new PR once all is in, sorry for the noise.

**Comment by yajo** [comment]
New PR: #870

**Pull request closed without merging**
