### PR TITLE
[FIX] coding style

### PR DESCRIPTION
**Pull request by hbrunn**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
flake8 is now correct, but there are some pylint errors and server doesn't work also. Can you please check it?

**Comment by hbrunn** [comment]
yes, that's for iteration 2 after lunch

**Comment by pedrobaeza** [comment]
Eet smakelijk!

**Comment by hbrunn** [comment]
gracias!

**Comment by pedrobaeza** [comment]
Please test it with OCB branch also.

**Comment by pedrobaeza** [comment]
Nevermind, this is 6.1, so there's no easy possibility of that. Then remove one of the Travis line, because they do the same.

**Comment by hbrunn** [comment]
done & squashed .travis.yml commits

**Comment by pedrobaeza** [comment]
:+1:

**Comment by dreispt** [comment]
:+1:

**Comment by pedrobaeza** [comment]
I merge to solve Travis finally.

**Pull request merged**
