### PR TITLE
[8.0] migration of auth_admin_passkey

### PR DESCRIPTION
**Pull request by anthony-muschang**
The module works in 8.0 with no modifications required.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
You can take the occassion to extract the description of the module and put it on README.rst file apart, so that both Odoo and Github read that file.

**Comment by pedrobaeza** [comment]
Otherwise, :+1:

**Comment by pedrobaeza** [comment]
The description file must be README.rst, not README.md, because this way parsers get confused about the syntax.

**Comment by pedrobaeza** [comment]
:+1:

**Comment by legalsylvain** [comment]
LGTM :+1:

**Pull request merged**
