### PR TITLE
[13.0][FIX] auditlog Readme images

### PR DESCRIPTION
**Pull request by emagdalenaC2i**

### CODE REVIEW

**Review by legalsylvain — CHANGES_REQUESTED** [review]
please replace by relative path. 

`` .. image:: ../static/description/rule.png``

thanks.

**Review by legalsylvain — APPROVED** [review]
thanks !

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Please squash commits together and put a meaningful commit message.

**Comment by emagdalenaC2i** [comment]
@pedrobaeza done

**Pull request merged**
