### PR TITLE
[12.0][MIG] Profiler from 11.0

### PR DESCRIPTION
**Pull request by thomaspaulb**
Migration of Profiler from 11.0 to 12.0 based on:

- https://github.com/OCA/server-tools/pull/1465
- https://github.com/OCA/server-tools/pull/1986
- https://github.com/OCA/server-tools/pull/2014

Replaces stale https://github.com/OCA/server-tools/pull/1369

### CODE REVIEW

**Comment by Rad0van** [comment]
Is this still alive?

**Comment by thomaspaulb** [comment]
@Rad0van I saw that this has an error, pushed a fix, hope it goes green now.

In general I'm having a hard time finding reviewers for the "profiler" PR's though, there's a couple on 11.0 as well.

**Comment by thomaspaulb** [comment]
@Rad0van It is green

**Review by StefanRijnhart — APPROVED** [review]

**Comment by thomaspaulb** [comment]
Since I've now adopted the module as maintainer..

/ocabot migration profiler

/ocabot merge nobump

**Pull request merged**
