### PR TITLE
10.0 mig external file location

### PR DESCRIPTION
**Pull request by cmsalmeida**
something went terrible wrong old #856

### CODE REVIEW

**Review by bealdav — APPROVED** [review]

**Comment by lasley** [comment]
Hi @cmsalmeida - why close?

**Comment by eugen-don** [comment]
@cmsalmeida 
I was trying to fork your fork/branch for this pr to test it on a local instance.
Can you reopen this PR

**Comment by eugen-don** [comment]
@cmsalmeida 
thaks for the effort.

Gues sftpfs is changed to maybe ftpfs?

Heres some error i get when i install it:
/opt/Software/10/custom/testing/external_file_location/tasks/sftp.py", line 14, in <module>
    class SftpTask(sftpfs.SFTPFS):

Error Log:
Software Server Error
Traceback (most recent call last):
  File "/opt/Software/10/srv/Software/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/Software/10/srv/Software/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/opt/Software/10/srv/Software/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/Software/10/srv/Software/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/Software/10/srv/Software/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/Software/10/srv/Software/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/opt/Software/10/srv/Software/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/opt/Software/10/srv/addons/web/controllers/main.py", line 889, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/Software/10/srv/addons/web/controllers/main.py", line 877, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/Software/10/srv/Software/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/opt/Software/10/srv/Software/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/Software/10/srv/Software/addons/base/module/module.py", line 410, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/opt/Software/10/srv/Software/addons/base/module/module.py", line 484, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/Software/10/srv/Software/modules/registry.py", line 82, in new
    Software.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/Software/10/srv/Software/modules/loading.py", line 339, in load_modules
    loaded_modules, update_module)
  File "/opt/Software/10/srv/Software/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/Software/10/srv/Software/modules/loading.py", line 122, in load_module_graph
    load_openerp_module(package.name)
  File "/opt/Software/10/srv/Software/modules/module.py", line 367, in load_openerp_module
    __import__('Software.addons.' + module_name)
  File "/opt/Software/10/local/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/opt/Software/10/srv/Software/modules/module.py", line 81, in load_module
    execfile(modfile, new_mod.__dict__)
  File "/opt/Software/10/custom/testing/external_file_location/__init__.py", line 3, in <module>
    from . import models
  File "/opt/Software/10/local/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/opt/Software/10/custom/testing/external_file_location/models/__init__.py", line 5, in <module>
    from . import location
  File "/opt/Software/10/local/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/opt/Software/10/custom/testing/external_file_location/models/location.py", line 6, in <module>
    from ..tasks.filestore import FileStoreTask
  File "/opt/Software/10/local/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/opt/Software/10/custom/testing/external_file_location/tasks/__init__.py", line 2, in <module>
    from . import sftp
  File "/opt/Software/10/local/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/opt/Software/10/custom/testing/external_file_location/tasks/sftp.py", line 14, in <module>
    class SftpTask(sftpfs.SFTPFS):
NameError: name 'sftpfs' is not defined

**Comment by florian-dacosta** [comment]
@eugen-don which version of python-fs are you using?
Like indicated in README file, you need "fs python module at version 0.5.4 or under"
It won't work if it is more than 0.5.4.

**Comment by eugen-don** [comment]
@florian-dacosta 

thanks, you were right, i had the wrong version of fs.

**Comment by lasley** [comment]
>It won't work if it is more than 0.5.4.

This seems like a pretty far out of date version to require in a new migration, which is supposed to upgrade all code.

**Comment by florian-dacosta** [comment]
@lasley 
Actually, there are kind of 2 fs lib.
pyfilesystem is up to version 0.5.4 and then pyfilesystem2 jumed to version 2.0.0.
This new pyfilesystem2 does not implement as much features as its predecessor for now, for example, sftp is not handled by this latest version. Maybe later it will...
The migration make the odoo module up to date, but not the lib it depends on. It would be better if it would, but it does not seem feasible for now (at least not without a huge amount of work)

**Comment by florian-dacosta** [comment]
@cmsalmeida Do you still plan to work on this PR?
There are some flake8 issues, can you fix it?
Also it could be nice to squash your commits a little bit

**Pull request closed without merging**
