### PR TITLE
fix travis (flake8)

### PR DESCRIPTION
**Pull request by gurneyalex**

### CODE REVIEW

**Comment by gurneyalex** [comment]
I had to use # noqa once because I could see no cleaner way to suppress the "import not at the top of the file" warning given the module structure.

**Comment by lepistone** [comment]
No need for `#noqa` @gurneyalex: you can just put that line at the top and leave everything as is.

**Comment by gurneyalex** [comment]
@lepistone are you sure this does not break anything? It will change the order of the elements in the list...

**Comment by gurneyalex** [comment]
travis is green -> can be merged IMO

**Comment by lepistone** [comment]
:+1: thanks

**Pull request merged**
