### PR TITLE
[FIX] smart button to open the list of analysis from a config

### PR DESCRIPTION
**Pull request by jcdrubay**
- Add missing code for smart button
- shorten the README for better readability

### CODE REVIEW

**Review by legalsylvain — APPROVED** [review]
Thanks ! 

code review, no test.

**Review by thomaspaulb — APPROVED** [review]

**Comment by StefanRijnhart** [comment]
Can you rebase and fix conflicts?

**Comment by cuongnmtm** [comment]
I created a new PR https://github.com/OCA/server-tools/pull/2822 to help @jcdrubay

**Comment by StefanRijnhart** [comment]
Closing in favour of https://github.com/OCA/server-tools/pull/2822

**Pull request closed without merging**
