### PR TITLE
[11.0] migrate external db sources

### PR DESCRIPTION
**Pull request by jlzhou**

### CODE REVIEW

**Comment by jlzhou** [comment]
Can someone here help to give suggestions on runbot and travis failed? I have no idea on this.

**Comment by elicoidal** [comment]
Actually Travis is failing for reasons external to this PR (Odoo/OCB).
Runbot status is red but seems accessible so you should be able to use it for functional tests.

**Comment by jlzhou** [comment]
I am still confused runbot error: ImportError: No module named sqlalchemy, I don't know how to add the dependencies in runbot setting, please help, thanks.

**Comment by max3903** [comment]
@jlzhou You need to add your library in the requirements.txt:
https://github.com/OCA/server-tools/blob/11.0/requirements.txt

**Comment by max3903** [comment]
@jlzhou I also suggest you follow this documentation to migrate modules:
https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0#howto
It will allow you to keep the history. 

You should also have one module per pull request. This will be easier to review your contributions and merge them.

Let me know if you know if you need further assistance.

Thank you.

**Comment by njeudy** [comment]
@jlzhou always on this migration ? will need this and can help to migrate.

**Comment by jlzhou** [comment]
go ahead, thanks

发自我的 iPhone

在 2018年6月3日，22:36，Nicolas JEUDY <notifications@github.com<mailto:notifications@github.com>> 写道：


@jlzhou<https://github.com/jlzhou> always on this migration ? will need this and can help to migrate.

**Comment by pedrobaeza** [comment]
Closing this by several reasons:

* This PR mixes a lot of modules
* It doesn't include commit history
* All CIs are red.

We are migrating them on OCA/server-backend for reference.

**Pull request closed without merging**
