### PR TITLE
11.0 mig fetchmail notify error to sender

### PR DESCRIPTION
**Pull request by nedaszilinskas**
continuation of https://github.com/OCA/server-tools/pull/1238 as discussed in https://github.com/OCA/server-tools/pull/1224

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Can you please check Travis status?
```
fetchmail_notify_error_to_sender/tests/test_fetchmail_notify_error_to_sender.py:18:80: E501 line too long (119 > 79 characters)
fetchmail_notify_error_to_sender/tests/test_fetchmail_notify_error_to_sender.py:22:80: E501 line too long (88 > 79 characters)
fetchmail_notify_error_to_sender/tests/test_fetchmail_notify_error_to_sender.py:23:80: E501 line too long (81 > 79 characters)
fetchmail_notify_error_to_sender/tests/test_fetchmail_notify_error_to_sender.py:24:80: E501 line too long (86 > 79 characters)
fetchmail_notify_error_to_sender/tests/test_fetchmail_notify_error_to_sender.py:38:80: E501 line too long (84 > 79 characters)
fetchmail_notify_error_to_sender/tests/test_fetchmail_notify_error_to_sender.py:57:80: E501 line too long (87 > 79 characters)
fetchmail_notify_error_to_sender/tests/test_fetchmail_notify_error_to_sender.py:66:80: E501 line too long (81 > 79 characters)
```

**Comment by nedaszilinskas** [comment]
@pedrobaeza looks like all is green. What are the next steps?

**Comment by pedrobaeza** [comment]
@nedaszilinskas I'm trying to push an squashed version of the PR for merging it, but I'm not able. Have you removed the option for allowing editors to do it?

seleccion_035

**Comment by nedaszilinskas** [comment]
@pedrobaeza no, its enabled. I did not changed it.

**Comment by pedrobaeza** [comment]
Then you should have any configuration at fork level that blocks me:

seleccion_037

**Comment by nedaszilinskas** [comment]
@pedrobaeza i did not changed any settings of the fork. I suspect that this may be related to the fact that this repo was forked from third party instead OCA. I added you as a collaborator to repo which should give you write access.

**Comment by pedrobaeza** [comment]
Yes, thanks, I have pushed the squashed history and if everything is green, then I merge, as @StefanRijnhart's comments were honored.

**Comment by pedrobaeza** [comment]
Merging. Thanks to all contributors and reviewers.

**Pull request merged**
