### PR TITLE
Add missing default oca icons

### PR DESCRIPTION
**Pull request by yvaucher**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1:

**Comment by alejandrosantana** [comment]
:+1:

**Comment by laetitia-gangloff** [comment]
:+1:

**Comment by hbrunn** [comment]
@yvaucher @pedrobaeza @alejandrosantana @laetitia-gangloff this commit causes `server_environment` to be loaded even if it's not installed, causing it to error out. Please fasttrack #230 to fix this soon

**Pull request merged**
