### PR TITLE
[MIG] base_user_role_company: Backport to 10.0

### PR DESCRIPTION
**Pull request by hbrunn**
This backports https://github.com/OCA/server-backend/tree/14.0/base_user_role_company to v10

### CODE REVIEW

**Comment by thomaspaulb** [comment]
@hbrunn If you rebase this, the runbot will probably turn green since [this commit](https://github.com/OCA/server-tools/commit/ddecc525b70f8848dc79713353b1cef034766ab1).

**Comment by hbrunn** [comment]
thanks @thomaspaulb, now it's just hoping for reviews

**Review by thomaspaulb — APPROVED** [review]
LGTM, code review. Tests run well also.

**Review by ntsirintanis — APPROVED** [review]

**Pull request merged**
