### PR TITLE
[14.0][IMP] base_changeset: optionally prevent self validation

### PR DESCRIPTION
**Pull request by Shamsidinkhon**

### CODE REVIEW

**Review by StefanRijnhart — APPROVED** [review]
Thanks!

**Comment by StefanRijnhart** [comment]
@hbrunn FYI, we have this as a customization on our own project I believe.

**Review by hbrunn — APPROVED** [review]
yes, but slightly differently, and I think what this PR implements is how it should be

**Comment by StefanRijnhart** [comment]
Thanks for fixing the iteration variable there!

**Pull request merged**
