### PR TITLE
mass_editing: Avoid errors if 'model_id' is not a list of ids.

### PR DESCRIPTION
**Pull request by hpestano**
When I try to make this query

```
@api.model
def get_default_fields(self):
    field_pool = self.env['ir.model.fields']
    fields = ['name', 'street', 'zip', 'city', 'email']
    ids = [field_pool.search([('model_id', '=', "'res.partner'"), ('name', '=', f)]).id for f in fields]
    return ids
```

I get this error

```
ValueError: invalid literal for int() with base 10: 'es.partne'
```

That is why i suggest this change

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Can you please explain your use case (steps to reproduce the error on the UI)?

You need also to send the CLA

**Comment by hpestano** [comment]
La Habana, 2016-01-07

I hereby agree to the terms of the Odoo Individual Contributor License
Agreement v1.0.

I declare that I am authorized and able to make this agreement and sign this
declaration.

Signed,

Henrik Pestano Pino hpestano@gmail.com https://github.com/hpestano

**Comment by hpestano** [comment]
The error is to make a search in the model 'ir.model.fields'
Using the domain `[('model_id', '=', 'res.partner'), ('name', 'in', ['name', 'street', 'zip'])]`

My goal is to get ids fields 'res.partner' but the addon mass_editing overwrites the search function in IrModelFields. When I run the query `ValueError "invalid literal for int () With base 10: 'es.partne'"`

**Comment by mvaled** [comment]
Hi @pedrobaeza,

I'm a coworker with @hpestano.  The point of this change is that without mass_editing installed a query like:

```
>>> imf.search([('model_id', '=', 'res.partner')])
    ir.model.fields(909, 929, 950, 954, 933, 914,..., 916)
```

works out of the box.  However, after installing mass_editing it fails cause it changes the `search` method of `ir.model.fields` and expects that strings are just comma-separate ids.

I'm working with @hpestano so that he signs the CLA and send it and also we're gonna rebase this change on top of 8.0.

Best regards,
Manuel.

**Comment by pedrobaeza** [comment]
@lasley, why did you merge it so fast? We haven't even checked the CLA.

**Comment by lasley** [comment]
Wait what? This is the first I've seen of this PR, I don't even see how I could have accidentally merged it. The merge itself only contains translations too, none of which was included in the commits in this PR, so I'm thoroughly confused 1861b63affca559af87a875be50249f0f76015ca

**Comment by lasley** [comment]
So uhhhh how do we fix this?

**Comment by pedrobaeza** [comment]
No, it seems that you haven't do anything. It has been auto-merged as they have make an strange GIT operation, resulting this PR in 0 commits. No worry then.

**Comment by lasley** [comment]
I wonder why it marked me as the merger though, that's weird. I guess this is why I sign my commits - maybe should start doing it on merges too in hindsight

**Comment by pedrobaeza** [comment]
I think it could happen because you have pushed a branch to GitHub that contains same commits, and detect this one as the same with commit history, and interpreted it as it was merged. But nothing to do with the signing of the commits.

**Comment by mvaled** [comment]
Hi @pedrobaeza, Indeed we reset our 8.0 branch to match that of OCA and created another branch with the patch (now PR #638).  This seems to have confused github somehow.  Sorry for the inconvenience.

**Comment by pedrobaeza** [comment]
The problem is that you used here the `8.0` branch instead of another different branch name. Try to avoid this next time.

**Comment by lasley** [comment]
@mvaled - FYI the commits you made on this fix are now gone, but still recoverable. I recommend you make a new branch, cherry pick 86dc30f & 6168a48, and submit a new PR (assuming you want to continue forward with the changes). You will also need to sign the CLA & send to cla@odoo-community.org

**Comment by mvaled** [comment]
@lasley I did that already.  Now is PR #638.  

I have personally signed the CLA, but since this change comes from my team, I've just sent the CLA for our organization https://github.com/merchise-autrement.

Best regards,
Manuel.

**Pull request merged**
