### PR TITLE
[15.0][UPD] module_auto_update: enable test that got disabled

### PR DESCRIPTION
**Pull request by thomaspaulb**
Same as https://github.com/OCA/server-tools/pull/2843

### CODE REVIEW

**Comment by thomaspaulb** [comment]
@sbidoul This runboat fail persists after retriggering, and I don't see any recent commits on 15.0 that would have broken this since a few days ago when I merged a 15.0 PR.

Arguably [pyopenssl](https://stackoverflow.com/questions/73830524/attributeerror-module-lib-has-no-attribute-x509-v-flag-cb-issuer-check) needs an update, but how could this have broken? And if it is, would this happen in other repos as well?

**Comment by sbidoul** [comment]
@thomaspaulb that's always this same story of compatibility of the latest `cryptography` with the old `pyopenssl` version that is installed by default.

The oca-ci image preinstall odoo's [requirements.txt](https://github.com/odoo/odoo/blob/15.0/requirements.txt).
This one has `cryptography==2.6.1` and `pyopenssl==19.0.0`, both pretty old.

Now, very likely, some external dependency of this repo require a more recent version of cryptography (for instance there is `acme` which requires `cryptography>=3.2.1`). So we see in the log that pip installs (correctly) cryptography 42. And that version is incompatible with pyopenssl 19.

The best solution I can think of now is to find the addon here that pulls `acme` and add, say, `pyopenssl>19` to its external dependencies, with a comment explaining it is to force pulling a more recent pyopenssl than the default one from Odoo for compatibility with cryptography that is an indirect dependency (yeah, it's complicated). This should force pip to find a correct solution.

**Comment by thomaspaulb** [comment]
Thanks, @sbidoul. I see in 14.0 they have solved by pinning cryptography to `<23.2.0`, and here in 15.0 someone else pinned `acme<2.0.0`, and I guess your trick would work as well. It seems to build now.

**Pull request merged**
