### PR TITLE
[16.0] rpc_helper: migrate to v16

### PR DESCRIPTION
**Pull request by simahawk**

### CODE REVIEW

**Review by ivantodorovich — APPROVED** [review]

**Comment by simahawk** [comment]
@sbidoul seems the bot is not working here. What can I check?

**Comment by sbidoul** [comment]
https://www.githubstatus.com/ :)

**Comment by simahawk** [comment]
> https://www.githubstatus.com/ :)

It didn't work several times in different days and time :man_shrugging: : 
Let's try again....

/ocabot migration nobump

**Comment by sbidoul** [comment]
@simahawk maybe you mean ocabot merge instead of ocabot migration? :coffee:

**Comment by simahawk** [comment]
> @simahawk maybe you mean ocabot merge instead of ocabot migration? coffee

hahahahahahaah can't believe that! :rofl: 

I'm gonna get another coffee :man_facepalming: 

Weird that the bot did not complain about a non existing command :thinking: 

/ocabot merge nobump

**Comment by sbidoul** [comment]
> Weird that the bot did not complain about a non existing command

The command exists, and worked - it just had nothing to do the second time. It could complain about the non-existing nobump argument but well... PR welcome I guess :)

**Comment by pedrobaeza** [comment]
The bot command has been correctly executed:

Selección_027

I suppose we can consider `nobump`, `major`, `minor` and `patch` as reserved words and we are not going to have any module with that names, and thus detect them to emit an error, but as @sbidoul says, that's an improvement to be done on the bot itself.

**Comment by simahawk** [comment]
Cool... I migrated the "bump" module too :rofl:

**Pull request merged**
