### PR TITLE
[11.0][ADD] base_binary_validation

### PR DESCRIPTION
**Pull request by simahawk**
TODO: add a note mentioning that `libmagic` should be installed to improve mimetype guessing.
Not really a requirement here but Odoo will use it if installed and in my experience you get much more reliable results.

### CODE REVIEW

**Review by guewen — APPROVED** [review]

**Comment by guewen** [comment]
Tests do not pass though, due to the test fake model.

**Comment by simahawk** [comment]
@guewen they pass but not w/ `EXCLUDE="database_cleanup"` :/

**Review by tschanzt — APPROVED** [review]
Looks good. Although tests fail.

**Review by grindtildeath — COMMENTED** [review]
For travis failing, IIRC you should adapt `.travis.yml` with : 
```
- TESTS="1" ODOO_REPO="OCA/OCB" EXCLUDE="database_cleanup,base_binary_validation"
- TESTS="1" ODOO_REPO="odoo/odoo" EXCLUDE="database_cleanup,base_binary_validation"
- TESTS="1" ODOO_REPO="OCA/OCB" INCLUDE="database_cleanup"
- TESTS="1" ODOO_REPO="odoo/odoo" INCLUDE="database_cleanup"
- TESTS="1" ODOO_REPO="OCA/OCB" INCLUDE="base_binary_validation"
- TESTS="1" ODOO_REPO="odoo/odoo" INCLUDE="base_binary_validation"
```
Otherwise code looks good to me.

**Comment by simahawk** [comment]
@grindtildeath updated, let's see :)

**Pull request closed without merging**
