### PR TITLE
[14.0][IMP] base_time_parameter: JSON data type

### PR DESCRIPTION
**Pull request by norlinhenrik**
Adding JSON data type

Adding tests for JSON and for get="data" & get="value"

### CODE REVIEW

**Comment by nimarosa** [comment]
Looks good to me. Let's fix checks.

**Comment by norlinhenrik** [comment]
The pre-commit errors are not related to this module.

**Comment by nimarosa** [comment]
@norlinhenrik 

I think they are related. 

`base_time_parameter/models/base_time_parameter_version.py:9:1: C901 '_validate' is too complex (18)`

I think it's because the function is too long. Maybe refactoring the function in smaller ones.

**Comment by norlinhenrik** [comment]
@nimarosa You were right. I have made smaller functions now.

**Review by nimarosa — APPROVED** [review]

**Pull request merged**
