### PR TITLE
[8.0] Add super_calendar_filters module

### PR DESCRIPTION
**Pull request by Ehtaga**
This module adds features to super_calendar:
- filters (current week/month and next week/month)
- groupby (day, week, month, quarter, year)

Depends on:
- [x] #139

### CODE REVIEW

**Comment by bwrsandman** [comment]
LGTM, but this seems like it should be by default in super_calendar

**Comment by eLBati** [comment]
I agree this should be added to super_calendar

**Comment by gurneyalex** [comment]
could you rebase your PR to benefit from the recent runbot fixes?

**Comment by Ehtaga** [comment]
Rebased.

**Comment by dreispt** [comment]
Good features, but this should definitely be added directly to `super_calendar`.
So :-1: for this particular PR

**Comment by Ehtaga** [comment]
Features directly added to super_calendar in this PR: https://github.com/OCA/server-tools/pull/222

**Pull request closed without merging**
