### PR TITLE
[12.0][FIX] auditlog: Add sudo() to retrieve record vals

### PR DESCRIPTION
**Pull request by TimLai125**
This PR fixes https://github.com/OCA/server-tools/issues/1984

### CODE REVIEW

**Review by atchuthan — APPROVED** [review]
:+1:

**Review by yostashiro — APPROVED** [review]
Functional review. Looks good. 👍

**Review by marcelsavegnago — APPROVED** [review]

**Comment by thomaspaulb** [comment]
@TimLai125 Can you forward port to other versions also?

**Review by thomaspaulb — APPROVED** [review]

**Comment by StefanRijnhart** [comment]
@TimLai125 thanks! A port to later versions would be appreciated indeed.

/ocabot merge patch

**Comment by TimLai125** [comment]
@StefanRijnhart OK, I will port this to other versions.

**Comment by pedrobaeza** [comment]
Values retrieved with sudo can vary from those returned with regular permissions.

**Comment by thomaspaulb** [comment]
@pedrobaeza Should [base_suspend_security](https://github.com/OCA/server-backend/pull/31) be used instead?

**Comment by pedrobaeza** [comment]
I'm not sure if that's enough. Think for example in a computed field that returns the number of records of something. Depending on the record rules, the computed value will vary according your "record visibility" from the record rules.

**Comment by StefanRijnhart** [comment]
@pedrobaeza you've got a point, but I don't see an easy solution for that. I think the impact on the validity of the data is limited, and having the bug is worse, so unless you've got a pointer to a way out, I think we can keep this change and port it to later versions.

**Comment by pedrobaeza** [comment]
Yes, we have come to the same conclusion on the 13.0 PR, and as this only happens on full log, it's not the usual logging option (or I think so).

**Comment by thomaspaulb** [comment]
The 'computed fields' example does not hold since non-stored computed fields are [now excluded from the auditlog](https://github.com/OCA/server-tools/pull/1975) for performance reasons (same PR was merged for 12 and 13 already)

**Comment by pedrobaeza** [comment]
Great then! I don't think that there are more possible differences then.

**Pull request merged**
