### PR TITLE
Corrected the icon.jpg location and made as per v8 standard

### PR DESCRIPTION
**Pull request by JayVora-SerpentCS**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Thanks :+1:

**Comment by dreispt** [comment]
Isn't there a policy for no partner branding on OCA modules?
To comply the icon should be removed.

**Comment by pedrobaeza** [comment]
Oh, I didn't see the icon was the Serpent logo. Daniel is right, you cannot put a brand image to the modules.

**Comment by yvaucher** [comment]
So this is a :-1:

**Comment by JayVora-SerpentCS** [comment]
Noted, Apologies. May be, we should put oca icon!

**Pull request closed without merging**
