### PR TITLE
port dbfilter from header to 8.0

### PR DESCRIPTION
**Pull request by sbidoul**
This branch does the following:
- merge 7.0 into master
- move all modules to **unported**
- adapt .travis.yml to 8.0
- port dbfilter_from_header to 8.0

### CODE REVIEW

**Comment by dreispt** [comment]
Remember to set `installed: False`in the unported modules.

**Comment by sbidoul** [comment]
I set installable = False in unported modules, and squashed history

**Comment by pedrobaeza** [comment]
:+1:

**Comment by rvalyi** [comment]
:+1:  LGTM

**Pull request merged**
