### PR TITLE
[FIX][9.0] auto_backup: Missing files

### PR DESCRIPTION
**Pull request by lasley**
This reverts commit 0111be2e599efb616170b4586bde80a73b12ba2c, which was committed directly to 9.0 & pulled the files from #620 that contained an identical commit 8a078fc4ec9df1993fcb4d498d0a4508eb7a5ecf.

This is the cleanest way that I see to resolve https://github.com/OCA/server-tools/issues/619#issuecomment-265404988. 

The alternative is another migration, which will add another 50 some odd commits.

Anyone have thoughts?

- [x] #614

### CODE REVIEW

**Review by antespi — APPROVED** [review]
LGTM :+1:

**Comment by lasley** [comment]
Dammit I just realized with this then we'll circle back around to the original #620. I guess re-migrating the module will be the best solution in hindsight. I'll just backport from my 10.0 #614 once merged.

**Comment by antespi** [comment]
Ok, thanks

**Comment by lasley** [comment]
I'm going to look at this in the next few days. I'm in conflict ~~heaven~~ hell in any sort of migration direction due to the translation files being on 9 branch. 

I guess I'm just going to start again, delete the migrations, then re-upgrade this module to 9. I really only needed it in 10 though, so bottom of my work stack TBH seeing as this is will be my third time migrating it to a version I don't need.

**Comment by lasley** [comment]
Ok I think I got this to the state it was on merge on 9. There's this dirty hack I had to do in 8c45b49 to delete the translations that are already there so that the commits could be walked back onto the branch. 

It seems there are some missing translation files in this PR though, but everything that I do ends up with them not there. I'm hoping maybe that will correct itself when Transifex tries to update the branch?

**Comment by antespi** [comment]
Thanks @lasley :+1:

**Comment by antespi** [comment]
Password for runbot: Admin:1234567890

**Comment by susport** [comment]
@antespi  With that password I can not authenticate in runbot

**Comment by lasley** [comment]
Username is `admin` Password is `Admin:1234567890`. Hah this repo is fun now that `password_security` is a thing

**Comment by antespi** [comment]
@lasley thanks for your clarification and sorry @susport for the confusion.
Now, OCA/server-tools runbots have this issue

**Comment by lasley** [comment]
I'm probably going to provide a fix for that soon. Something to disable the security on the admin user unless an option is explicitly enabled I'm thinking

**Comment by lasley** [comment]
I'm going to go ahead and merge this. It's pretty broken on 9.0 branch as it is & this was all approved a bunch of times, so I don't see the harm. Worse case scenario it's still broken, right? 😛

**Pull request merged**
