### PR TITLE
14.0: sql_request_abstract : add legalsylvain as maintainers

### PR DESCRIPTION
**Pull request by legalsylvain**
trivial PR. adding me as maintainers. (I'm the original co-author of the module)

CC : @florian-dacosta

### CODE REVIEW

**Review by florian-dacosta — APPROVED** [review]

**Review by sebastienbeau — APPROVED** [review]

**Comment by legalsylvain** [comment]
@sebastienbeau : this merge request failed due to ``letsencrypt`` error due to connexion error.
maybe relaunching the order could fix the problem...

https://app.travis-ci.com/github/OCA/server-tools/jobs/525671402#L2552

**Comment by sebastienbeau** [comment]
I have relaunched the job

**Comment by sebastienbeau** [comment]
note let'sencrypt module should use a mock to avoid such issue

**Comment by legalsylvain** [comment]
> note let'sencrypt module should use a mock to avoid such issue

@NL66278, what do you think about that point ?

**Comment by NL66278** [comment]
@legalsylvain I did not see that letsencrypt was the culprit here. In general I am in favour of mocking external servers. I realize that you then do not test the stability of those servers, but IMHO that is not the purpose of unit tests. Anyway letsencrypt does use mock, but I have not studied the code enough to check whether no testing with external services is done at all.

**Pull request merged**
