### PR TITLE
[ADD] migrate from product_images v7 if necessary

### PR DESCRIPTION
**Pull request by hbrunn**
see discussion in https://github.com/OCA/OpenUpgrade/pull/635

### CODE REVIEW

**Comment by hbrunn** [comment]
@pedrobaeza this is the PR I promised

**Comment by moylop260** [comment]
What about use migration script?

**Comment by hbrunn** [comment]
that's not going to work, because there's no older version of this module. During an upgrade, it will be pulled as a dependency when the v7 database had product_images installed, so technically, it's not an upgrade of this module. And we can't do it as migration script of product_multi_image because at the time this is run, base_multi_image is already installed

**Comment by moylop260** [comment]
What about the following case?
- I have `base_multi_image` (sha before of this change) installed.
- I pull sha of this pr
- I execute a `-u base_multi_image`

Is called the script `pre_init_hook`?

**Comment by hbrunn** [comment]
no, the init hook is only called for a fresh install (even not if you say -i base_multi_image when the module is already installed: https://github.com/OCA/OCB/blob/8.0/openerp/modules/loading.py#L145). So for this to break, you'd have to try really hard, like patching the module's state in the database to uninstalled or to install and then initialize it again

**Comment by pedrobaeza** [comment]
product_images module contains all the product images? Or the main image is treated separately?

**Comment by StefanRijnhart** [comment]
@pedrobaeza main image is a reference to the first image https://github.com/OCA/product-attribute/blob/7.0/product_images/product.py#L62 (it is the same in product_multi_image)

**Review by StefanRijnhart — APPROVED** [review]

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
