### PR TITLE
[13.0][MIG]base_exception

### PR DESCRIPTION
**Pull request by ntodorova**
[13.0][MIG]base_exception

### CODE REVIEW

**Comment by rousseldenis** [comment]
@ntodorova Are you aware of this one : #1760 ?

**Comment by ntodorova** [comment]
Oh, no, I have checked in the https://github.com/OCA/server-tools/issues/1679 and there is nothing. May be someone can update it. Thank you @rousseldenis

**Comment by rousseldenis** [comment]
> Oh, no, I have checked in the #1679 and there is nothing. May be someone can update it. Thank you @rousseldenis

Hi, no problem. Indeed, someone has to pass there to update it. To be sure, make a little search on open PR's. Maybe, could you review it in order to merge it as it's nearly green?

**Comment by ntodorova** [comment]
Yes, I think that I can manage a review soon.

**Comment by ntodorova** [comment]
Duplicate of #1760

**Pull request closed without merging**
