### PR TITLE
[MIG][11.0] fetchmail_notify_error_to_sender

### PR DESCRIPTION
**Pull request by nedaszilinskas**

### CODE REVIEW

**Comment by nedaszilinskas** [comment]
@pedrobaeza would you be so kind giving me a hint on how to solve the issues above (Missing base report)?

**Comment by pedrobaeza** [comment]
Which issue?

**Comment by nedaszilinskas** [comment]
The checks - codecov/patch and codecov/project say "Missing base report.". From docs I read:
_Best Practice: Always fork a branch from a successful CI commit that has coverage uploaded, as illustrated below._
Not sure I understand what its about since the previous commit on my fork was passing.

**Comment by pedrobaeza** [comment]
I don't see such message, but the red crosses is due to the lack of tests on the modules that lower the test coverage. It can be acceptable in some cases where the function is not considered critical.

**Comment by nedaszilinskas** [comment]
I do not see that there were tests for this module on any of the previous versions so I take its the case when it can be accepted?

**Comment by pedrobaeza** [comment]
Yeah, that's a pending topic in several modules. It's a question of quality, for avoiding problems, but if you don't feel qualified for making them, I think reviewers can accept the migration itself without them.

**Comment by nedaszilinskas** [comment]
At the moment I just do not have time to make improvements, I just want to contribute a migration.

**Comment by pedrobaeza** [comment]
OK, as you prefer.

**Comment by pedrobaeza** [comment]
This PR doesn't preserve commit history. Closing in favor of #1238, that already includes it.

**Comment by nedaszilinskas** [comment]
@pedrobaeza my interest is to have this module on v11 as soon as possible. What we can do to help contributing here and fast-forwarding it?

**Comment by pedrobaeza** [comment]
But the migration is not correct. Review the other PR.

**Comment by nedaszilinskas** [comment]
@pedrobaeza what would be the process of contributing to that other PR (https://github.com/OCA/server-tools/pull/1238)?
From my understanding - I would need to fork "haidd:11.0-mig-fetchmail_notify_error_to_sender", make changes and create PR first to "haidd:11.0-mig-fetchmail_notify_error_to_sender"? That looks like too much of the process.

**Comment by pedrobaeza** [comment]
@nedaszilinskas there are 2 possibilities:

* The one you mention, which is a bit more work, but it's a courtesy to the author of the other PR if he/she is still active, but is not able to perform the changes.
* If the author didn't answer in a time, which is the case, then you fork from the PR branch, but start a new PR you control, and then we superseed the PR. This is also not discourteous at all, as we are keeping his/her initial migration commit.

The second one is the suitable IMO for this case.

**Pull request closed without merging**
