### PR TITLE
[15.0][MIG] mig base_search_fuzzy

### PR DESCRIPTION
**Pull request by Shide**
Hello,
ready for review

- [x] Bump version to bump version to 15.0.1.0.0
- [x] Fixed context on test
- [x] Removed strings on <form> and <tree> views
- [x] Removed string on fields that have the same string text than field

@pedrobaeza, @StefanRijnhart

MT-358 @moduon

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]
Please add a note saying that on v16, it's not needed as Odoo has added these indexes in the core: https://github.com/odoo/odoo/pull/83015

**Review by yajo — APPROVED** [review]

**Comment by Shide** [comment]
> Please add a note saying that on v16, it's not needed as Odoo has added these indexes in the core: [odoo/odoo#83015](https://github.com/odoo/odoo/pull/83015)

Done in ROADMAP.rst

**Pull request merged**
