### PR TITLE
[7.0] Add fetchmail_bydate

### PR DESCRIPTION
**Pull request by eLBati**
This module allows to fetch new emails (using IMAP) using their date,
in addition to 'unseen' status.

To enable this, you have to set a 'Last Download Date' in the fetchmail.server
After that, emails with an internal date greater than the saved one will be
downloaded

### CODE REVIEW

**Comment by archetipo** [comment]
:+1:

**Comment by hurrinico** [comment]
:+1:

**Comment by eLBati** [comment]
Can this be merged?
Does anybody know why runbot is red?

**Comment by pedrobaeza** [comment]
It's only some warnings, but no errors. If you want to clean them, please check the log.

I merge.

**Pull request merged**
