### PR TITLE
[12.0][MIG] base_exception

### PR DESCRIPTION
**Pull request by ivantodorovich**
This superseeds https://github.com/OCA/server-tools/pull/1395, because that one needs fixing and it seems unactive.

In addition to the migration, I've updated the views to use the ace widget for Python Code, and made it match the style of Odoo Scheduled Actions views.

image

image

### CODE REVIEW

**Comment by ivantodorovich** [comment]
Also I'm thinking we should move the configuration menu under some of the existing submenues, maybe under the 'Automation' menu.

What do you think?

image

**Comment by ivantodorovich** [comment]
Just added `_description` to the models to fix runbot error:
```
WARNING openerp_test odoo.models: The model exception.rule.confirm has no _description
WARNING openerp_test odoo.models: The model base.exception has no _description
```

**Comment by bealdav** [comment]
Hi @ivantodorovich good news here.

Note there are updates in v10 in this module that needs to be added here. I'll list them here.

https://github.com/OCA/server-tools/commit/7db7db8301055b411abe9ffdb4201cac5a22313d
https://github.com/OCA/server-tools/commit/34ae095f2c898acace0a6cdcc95ce8e4dca8fa69
https://github.com/OCA/server-tools/commit/386c5e1055a42d6e5cd7f688207fb34ac332a814
https://github.com/OCA/server-tools/commit/c640d3e6af9fbed791358d80a23fc08b5230ad7f
https://github.com/OCA/server-tools/commit/252ee4362080241a24682057cf5f6d80d0d25279

Please cherry pick them.

Probably applying them according to date

Thanks a lot

**Comment by ivantodorovich** [comment]
@bealdav done 👌

**Review by rvalyi — APPROVED** [review]
Thank you all for the hard work, I approve the merge.

BTW, I recently discovered a Python module from the standard library you may not be aware of and could play a role along with this module. The Warnings module. It allows to catch errors without blocking the flow like exceptions. Unlike this module it also don't persist the errors for later retrieval. But it may still be useful in Odoo in some situations like form validations https://docs.python.org/3/library/warnings.html

**Review by bealdav — APPROVED** [review]

**Review by sebalix — APPROVED** [review]

**Review by florian-dacosta — APPROVED** [review]

**Pull request merged**
