### PR TITLE
[MIG][10.0] base_external_dbsource

### PR DESCRIPTION
**Pull request by jlzhou**
Adapted to 10.0
#565

### CODE REVIEW

**Comment by jlzhou** [comment]
#565

**Comment by pedrobaeza** [comment]
Annotated in the issue

**Comment by jlzhou** [comment]
@pedrobaeza Can you describe in detail? I'm new here.

**Comment by jlzhou** [comment]
Can anyone help to indicate what's wrong here?

Some checks were not successful
1 failing and 1 successful checks

**Comment by pedrobaeza** [comment]
There are lint errors:

https://travis-ci.org/OCA/server-tools/jobs/168909969

**Comment by jlzhou** [comment]
@pedrobaeza Please advise where to see the detailed failure information, thanks!
By clicking ci/runbot's details link on the right below, I could get nothing.

**Comment by pedrobaeza** [comment]
Pressing the gear button and clicking on "Full all logs", you can see the error: https://runbot2.odoo-community.org/runbot/static/build/3271468-578-10ad16/logs/job_20_test_all.txt

But it's not your fault. It's something with Odoo. See https://github.com/odoo/odoo/issues/14057

**Comment by jlzhou** [comment]
What should I do next? The process of PR is too slow.
@pedrobaeza

**Comment by pedrobaeza** [comment]
If people are not interested in this module, they're not going to review it. You can review other PRs of the same topic/repository and ask for a review here in exchange. You can also enroll other colleagues to review your work.

**Comment by lnkdel** [comment]
I think this PR is good. My PR #596 depends on it.

**Comment by mstuttgart** [comment]
LGTM :+1:

**Comment by aldo774** [comment]
LGTM :+1:

**Comment by max3903** [comment]
:+1:

**Pull request merged**
