### PR TITLE
[15.0][MIG] base_time_parameter (base_time_dependent_parameter)

### PR DESCRIPTION
**Pull request by norlinhenrik**

### CODE REVIEW

**Comment by thomaspaulb** [comment]
@norlinhenrik Please rebase on the latest 15.0 to fix the tests

Also, you have an issue in pre-commit, and did you sign the CLA?

**Comment by norlinhenrik** [comment]
I have signed the CLA. Do I need to do anything more for OCA to know that @norlinhenrik has signed?

I will update this PR after #2427 is merged.

**Comment by thomaspaulb** [comment]
@norlinhenrik Maybe send a mail to cla@odoo-community.org to see why you're not correctly registered, i've seen more of these false negatives

**Comment by nimarosa** [comment]
I think the CLA bot it's not working great. I've seen this issue in many other repos.

**Comment by rjg-odoonz** [comment]
@norlinhenrik hopefully this has been sorted now, I've added all your github accounts into the instance and tagged our ICLA                                       
@nimarosa it doesn't look like we have a signed CLA for you though....

**Comment by nimarosa** [comment]
@rjg-odoonz Hi! I sent it to the CLA email the day I become PSC for hr repos. But I didn't received any response or know how to check if it's already linked with my account. 

Should I send it again?

Edit: just sent it again to the CLA email. Hope it gets linked this time.

**Comment by rjg-odoonz** [comment]
It's weird as your github name is there  but not the cla.
Yes, send it again to be safe and I will action it for you.

**Comment by nimarosa** [comment]
@rjg-odoonz i sent it again yesterday, you can search for it with my instance email. Thanks for the help

**Comment by rjg-odoonz** [comment]
Hi @nimarosa I've just actioned it.
Let me know how you get on.

Cheers,
Rebecca

**Comment by nimarosa** [comment]
@norlinhenrik can you rebase with new 14.0 branch changes and check tests to the module so we can move forward with the migration too? I will also want to migrate it to 16.0 when we are ready with this PR.

**Comment by nimarosa** [comment]
> Hi @nimarosa I've just actioned it.
> 
> Let me know how you get on.
> 
> 
> 
> Cheers,
> 
> Rebecca

Yes I received the email a few days ago. Thanks for the help!

**Comment by nimarosa** [comment]
@norlinhenrik Will you finish this PR and also the 16.0 migration? So we can proceed with payroll migrations.

**Comment by norlinhenrik** [comment]
@nimarosa Would you like to make PR for 15.0 and 16.0? I am too overloaded...

**Comment by nimarosa** [comment]
@norlinhenrik yes no problem, I will make it next week.

**Pull request closed without merging**
