### PR TITLE
[15.0][FW] auditlog: multiple ports from 14.0

### PR DESCRIPTION
**Pull request by sebalix**
Port of the following PRs from 14.0 to 15.0:
- #2471 (blacklisted as it's not relevant for 15.0)
- #2485

### CODE REVIEW

**Comment by sebalix** [comment]
Tests failing on `letsencrypt` and `auto_backup` (failing too on other PR builds), so not related to these changes.

**Comment by sebalix** [comment]
@etobella @kittiu your PR is not relevant anymore on 15.0 right? I'm not sure.

**Review by SilvioC2C — APPROVED** [review]
LGTM

**Review by StefanRijnhart — APPROVED** [review]

**Pull request merged**
