### PR TITLE
[13.0][FIX] Add sudo() to retrieve record vals

### PR DESCRIPTION
**Pull request by TimLai125**
Forward Port to 13.0 of https://github.com/OCA/server-tools/pull/1985

### CODE REVIEW

**Review by len-foss — APPROVED** [review]

**Review by marcelsavegnago — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Values retrieved with sudo can vary from those returned with regular permissions.

**Comment by len-foss** [comment]
@pedrobaeza If it was deemed necessary in 12.0 it certainly is in 13.0 (the FP was explicitly asked for)? 
Furthermore IIRC the sudo refactoring was in 12.3, so the impact should be less important than in 12.0
In the worst case, that would pollute the audit.log, which is a bad thing, but the issue would be uncovered after a debugging session. Whereas without the fix you risk to make standard flows explode because of the logging.

**Comment by pedrobaeza** [comment]
See my comment for https://github.com/OCA/server-tools/pull/1985#issuecomment-762331958

I don't know if it can affect and I'm not a user of this module, but I'm just throwing out the comment for you to know about it and take it into account if applicable.

**Comment by len-foss** [comment]
@pedrobaeza I see, thank you. You make a point, but since the risk/reward is asymmetrical if think it's good enough as long as nobody has time to devote to find and fix these tricky corner case(s). However it would warrant adding a todo comment to mention it.

**Comment by pedrobaeza** [comment]
If the problem is with the full log, then that sudo shouldn't be put only on that mode?

**Comment by len-foss** [comment]
It's in the create_full method...

**Comment by pedrobaeza** [comment]
Ah, OK, sorry for the noise then.

**Comment by StefanRijnhart** [comment]
~~True, a note in the USAGE would be nice.~~ Computed fields are not reflected in the auditlogs as per https://github.com/OCA/server-tools/pull/1985#issuecomment-762420934

**Review by thomaspaulb — APPROVED** [review]

**Review by StefanRijnhart — APPROVED** [review]

**Pull request merged**
