### PR TITLE
[DEL] pyc file

### PR DESCRIPTION
**Pull request by thomaspaulb**
Saw a stray .pyc file, deleting it

### CODE REVIEW

**Comment by sbidoul** [comment]
IIRC the presence of that file is important for testing the hashing algorithm.

**Comment by thomaspaulb** [comment]
Isn't it excluded?

https://github.com/OCA/server-tools/blob/10.0/module_auto_update/tests/test_addon_hash.py#L65

**Comment by sbidoul** [comment]
As you can see tests fail because the file must be present.

**Comment by thomaspaulb** [comment]
Thanks, closing then.

**Pull request closed without merging**
