### PR TITLE
[10.0][FIX]base_jsonify: Preserve initial order on ir.export.line

### PR DESCRIPTION
**Pull request by lmignon**
We can't change the order on ir.export.line since it's used to preserve the order speicifed by the user when creating a export filter into the UI

### CODE REVIEW

**Review by foutoucour — APPROVED** [review]

**Review by sebastienbeau — APPROVED** [review]
Ok for me

**Review by simahawk — APPROVED** [review]
I wonder how important is this order anyway. By default is ordered by ID which means that to control it you have to delete/create items. Am I wrong?

**Comment by lmignon** [comment]
Tests for `base_custom_info` are failing...... :cry: (Not related to my changes even the 10.0 branch is red :tired_face: )

**Comment by lmignon** [comment]
Tecnativa https://github.com/OCA/server-tools/pull/1661/commits/f499379c02ce24be64aa8538540c48ec0a153c91 fixes a bug into base_custom_info due to a change into the ORM

**Comment by lmignon** [comment]
> I wonder how important is this order anyway. By default is ordered by ID which means that to control it you have to delete/create items. Am I wrong?

You are right. But when the user create a custom export for a model, he can specify the order of the column into the exported document by ordering the selected fields with the arrows up and down. This order is preserved since the ir.export.line are created into the same order than the list of selected fields. That's why we can't change the order of ir.export.line otherwise the functionality is lost and the exported documents no more respect the expected order for columns.

**Comment by pedrobaeza** [comment]
> Tecnativa f499379 fixes a bug into base_custom_info due to a change into the ORM

Thanks for that.

**Pull request merged**
