### PR TITLE
[15.0] [MIG] base_changeset

### PR DESCRIPTION
**Pull request by JasminSForgeFlow**
Standard Migration

@ForgeFlow

### CODE REVIEW

**Comment by StefanRijnhart** [comment]
Please include recent 14.0 merges
* https://github.com/OCA/server-tools/pull/2252
* https://github.com/OCA/server-tools/pull/2245
* https://github.com/OCA/server-tools/pull/2244
 
I would also like to ask you to check if you can include this trivial PR of today: https://github.com/OCA/server-tools/pull/2411

But most of all I would like to ask you to adopt these security improvements that @hbrunn originally implemented in the 12.0 backport of the module: https://github.com/OCA/server-tools/pull/2246/

**Comment by MiquelRForgeFlow** [comment]
@StefanRijnhart done!

**Review by StefanRijnhart — APPROVED** [review]
Fantastic, thank you!

**Review by houssine78 — APPROVED** [review]

**Comment by houssine78** [comment]
@StefanRijnhart I think the module can be merged now :)
thanks !

**Comment by StefanRijnhart** [comment]
@houssine78 alright, thanks!

/ocabot merge nobump

**Pull request merged**
