### PR TITLE
auth_session_timeout hasn't been working in 10.0 for about 1 year

### PR DESCRIPTION
**Pull request by yelizariev**
See https://github.com/OCA/server-tools/issues/1237

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Haven't you got any solution instead of disabling it?

**Comment by yelizariev** [comment]
We just need to apply this: https://github.com/OCA/server-auth/commit/f19bd6ef199e284cbbfd002ba0b40ef3bd67b598
But I don't plan to do it in coming months. Disabling module would clearly mark module as not working and there is chance that someone else do it before me

**Comment by pedrobaeza** [comment]
Then at least add that text to the README or in any place for being identifiable what to do.

**Comment by yelizariev** [comment]
I've added a note to Roadmap section

**Comment by pedrobaeza** [comment]
I'm thinking about those that have the module installed. Isn't better to only not working than having an error reporting missing module?

**Comment by yelizariev** [comment]
I don't really feel a difference. Both are errors

> Isn't better to only not working than having an error reporting missing module?

Existing users who use the old version of odoo will get a problem if they update to latest version of the module at any case (whether we fix module or mark as non-installable).

What is more important for me here is whether we allow non-working module in OCA repo or not.

**Comment by pedrobaeza** [comment]
Why they will have an error? I think they will only have a non time-out system, isn't it?

**Comment by yelizariev** [comment]
Correct. Non time-out is a bug, not an error. User will not get any error messsages. 
With an alternative option, user will get "module is not installable" warning. I'm not sure whether the update will break such odoo database or not.
Ok, I think we can just update README then

**Comment by pedrobaeza** [comment]
Yeah, I prefer that option, as the other one have chances of breaking things.

**Comment by yelizariev** [comment]
I've updated PR

**Review by pedrobaeza — APPROVED** [review]
Thanks. Travis error is unrelated. Fast-tracking this

**Pull request merged**
