### PR TITLE
web_context_tunnel v8 port: asset bundle + tests

### PR DESCRIPTION
**Pull request by rvalyi**
ported web_context_tunnel to v8:
wrapped into asset bundle and updated qunit tests to get it green
(well there are some qunit tests errors in the core but it's absolutely unrelated to my module; you could see these fail on runbot here http://17194-8-0-d9e72a.runbot6.odoo.com/web/tests )

### CODE REVIEW

**Comment by rvalyi** [comment]
note, the Travis error is a Pylink error with server_environment/serv_config.py:57 that is it' is unrelated to my web_context_tunnel port here, so I appreciate if people ca still review here for merge.

**Comment by bguillot** [comment]
It seems that the travis error is not linked to the PR so that looks good. 

:+1:

**Comment by pedrobaeza** [comment]
Example put in the manifest doesn't work:

https://github.com/openerpbrasil/l10n_br_core/compare/develop...feature%2Fsale-web-context-tunnel

**Comment by rvalyi** [comment]
Hum you are right Pedro, it's because we merged the branch meanwhile so there is no diff anymore in the compare view. I'm updating with the specific commit instead.

**Comment by pedrobaeza** [comment]
Thanks, @rvalyi. Now it's clear the sample usage.

For this PR, :+1: 

Can you please change also the example in v7 module manifest?

**Comment by rvalyi** [comment]
Here you go for v7 @pedrobaeza https://github.com/OCA/server-tools/pull/67
good to merge?

**Comment by lepistone** [comment]
:+1: Thanks!

**Pull request merged**
