### PR TITLE
[ADD] Added auditlog_easy_config module.

### PR DESCRIPTION
**Pull request by alejandrosantana**
Module _auditlog_easy_config_ aims to make easier and faster the management od _auditlog_ module.
It enables to create and subscribe at once a rule for each model in the database, at any time.
Also allows to select some rules and subscribe, unsubscribe and change tracked actions.

### CODE REVIEW

**Comment by alejandrosantana** [comment]
We will be dealing with @forvas CLA during this week.

**Comment by pedrobaeza** [comment]
Why not integrating this options in the same module?

**Comment by alejandrosantana** [comment]
Did not think on it! We created it as an extension for a customer and then we thought it could be useful. But yes, it can be integrated into original _auditlog_. We will do it this week, then.

**Comment by alejandrosantana** [comment]
Close this PR. We will integrate new functionality into _auditlog_ module, as suggested.

**Pull request closed without merging**
