### PR TITLE
[9.0] auth_keycloak : Backported from 10.0

### PR DESCRIPTION
**Pull request by grindtildeath**
Based on :
 - [ ] https://github.com/OCA/server-auth/pull/48

### CODE REVIEW

**Comment by grindtildeath** [comment]
@simahawk Please have a look

**Comment by simahawk** [comment]
@grindtildeath sorry, goes here https://github.com/OCA/server-auth ;)

**Comment by grindtildeath** [comment]
@simahawk There are no modules in 9.0 branch of server-auth. All the auth modules are here until 10.0, so wouldn't make sense to have this one alone over there.

**Comment by simahawk** [comment]
@grindtildeath nope, is the same for v10. We agreed on this. https://github.com/OCA/server-tools/issues/1398

**Comment by grindtildeath** [comment]
Moved to https://github.com/OCA/server-auth/pull/49

**Pull request closed without merging**
