### PR TITLE
Revert "Merge pull request #1542 from sunflowerit/8.0-logging_json-do…

### PR DESCRIPTION
**Pull request by sergiocorato**
…nt-bork-on-missing-package"

This reverts commit 4e22ed02f6ba36e070df043138bab3f934f99981, reversing
changes made to eacac19f0fe31d6b3d5755aa2724136b3b2f6de5.
#1546

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Sorry, but this has nothing to do with the issue you mention, and the fix is correct.

**Comment by sergiocorato** [comment]
> Sorry, but this has nothing to do with the issue you mention, and the fix is correct.

I don't find a relation too, but removing the fix, the bug disappear...

**Comment by pedrobaeza** [comment]
Then the problem is in the other module that is not handling correctly the situation. Probably the previous error makes this one to not appear, but the correct fix is to solve the problem in `server_environment` module.

**Comment by sergiocorato** [comment]
:+1: but i don't use that module

**Comment by pedrobaeza** [comment]
You haven't put what is the error in the issue, so it's difficult then to deduce the problem.

**Comment by sergiocorato** [comment]
> You haven't put what is the error in the issue, so it's difficult then to deduce the problem.

sorry, I wrote it in the title, I put more info now

**Pull request closed without merging**
