### PR TITLE
11.0 mig base user role

### PR DESCRIPTION
**Pull request by novawish**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Maybe this is better suited now in server-backend instead of here. @lasley @sebalix  what do you think?

**Comment by sebalix** [comment]
No problem with that. I suppose `auditlog` like others "user application" should be migrated there too.

**Review by jcdrubay — APPROVED** [review]

**Comment by novawish** [comment]
As @pedrobaeza mentioned, i created a new PR of this module to `server-backend` repository: https://github.com/OCA/server-backend/pull/1

Therefore, I will close this PR since it was replaced by the new PR

**Comment by pedrobaeza** [comment]
Thanks.

**Pull request closed without merging**
