### PR TITLE
[ADD] inhibit warnings from acl tests

### PR DESCRIPTION
**Pull request by hbrunn**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Isn't better to inhibit the functionality when tests are enabled and you're testing other modules?

**Comment by hbrunn** [comment]
yes, but we have no influence on that: https://github.com/OCA/OCB/blob/8.0/openerp/addons/base/ir/ir_model.py#L767

**Comment by pedrobaeza** [comment]
OK, I see. Then :+1:

**Comment by moylop260** [comment]
👍

**Comment by gurneyalex** [comment]
@hbrunn @pedrobaeza this merge broke the 8.0 build.

**Comment by pedrobaeza** [comment]
It was green in its moment, so I don't know what is happening. Do you have any clue?

**Comment by gurneyalex** [comment]
oh I think I pinged the wrong PR. Sorry.

**Comment by gurneyalex** [comment]
I don't know, I just noticed the travis builds turned red on the build of the merge. Can be unrelated to this PR and related to #505 (database_cleanup breaking the build on 9.0), since the errors seem to be related to that module.

**Comment by gurneyalex** [comment]
see also #507

**Pull request merged**
