### PR TITLE
[12.0][FIX] excel_import_export

### PR DESCRIPTION
**Pull request by kittiu**
Fix Import Excel wizard, cannot download template as in v12 core Odoo prevent download default binary.

### CODE REVIEW

**Comment by youring** [comment]
Functional test OK! Thanks.

**Comment by kittiu** [comment]
This is ready to be merged. Thanks!

**Comment by kittiu** [comment]
Greenified, ready to merge.

**Review by gurneyalex — APPROVED** [review]

**Review by ivantodorovich — APPROVED** [review]
LGTM :+1: Thanks!

**Pull request closed without merging**
