### PR TITLE
[17.0][MIG]  base_view_inheritance_extension

### PR DESCRIPTION
**Pull request by alexis-via**
No code change.
This module is above my technical skills, so review carefully and make sure we didn't need to change anything.

### CODE REVIEW

**Comment by alexis-via** [comment]
Can a maintainer have a look at it ? We have PRs that depend on this PR.

**Review by StefanRijnhart — APPROVED** [review]
Also above my technical skill level, but I checked the upstream ir.ui.view API that this module overrides and it does not have changed between 16 and 17.

**Review by thomaspaulb — APPROVED** [review]

**Pull request merged**
