### PR TITLE
[14.0][MIG] sentry

### PR DESCRIPTION
**Pull request by dnplkndll**
basic migrate 
to test with a sentry install from helm using cert-manager I had to add
`?verify_ssl=0` 
to the dsn due to missing ssi support

### CODE REVIEW

**Comment by hparfr** [comment]
Thanks  dnplkndll.

Please review this PR https://github.com/OCA/server-tools/pull/1942 about the new Sentry SDK.

**Comment by dnplkndll** [comment]
> Thanks dnplkndll.
> 
> Please review this PR #1942 about the new Sentry SDK.

#1942 added
tested on sentry_sdk==0.19.5

looking at [RedisIntegration()] for use with [session_redis](https://github.com/camptocamp/odoo-cloud-platform/tree/14.0/session_redis)

```
sentry_sdk.init(
    dsn='https://examplePublicKey@o0.ingest.sentry.io/0',
    integrations=[RedisIntegration()]
)
```

**Comment by max3903** [comment]
Closing. sentry migrated and merged in #1997

**Comment by moylop260** [comment]
@dnplkndll 

We are working to use sentry-sdk here before this one:
 - https://github.com/OCA/server-tools/pull/1942

Could you review it, please?

**Comment by max3903** [comment]
@moylop260 We will test.

**Comment by dnplkndll** [comment]
#1942 was the inspiration on this PR

**Comment by moylop260** [comment]
What about testing and approve the other on in other to merge it so we can propagate it for all branches

**Comment by fernandahf** [comment]
@dnplkndll 

Good for this migration!

Have you ever tested this migration in a production server?

**Comment by dnplkndll** [comment]
> @dnplkndll
> 
> Good for this migration!
> 
> Have you ever tested this migration in a production server?

Yes it is in our repos.yaml. We use with a gitlab auto-devops and then pass the release in the .gilab-ci file each week and the env are secrets set on the environments. So we end up with a nice system tracking the errors by release and environment. I would like to drop the DeprecationWarning: `sentry_transport` But the sentry server is just a chart in the cluster as well, easy setup and works great.

**Comment by hoangtrann** [comment]
@moylop260 @max3903 shall we propagate the PR from `12.0`?

**Comment by hparfr** [comment]
@dnplkndll  @atchuthan the commit history looks wrong. Is this PR based on v12 ?

**Comment by dnplkndll** [comment]
https://github.com/OCA/server-tools/pull/2223

updated to a sdk update from a mig

**Pull request closed without merging**
