### PR TITLE
[14.0][FIX] base_changeset: fix write return type

### PR DESCRIPTION
**Pull request by StefanRijnhart**
Port of https://github.com/OCA/server-tools/pull/2237

### CODE REVIEW

**Review by legalsylvain — APPROVED** [review]

**Review by thomaspaulb — APPROVED** [review]

**Comment by StefanRijnhart** [comment]
Huh. Looks like it might be a temporary failure?
```
 2022-09-01 06:07:27,982 272 ERROR odoo odoo.addons.letsencrypt.tests.test_letsencrypt: ERROR: TestLetsencrypt.test_dns_challenge
Traceback (most recent call last):
  File "/opt/odoo-venv/lib/python3.6/site-packages/mock/mock.py", line 1346, in patched
    return func(*newargs, **newkeywargs)
  File "/__w/server-tools/server-tools/letsencrypt/tests/test_letsencrypt.py", line 119, in test_dns_challenge
    self.env["letsencrypt"]._cron()
  File "/__w/server-tools/server-tools/letsencrypt/models/letsencrypt.py", line 89, in _cron
    self._register_client(client, account_key)
  File "/__w/server-tools/server-tools/letsencrypt/models/letsencrypt.py", line 248, in _register_client
    client.new_account(new_reg)
  File "/opt/odoo-venv/lib/python3.6/site-packages/acme/client.py", line 632, in new_account
    response = self._post(self.directory['newAccount'], new_account)
  File "/opt/odoo-venv/lib/python3.6/site-packages/acme/client.py", line 103, in _post
    return self.net.post(*args, **kwargs)
  File "/opt/odoo-venv/lib/python3.6/site-packages/acme/client.py", line 1272, in post
    return self._post_once(*args, **kwargs)
  File "/opt/odoo-venv/lib/python3.6/site-packages/acme/client.py", line 1286, in _post_once
    response = self._check_response(response, content_type=content_type)
  File "/opt/odoo-venv/lib/python3.6/site-packages/acme/client.py", line 1131, in _check_response
    raise messages.Error.from_json(jobj)
acme.messages.Error: urn:ietf:params:acme:error:serverInternal :: The server experienced an internal error :: failed check for existing account
```

**Comment by thomaspaulb** [comment]
It was, apparently.

**Pull request merged**
