### PR TITLE
[IMP] base_time_dependent_parameter -> base_time_parameter

### PR DESCRIPTION
**Pull request by ghost**
Main changes:
* Module renamed to `base_time_parameter`
* Models renamed to `base.time.parameter` & `base.time.parameter.value`
* Field `parameter_version_ids `renamed to `value_ids`
* The parameter value may be a TEXT or a REFERENCE. I need to reference account.account. Other models may be added when needed.
* "development_status": "Alpha"

I have not written any migration script, and I think nobody is using this module yet.

When I make it a dependency for `payroll`, I will write a migration script in `payroll`. Payroll can keep a user interface to access the time parameters.

### CODE REVIEW

**Review by nimarosa — APPROVED** [review]

**Comment by nimarosa** [comment]
Code looks good to me. I also tested it functional and appears working. Since the module is still in alpha i think we could merge since nobody is using it yet. 

Maybe in the future we can add some tests to shut codecov but everything looks good. 
Great PR @appstogrow you really improved the module. 

Merging. 

/ocabot merge minor

**Comment by nimarosa** [comment]
Weird, i'm a declared maintainer... last PR the bot allowed me for merging. 

@pedrobaeza Can you merge this for us?

**Comment by pedrobaeza** [comment]
As you have renamed the modules, maintainers don't work.

/ocabot merge major

**Comment by pedrobaeza** [comment]
Please rebase to see the problem.

**Comment by nimarosa** [comment]
@appstogrow @pedrobaeza I see all checks passing, except codecov but that should not make merge fail. Should we try again?

**Comment by norlinhenrik** [comment]
I rebased on Friday. There has been no merges in server-tools this week, so the rebase is still "up to date".
@pedrobaeza Could you please merge?

**Comment by pedrobaeza** [comment]
Codecov is not very trustable.

/ocabot merge major

**Pull request merged**
