### PR TITLE
[MIG] auth_user_case_insensitive: Migration to 11.0

### PR DESCRIPTION
**Pull request by gavindav**

### CODE REVIEW

**Comment by gavindav** [comment]
Migrated from 10.0 to 11.0. No code changes required as it ran successfully under 11.0

**Comment by pedrobaeza** [comment]
Please preserve commit history following technical method explained in https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

**Comment by etobella** [comment]
It should go to server-auth, isn't it?

**Comment by pedrobaeza** [comment]
Yes, indeed

**Comment by etobella** [comment]
@pedrobaeza The PR can be closed, as it was merged on OCA/server-auth#35

**Pull request closed without merging**
