### PR TITLE
[10.0][FIX] sentry: fix tests after raven 6.4.0

### PR DESCRIPTION
**Pull request by naglis**
This should fix https://github.com/OCA/server-tools/issues/1096.

### CODE REVIEW

**Review by lasley — APPROVED** [review]
Thanks @naglis 

I'm quick merging this one to fix our build

**Comment by lasley** [comment]
@naglis - I notice you use GPG. Would you like to squash this yourself before merge so I don't destroy your sig?

**Comment by naglis** [comment]
@lasley I've squased the commits, however as only my work email has OCA CLA signed I would only be able to sign it on Monday (d'oh!). I don't mind if you'd merge it before then.

**Comment by lasley** [comment]
Works for me, thanks @naglis!

**Pull request merged**
