### PR TITLE
[FIX] dbfilter_from_header issue when header does not exist

### PR DESCRIPTION
**Pull request by thomaspaulb**

### CODE REVIEW

**Review by GSLabIt — APPROVED** [review]
it should work

**Comment by cvinh** [comment]
Hello
Do you think this commit has to be forwarded to last version ?

**Comment by thomaspaulb** [comment]
I don't think so, unless someone would want to forward-port https://github.com/OCA/server-tools/pull/1657/files also, because the introduction of that code made it necessary for the result to always be a string. In current 18.0 it's fine if it's `None`.

**Pull request merged**
