### PR TITLE
[FIX] avoid useless calls to check_credentials

### LINKED ISSUE #529: [auth_admin_passkey] User account is locked each time we use auth_admin_passkey
We are using auth_admin_passkey in our odoo 8.0 instance with the auth_ldap module.
Our LDAP is an Active Directory (AD).
Unfortunately, each time we use the admin password to log in, the corresponding user account is locked in our AD.
Fyi, our policy is to lock an account after 5 unsuccessful attempts.
Any idea why auth_admin_passkey could generate 5+ unsuccessful log in attempts and how to prevent it ?

### PR DESCRIPTION
**Pull request by nowheresly**
By storing in http session a flag indicating whether the current user is authenticated with the admin password, we can now reduce the number of times check_credentials is called. 
It may avoid locking account when module such as auth_ldap are used with auth_admin_passkey.
Fixes #529

### CODE REVIEW

**Comment by nowheresly** [comment]
This is a different approach from PR #533 .
Now, this PR stores in http session a flag indicating the user is authenticated by means of admin password.
This way, it should reduce the number of wrong login attempts.

**Comment by StefanRijnhart** [comment]
Sorry I'm coming late to this PR. Thank you for changing the approach. Looks good to me, but needs a rebase.

**Comment by yvaucher** [comment]
Still needs a rebase
@Nowheresly are you willing to do it?

**Review by legalsylvain — APPROVED** [review]
Thanks. (Code review, no test).

**Comment by nowheresly** [comment]
new PR #1138 created instead of this one based on branch 8.0

**Pull request closed without merging**
