### PR TITLE
9.0

### PR DESCRIPTION
**Pull request by nadiaafa**
On the module **users_ldap_groups**  file **users_ldap_groups.xml** 
line 10, inheritance was using string as selector  :

`                <xpath expr="//form[@string='LDAP Configuration']" position="inside">
`

which result the following error;

> View inheritance may not use attribute 'string' as a selector.

we can't use string as selector in the xpath for odoo 9.0, instead we can do the following:

`<xpath expr="//field[@name='ldaps']/form" position="inside">`

Thank you

### CODE REVIEW

**Comment by LoisRForgeFlow** [comment]
@nadiaafa I think your target branch is wrong

**Comment by nadiaafa** [comment]
No @lreficent i am sure on the 9.0 branch, please check that

**Comment by lasley** [comment]
Hi @nadiaafa - This PR is targeting OCA/10.0. I went to update the target to 9.0 and it seems that it's just a PR from OCA/9.0 => OCA/10.0. Is this intentional?

**Comment by nadiaafa** [comment]
@lasley ah yeah sorry

**Pull request closed without merging**
