### PR TITLE
[14.0][IMP] base_time_parameter: type reference -> type record

### PR DESCRIPTION
**Pull request by ghost**
When the value should be a record:

* Select `Type` = Record
* Select `Record Model`
  - If empty, for each value select a model and a record (`value_reference`)
  - If Account, for each value select an account (`value_account_id`, see the [account_time_parameter](https://github.com/appstogrow/apps/tree/14.0/account_time_parameter) module)

### CODE REVIEW

**Comment by ghost** [comment]
I wonder if we should change the model name to e.g. `res.time.parameter` or just `time.parameter`. It is a bit strange to work with `account_time_parameter` and similar modules and do all changes in base.time.parameter model.

**Review by nimarosa — APPROVED** [review]
Changes look okay to me.

@appstogrow i suggest we don't change the name of the model again, since I had a lot of headaches in production databases when we changed from rule_parameters to this new module. 

What is the thing you perceive odd when working in account_time_parameter?

**Comment by norlinhenrik** [comment]
@nimarosa Are you using type reference? Then potentially this update could cause you problems, just like when we changed the model name. I think the solution to both scenarios is to **update base_time_parameter in the database the first time** the database is exposed to the code update.

I just checked the non-transient models in my production database.
61 model names start with ir. (internal resource)
22 model names start with res. (resource)
3 model names start with base. (base.time.parameter, base.time.parameter.value & another model which I have made.)
Since starting with base. is not common, _I suggest changing the model name when migrating to 15.0._
I would prefer "time.parameter" or "res.time.parameter".

I came back to this PR now because of a small bug that I introduced in the beginning and now I fixed it. When a parameter value exists, always return it.

**Comment by norlinhenrik** [comment]
@nimarosa Would you like to merge this? (reference -> record, and always return value)

The failing tests are not related to base_time_parameter.

**Comment by nimarosa** [comment]
Lets rebase to see if tests pass now.

/ocabot rebase

**Comment by nimarosa** [comment]
@appstogrow i think we have to wait till tests fixed. Will see tomorrow if I can make a PR but not sure which module is failing.

**Pull request merged**
