### PR TITLE
[15.0][MIG] base_translation_field_label

### PR DESCRIPTION
**Pull request by JasminSForgeFlow**
Standard Migration

@ForgeFlow

### CODE REVIEW

**Review by GuillemCForgeFlow — CHANGES_REQUESTED** [review]
I see that tests are failing because it doesn't find the language used on the test. Perhaps we need to unarchive it first on the test so it can be found.

**Comment by JasminSForgeFlow** [comment]
> I see that tests are failing because it doesn't find the language used on the test. Perhaps we need to unarchive it first on the test so it can be found.

Its done,
Thanks

**Review by GuillemCForgeFlow — APPROVED** [review]
LGTM! 👍🏽

**Review by JordiMForgeFlow — APPROVED** [review]
Code + functional review 👍🏼

**Review by LoisRForgeFlow — APPROVED** [review]
LGTM

**Pull request merged**
