### PR TITLE
[11.0] Backport of profiler

### PR DESCRIPTION
**Pull request by etobella**
Backport for profiler from #1369 
@moylop260 @jbeficent

### CODE REVIEW

**Comment by etobella** [comment]
Travis is failing due to #1466

**Comment by JordiBForgeFlow** [comment]
@etobella now that #1466 is merged, can you rebase to check that Travis is green?

**Comment by etobella** [comment]
@jbeficent Now it is green and rebased.

**Review by JordiBForgeFlow — APPROVED** [review]
We have used it now for several months and works great!

**Comment by JordiBForgeFlow** [comment]
@moylop260 this one LGTM. If you are good with it too we can merge!

**Comment by etobella** [comment]
I will apply commit 5355ab8b58b4c975ddf32f1b1318f45dbf0784a0 from v12 in order to make it similar,
Also, I made some tests in order to improve the coverage, maybe it is interesting to apply them on v12 @moylop260

**Review by pedrobaeza — APPROVED** [review]
Please squash a bit the commit history of initial ones.

**Comment by rousseldenis** [comment]
@etobella Could you squash ?

**Comment by etobella** [comment]
I have squashed my commits except the patching rpccalls, as it already exists on 12.0

**Comment by rousseldenis** [comment]
@OCA/core-maintainers

**Comment by moylop260** [comment]
@etobella 
Thanks for finishing the work

> Also, I made some tests in order to improve the coverage, maybe it is interesting to apply them on v12 @moylop260

Yes, of course.
Sorry for delay about my PR
Could you help me to finish my own PR or creating another one for v12.0, please?

**Pull request merged**
