### PR TITLE
[17.0] dotfiles update needs manual intervention

### PR DESCRIPTION
**Pull request by sbidoul**
Dear maintainer,

After updating the dotfiles, `pre-commit run -a`
fails in a manner that cannot be resolved automatically.

Can you please have a look, fix and merge?

Thanks,

Handled by @Tecnativa

### CODE REVIEW

**Comment by legalsylvain** [comment]
hi @sbidoul. 

I just tried to fix it. But when I run locally ``pre-commit run -a``, it doesn't fix the errors. Is there a regression on V17 ? 
In v16 and before, running pre-commit was fixing incorrect python and xml files.

Thanks !

**Comment by sbidoul** [comment]
@legalsylvain I don't think there has ever been auto fixes for line too long when it requires to split strings?

**Comment by pedrobaeza** [comment]
FYI I'm handling this.

**Pull request merged**
