### PR TITLE
[14.0][mig]configuration_helper

### PR DESCRIPTION
**Pull request by hkapatel-initos**

### CODE REVIEW

**Review by fshah-initos — APPROVED** [review]
LGTM. Code review and functional test

**Comment by hkapatel-initos** [comment]
it would be nice if someone reviews it here

**Comment by hkapatel-initos** [comment]
@thomaspaulb and @sebalix it would be nice if you both review it here.

**Comment by hkapatel-initos** [comment]
@atchuthan can you please review here.

**Comment by hkapatel-initos** [comment]
it would be nice if someone reviews it here

**Review by thomaspaulb — APPROVED** [review]

**Comment by hkapatel-initos** [comment]
Hello maintainers,
It would be nice if you are trying to merge it

**Comment by thomaspaulb** [comment]
@hbrunn Is that something you could do

**Comment by hbrunn** [comment]
/ocabot merge nobump

direct nags to merge something should happen very very seldom, there are a lot of people wanting to get their stuff merged

**Pull request merged**
