### PR TITLE
[10.0][MIG] base_report_auto_create_qweb

### PR DESCRIPTION
**Pull request by grindtildeath**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
I'm thinking that this one fits better on OCA/reporting-engine, don't you think?

**Comment by damdam-s** [comment]
@pedrobaeza It's more a very technical module than a reporting module. So I would tend to keep it here.

**Comment by pedrobaeza** [comment]
Ok, no problem

**Review by gurneyalex — APPROVED** [review]

**Review by eLBati — APPROVED** [review]
LGTM

**Review by simahawk — APPROVED** [review]

**Comment by simahawk** [comment]
anything else missing here to hit the button? :)

**Pull request merged**
