### PR TITLE
[15.0][MIG] base_multi_image

### PR DESCRIPTION
**Pull request by flachica**
Dependency below, please review

https://github.com/OCA/connector-prestashop/pull/151
https://github.com/OCA/sale-workflow/pull/2005
https://github.com/OCA/connector-ecommerce/pull/70
https://github.com/OCA/server-tools/pull/2334
https://github.com/OCA/product-attribute/pull/1070
https://github.com/OCA/product-attribute/pull/1069

### CODE REVIEW

**Comment by rousseldenis** [comment]
@flachica Thanks for this.

Could you update your last commit message in order to have something like '[15.0][MIG] base_multi_image'?

**Review by rousseldenis — APPROVED** [review]
Code review

**Comment by flachica** [comment]
> @flachica Thanks for this.
> 
> Could you update your last commit message in order to have something like '[15.0][MIG] base_multi_image'?

Changed, thanks for your reviews

**Comment by jacekmichalski** [comment]
@pedrobaeza isn't it ready to be merged?

Btw, what about https://github.com/OCA/product-attribute/pull/1070 ?

**Comment by pedrobaeza** [comment]
I miss a second review, but I suppose yours counts as second one. Please use the proper GitHub review mechanism.

/ocabot merge nobump
/ocabot migration base_multi_image

**Pull request merged**
