### PR TITLE
[FIX] we need to call our login method old style

### PR DESCRIPTION
**Pull request by hbrunn**

### CODE REVIEW

**Comment by sebalix** [comment]
:+1:

**Comment by moylop260** [comment]
:+1:

**Comment by sebalix** [comment]
Two thumbs up, I think it can be merged?

**Comment by hbrunn** [comment]
yes please!

**Comment by pedrobaeza** [comment]
I see no upstream PR. Doesn't it apply?

**Comment by pedrobaeza** [comment]
Sorry, I got confused with OCB. Merging.

**Pull request merged**
