### PR TITLE
[14.0] [mig] datetime_formatter

### PR DESCRIPTION
**Pull request by dsolanki-initos**

### CODE REVIEW

**Review by fshah-initos — APPROVED** [review]
LGTM.

**Comment by dsolanki-initos** [comment]
Hi @ernestotejeda 
Can you please review this PR?

**Comment by dsolanki-initos** [comment]
Hi @joao-p-marques 
It would be nice if you review the PR

**Comment by dsolanki-initos** [comment]
@Yajo 
It will be nice if you can add reviews here

**Review by ernestotejeda — APPROVED** [review]
LGTM :+1:

**Pull request merged**
