### PR TITLE
[14.0] Replace base_jsonify w/ jsonifier

### PR DESCRIPTION
**Pull request by simahawk**
Continues #2326 to address #2134.

Rationale:

1. the name reflects better what it does
   as this is not _just_ a base module

2. solves publication issue on odoo apps store
   due to an old module registered w/ the same name
   that even if un-published blocks publishing the module
   for all versions.
   This in turn, blocks the publication of ALL modules
   that depend on base_jsonify.

This change makes `base_jsonify` dependent on `jsonifier`: no harm on existing modules AFAIK.

**TODO**

- [x] test integration in existing projects

### CODE REVIEW

**Comment by simahawk** [comment]
I've tested this on 2 existing projects: seems all good.
No change is required on depending modules, so if you update only server-tools on your instances nothing will be broken (if you install `jsonifier`).

However, I'll start replacing `base_jsonify` dependencies on `shopfloor*` and `connector_search_engine` because it's a pity that those modules are not on the apps store.

**Comment by simahawk** [comment]
@sebastienbeau @lmignon @hparfr @ivantodorovich could any of  you review this?

**Review by mmequignon — APPROVED** [review]

**Review by lmignon — APPROVED** [review]

**Comment by simahawk** [comment]
image

@sbidoul does it sound familiar?

**Comment by sbidoul** [comment]
@pedrobaeza mentioned the same this morning. No idea what's happening...

**Comment by simahawk** [comment]
@pedrobaeza @sbidoul according to https://github.com/actions/checkout/issues/363 and https://github.com/actions/checkout/issues/335 upgrading GIT might solve the problem. 
I could test it here.

**Comment by simahawk** [comment]
bah, probably is not "the" solution... I'll check again later

**Comment by simahawk** [comment]
I see PRs on other repo succeeding... let's try again!

/ocabot merge nobump

**Comment by pedrobaeza** [comment]
The problem has escalated everywhere: https://github.com/OCA/l10n-spain/runs/6135379246?check_suite_focus=true

I don't know which part do the POT update, but may it be that an update on GH machinery puts the target directory in another environment variable or similar?

**Comment by pedrobaeza** [comment]
Now it should be working:

/ocabot merge nobump

**Pull request merged**
