### PR TITLE
[IMP][12.0][auto_backup] Support pysftp==0.2.9 - Auto-add host to known_hosts, if it's the first time we connect

### PR DESCRIPTION
**Pull request by ivantodorovich**
Adds support for `pysftp==0.2.9`

With this PR, if it's the first time we connect to that server (meaning, not in known hosts list), we add it to the list.

pinging authors:
@Yenthe666 
@archetipo 
@lasley

### CODE REVIEW

**Comment by ivantodorovich** [comment]
Any idea on how to fix tests, without removing them? :thinking: 

```
` AssertionError: Expected call: Connection(cnops=<MagicMock name='pysftp.CnOpts()' id='140476525840648'>, host='test_host', password='password', port=222, username='tuser')
` Actual call: Connection(cnopts=<MagicMock name='pysftp.CnOpts()' id='140476525840648'>, host='test_host', password='password', port=222, username='tuser')
```

**Comment by mamcode** [comment]
@ivantodorovich I have tested the module in my local instance and I found an error, I am testing a simple sftp connection to localhost, this error is raised when I click on button "Test SFTP Connection", without the PR the connection is succesful, however with the PR all unit tests run satisfactorily, what may be happening ?
```
Odoo Server Error
Traceback (most recent call last):
  File "/opt/Virtualenvs/odoo12.0/odoo/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/Virtualenvs/odoo12.0/odoo/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/Virtualenvs/odoo12.0/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/Virtualenvs/odoo12.0/odoo/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/opt/Virtualenvs/odoo12.0/odoo/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/Virtualenvs/odoo12.0/odoo/odoo/service/model.py", line 98, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/Virtualenvs/odoo12.0/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/Virtualenvs/odoo12.0/odoo/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/opt/Virtualenvs/odoo12.0/odoo/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/opt/Virtualenvs/odoo12.0/odoo/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/Virtualenvs/odoo12.0/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/Virtualenvs/odoo12.0/odoo/odoo/api.py", line 759, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/opt/Virtualenvs/odoo12.0/odoo/odoo/api.py", line 746, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/Virtualenvs/odoo12.0/extra-addons/OCA/server-tools/auto_backup/models/db_backup.py", line 132, in action_sftp_test_connection
    with self.sftp_connection():
  File "/opt/Virtualenvs/odoo12.0/extra-addons/OCA/server-tools/auto_backup/models/db_backup.py", line 305, in sftp_connection
    cnopts = pysftp.CnOpts()
AttributeError: module 'pysftp' has no attribute 'CnOpts'
```

auto backup test sftp connection error

**Comment by mamcode** [comment]
I have pysftp==0.2.8 installed in my environment.

**Comment by ivantodorovich** [comment]
Actually now that I look at this again, I realize I've been using `pysftp==0.2.9`, which introduced hostchecks.

I guess what this PR tries to fix is not really an issue when using `pysftp==0.2.8`. It's actually adding support for `pysftp 0.2.9`. I'll rename it

**Pull request closed without merging**
