### PR TITLE
[11.0] [MIG] [REN] mail_log_message_to_process -> fetchmail_incoming_log

### PR DESCRIPTION
**Pull request by HviorForgeFlow**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
This should be called `fetchmail_incoming_log` or similar. Any way, this is something that now Odoo does, isn't it?

**Comment by HviorForgeFlow** [comment]
Yes, odoo throw some logs if email is correctly recieved. This modules aims to launch logs before odoo process incoming email, so even if it has an error you can see preprocessed message in logs.

@jbeficent What do you think about proposed module name?

**Review by LoisRForgeFlow — APPROVED** [review]
LTGM :+1:  Thank for adding tests!

**Review by MiquelRForgeFlow — APPROVED** [review]
LGTM

**Pull request merged**
