### PR TITLE
[MIG] upgrade_analysis: Migration to 16.0

### PR DESCRIPTION
**Pull request by StefanRijnhart**
Includes https://github.com/OCA/server-tools/pull/2416

### CODE REVIEW

**Comment by sebalix** [comment]
@StefanRijnhart I created a new release [0.9.0](https://pypi.org/project/OdooRPC/0.9.0/) for OdooRPC, tests are now running fine, not runboat (need to wait a bit I guess, it still installs the 0.8.0 version, cache issue?)

**Comment by StefanRijnhart** [comment]
@sebalix brilliant, thanks! Runboat is now fine as well.

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
We can go with this one as well:

/ocabot merge nobump

**Pull request merged**
