### PR TITLE
[10.0][IMP] .travis.yml: Update to latest template

### PR DESCRIPTION
**Pull request by rousseldenis**

### CODE REVIEW

**Comment by rousseldenis** [comment]
@pedrobaeza Is it planned to switch to Travis Github app on all repositories or is it at demand ?

**Comment by pedrobaeza** [comment]
Not sure how it works, as 13.0 was set mainly by @sbidoul. Maybe he can say.

**Comment by rousseldenis** [comment]
> Not sure how it works, as 13.0 was set mainly by @sbidoul. Maybe he can say.

Yes, tested recently with him. That's to avoid sometimes webhooks problems. Ok, I'll ask

**Comment by rousseldenis** [comment]
@OCA/core-maintainers This one is :green_apple:

**Comment by sbidoul** [comment]
> Yes, tested recently with him. That's to avoid sometimes webhooks problems. Ok, I'll ask

I migrated `OCA/server-*` repos to travis-ci.com. Let me know how it goes.

**Comment by rousseldenis** [comment]
> > Yes, tested recently with him. That's to avoid sometimes webhooks problems. Ok, I'll ask
> 
> I migrated `OCA/server-*` repos to travis-ci.com. Let me know how it goes.

Tested with no problem. Merge this ?

**Comment by rousseldenis** [comment]
@OCA/core-maintainers

**Comment by sbidoul** [comment]
LGTM.

/ocabot merge nobump

**Pull request merged**
