### PR TITLE
[FIX][auth_signup_verify_email] Remove error from logs

### LINKED ISSUE #981: [9.0] [auth_signup_verify_email] seems to cause errors in Travis
See: https://travis-ci.org/OCA/server-tools/jobs/275353505#L2403
Seems to be caused by the module testing the emails

cc @Yajo

### PR DESCRIPTION
**Pull request by yajo**
This fixes #981.

@Tecnativa

### CODE REVIEW

**Comment by JordiBForgeFlow** [comment]
Travis is failing

**Comment by yajo** [comment]
I think now I muted all failure logs, but [there's still a problem with `oauth_provider`, with really failing tests](https://travis-ci.org/OCA/server-tools/jobs/275449919#L1749-L1765).

I never touched that addon, I guess @sylvain-garancher can help with that better than me...

**Comment by Garamotte** [comment]
Sorry, I currently don't have time to look at this issue :(
Maybe during Odoo Experience.

**Comment by Garamotte** [comment]
FYI, the OAuth test is failing due to [a modification in `oauthlib`](https://github.com/OCA/server-tools/issues/1011), this should be fixed soon.

**Review by pedrobaeza — APPROVED** [review]
Test fixed and branch green, so I merge.

**Pull request merged**
