### PR TITLE
[FIX] Typo in font name

### PR DESCRIPTION
**Pull request by ateijelo**

### CODE REVIEW

**Comment by lasley** [comment]
@ateijelo - are you planning on re-submitting from a different fork or something? This looks to have been a perfectly valid fix IMO

**Comment by ateijelo** [comment]
Yes, I mean to resubmit it. But I just realized after hastily creating it that some of the changes were inside `msgid`'s. So I panicked :) and decided to go back and review this more carefully.

**Comment by ateijelo** [comment]
By the way, I don't know where else to ask this, but I believe the `msgid`s inside the `.po` files should be kept "id-like". And then one should have the long unwieldy blocks of text in the msgstr of each language.

**Comment by ateijelo** [comment]
I apologize for this mess :) I created a new PR: https://github.com/OCA/server-tools/pull/765

**Pull request closed without merging**
