### PR TITLE
[DEL] Make obsolete base_concurrency module uninstallable

### PR DESCRIPTION
**Pull request by thomaspaulb**

### CODE REVIEW

**Comment by thomaspaulb** [comment]
@NL66278 What was the rationale behind this?

**Comment by NL66278** [comment]
@thomaspaulb As far as I understand there were problems in the past if a user was accessing Odoo from different tabs in concurrent updates of the last login time in the res.users model. This should now be handled in the base code by updating through a separate cursor. That is already in Odoo 8.0.

**Review by NL66278 — APPROVED** [review]
:+1: LGTM

**Comment by pedrobaeza** [comment]
For v8, this is still needed, as it requires a change in the DB layout. For v9, Odoo already includes it in core.

**Comment by thomaspaulb** [comment]
@pedrobaeza Which database change is that?

**Comment by NL66278** [comment]
@thomaspaulb Do we really need to disable installation? Maybe enough just not to install the module if not needed?

**Comment by thomaspaulb** [comment]
Alright.

**Pull request closed without merging**
