### PR TITLE
[12.0] Fixing travis and runbot

### PR DESCRIPTION
**Pull request by etobella**
This was making travis fail:
https://travis-ci.org/OCA/server-tools/builds/636779904?utm_source=github_status&utm_medium=notification

### CODE REVIEW

**Comment by etobella** [comment]
The first commit fixes Travis, the second one, fixes Runbot

**Comment by etobella** [comment]
@p-tombez @StefanRijnhart @hbrunn @OCA/tools-maintainers

**Review by jarroyomorales — APPROVED** [review]

**Review by LoisRForgeFlow — APPROVED** [review]
Thanks!! :1st_place_medal:

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
