### PR TITLE
[14.0] [mig] module_prototyper

### PR DESCRIPTION
**Pull request by dsolanki-initos**

### CODE REVIEW

**Comment by houssine78** [comment]
Hi @dsolanki-initos could you fix test that make travis fail ?

Thanks !

**Comment by houssine78** [comment]
Hi @dsolanki-initos do you'll have time to fix travis and runbot ?

**Review by houssine78 — APPROVED** [review]

**Review by fshah-initos — APPROVED** [review]
Functional Tests and Code review LGTM

**Comment by hkapatel-initos** [comment]
Hello, @dreispt I tried to resolve this issue can you please try to merge it again.

**Comment by hkapatel-initos** [comment]
Hello, @njeudy  can you please help me to resolve this issue
https://github.com/OCA/server-tools/pull/2073#issuecomment-907666512

**Comment by hkapatel-initos** [comment]
> @dreispt The merge process could not be finalized, because command `oca-gen-addon-readme --org-name OCA --repo-name server-tools --branch 14.0 --addons-dir /tmp/tmp6rolxz_x --commit` failed with output:
> 
> ```
> /tmp/tmp6rolxz_x/module_prototyper/README.rst:118: (SEVERE/4) Title level inconsistent:
> 
> Maintainers
> ~~~~~~~~~~~
> Traceback (most recent call last):
>   File "/usr/local/bin/oca-gen-addon-readme", line 11, in <module>
>     load_entry_point('oca-maintainers-tools', 'console_scripts', 'oca-gen-addon-readme')()
>   File "/ocamt-readme/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
>     return self.main(*args, **kwargs)
>   File "/ocamt-readme/lib/python3.8/site-packages/click/core.py", line 1062, in main
>     rv = self.invoke(ctx)
>   File "/ocamt-readme/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/ocamt-readme/lib/python3.8/site-packages/click/core.py", line 763, in invoke
>     return __callback(*args, **kwargs)
>   File "/ocamt-readme/src/oca-maintainers-tools/tools/gen_addon_readme.py", line 312, in gen_addon_readme
>     check_rst(readme_filename)
>   File "/ocamt-readme/src/oca-maintainers-tools/tools/gen_addon_readme.py", line 239, in check_rst
>     publish_file(
>   File "/ocamt-readme/lib/python3.8/site-packages/docutils/core.py", line 370, in publish_file
>     output, pub = publish_programmatically(
>   File "/ocamt-readme/lib/python3.8/site-packages/docutils/core.py", line 664, in publish_programmatically
>     output = pub.publish(enable_exit_status=enable_exit_status)
>   File "/ocamt-readme/lib/python3.8/site-packages/docutils/core.py", line 216, in publish
>     self.document = self.reader.read(self.source, self.parser,
>   File "/ocamt-readme/lib/python3.8/site-packages/docutils/readers/__init__.py", line 71, in read
>     self.parse()
>   File "/ocamt-readme/lib/python3.8/site-packages/docutils/readers/__init__.py", line 77, in parse
>     self.parser.parse(self.input, document)
>   File "/ocamt-readme/lib/python3.8/site-packages/docutils/parsers/rst/__init__.py", line 191, in parse
>     self.statemachine.run(inputlines, document, inliner=self.inliner)
>   File "/ocamt-readme/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 170, in run
>     results = StateMachineWS.run(self, input_lines, input_offset,
>   File "/ocamt-readme/lib/python3.8/site-packages/docutils/statemachine.py", line 238, in run
>     context, next_state, result = self.check_line(
>   File "/ocamt-readme/lib/python3.8/site-packages/docutils/statemachine.py", line 460, in check_line
>     return method(match, context, next_state)
>   File "/ocamt-readme/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 3007, in text
>     self.section(title.lstrip(), source, style, lineno + 1, messages)
>   File "/ocamt-readme/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 327, in section
>     self.new_subsection(title, lineno, messages)
>   File "/ocamt-readme/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 393, in new_subsection
>     newabsoffset = self.nested_parse(
>   File "/ocamt-readme/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 281, in nested_parse
>     state_machine.run(block, input_offset, memo=self.memo,
>   File "/ocamt-readme/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 196, in run
>     results = StateMachineWS.run(self, input_lines, input_offset)
>   File "/ocamt-readme/lib/python3.8/site-packages/docutils/statemachine.py", line 238, in run
>     context, next_state, result = self.check_line(
>   File "/ocamt-readme/lib/python3.8/site-packages/docutils/statemachine.py", line 460, in check_line
>     return method(match, context, next_state)
>   File "/ocamt-readme/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2771, in underline
>     self.section(title, source, style, lineno - 1, messages)
>   File "/ocamt-readme/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 326, in section
>     if self.check_subsection(source, style, lineno):
>   File "/ocamt-readme/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 367, in check_subsection
>     self.parent += self.title_inconsistent(source, lineno)
>   File "/ocamt-readme/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 371, in title_inconsistent
>     error = self.reporter.severe(
>   File "/ocamt-readme/lib/python3.8/site-packages/docutils/utils/__init__.py", line 237, in severe
>     return self.system_message(self.SEVERE_LEVEL, *args, **kwargs)
>   File "/ocamt-readme/lib/python3.8/site-packages/docutils/utils/__init__.py", line 195, in system_message
>     raise SystemMessage(msg, level)
> docutils.utils.SystemMessage: /tmp/tmp6rolxz_x/module_prototyper/README.rst:118: (SEVERE/4) Title level inconsistent:
> 
> Maintainers
> ~~~~~~~~~~~
> ```
 I tried to resolve this issue can you please try to merge it again.

**Comment by dreispt** [comment]
@hkapatel-initos I had a case where I needed subtitles in the README, and had a similar problem.
Here is what ended up working for me, I hope the example helps:
https://raw.githubusercontent.com/OCA/account-fiscal-rule/14.0/account_avatax/readme/USAGE.rst

**Comment by hkapatel-initos** [comment]
> @hkapatel-initos I had a case where I needed subtitles in the README, and had a similar problem. Here is what ended up working for me, I hope the example helps: https://raw.githubusercontent.com/OCA/account-fiscal-rule/14.0/account_avatax/readme/USAGE.rst

Hello @dreispt can you please try to merge it again.

**Comment by hkapatel-initos** [comment]
Hello @dreispt can you please try to merge it again?

**Comment by dsolanki-initos** [comment]
Can we try to merge it again?

**Comment by houssine78** [comment]
Hi @pedrobaeza , could you try to merge this PR ? Thank you.

**Pull request merged**
