### PR TITLE
Fix name search to honor additional domain if provided

### LINKED ISSUE #476: [8.0] base_name_search_improved, problem with domain of many2one filed.
As I install this seemingly useful module (with out any configuration yet). Domain stop working properly.
For example,
In Supplier Payment, the payment method should display only Cash or Bank. Now, it display every journal.
It does affect many fields not just payment method.

### PR DESCRIPTION
**Pull request by dreispt**
Fixes #476

### CODE REVIEW

**Comment by dreispt** [comment]
I testes on Runbot (on Manufacturing Orders, "Bill of Materials" has a domain filter depending on the "product" selected) and LGTM.

**Comment by dreispt** [comment]
I forgot to bump the module version...

**Comment by yvaucher** [comment]
Code review :+1:

**Comment by lasley** [comment]
LGTM 👍

**Comment by yvaucher** [comment]
Merging (i'll bump the version)

**Comment by yvaucher** [comment]
Merged at https://github.com/OCA/server-tools/commit/72f375ac6880e3fc704e4d5b9fc6307030311cb5

**Comment by dreispt** [comment]
@yvaucher Thanks! I was away these days so could fix the version sooner.

**Pull request merged**
