### PR TITLE
[16.0][IMP] tracking_manager: Test compatibility

### PR DESCRIPTION
**Pull request by victoralmau**
Previously the `bank_ids` field was used but [account](https://github.com/odoo/odoo/blob/16.0/addons/account/models/res_partner_bank.py#L176) adds messages in partner when a related bank account is created/modified/deleted, causing tests to fail. Related to https://github.com/OCA/server-tools/pull/2789#issuecomment-1870227588

The `user_ids` field of `res.partner` is now used to avoid the side effect in tests and the fake model is removed.

Please @pedrobaeza and @chienandalu can you review it?

@Tecnativa TT50571

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Isn't possible to do the test without creating an extra model? In other place/field?

**Comment by victoralmau** [comment]
I think it would be possible to use the `user_ids` field but that would make a very large diff.

**Comment by pedrobaeza** [comment]
Well, right now you have a large diff changing `bank_ids` by `custom_bank_ids`...

**Comment by victoralmau** [comment]
Changes done: The `user_ids` field of `res.partner` is now used (although everything is **only** in fake models for tests).

**Comment by pedrobaeza** [comment]
I only see `category_ids` used in:

https://github.com/OCA/server-tools/blob/312daa160949916efdb3b828bcf8b97ca82a859c/tracking_manager/tests/test_tracking_manager.py#L192

I think you can use another field and remove the FakeModelLoader.

**Review by pedrobaeza — APPROVED** [review]

**Review by Kev-Roche — APPROVED** [review]

**Pull request merged**
