### PR TITLE
[16.0][MIG] base_import_default_enable_tracking: Migration to 16.0

### PR DESCRIPTION
**Pull request by SirAionTech**
Standard migration from `10.0` (https://github.com/OCA/server-tools/tree/456a6ca7aec6f2415e78027874915576616f1587/base_import_default_enable_tracking).

### CODE REVIEW

**Review by StefanRijnhart — COMMENTED** [review]
A migration from 10 to 16! And yet so useful, thank you!

Can you improve the module description by stating this concerns the setting `Track history during import` that is only visible in debug mode?

**Comment by SirAionTech** [comment]
> A migration from 10 to 16! And yet so useful, thank you!
> 
> Can you improve the module description by stating this concerns the setting `Track history during import` that is only visible in debug mode?

Thanks for your review!
Done

**Review by StefanRijnhart — APPROVED** [review]
Thanks for the update!

**Comment by SirAionTech** [comment]
@OCA/tools-maintainers this has enough reviews, can someone please merge?

**Comment by SirAionTech** [comment]
> /ocabot merge nobump

Thanks :smile:

**Pull request merged**
