### PR TITLE
[13.0][UPT]fetchmail_notify_error_to_sender remove dependency on test_mail

### PR DESCRIPTION
**Pull request by AaronHForgeFlow**
Why this? Because of that:
https://github.com/OCA/server-tools/pull/1485#discussion_r289751883

### CODE REVIEW

**Comment by AaronHForgeFlow** [comment]
@LoisRForgeFlow

**Review by LoisRForgeFlow — APPROVED** [review]
Thanks! we are making production environments a little bit less heavy :)

**Comment by LoisRForgeFlow** [comment]
@Yajo can you have a look?

**Review by etobella — APPROVED** [review]
LGTM :+1: Great to remove this dependency

**Review by jarroyomorales — APPROVED** [review]
LGTM

**Review by AdriaGForgeFlow — APPROVED** [review]

**Pull request merged**
