### PR TITLE
[18.0][MIG] dbfilter_from_header: Migration to 18.0

### PR DESCRIPTION
**Pull request by remytms**

### CODE REVIEW

**Review by mostafabarmshory — APPROVED** [review]
All things seams ok, but test coverage.

**Review by f-nadimi — APPROVED** [review]

**Review by Sanazzzmi — APPROVED** [review]

**Review by fardinmardani — APPROVED** [review]

**Comment by mostafabarmshory** [comment]
@remytms 

Any news?
I could not understand why this was not merged with branch 18.0.
Even not listed in  #3047

**Comment by remytms** [comment]
The issue you mentionned is for OpenUpgrade script, that why this OCA module is not listed there. OpenUpgrade scripts are only for standard Odoo module.

Each repository is manager by PSCs, and they can decide if this can be merge with the red ci for test coverage. PSC can be found [here](https://oca.github.io/repo-maintainer-conf/server.html).

**Review by houssine78 — APPROVED** [review]
LGTM

**Comment by houssine78** [comment]
@pedrobaeza this PR can be merged too. thanks !

**Pull request merged**
