### PR TITLE
[15.0][MIG] sql_request_abstract: Migration to 15.0

### PR DESCRIPTION
**Pull request by yankinmax**

### CODE REVIEW

**Comment by yankinmax** [comment]
@legalsylvain can you pls approve workflow?

**Comment by legalsylvain** [comment]
No.
unfortunately, I don't have write access on that repo/

**Comment by yankinmax** [comment]
@legalsylvain then review pls

**Comment by yankinmax** [comment]
@simahawk can you pls approve workflow?

**Review by sebalix — COMMENTED** [review]
You forgot to add the name of the addon in the `[IMP] : black, isort, prettier` commit, otherwise LG

**Comment by sebalix** [comment]
@yankinmax I checked the migration status issue there: https://github.com/OCA/server-tools/issues/2192
This addon has been migrated and moved to another repo: https://github.com/OCA/reporting-engine/pull/552

So I close this PR.

**Pull request closed without merging**
