### PR TITLE
[FIX] inverse password check to ensure auth_ldap compatibility.

### PR DESCRIPTION
**Pull request by nowheresly**
The check_credentials method checks first if the given password is the admin password.
If not, then it returns True if the password is correct for the given user, False otherwise.

### CODE REVIEW

**Comment by lasley** [comment]
👍  seems like this should help in #529 as well assuming passkey doesn't have lockout policies as well

**Comment by nowheresly** [comment]
This PR is related to the issue #529. In check_credentials method, if we invert the check, ie, first we check the admin password, then we check the user password, we avoid calling auth_ldap too much often.
Of course, if the admin user is a LDAP-user, we're back to the same issue.
But as stated by @lasley in #529, it is not recommended to have the admin user as a LDAP-user.

After applying this PR, the only unsuccessful login attempt is the one made to ensure the password of the user is not the same as the admin password. And I don't see an easy way to prevent this call...
Any thought ?

**Comment by StefanRijnhart** [comment]
This will lead to a lot more alarming warnings about bad passwords for admin. It will also hit the access error a lot more (every time any regular user logs on) than the original version (when you are using the passkey as an admin). I would try to investigate the real problem instead if I were you.

**Comment by sbidoul** [comment]
@Nowheresly the inheritance order is depending in the loading order of modules. I'm not sure there is any determinism in that order when modules don't depend on each other. So it could be this PR works by chance because auth_ldap is in the parents of auth_admin_passkey, but on another database it could very well be the other way around. Not sure... but I have no better idea at the moment.

**Comment by lasley** [comment]
~~Wouldn't we want to always prefer logins from the installed module over superclass, no matter the load order? Outside of the sudo condition there, anyways.~~

On second thought, six of one half a dozen of the other really. Probably best for the least expensive operation (local user) first

**Comment by nowheresly** [comment]
Hi @sbidoul 
Thanks for your review!
I'm not sure about the determinism of these modules installation too. 
To my understanding, auth_admin_passkey should always be the children of all other true auth providers (such as auth_crypt or auth_ldap). Otherwise, the second check performed by auth_admin_passkey (ie: the check wither SUPERUSER) will always fail if the auth provider of user admin is a children of auth_admin_passkey.
For example, if admin is only defined in LDAP and the authentication chain is defined as below : 
[auth_ldap] -> [auth_admin_passkey] -> [auth_crypt]
then log in with any user with the admin password will always fail...

So, unless I miss something, I don't think my PR would not work anymore if inheritance of auth module is modified. 
Yet, this PR will generate a lot more wrong login attempts for the admin user than auth_admin_passkey used to do before...

**Comment by nowheresly** [comment]
Hi @StefanRijnhart 
Thanks for your review. 
You're perfectly right. This PR will generate a lot more wrong login attempts for the admin user.
Yet, as much as I understand this module, I think auth_admin_passkey, **by design**, generates a lot of wrong login attempts for the admin user, right ?
As soon as a user mistakenly enters a wrong password, auth_admin_passkey checks whether it could be the admin password. 
Same thing if a user enters his/her right password but the account is locked.
For a normal days, it seems enough to generate dozens of unsuccessful login attempts for the admin user IMHO.

This is certainly far less than what this PR could generate (a wrong admin login attempt per login request) but still too much to enforce some sort of security policy on the admin account (ie: locking the admin after n unsuccessful consecutive login attempts).

Yet, I agree with you, this PR sounds maybe too simple... I'll try something else.
Thanks for your time and advices to all of you @sbidoul @lasley @StefanRijnhart .

**Comment by StefanRijnhart** [comment]
Closing in favour of https://github.com/OCA/server-tools/pull/534

**Pull request closed without merging**
