### PR TITLE
9.0 mig datetime formatter

### PR DESCRIPTION
**Pull request by cubells**
- Imported last updates from v8
- Adapted to v9
- Updated README

@Tecnativa

### CODE REVIEW

**Comment by cubells** [comment]
related: https://github.com/OCA/server-tools/pull/606

**Comment by sebalix** [comment]
This PR updates many modules:
- auth_from_http_remote_user
- base_multi_image
- date_range
- datetime_formatter
- mass_editing

Do you follow the [migration instructions](https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-9.0#technical-method-to-migrate-a-module-from-80-to-90-branch) to migrate only `datetime_formatter`? 
As such it is :-1:

**Comment by cubells** [comment]
@sebalix Now It's correct. Sorry

**Review by pedrobaeza — APPROVED** [review]
Errors in Travis are unrelated.

**Comment by pedrobaeza** [comment]
cc @Tecnativa

**Review by susport — COMMENTED** [review]
👍

**Review by moylop260 — APPROVED** [review]

**Pull request merged**
