### PR TITLE
only ldap groups fix

### PR DESCRIPTION
**Pull request by luc-demeyer**
Without this fix, the "map_groups" is never called for existing users, hence a change of access rights in LDAP is not reflected in the odoo groups.

### CODE REVIEW

**Comment by hbrunn** [comment]
the function is never called for existing users _with a password in the odoo database_. The local login _must_ fail, only then the user is considered a ldap user. Clear out your passwords in the database, then the code works unaltered.

**Comment by luc-demeyer** [comment]
@hbrunn,
please reopen since your statement is not correct, at least not for the current version of Odoo 8:

cf. v8 official addons, auth_ldap/users_ldap.py, line 251:

```
def _login(self, db, login, password):
    user_id = super(users, self)._login(db, login, password)
    if user_id:
        return user_id
```

Hence the get_or_create_user call is never executed.

**Comment by hbrunn** [comment]
yes, and what do you think is the reason a user id comes back? Because the login worked locally, so it's not a ldap account from the point of view of odoo. As said before: Clear out your local passwords in res_users, then you get an actual ldap login and then you're fine

**Comment by luc-demeyer** [comment]
@hbrunn 
Please close a PR only after the issue is clearly identified and fixed.

More in depth: 
I checked the res_users password field before making the fix.
Clearing out the password from the db also doesn't apply to the specific project I made this patch for since we work with 'Create User' set to True and no 'Template User'. 
In such a case the first connection works fine with the current OCA module, the user gets created with the correct security groups. At the second login the 'get_or_create_user' call is never entered into.

Now reading the code:

the auth_ldap does a super of the _login method.
In the base _login method the '_check_credentials' is called, this one will indeed never get into the ldap credential checking if the standard login/password is succesful.
When this standard login fails (e.g. because of cleared out password or newly created LDAP user), the code performs the ldap_authenticate call (cf. auth_ldap, users_ldap.py, check_credentials method) and if that call is succesful it returns (no raise -> final result is user_id being returned after def _login and no call to 'get_or_create_user').

**Comment by hbrunn** [comment]
wow, I'm so sorry, din't look good enough at the changes in auth_ldap. My apologies! :+1:

**Comment by lanouettea** [comment]
I am experiencing the same issue and would be voting for this pull request. Users gets created with the correct groups.  But the call to map the groups never gets called after initial user creation.

I confirm that the password are NOT saved in database for any user. I stepped through the login process with pdb and see the comportment described by @luc-demeyer. I also believe that issue #348 is caused by the same issue.

**Comment by luc-demeyer** [comment]
we are currently running with this fix on 3 production databases, hence it's safe to merge.

**Review by sebalix — APPROVED** [review]
LGTM, :+1:

**Review by yvaucher — APPROVED** [review]
LGTM

**Pull request merged**
