### PR TITLE
[ADD] company_country: Backport module from 12.0

### PR DESCRIPTION
**Pull request by luisg123v**
This module allows to set a country to the main company before the
`account` module is installed, so the hook of that module installs the
correct `l10n_***` module.

This is useful because, if the company isn't already set correctly when
the `account` module is installed, the generic accounting chart will be
installed (`l10n_generic_coa`), which may be incorrect depending on your
company's country.

This is a backport from:
https://github.com/OCA/server-tools/tree/12.0/company_country

Co-authored-by: Moisés López <moylop260@vauxoo.com>

### CODE REVIEW

**Comment by moylop260** [comment]
@luisg123v 
Could you check the travis error, please?

**Comment by luisg123v** [comment]
@moylop260
Done, error fixed.

Travis is still red but it's unrelated (only `database_cleanup`)

**Comment by luisg123v** [comment]
Hi @moylop260,

The target branch is already red due to the same error. Do you think it's feasible to merge this manually?

**Pull request merged**
