### PR TITLE
Fix new pylint rules

### PR DESCRIPTION
**Pull request by bwrsandman**
See new rules at https://github.com/OCA/maintainer-quality-tools/pull/127

### CODE REVIEW

**Comment by bwrsandman** [comment]
@pedrobaeza, @gurneyalex, @dreispt please review

**Comment by pedrobaeza** [comment]
There is a pylint error left:

```
************* Module server-tools.mass_editing.wizard.mass_editing_wizard
mass_editing/wizard/mass_editing_wizard.py:200: [W0622(redefined-builtin), mass_editing_wizard.create] Redefining built-in 'id'
```

**Comment by legalsylvain** [comment]
Sorry,
I think I dit part of the work and it is merged. https://github.com/OCA/server-tools/pull/86

**Comment by pedrobaeza** [comment]
We can close this then.

**Pull request closed without merging**
