### PR TITLE
[10.0] Port onchange_helper to v10

### PR DESCRIPTION
**Pull request by alexis-via**

### CODE REVIEW

**Comment by alexis-via** [comment]
This module onchange_helper is used by the OCA/edi/account_invoice_import for v10, cf this PR https://github.com/OCA/edi/pull/14

**Comment by mourad-ehm** [comment]
In odoo 10.0, there is a a method _convert_to_write that can return a value of onchange . ex: 
   procurement = Procurement.new(values)
   procurement.onchange_product_id()
   return Procurement.create(procurement._convert_to_write(procurement._cache)).
This behaviour is not the same as this module ?

**Comment by gurneyalex** [comment]
@alexis-via I'm not sure the travis failure is related to the PR. Could you rebase?

**Review by gurneyalex — APPROVED** [review]

**Comment by alexis-via** [comment]
rebase done

**Review by atchuthan — APPROVED** [review]

**Pull request merged**
