### PR TITLE
[ADD] Add the module security_safe_password

### PR DESCRIPTION
**Pull request by tungocbui**
This module will help to make sure user password is strong enough by adding some constraints (at least 1 upper case, 1 lower case, 1 number, long enough). It also supports the check with cracklib package.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
This module looks very similar to https://github.com/OCA/server-tools/pull/162, which was proposed a long time ago. Maybe both can join forces to get an unified OCA module.

**Comment by tungocbui** [comment]
@pedrobaeza: thks for pointing that pull request. I just took a quick look on that pull request and indeed the idea / purpose of both pull requests is almost the same. Do you have any idea on when the pull request [162](https://github.com/OCA/server-tools/pull/162) will be merged into OCA? On our side, we can try to contribute the check with "cracklib" package after that module is merged.

Please share with me if you have any other ideas on how we should help to have a unified OCA module.

Have a nice day!

**Comment by pedrobaeza** [comment]
As far as I see, the PR got stopped because some comments were not attended by the author. I have commented in that PR if the author wants to give you the possibility to enhance that module or if he's going to do it himself.

**Comment by hhgabelgaard** [comment]
#294 is my attempt to implement #134/#162 - But currently targeting v8.
@tungocbui Does your module support password reset from the login page? In v8 I need to override web_auth_reset_password in AuthSignupHome from auth_signup to get the validation messages displayed

**Comment by tungocbui** [comment]
@hhgabelgaard: yes, it does. You will find that we overwrite the function "change_password" in the file "security_safe_password/controllers/main.py" to get the validation messages displayed.

**Comment by tungocbui** [comment]
what should i do on this PR now? there is no feedback from #162 until now...

**Comment by hhgabelgaard** [comment]
Good question - What is the next step?

It seems like a lot of people need/want this - We have the original PR #134, #162 and my #294 - all for v8 and now this new implementation for v9

How do we get #294 and #350 merged? What is missing? Should we make them more alike to ease upgrading?

**Comment by dreispt** [comment]
@tungocbui @hhgabelgaard I see no point in having two different implementations on 9.0 (this #350) and 9.0 (#294).
We should create a version that takes the best from each implementation.
It would be nice to agree on which PR the work should be based. 
I suggest for authorship to be attributed to both.

**Comment by hhgabelgaard** [comment]
#294 is for 8.0

But I agree, no point in having to functionally identicall modules

**Comment by tungocbui** [comment]
@dreispt i totally agree with your point. So could you (or anyone in OCA) please take a look and suggest which module should be used as a base?

**Comment by dreispt** [comment]
I just went through the code. The #294 seems like a richer implementation. #350 adds a cracklib check.
IMO we should work on #294, and then add the cracklib feature, as an option (only if the lib is installed) and then port it to 9.0 (should be straightforward AFAICS).

**Comment by tungocbui** [comment]
Thks for your input. It's ok for me. So i will close this pull request? 

Let me know if i can help on any parts in #294.

**Comment by dreispt** [comment]
Yes I think we should close this, if you don't mind.
It would be great if you could help with #294. First by doing a second code review, and when it's merged, by adding your cracklib feature and doing the port to 9.0.

**Comment by tungocbui** [comment]
Ok for me. Please close it.

I will spend some time to take a look at #294 (but only next week)

**Pull request closed without merging**
