### PR TITLE
[ADD] auth_oauth_multi_token

### PR DESCRIPTION
**Pull request by fmdl**
Continus work of @simahawk after the modification of the Odoo code : https://github.com/odoo/odoo/commit/da1f153d61d747d9357694382fe04f96c0ca886a

From https://github.com/OCA/server-tools/pull/1032

Nota : This module is already mig in V11 : https://github.com/OCA/server-auth/tree/11.0/auth_oauth_multi_token

@guewen 
@mpanarin 
@oleksandrpaziuk 
@alnslang 

Regards

### CODE REVIEW

**Comment by simahawk** [comment]
@fmdl can you change base branch w/ `add-auth_oauth_multi_token` to include only your last commit? tnx

**Comment by fmdl** [comment]
@simahawk I don't understand what you want ?

**Comment by simahawk** [comment]
@fmdl ~you are issueing the PR against my branch 10.0. You should do it against proper branch ;)~
Ah, dammit, sorry... I realized now that you've created a new PR on OCA :stuck_out_tongue:
I asked a PR against my fork... no problem: do you want to update this or shall I close mine (already has reviews ;))?

**Comment by fmdl** [comment]
I don't know why I can not create a merge request in your fork. Could you make a cherry-pick in your PR ?

**Comment by simahawk** [comment]
@fmdl you can close this

**Pull request closed without merging**
