### PR TITLE
[14.0][MIG] auto_backup

### PR DESCRIPTION
**Pull request by SimoneVagile**

### CODE REVIEW

**Comment by LoisRForgeFlow** [comment]
Please, check travis errors.

**Comment by newtratip** [comment]
@SimoneVagile, please fix conflict files.

**Review by newtratip — APPROVED** [review]
LGTM :+1:

**Review by fshah-initos — COMMENTED** [review]
LGTM.
Please change the sequence of Pre-commit and migration commit as per guideline.

**Comment by fshah-initos** [comment]
It would be nice if you check the above comments

**Comment by SimoneVagile** [comment]
> It would be nice if you check the above comments

@fshah-initos done

**Review by fshah-initos — APPROVED** [review]
LGTM

**Pull request merged**
