### PR TITLE
[14.0] model_read_only

### PR DESCRIPTION
**Pull request by solo4games**
Module disables modification operations (write, create, delete) on selected model to selected users groups.
supersedes [2509](https://github.com/OCA/web/pull/2509)

### CODE REVIEW

**Review by geomer198 — APPROVED** [review]
Code review ok!

**Review by francesco-ooops — APPROVED** [review]
Functional review ok!

**Comment by francesco-ooops** [comment]
@OCA/tools-maintainers good for merge?

**Pull request merged**
