### PR TITLE
10.0 typo - base_search_fuzzy

### PR DESCRIPTION
**Pull request by gdgellatly**
@lasley satisfy my OCD please, can we squash the commit? in my excitement I forgot to pull before commit.

### CODE REVIEW

**Comment by lasley** [comment]
@gdgellatly - Go for it! Less commits, the better. Try not to amend/squash things that someone has reviewed though. Everything else, squashing is totally the best policy unless you're testing and expect to need to revert things.

Also, mergers will typically use the Github Squash & Merge feature as long as the PR is all one author and doesn't contain multiple migrations.

image

**Comment by lasley** [comment]
Oh I see, best in this case would instead be to:
```
git reset --hard 379da5218824a45f3f15eb02fd840a9ae9f1224d
git rebase OCA/10.0
git push -f
```

**Comment by gdgellatly** [comment]
@lasley thanks, I got the idea even if my remotes are named differently.  Indeed, perhaps I should use origin for my own branches, just I never expect to make a PR.

**Review by lasley — APPROVED** [review]
Thanks @gdgellatly

**Comment by pedrobaeza** [comment]
Please change module version according https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md#version-numbers (this requires a module update).

**Comment by gdgellatly** [comment]
@pedrobaeza which one of x.y.z? , I'm just about to leave office for a couple of days so I'm going to guess y. A module upgrade is needed, although it could be z as it's not like anything breaks without an upgrade and it isn't a new feature.  Or it could be x as a view has changed.

Fun.  I'll just do y.  It can wait if I'm wrong.

**Comment by pedrobaeza** [comment]
Indeed `y` is the correct one IMO.

**Comment by gdgellatly** [comment]
@pedrobaeza OK I did it.  I suspect I might have messed it as the force push has changed the SHA when it usually doesn't.  If its a problem let me know and I'll sort on Friday.

EDIT: OK Refreshed screen.  Looks better

**Comment by pedrobaeza** [comment]
No, it's OK for me. Thanks.

I'm remembering... how was your surgery? I suppose all goes well.

**Review by pedrobaeza — APPROVED** [review]

**Comment by gdgellatly** [comment]
@pedrobaeza thanks, it's fine, all minor stuff. One to go and I'm done.

**Review by mFlayyan — APPROVED** [review]

**Pull request merged**
