### PR TITLE
[WIP] 8.0: module_prototyper: Export data and demo data

### PR DESCRIPTION
**Pull request by mvaled**
Implements (to some degree) the option to export the data of a module when generating a module from the module_prototyper.

### CODE REVIEW

**Comment by max3903** [comment]
@mvaled Data and demo data are exported in the version 10.0.1.0.0. You may want to backport what has been done there....

**Comment by mvaled** [comment]
Hi @max3903, 

Thanks.  We will check it out.

cc: @hpestano

**Comment by kalmenchia** [comment]
Hi, Tested the data export in version 10.0 , at prototyper , selected the fields for the model at the fields tab and also at the Data & Demo tabs , select data filters , created a simple data filter record , filter name = user , Model = res.users , other fields default values. but click export , expecting res_users.xml have data but is blank between <odoo> tag. 

is this a bug or i have missed something ?
Thanks.

**Comment by mvaled** [comment]
Hi @max3903,

I checked the 10.0 branch and I don't see that data is exported.  Nevertheless, I'm closing this PR and putting another to 10.0 branch.

**Pull request closed without merging**
