### PR TITLE
[9.0]Remove base concurrency

### PR DESCRIPTION
**Pull request by petrus-v**
according this [commit](https://github.com/odoo/odoo/commit/94a0bbed0a94e4bd34965c1466615d225ac8e509), I think this module is no longer needs!

### CODE REVIEW

**Comment by pedrobaeza** [comment]
That's right :+1:

**Comment by petrus-v** [comment]
Your are so fast, I was writing to ask you to update #271, thanks!

**Comment by max3903** [comment]
:+1:

**Comment by lmignon** [comment]
:+1:

**Pull request merged**
