### PR TITLE
[9.0] [ADD] base search fuzzy

### PR DESCRIPTION
**Pull request by serpentcs-dev1**
- Migrated base_search_fuzzy module to v9

### CODE REVIEW

**Comment by jbeficent** [comment]
:+1 Tested with https://github.com/OCA/social/pull/143

**Review by JordiBForgeFlow — APPROVED** [review]
:+1:   Tested with https://github.com/OCA/social/pull/143

**Comment by JordiBForgeFlow** [comment]
@lreficent @aheficent, can you test, together with OCA/social#143?

**Review by AaronHForgeFlow — APPROVED** [review]
Tested with https://github.com/OCA/social/pull/143 :+1:

**Review by LoisRForgeFlow — APPROVED** [review]
Tested with OCA/social#143 :+1:

**Comment by JordiBForgeFlow** [comment]
@christophlsa are you ok to merge?

**Comment by pedrobaeza** [comment]
@jbeficent, please squash commits by author first.

**Comment by JordiBForgeFlow** [comment]
@pedrobaeza We have only added 1 commit to migrate to v9. The others are commits from v8. Shall we still squash??

**Comment by pedrobaeza** [comment]
Yes, please, because this commit story is meaningless in this branch (all the "OCA Transbot..." for example, you want final translations, not all the middle diffs). The same can apply for the consecutive code refinements made by the same author (probably from the 8.0 PR, that wasn't squashed there). You already have that history on 8.0 branch, that is where matters. Here, you only need to respect attribution.

**Comment by JordiBForgeFlow** [comment]
@darshan-serpent Can you take care of the request from @pedrobaeza ?

**Comment by JordiBForgeFlow** [comment]
@pedrobaeza.  I see some changes proposed to files outside this module, but seem to be the result of migrating commit history from v8. They are harmless changes. IMHO this one is ready to merge.

**Comment by JordiBForgeFlow** [comment]
cc @pedrobaeza Can we merge?

**Pull request merged**
