### PR TITLE
8.0 base import security group

### PR DESCRIPTION
**Pull request by StefanRijnhart**
Picking up where https://github.com/OCA/server-tools/pull/154 left off. Refactored javascript and added tests.

### CODE REVIEW

**Comment by StefanRijnhart** [comment]
I'm making inquiries after this heartrending phantomjs timeout here: https://github.com/OCA/maintainer-quality-tools/issues/432

**Comment by StefanRijnhart** [comment]
Tests are fixed thanks to @moylop260 who recognized that the Postgres version was the problem.

**Review by moylop260 — APPROVED** [review]

**Review by andhit-r — APPROVED** [review]
:+1: Functionality tested on runbot

**Review by NL66278 — APPROVED** [review]
LGTM and would seem to me extremely usefull

**Comment by sbidoul** [comment]
Looks good to me. 3 approvals. I merge.

**Pull request merged**
