### PR TITLE
[14.0][FIX] attachment_delete_restrict: adapt to Odoo permission change

### PR DESCRIPTION
**Pull request by jonsgit**
Fixes tests after https://github.com/odoo/odoo/commit/d3a6a20788c78ddaaff0919ea627e7b10c7ab81c broke them.

### CODE REVIEW

**Review by StefanRijnhart — APPROVED** [review]
Thanks! I see the tests of this module used an attachment that was not linked to any particular record. After the upstream change, only owners have permissions on such attachments. Now that the attachment is linked to an actual partner, modifying or deleting its attachments requires a group that has write access on the partner model. All in all, this seems like the right fix for this module's tests.

**Comment by pedrobaeza** [comment]
Let's merge it then to fix the branch:

/ocabot merge patch

**Comment by StefanRijnhart** [comment]
@jonsgit do you agree this one is "Ready for review" (i.e. merge)?

**Review by yostashiro — APPROVED** [review]
LGTM. Thanks for the fix!

**Comment by Kev-Roche** [comment]
Thanks @jonsgit

**Review by Kev-Roche — APPROVED** [review]

**Pull request merged**
