### PR TITLE
[14.0][IMP] base_custom_info: new field: code

### PR DESCRIPTION
**Pull request by norlinhenrik**
I would like to add the field "code", because I would like to use it for payroll calculations.

### CODE REVIEW

**Review by nimarosa — APPROVED** [review]

**Comment by norlinhenrik** [comment]
`record.get_custom_info_value(properties)` is not so useful when only the code is known. Now this also works:
`record.get_custom_info_value("my_code")`

**Comment by norlinhenrik** [comment]
When the type is Selection, by default _compute_value() will return the option's display_name. Now it may return the code:
`custom_info_value_record.with_context(custom_info_option_field="code").value`

**Comment by norlinhenrik** [comment]
I have just improved the code and code descriptions.
In payslip rules I want to look for custom info by code, e.g.
`value = employee.address_home_id.get_custom_info_value(code="house_tax_value").value`

@pedrobaeza @Rad0van What do you think?

**Comment by Rad0van** [comment]
@norlinhenrik I actually have a small module in place where I add code to custom.info.property but you use it in an extended way. I like it.

**Review by pedrobaeza — APPROVED** [review]

**Comment by norlinhenrik** [comment]
Inside the `custom.info` model, I made `get_custom_info()` to replace `get_custom_info_value()` (the original method is still there, with a deprecation notice and returning `get_custom_info()`).

Then a typical use case would be `get_custom_info(properties or code).value`, and I would prefer this.

What do you think?

**Comment by pedrobaeza** [comment]
Seems OK as you are respecting previous API. Some tests are failing.

**Comment by nimarosa** [comment]
Agree with the new changes.

**Review by nimarosa — APPROVED** [review]

**Comment by norlinhenrik** [comment]
Can we please set this PR in **draft** state?

I will change so that `get_custom_info()` will return not the value record, but the actual value, similar to `get_time_parameter()`.

**Comment by norlinhenrik** [comment]
`get_custom_info()` is ready now, with a test. I think the PR is ready for migration.

**Comment by nimarosa** [comment]
@appstogrow @norlinhenrik Tests shows this error: 
`TypeError: get_custom_info() got an unexpected keyword argument 'properties'`

The rest of the changes look good.

**Comment by norlinhenrik** [comment]
Now I have fixed the test, rebased and squashed commits.

**Pull request merged**
