### PR TITLE
[MIG][11.0] external file location

### PR DESCRIPTION
**Pull request by thomaspaulb**

### CODE REVIEW

**Comment by thomaspaulb** [comment]
@pedrobaeza Do you have any idea what I can do to make this green?

**Comment by pedrobaeza** [comment]
There's a warning in runbot:
```
2018-12-24 18:09:19,747 165 INFO openerp_test odoo.modules.loading: loading attachment_base_synchronize/data/cron.xm
2018-12-24 18:09:19,753 165 WARNING openerp_test odoo.models: ir.cron.create() includes unknown fields: args
```

**Comment by thomaspaulb** [comment]
> 2018-12-24 18:09:19,753 165 WARNING openerp_test odoo.models: ir.cron.create() includes unknown fields: args

@pedrobaeza Where to see this one? If I click on "Details" for the failed build of ci/runbot, I just see two INFO messages. And I don't have the password to login.

**Comment by pedrobaeza** [comment]
seleccion_016

**Comment by thomaspaulb** [comment]
Really. How did I miss that, thanks.

So we have another one:
```
2019-01-16 18:16:35,242 165 WARNING openerp_test odoo.models: ir.cron.create() includes unknown fields: args, function
```

**Comment by pedrobaeza** [comment]
It's the same AFAIK

**Comment by NL66278** [comment]
@thomaspaulb Maybe push again to try to resolve runbot error....

**Comment by thomaspaulb** [comment]
@Kiplangatdan Could you rebase this and push again

**Pull request closed without merging**
