### PR TITLE
[13.0][MIG] iap_alternative_provider

### PR DESCRIPTION
**Pull request by hendrixcosta**

### CODE REVIEW

**Review by mileo — APPROVED** [review]

**Comment by mileo** [comment]
Please update the README

**Comment by mileo** [comment]
https://github.com/oca/maintainer-tools/#readme-generator

**Comment by legalsylvain** [comment]
@mileo : it is not necessary. Readme file will be updated automatically by ocabot, when merging.
Kind regards.

**Review by PierrickBrun — APPROVED** [review]

**Pull request merged**
