### PR TITLE
10.0 fgarbely migration auditlog

### PR DESCRIPTION
**Pull request by BT-fgarbely**
First, I cherry picked all auditlog commits from branch 9.0, which was added after the creation of the branch 10.0.
Then, I made the changes in auditlog to make it work in v10.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
FYI, you can follow this migration guide to avoid to cherry-pick manually each missing commit: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0#technical-method-to-migrate-a-module-from-90-to-100-branch

**Comment by BT-fgarbely** [comment]
Thanks a lot.
I didn't know this checklist.

**Comment by BT-fgarbely** [comment]
Hello @pedrobaeza 

I have seen that I forgot to change some things (according to the migration guide).

Should I change this in a new commit, or should I close this PR and create a new one according to the migration guide?

Thanks for your support.

Regards,

**Comment by pedrobaeza** [comment]
You can start from scratch on your local and follow the guide, and then cherry-pick the migration commit. Then, you just need to force push the result to the same branch name as the one of this PR (`10.0_fgarbely_migration_auditlog`), and this PR can be recycled for the new code.

**Comment by BT-fgarbely** [comment]
New PR #707 

Hello @pedrobaeza 

I was easier for me to create a completely new PR.

**Pull request closed without merging**
