### PR TITLE
[Updated] database_cleanup icon

### PR DESCRIPTION
**Pull request by jonisunz**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Same comments as in https://github.com/OCA/server-ux/pull/200#pullrequestreview-478352763

**Comment by HaraldPanten** [comment]
Could you check runbot? I tried the rebuild but it's not working. Any idea, Pedro?

**Comment by pedrobaeza** [comment]
It seems a runbot glitch, so let's ignore it for now.

**Review by HaraldPanten — APPROVED** [review]
Icon LGTM

**Comment by pedrobaeza** [comment]
Please squash the 3 commits into one.

**Review by MiquelRForgeFlow — APPROVED** [review]
LGTM

**Comment by pedrobaeza** [comment]
This can be fw-ported to v13/v14

**Pull request merged**
