### PR TITLE
[9.0][FIX] Update requirements.txt

### PR DESCRIPTION
**Pull request by igallart**
pyotp in python2.7 is supported in versions <2.4

### CODE REVIEW

**Comment by igallart** [comment]
View https://github.com/OCA/server-tools/pull/1875

**Comment by igallart** [comment]
Is there a problem with commit?

**Comment by pedrobaeza** [comment]
Yes, Travis is red.

**Comment by igallart** [comment]
@pedrobaeza , I think that this change in requirements is necessary because the higher versions do not work and will not start Odoo, it has been made in version 8 and 10. The fails in Travis I doubt very much had to do with this change.

**Pull request merged**
