### PR TITLE
[FIX] auto_backup: Empty dump using sftp backup option (#428 issue)

### PR DESCRIPTION
**Pull request by jabibi**
Fix for issue: [8.0][auto_backup] Empty dump using sftp backup option #428

### CODE REVIEW

**Comment by Daniel-CA** [comment]
Great @jabibi , let me check and I will give my thumbs up

**Comment by Daniel-CA** [comment]
:+1: works fine now.

**Comment by moylop260** [comment]
:+1:

**Comment by jabibi** [comment]
can be merged?

**Comment by jabibi** [comment]
Thanks @pedrobaeza

**Pull request merged**
