### PR TITLE
[14.0][IMP] base_time_parameter: LGPL-3; rename model to base.time.parameter.version

### PR DESCRIPTION
**Pull request by ghost**
LGPL-3 licence since it is a dependency for payroll.

Each parameter version has a start date and a value.

### CODE REVIEW

**Review by legalsylvain — CHANGES_REQUESTED** [review]
- could you split commits (. Licence change + model rename) ?
- could you provide migration scripts ?

Thanks.

**Comment by nimarosa** [comment]
@appstogrow Hi Henrik, i think like @legalsylvain said, we have to split the commits. I don't think migration scripts are necessary since the module it's too new and i don't think anyone is using it right now. 

I think we can merge with splitted commits. Can you do it?

**Comment by norlinhenrik** [comment]
I have written [migration script for payroll](https://github.com/OCA/payroll/pull/87) which will depend on base_time_parameter.

**Comment by nimarosa** [comment]
Okay so we can merge this so we can continue and test the PR in payroll. 

/ocabot merge patch

**Pull request merged**
