### PR TITLE
[13.0][MIG] excel_import_export, excel_import_export_demo

### PR DESCRIPTION
**Pull request by kittiu**
Standard migration, ready for review.

### CODE REVIEW

**Comment by kittiu** [comment]
Not sure what following error in Travis is about,
```
invalid module names, ignored: database_cleanup
```

**Comment by pedrobaeza** [comment]
That's because .travis.yml contain specific build with `INCLUDE=database_cleanup`. Remove it for now.

**Comment by kittiu** [comment]
May be, can use the following PR ways to improve this PR too.
https://github.com/OCA/reporting-engine/pull/353

**Comment by sbidoul** [comment]
@kittiu there are two way to resolve the travis issue regarding installation of `openpyxl`:

1. adding a file named `requirements.txt` with `openpyxl` at the repo root
2. [experimental] adding a global environment variable `MQT_DEP=PIP` in `.travis.yml`, which will trigger automatic detection of dependencies declared in addons manifests

**Comment by kittiu** [comment]
@sbidoul I choose 2nd option and it works.

Thank you, and be healthy ;)

**Comment by tarbib** [comment]
@kittiu Hello happy to see that it worked for you! Did you mange to fix the Travis error on your side ? Would be wonderful if it's module could be available on 13.0 branch :)

**Comment by kittiu** [comment]
@tarbib 
It was ok before I rebase. After rebase, it seem to have problem with `base_view_inheritance_extension` which I can't recon.
https://travis-ci.com/github/OCA/server-tools/jobs/359639977#L1322

@sergio-teruel do you know what it could be?

Note: I did also try another clean migration, https://github.com/OCA/server-tools/pull/1867, same error.

**Comment by pafnow** [comment]
I tried to use that module on my Odoo 13 installation and got some issue while using the import feature for lines of an existing order (for example). The error mentioned that it was not allowed to modify a dict while iterating over it.

I fixed it by modifying two lines here:
https://github.com/ecosoft-odoo/server-tools/blob/b00aff644d10d1acd0a673a094e43116f1ece34f/excel_import_export/models/xlsx_import.py#L92

Adding copy() as below:
```
            # Remove _NODEL_ from dict
            for s, _sv in data_dict.copy().items():
                for f, _fv in data_dict[s].copy().items():
                    if "_NODEL_" in f:
```

**Comment by kittiu** [comment]
> I tried to use that module on my Odoo 13 installation and got some issue while using the import feature for lines of an existing order (for example). The error mentioned that it was not allowed to modify a dict while iterating over it.
> 
> I fixed it by modifying two lines here:
> https://github.com/ecosoft-odoo/server-tools/blob/b00aff644d10d1acd0a673a094e43116f1ece34f/excel_import_export/models/xlsx_import.py#L92
> 
> Adding copy() as below:
> 
> ```
>             # Remove _NODEL_ from dict
>             for s, _sv in data_dict.copy().items():
>                 for f, _fv in data_dict[s].copy().items():
>                     if "_NODEL_" in f:
> ```

Make sense, so I include it.

**Comment by kittiu** [comment]
Moved https://github.com/OCA/server-tools/pull/1887

**Comment by kittiu** [comment]
> @sbidoul I choose 2nd option and it works.
> 
> Thank you, and be healthy ;)

Just for the note. It seem that the 2nd option not work thoroughly, we still got error from yaml,
https://travis-ci.com/github/OCA/server-tools/jobs/377590279#L1366

But when I change to add `openpyxl` in requirement.txt, it now ok.

**Pull request closed without merging**
