### PR TITLE
[13.0][MIG] base_technical_user

### PR DESCRIPTION
**Pull request by HviorForgeFlow**
Standard migration

- [x] Include https://github.com/OCA/server-tools/pull/1824

CC @ForgeFlow @rousseldenis

### CODE REVIEW

**Review by rousseldenis — APPROVED** [review]

**Review by LoisRForgeFlow — APPROVED** [review]
LGTM :+1:

**Comment by pedrobaeza** [comment]
I think this module is not needed anymore, as this is the exact definition of OdooBot/`__system__` user.

**Comment by florian-dacosta** [comment]
I am not sure about multi company case? It may be usefull to have a different technical user with a dedicated company in some cases no?

**Comment by pedrobaeza** [comment]
No, that user is tolerant with any company.

**Review by AdriaGForgeFlow — APPROVED** [review]

**Comment by rousseldenis** [comment]
> No, that user is tolerant with any company.

Indeed, but @florian-dacosta is right, I think you need to change OdooBot company if you want to do actions in that context.

The aim here is to have a fixed user per company.

Something like 'MyCompanyA_Bot', 'MyCompanyB_Bot

OdooBot is the big boss Bot user

**Review by ValentinVinagre — APPROVED** [review]
LGTM

**Comment by rousseldenis** [comment]
@OCA/core-maintainers

**Comment by rousseldenis** [comment]
@simahawk

**Pull request merged**
