### PR TITLE
[14.0][mig]base_kanban_stage_state

### PR DESCRIPTION
**Pull request by hkapatel-initos**
Migration to 14.0
Depends on:

[14.0][mig]base_kanban_stage #2117

### CODE REVIEW

**Review by dsolanki-initos — APPROVED** [review]
No Major change. LGTM

**Comment by hkapatel-initos** [comment]
it would be nice if someone reviews here.

**Comment by MiquelRForgeFlow** [comment]
You should rebase now that the other module is merged.

**Comment by hkapatel-initos** [comment]
@MiquelRForgeFlow it would be nice if could you review it here.

**Review by MiquelRForgeFlow — APPROVED** [review]
Runbot is not working, it's not your problem.

**Comment by hkapatel-initos** [comment]
@dreispt can we merge this?

**Pull request merged**
