### PR TITLE
[16.0] [MIG] base_search_fuzzy

### PR DESCRIPTION
**Pull request by Nikul-OSI**

### CODE REVIEW

**Comment by Nikul-OSI** [comment]
@dreispt Can you please take a look?

**Review by AungKoKoLin1997 — APPROVED** [review]
Functional Review.
It works as expected.

**Review by ghost — APPROVED** [review]

**Comment by PicchiSeba** [comment]
Looking at this module in v16 I stumbled into a line in [readme/ROADMAP.rst](https://github.com/OCA/server-tools/blob/16.0/base_search_fuzzy/readme/ROADMAP.rst) which states this module isn't needed in v16 anymore as it has been merged

So is this still required for a fuzzy search?

**Comment by pedrobaeza** [comment]
It shouldn't. @dreispt there is now the possibility of defining fuzzy indexes directly in Odoo ORM.

**Comment by PicchiSeba** [comment]
Hi @pedrobaeza , I opened an issue both in Odoo and this module because of some concerns regarding different behavior between this module and the before-mentioned update to Odoo's trigram indexes

**Pull request merged**
