### PR TITLE
11 update onchange helper

### PR DESCRIPTION
**Pull request by EBII**
use import base

### CODE REVIEW

**Comment by thomaspaulb** [comment]
Why refactor to using Base?

**Comment by ap-wtioit** [comment]
This merge request also fixes the breaking onchange_helper tests since https://github.com/odoo/odoo/commit/2054b5928574affbb7efcd8a9ab146ee4fa34938 for us

**Comment by EBII** [comment]
Any one know how to test onchange_helper on one2many field and which one ?

**Review by etobella — APPROVED** [review]
LGTM :+1:

**Review by JordiBForgeFlow — APPROVED** [review]

**Pull request merged**
