### PR TITLE
WIP: [9.0] module_prototyper migrate

### PR DESCRIPTION
**Pull request by njeudy**

### CODE REVIEW

**Comment by max3903** [comment]
@njeudy Thanks for the effort!

The `license` key is empty in the exported module, in addition to the small issues I mentioned to @kurkop in https://github.com/OCA/server-tools/pull/279#issuecomment-158258347

Otherwise :+1:

**Comment by gurneyalex** [comment]
:+1:

**Comment by lmignon** [comment]
@njeudy In the module_prototyper view to default version should be 9.0.1.0.0
image

**Comment by lmignon** [comment]
This one is ready to merge. I'll fix my comment  in #398

**Pull request merged**
