### PR TITLE
[11.0] [MIG] date_range: Migration to 11.0

### PR DESCRIPTION
**Pull request by etobella**
Migration to 11.0.
No major changes.

### CODE REVIEW

**Review by JordiBForgeFlow — CHANGES_REQUESTED** [review]
The option to select a date range in date filters has disappeared:
image

Not sure why yet.

**Review by yajo — CHANGES_REQUESTED** [review]
Squash all translation commits in a single one please.

**Comment by pedrobaeza** [comment]
Please move this PR to new repo https://github.com/OCA/server-ux according #1006

**Comment by etobella** [comment]
Migrated to server-ux by @lmignon 
OCA/server-ux#3

**Pull request closed without merging**
