### PR TITLE
Improve readme and fix dep

### PR DESCRIPTION
**Pull request by hparfr**
1° Readme: (in example) prefix function with _
2° Dep: add a depency to base_setup in order to use xml id "base.menu_config" in https://github.com/OCA/server-tools/blob/9.0/keychain/views/keychain_view.xml#L47

### CODE REVIEW

**Comment by florian-dacosta** [comment]
:+1:

**Comment by bealdav** [comment]
Please remove base, if you add base_setup. Otherwise, :+1: 
"Qui peut le + peut le moins"

**Comment by hparfr** [comment]
>Please remove base, if you add base_setup. Otherwise, 👍

Fixed.

Thanks for your reviews

**Comment by bealdav** [comment]
Why several commits here, for 2 lines ? --force

**Comment by hparfr** [comment]
--forcing a push on a public branch is not a good thing
It breaks the history of the comments (like inline review).

**Review by tafaRU — APPROVED** [review]
LGTM even though I'd prefer commits to be squashed to only one.

**Comment by legalsylvain** [comment]
thanks.

**Pull request merged**
