### PR TITLE
[auto_backup] FIX: failure type notification

### PR DESCRIPTION
**Pull request by Yenthe666**
Fixes https://github.com/OCA/server-tools/issues/710

### CODE REVIEW

**Review by rousseldenis — APPROVED** [review]
Code review

**Review by rousseldenis — COMMENTED** [review]
@Yenthe666 Can you just fix Flake8 ?

**Review by lasley — APPROVED** [review]
Thanks @Yenthe666 - LGTM other than the lint issue

**Comment by lasley** [comment]
I went ahead and amended the lint fix in to save @Yenthe666 a bit of maintenance on an otherwise approved bug fix. 

Would another maintainer mind providing a third thumb and a quick merge on this one to fix a bug in production (once CI 🍏 )?

**Comment by Yenthe666** [comment]
Thanks @lasley :-)

**Pull request merged**
