### PR TITLE
[MIG][10.0] password_security

### PR DESCRIPTION
**Pull request by lasley**
- Bump versions
- Installable to True
- Add Usage section to ReadMe w/ Runbot link

### CODE REVIEW

**Comment by jcdrubay** [comment]
I tested it quickly and Runbot. Very nice module.

@pedrobaeza : maybe you could add to `OCA/maintainer-tools/wiki/Migration-to-version-10.0#tasks-to-do-in-the-migration`:

> Replace the `<openerp>` tag in xml files by `<odoo>`

(sorry if it is not the right place to say that)

**Comment by hbrunn** [comment]
it's not the right place, but I think the people busy with the maintainer tools will appreciate your PR on changing the docs

**Comment by pedrobaeza** [comment]
@jcdrubay, OK, thanks for the suggestion. I have added the line in the wiki, so no need you to do it anything more.

**Review by elicoidal — APPROVED** [review]
:+1:

**Review by susport — COMMENTED** [review]
👍

**Pull request merged**
