### PR TITLE
[18.0][MIG] session_db

### PR DESCRIPTION
**Pull request by sbidoul**

### CODE REVIEW

**Comment by sbidoul** [comment]
The CI failed on WARNING :+1:, `mute_logger` to the rescue.

**Comment by sbidoul** [comment]
Tested manually :+1:

**Review by qgroulard — APPROVED** [review]
LGTM (code review)

**Comment by sbidoul** [comment]
> mute_logger to the rescue

or better, `self.assertLogs`

**Review by houssine78 — APPROVED** [review]
LGTM

**Pull request merged**
