### PR TITLE
[18.0][MIG] upgrade_analysis: Migration to v18

### PR DESCRIPTION
**Pull request by sergio-teruel**
cc @Tecnativa 

ping @legalsylvain @pedrobaeza

### CODE REVIEW

**Comment by legalsylvain** [comment]
Hi. Thanks for contributing ! 

could you take a look on red CI ? 
https://github.com/OCA/server-tools/actions/runs/11673043926/job/32502925859?pr=3108#step:8:154

```
2024-11-04 21:33:37,645 247 WARNING odoo odoo.addons.base.models.ir_model: Rule upgrade.record all has no group, this is a deprecated feature. Every access-granting rule should specify a group. 
```

**Comment by sergio-teruel** [comment]
@legalsylvain Changes done!!

**Review by pedrobaeza — APPROVED** [review]
Code review + see the result

You may squash a bit administrative commits.

**Review by legalsylvain — APPROVED** [review]
quick diff review. LGTM. thanks for porting this module !

**Comment by sergio-teruel** [comment]
Squashed administrative commits!!

**Pull request merged**
