### PR TITLE
[17.0][FW][FIX] database_cleanup: Bug introduced by #2098

### PR DESCRIPTION
**Pull request by HekkiMelody**
https://github.com/OCA/server-tools/commit/0e3a449471fac29d8eb946a3e4a7b97070a0137b

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please use proper commit message: https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#commit-message

**Comment by HekkiMelody** [comment]
Thank you. Updated the commit message.

Failing tests are unrelated.

**Review by sebalix — APPROVED** [review]

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge patch

**Comment by pedrobaeza** [comment]
Please check CI

**Comment by StefanRijnhart** [comment]
Looks like https://github.com/OCA/server-tools/pull/3020 fixes some issues with the test of tracking_manager. Let's try again.

/ocabot merge patch

**Pull request merged**
