### PR TITLE
[15.0][MIG] base_sparse_field_list_support

### PR DESCRIPTION
**Pull request by HviorForgeFlow**
Standard migration

CC @ForgeFlow

### CODE REVIEW

**Comment by thomaspaulb** [comment]
@HviorForgeFlow Small issue with [pre-commit](https://github.com/OCA/server-tools/runs/7280480706?check_suite_focus=true), should be easy to fix

**Review by MiquelRForgeFlow — APPROVED** [review]

**Review by thomaspaulb — APPROVED** [review]

**Review by JuanyDForgeflow — APPROVED** [review]
LGTM

**Comment by MiquelRForgeFlow** [comment]
@thomaspaulb could you retry the merge please?

**Comment by JasminSForgeFlow** [comment]
Rebased!

**Comment by JasminSForgeFlow** [comment]
@thomaspaulb can you please try again to merge?

**Pull request merged**
