### PR TITLE
[9.0][IMP] server_environment: Update Error Guards

### PR DESCRIPTION
**Pull request by tedsalmon**
* Convert Exceptions to EnvironmentErrors
* Move config checking into function `_load_config()`
* Guard execution of `_load_config()` against EnvironmentErrors and log info
* Update exception verbiage

### CODE REVIEW

**Review by lasley — APPROVED** [review]
Yes, exceptions out of global namespace. Thanks @t3ddftw 👍 

The exceptions should be translated though IMO.

**Review by sbidoul — CHANGES_REQUESTED** [review]
It is important that a missing `running_env` remains a hard error preventing the server to start, rather than a quiet log entry. At first glance this PR changes this behaviour.

**Comment by lasley** [comment]
@sbidoul - Without this change, simply cloning the `server-tools` repo into Odoo breaks installations badly. It seems to me that no matter the reasoning, breaking existing installations with modules that are not installed should not happen. Am I incorrect in this evaluation?

**Comment by sbidoul** [comment]
@lasley I thought this particular issue you mention was resolved by #670. This PR seems to go further. IMO, preventing the server to start when `running_env` is absent is a design feature of `server_environment` and must be preserved.

**Comment by lasley** [comment]
@sbidoul - That only partially resolves the issue because the Exception is still raised inside of the global namespace if the import passes. Odoo still attempts the module load, which ends us with an emergency line call in the middle of the night/early morning.

 I see your #676 & will review that. Thanks!

**Comment by tedsalmon** [comment]
@lasley,

The changes in #676 indeed resolve the issue. I'll go ahead and close this PR :).

Thanks!

**Pull request closed without merging**
