### PR TITLE
[ADD] base_ir_filters_active

### PR DESCRIPTION
**Pull request by hbrunn**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please put the name in singular. Isn't convenient to use "active" word in the technical name (_base_ir_filter_active_)?

**Comment by hbrunn** [comment]
@pedrobaeza good point about `active`, makes sense for a technical module. For plural/singular, I sticked to the model name: https://github.com/OCA/OCB/blob/8.0/openerp/addons/base/ir/ir_filters.py#L27 - agreeable? (I don't want to have to change the name several times, to let's get it right on the first rename)

**Comment by pedrobaeza** [comment]
OK, as the model name is in plural, then let's stick to that plural.

**Comment by hbrunn** [comment]
@pedrobaeza rename done

**Comment by pedrobaeza** [comment]
:+1: 

Thanks

**Comment by guewen** [comment]
:+1:

**Pull request merged**
