### PR TITLE
[9.0][FIX] .travis: Update to latest template

### PR DESCRIPTION
**Pull request by rousseldenis**

### CODE REVIEW

**Comment by rousseldenis** [comment]
@pedrobaeza

**Comment by pedrobaeza** [comment]
Please check Travis status

**Comment by rousseldenis** [comment]
@pedrobaeza We need to merge this manually as it is intended to restore travis run.

Then, we need to ask people in charge of failing modules to solve errors.

**Comment by pedrobaeza** [comment]
Ok

**Pull request merged**
