### PR TITLE
[10.0] Add Firebird database support to base_external_dbsource

### PR DESCRIPTION
**Pull request by mstuttgart**
* Add Firebird database support to `base_external_dbsource` module using the `fdb` python package https://pypi.python.org/pypi/fdb/
* Code adjust and update README.rst from module.

### CODE REVIEW

**Review by max3903 — APPROVED** [review]
@mstuttgart Can you bump the version to 10.0.1.0.1?

**Comment by aldo774** [comment]
LGTM :+1:

**Review by lasley — CHANGES_REQUESTED** [review]
Thanks @mstuttgart - code looks good. Please check the 🔴  Travis though

**Comment by mstuttgart** [comment]
@lasley Travis CI fixed. Thks!

**Review by lasley — APPROVED** [review]
Hmmmm Runbot is broken, but it's definitely broken on something other than this. @mstuttgart let's consider this approved, can you please squash your commits and push? Hopefully that will fix the Runbot so we can merge without a 🔴 .

**Pull request merged**
