### PR TITLE
7.0 add search enhanced operators

### PR DESCRIPTION
**Pull request by OSguard**
Allows =ilike operator to advanced search option.
Use % as a placeholder. 
Example: "Zip matches 1%" gives all zip starting with 1

### CODE REVIEW

**Comment by hbrunn** [comment]
very useful, thanks! But I would put this module rather into https://github.com/OCA/web than here.

Also, even though I admit doing the same from time to time, words like 'enhanced' are imho a poor choice for a name, better describe the specific enhancement, like advanced_search_wildcards or something like that?

It might be worth mentioning in the module's description that this also allows case insensitive exact searches, so 'John' matches the input 'john', but not 'Johnson'.

**Comment by OSguard** [comment]
The reason to add it here, is that is a simular improvement like "mass_editing" and combine they are really greate. But i can also move to the web repository, it depends on 'web'.

So for the new name i think: web_advanced_search_wildcard would be fit.

**Comment by bealdav** [comment]
Maybe I missed something but without this module, in products
if I do 'bou%e' in search box
I get 'bougie' and 'bouge'

The same in partner with zip

It works ok with no module.

What is the difference ?

**Comment by bealdav** [comment]
Search box has an item named 'advanced search'. Is it only for this search or classic search too ?

**Comment by OSguard** [comment]
bou%e will be transformed to %bou%e%

if you search 3% in zip you get all data with 3 inside zip (so %3% will the search), but i want to search only witch starts with 3.

And yes it only adds an option for the text dropdown in the "advance search" of the search box, classic is not affected.

**Comment by bealdav** [comment]
thanks for these clarifications

**Comment by OSguard** [comment]
PR moved https://github.com/OCA/web/pull/38

**Pull request closed without merging**
