### PR TITLE
[18.0][MIG] base_exception: Migration to 18.0

### PR DESCRIPTION
**Pull request by xaviedoanhduy**
### OCA - Port

- https://github.com/OCA/server-tools/pull/3046

### CODE REVIEW

**Review by nicolascol — APPROVED** [review]
Functional review OK (test in https://github.com/oca/sale-workflow/pull/3359)

**Review by sebalix — APPROVED** [review]

**Review by lef-adhoc — APPROVED** [review]

**Comment by xaviedoanhduy** [comment]
hi @simahawk, can you merge it again?

**Pull request merged**
