### PR TITLE
11.0 mig sequence check digit

### PR DESCRIPTION
**Pull request by etobella**
No major changes with version 10.0.
Travis was modified because:
* Python module MySQL-python is not compatible with Python 3
* Module database_clean is not updated yet

### CODE REVIEW

**Comment by lasley** [comment]
@etobella - would you mind submitting the Travis changes in a separate PR please?

**Comment by etobella** [comment]
I understand that the changes I made on Travis will be solved on PR #1009, then, is it necessary to create the second PR when it will be solved in a few days?

**Comment by lasley** [comment]
@etobella - Ok don't worry about it - really it should have been broken from that PR. This is why changes like this should be broken out - because a lot of people need them and they aren't obvious nested elsewhere. If it was a simple PR for the Travis change, I could just quick merge it right now and we could go on with life 😑

**Review by lasley — APPROVED** [review]
Code 👍

**Review by rgarnau — APPROVED** [review]
Code and functional review :+1:

**Review by JordiBForgeFlow — APPROVED** [review]
:+1: Functional review. But before merge we need to consider that the destination repo could change: https://github.com/OCA/server-tools/issues/1006

**Comment by etobella** [comment]
Migrated to server-ux repository.

**Pull request closed without merging**
