### PR TITLE
[15.0] [MIG] fetchmail incoming log: Migration to 15.0

### PR DESCRIPTION
**Pull request by ghost**
Redo of PR https://github.com/OCA/server-tools/pull/2211 to fix folder structure issue!!
Bumped version to 15.0.1.0.0
Rebased Translation Files
Cleared PyLint issues using commit https://github.com/OCA/server-tools/pull/2211/commits/9d5838030c441a3b82923dde1fd1d31808b8acb8 by @MiquelRForgeFlow 
Tested on clean Ubuntu 20.04 VM with only discuss app enabled. All Works.

### CODE REVIEW

**Review by MiquelRForgeFlow — APPROVED** [review]

**Comment by ghost** [comment]
@pedrobaeza @joao-p-marques are one of you able to push this through?

**Comment by pedrobaeza** [comment]
@EAJGlobal review other PRs and ask in exchange that they review yours.

**Comment by ghost** [comment]
@pedrobaeza not a real big Github user learning as I go on so apologies will look into others code shortly.

**Comment by pedrobaeza** [comment]
Great, thanks for the predisposition.

**Comment by ghost** [comment]
@pedrobaeza could you add the needs review label please

**Review by mlaitinen — APPROVED** [review]
Reviewed and tested this. Works as expected. There's something wrong with Runbot, but that seems to be a Runbot-specific problem, not a problem with this MR.

**Comment by ghost** [comment]
@mlaitinen Runbot doesn't work with version 15 yet. Its a known problem that all PR's are going to fail with.
@MiquelRForgeFlow  & @mlaitinen thank you for the peer reviews. hopefully now oca-bot will start to merge

**Comment by ghost** [comment]
@pedrobaeza your the only participant listed as an OCA member. Can you push this through please.

**Comment by pedrobaeza** [comment]
OK, let's do it trusting the reviewers:

/ocabot merge nobump

/ocabot migration fetchmail_incoming_log

**Comment by ghost** [comment]
@pedrobaeza thank you!

**Pull request merged**
