### PR TITLE
[14.0][MIG] base_deterministic_session_gc

### PR DESCRIPTION
**Pull request by nilshamerlinck**
Migration of https://github.com/OCA/server-tools/pull/2132 to 14.0

### CODE REVIEW

**Review by fshah-initos — COMMENTED** [review]
No major change.
Please keep Migration and Pre-commit seperate.

**Comment by fshah-initos** [comment]
Hi @nilshamerlinck 
It would be nice if you have a look at above comments

**Comment by nilshamerlinck** [comment]
Hi @fshah-initos I'm not sure to understand what you're expecting: can you please clarify?

**Comment by fshah-initos** [comment]
We need to follow the guideline to commit. You can have a look at the below link
https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0

**Comment by hkapatel-initos** [comment]
@nilshamerlinck can you please follow the guideline to commit.

**Comment by hkapatel-initos** [comment]
@nilshamerlinck can you please follow the guideline to commit.

**Comment by hkapatel-initos** [comment]
@nilshamerlinck can you please follow the guideline to commit.

**Comment by nilshamerlinck** [comment]
Hi @hkapatel-initos can you be more specific in what you are expecting? I don't see anything wrong here with the commits history

**Comment by hkapatel-initos** [comment]
> Hi @hkapatel-initos can you be more specific in what you are expecting? I don't see anything wrong here with the commits history

Can you please check this guideline (https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0
Please keep Migration and Pre-commit separate for 14.0 and then add 
 ( [MIG] base_deterministic_session_gc: Migration to 14.0) this commit.
you can take references from  https://github.com/OCA/server-tools/pulls

**Comment by nilshamerlinck** [comment]
ok @hkapatel-initos fixed, thanks for your attentive review :)

**Review by hkapatel-initos — CHANGES_REQUESTED** [review]
code review: LGTM

**Review by hkapatel-initos — APPROVED** [review]

**Comment by hkapatel-initos** [comment]
if would be nice if we get reviews here.

**Comment by hkapatel-initos** [comment]
if would be nice if we get reviews here.

**Comment by fshah-initos** [comment]
if would be nice if we get reviews here.

**Comment by dsolanki-initos** [comment]
if would be nice if someone reviews it.

**Comment by dsolanki-initos** [comment]
if would be nice if we add reviews here.

**Comment by dsolanki-initos** [comment]
if would be nice if we add reviews here.

**Comment by dsolanki-initos** [comment]
if would be nice if we get the reviews here.

**Comment by dsolanki-initos** [comment]
if would be nice if we get the reviews here.

**Comment by dsolanki-initos** [comment]
if would be nice if we get the reviews here.

**Comment by dsolanki-initos** [comment]
if would be nice if we get the reviews here.

**Comment by dsolanki-initos** [comment]
Can we get the reviews here?

**Comment by dsolanki-initos** [comment]
Hello @hparfr could you review this pull?

**Review by fshah-initos — COMMENTED** [review]
Hello @hparfr could you please review this pull?

**Comment by ikapasi-initos** [comment]
Hello @hparfr could you please review this pull?

**Review by hparfr — APPROVED** [review]
Code review

**Review by ikapasi-initos — APPROVED** [review]
Code review and functional test
LGTM

**Pull request merged**
