### PR TITLE
[15.0][MIG] base_cron_exclusion

### PR DESCRIPTION
**Pull request by ChrisOForgeFlow**
Standard Migration
@ForgeFlow

### CODE REVIEW

**Comment by LoisRForgeFlow** [comment]
Hi @ChrisOForgeFlow you should preserve the commit history on migration, see this guide to see the technical process: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-15.0.

**Review by LoisRForgeFlow — APPROVED** [review]
LGTM

**Review by JoanSForgeFlow — APPROVED** [review]
LGTM! :+1:

**Comment by LoisRForgeFlow** [comment]
Cache issue with pre-commit again (https://github.com/OCA/server-tools/runs/4562332245?check_suite_focus=true)

/ocabot merge nobump

**Pull request merged**
